### ISSUE TITLE
Window onMessage is throwing errors in the console

### ISSUE THREAD

**Issue by arqex** [zalmoxisus/redux-devtools-extension#10]
Hi,

I have found an issue that is annoying. I see that redux-devtools-extension is using messages to interact with the page:

```js
// Resend messages from the page to the background script
	window.addEventListener('message', function (event) {
	  if (!event || event.source !== window || typeof event.data !== 'string') return;
	  var message = JSON.parse(event.data);
	  if (message.source !== 'redux-page') return;
	  payload = message.payload;
	  chrome.runtime.sendMessage(message);
	});
```

It assumes that, if the event.data is a string, it will by a stringified JSON object. But sometimes it isn't and an exception is thrown.

Freezer is using also messages to implement the `nextTick` function, and its message data is just the string `"nextTick"`, so the console is full of these errors. You can see it here:

http://freezer-redux-devtools.divshot.io/

**Comment by zalmoxisus** [comment]
Thanks for reporting this!
Actually, we just add JSON here to fix issues with circular references as reported in #5.
