### ISSUE TITLE
Export/Import immutable structures

### ISSUE THREAD

**Issue by acnovais** [zalmoxisus/redux-devtools-extension#100]
Export/Import feature does not work with immutable structures.
Do you see adding a "deserialize state as immutable" a possibility for import?

**Comment by zalmoxisus** [comment]
Yes, we have [`deserializeState` and `deserializeAction` functions](https://github.com/zalmoxisus/redux-devtools-extension#api), but need to implement them on the [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument) part.

**Comment by zalmoxisus** [comment]
Implemented in `v1.3.0`. See the [API section](https://github.com/zalmoxisus/redux-devtools-extension#api) for the details and an example of usage. Feel free to reopen the issue if you have any troubles with this.
