### ISSUE TITLE
`state = falsy` will not refresh DevTools

### ISSUE THREAD

**Issue by techniq** [zalmoxisus/redux-devtools-extension#102]
Just getting into React/Redux, and this tripped me up for a while trying to use this extension with the simple counter reducer as my root reducer.  Initially I thought "Reset" was broken, but then I found it working on the example projects and started digging into how my setup was different.

Turns out, if the returned `state` is simply a falsy value (`0`, `false`, etc), this extension will not re-render without toggle to a different Chrome tab and then back.

You can reproduce this by using the example counter project, but changing the [default export root reducer](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/counter/reducers/index.js) from `export default rootReducer;` to `export default counter;`.  You'll also need to update any state references from `state.counter` to just `state` (for example, [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/counter/containers/App.js#L8) - this might be the only one but I didn't test as my local counter example is slightly different and using react-redux).

Anyways, I changed to use `combineReducers` with a single reducer like your examples so my state is `{counter: 0}` and not just `0` and this worked around the problem, but I could see this tripping up another newcomer to the world of Redux.

**Comment by zalmoxisus** [comment]
Thanks for reporting it. Should be fixed in https://github.com/zalmoxisus/remotedev-app/commit/ba3d870b79dba64e516f6c51845b3169b2b480b0. Will push here and publish to Chrome store soon.

**Comment by techniq** [comment]
Thanks for the quick fix :)
