### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by tuler** [zalmoxisus/redux-devtools-extension#105]
Here is my environment:
- Redux DevTools version 1.1.1 download from chrome web store
- OSX El Capitan 10.11.4
- Chrome 51.0.2704.36 beta (64-bit)

Running the counter example, HMR connects fine, but when I change the Couter.js file, the browser console prints: 

[HMR] bundle rebuilding
[HMR] bundle rebuilt in 331ms
[HMR] Checking for updates on the server...
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
[HMR]  - ./components/Counter.js

The same happens with the other examples (router and todomvc).

**Comment by zalmoxisus** [comment]
Hey @tuler,

This is an expected behaviour for `react-transform-hmr` and is not related to the extension. Try to change something in the reducer and see if it is reloaded. Hopefully React Hot Loader 3 works better, but it is not released yet.

**Comment by tuler** [comment]
Ok, I was slowly coming to this conclusion. I'll try React Hot Loader 3 instead.
Thanks!
