### ISSUE TITLE
Upgrade to redux-dev-tools 3.3.0

### ISSUE THREAD

**Issue by rubyboy** [zalmoxisus/redux-devtools-extension#106]
There's a new version of the redux-dev-tools version that now supports Observales. Are you able to release a new version of the Chrome extension to the store that uses the new https://www.npmjs.com/package/redux-devtools version?
Thanks.

**Comment by zalmoxisus** [comment]
Thanks for letting me know. Just released `1.2.0`. Should appear on Chrome store in about an hour.

**Comment by rubyboy** [comment]
Works a treat! It's already there.
Thanks heaps.
