### ISSUE TITLE
Uncaught Error: DevTools.instrument({ maxAge }) option, if specified, may not be less than 2.

### ISSUE THREAD

**Issue by axelson** [zalmoxisus/redux-devtools-extension#108]
This is most likely an upstream error but creating this anyway for tracking if nothing else. On all the redux-dev-tools enabled pages that I've found I get `Uncaught Error: DevTools.instrument({ maxAge }) option, if specified, may not be less than 2.` error in the console which actually blocks rendering. I'm seeing this on the sample pages as well:

http://zalmoxisus.github.io/redux-devtools-extension/examples/counter/

http://zalmoxisus.github.io/redux-devtools-extension/examples/todomvc/

This error may be related to #89.

**Comment by axelson** [comment]
So this was bugging me and I looked into it some more and it looks like the "actions history limit" setting no longer accepts 0. According to [this comment](https://github.com/gaearon/redux-devtools/pull/267#issuecomment-209813741) 0's should have been migrated but I guess that didn't work for me. Not sure if 0's are supported going forward but I've just set a very high limit (500) and at least the pages are rendering for me now.

**Comment by huchenme** [comment]
+1

**Comment by zalmoxisus** [comment]
Thanks for the report! As I explained [here](https://github.com/zalmoxisus/redux-devtools-extension/pull/54#issuecomment-216465854), we don't want to have the history infinite anymore as it will crash the extension at some point or the extension will not be able to open the monitor as it has to serialize all the data before. The user can still put there a very high value, but he will acknowledge that it affects the productivity.

Of course, we should remove that comment about `0 - unlimited`. Sorry about that!

**Comment by axelson** [comment]
Thanks!
