### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by farrrr** [zalmoxisus/redux-devtools-extension#11]
When I try to upload image by React-Dropzone-Component,
the browser hanged, after 20secs console will throw errors.
![screen shot 2015-11-05 at 2 41 55 am](https://cloud.githubusercontent.com/assets/1716558/10948156/14fb9740-8367-11e5-88e3-5edbebd543da.png)

If I disabled the extension, everything is ok.

**Comment by zalmoxisus** [comment]
Hey, @farrr. Thanks for reporting this!
I tried React-Dropzone-Component's example and it doesn't conflict with the extension. Anyway, the extension does nothing before you pass the store to it.

Could you please tell more about your user case? Do you store the images' blobs into states? What is the purpose of storing big data? Could you please provide an example project to run or [run the extension in dev mode](https://github.com/zalmoxisus/redux-devtools-extension#implementation) to see if it is breaking on serializing the data or on sending them?

**Comment by farrrr** [comment]
ok, I will make an reproducible example for it.

**Comment by zalmoxisus** [comment]
Should be fixed in https://github.com/zalmoxisus/redux-devtools-extension/commit/1eb618f0139144e9e2401ac04f9a04652fca8832. Please confirm if it is. The new version (0.3.1) will be available on Chrome Store in several hours, but you may build it from the repo.
