### ISSUE TITLE
Not correct js in example file

### ISSUE THREAD

**Issue by landed1** [zalmoxisus/redux-devtools-extension#111]
I refer to this line ! As someone who doesnt know this or redux currently it deserves a comment to say what its for firstly. Secondly in js equals or is greater than is supposed to be >= it confuses new arrow notation and thirdly f is undefined. It gave my js linting a nightmare.

window.devToolsExtension ? window.devToolsExtension() : f => f

window.devToolsExtension ? window.devToolsExtension() : f >= f

I dont have a nice solution for f not being defined.

**Comment by minedeljkovic** [comment]
`f => f` is not comparison expression, but function expression. It represents identity function (return whatever is received as parameter) and it is used here as "dummy" [store enhancer](http://redux.js.org/docs/Glossary.html#store-enhancer) that does nothing if devToolsExtension is not present

**Comment by landed1** [comment]
It cannot be linted as is thats all I am saying. If it is an arrow expression then its also wrong according to the linter. 
All I am saying is what the linter is telling me.

**Comment by minedeljkovic** [comment]
It is perfectly valid arrow function expression and `eslint` does not complain.
What linter do you use? Breaking of what rule is it reporting?

**Comment by landed1** [comment]
If I am unable to prove this again then mark this down to my lack of understanding thanks.
I remember it asking to have (f)=>{} the need for parenthesis around the f.
I am in linting hell atm trying to get a react project linting correctly with https://github.com/timoxley/standard-loader

**Comment by minedeljkovic** [comment]
It is probably enforcing [arrow-parens](http://eslint.org/docs/rules/arrow-parens) rule.
In that case you should just:

```js
window.devToolsExtension ? window.devToolsExtension() : (f) => f
```

I would personally recommend switching off this rule, it is fairly common practice to not write parens on single parameter arrow function expressions.

**Comment by zalmoxisus** [comment]
> I remember it asking to have (f)=>{} the need for parenthesis around the f.

It should be `(f) => { return f; }`.

As @minedeljkovic said, it's just a simple example. You can use one enhancer variable for production and another for development or like this:
```js
const enhancer = window.devToolsExtension ? 
  compose(
      applyMiddleware(thunkMiddleware),
      window.devToolsExtension ? window.devToolsExtension() : f => f
    )) :  applyMiddleware(thunkMiddleware);

const store = createStore(reducer, initialState, enhancer);
```

**Comment by landed1** [comment]
Thanks guys :)
