### ISSUE TITLE
Realtime filtering

### ISSUE THREAD

**Issue by arcanis** [zalmoxisus/redux-devtools-extension#113]
Something that could really help would be to have the ability to filter the action list at runtime, just like what [redux-devtools-filterable-log-monitor](https://bvaughn.github.io/redux-devtools-filterable-log-monitor/) does. I know that it can be filtered from the options, but it's not really convenient, since I usually want to see every type of actions, just not at the same time.

**Comment by zalmoxisus** [comment]
You can use Inspect Monitor, it can filter actions the same as Filterable monitor does.

**Comment by arcanis** [comment]
Nice! Is it possible to open this view in the devtools rather than in a popup? I've tried to set the right panel to this, but it apparently didn't worked, and I can't find a settings to change this.

**Comment by zalmoxisus** [comment]
Just released `v1.3.0`, and it's possible now to select monitors directly in the monitor window, Chrome devtools panel or browser action popup. Feel free to reopen the issue if you have other troubles or suggestions about this.

**Comment by arcanis** [comment]
I forgot to answer, but thank you, it's much better now ! :)
