### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by gpbl** [zalmoxisus/redux-devtools-extension#114]
👋  My devtools stopped working 🆘  

The window is not able anymore to automatically select the instance, and the view in the _Redux_ tab isn't reacting to dispatched actions anymore. Any idea how can I debug this? Could it be related to a bug in my code? 

The extension is throwing an error `Cannot read property 'toString' of null`. As the code is minified i don't think the stack trace would help (I think a not-minified version would help to debug, is minifying necessary?)

Thanks for this fantastic extension, I feel lost without it :)

**Comment by zalmoxisus** [comment]
Hey @gpbl,

So, when you select the instance explicitly it works, right?

To get more detailed information you should clone the branch and [run the extension from there in the development mode](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension).

**Comment by gpbl** [comment]
Nope even selecting the instance it doesn't. Now installing in dev mode, will report soon! Thanks for the fast reply !

**Comment by gpbl** [comment]
Ah! I got it: one of my actions is returning a `null` type, yet a [recent change](https://github.com/gaearon/redux-devtools-log-monitor/commit/b132439121dc63c9681ff2d148999804690c7217) to `redux-devtools-log-monitor` can't work with `null` types. I changed my action type to `NOOP` and ignored it in the extension settings.

Life is shiny again :) Thanks @zalmoxisus for the suggestions!

**Comment by zalmoxisus** [comment]
@gpbl, thanks for the details!

Strange, this should be prevented by https://github.com/gaearon/redux-devtools/pull/232.

I've just published a new release without uglifying the bundle. So the zip archive now is 1.9MB instead of 837KB (which was before), but I think it would be useful indeed to stack trace the troubels.

**Comment by gpbl** [comment]
Yes, an error is thrown when the type is `undefined`, while `null` should be a valid type to _not_ dispatch an action. I think this is a bit on the edge, I'll investigate further and eventually file an issue to the log monitor repo. 

Thanks for the not-uglifyied version 👍
