### ISSUE TITLE
Dev tools tab is blank

### ISSUE THREAD

**Issue by molily** [zalmoxisus/redux-devtools-extension#116]
Hi, first of all thank you for this great project!

I’m using the extension since months and suddenly the Chrome dev tools tab stopped working. It’s starting (“No store found” message disappears) but then it’s just blank.

In contrast, clicking on the extension button works as expected. But I prefer to use the tab.

![Screenshot](https://cloud.githubusercontent.com/assets/51251/15399972/10fd72c6-1dea-11e6-9d0c-e18a65afad59.png)

Any ideas or tips?

From my code (I’m using the standard approach, it used to work fine, haven’t changed it):

```js
let enhancer = applyMiddleware(
  thunk, reduxRouterMiddleware
);
if (process.env.NODE_ENV === 'development') {
  const DevTools = require('../DevTools').default;
  enhancer = compose(
    enhancer,
    typeof window === 'object' && window.devToolsExtension ?
      window.devToolsExtension() :
      DevTools.instrument()
  );
}
const store = createStore(reducer, state, enhancer);
```

Anything obvious that I’m missing here?

Can I provide some information that helps?

Chrome 50.0.2661.102 (64-bit) on MacOS 10.11.5
Redux DevTools 1.3.1
Redux 3.3.1
Middlewares: react-router-redux 4.0.0, redux-thunk 2.0.1

Thank you very much for your time.

**Comment by zalmoxisus** [comment]
Could you replicate this with [our examples](https://github.com/zalmoxisus/redux-devtools-extension#examples)?

**Comment by molily** [comment]
Yes, unfortunately.
![bildschirmfoto 2016-05-20 um 13 26 55](https://cloud.githubusercontent.com/assets/51251/15427648/da266246-1e96-11e6-91d7-d1d35da3a3e5.png)
My assumption is that I have a broken Chrome user profile since the devtools tab works fine in my separate Chrome Canary intsallation. I’ll try to clean my user profile somehow. :/

**Comment by zalmoxisus** [comment]
Thanks for the details. No, it's not related to the user's profile. It should be just in exception in our script. Unfortunately, Chrome doesn't show errors for devtools panels. Reloading the extension or removing and installing it again should help. If you can replicate it again after that, steps of reproducing would be welcome.

**Comment by molily** [comment]
Thanks for your help! Already removed and reinstalled the extension, but it did not fix the problem. The tab is still empty.

But I created a second, fresh Chrome profile and the tab works fine there:

![bildschirmfoto 2016-05-20 um 17 26 25](https://cloud.githubusercontent.com/assets/51251/15432829/1a2259ea-1eb0-11e6-8d0b-2807bb47748f.png)

So I guess it’s something related to my main Chrome profile.

**Comment by zalmoxisus** [comment]
That's interesting. The settings are sticked to the Chrome profile. Could you please check what are the differences on the extension's option page (just click the last button from the bottom in the popup)?

**Comment by molily** [comment]
I can’t spot any differences in the extension preferences, both look the same:

![bildschirmfoto 2016-05-20 um 23 38 50](https://cloud.githubusercontent.com/assets/51251/15443164/5972c270-1ee6-11e6-86ae-b31b1c7fb80b.png)

**Comment by crw** [comment]
I am also having this issue. Opening a panel left, right, bottom, or from clicking the toolbar icon work fine. The panel within Developer Tools itself is blank.

**Comment by zalmoxisus** [comment]
I just published `1.3.2`. It should be now an error there instead of being blank. Please let me know what error message is shown.

**Comment by derekmok9201** [comment]
I'm seeing similar behaviour. The LogMonitor is completely blank and no actions are recorded. Interestingly, when I don't use thunk in my app, everything is working fine.

I'm also seeing this error when I bring up the chrome console while the extension is focused:

`extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'toString' of undefined
    at LogMonitorAction.render (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:38846:14)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:14594:35)
    at ReactCompositeComponentMixin._renderValidatedComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:14614:33)
    at ReactCompositeComponentMixin.performInitialMount (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:14198:31)
    at ReactCompositeComponentMixin.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:14129:22)
    at Object.ReactReconciler.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:7454:36)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:13401:45)
    at ReactDOMComponent.Mixin._createInitialChildren (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:10405:33)
    at ReactDOMComponent.Mixin.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:10251:13)
    at Object.ReactReconciler.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:7454:36)handler @ extensions::uncaught_exception_handler:8`

I'm on chrome 50.0.2661.102 64 bit.
Using redux-thunk 2.1.0
Redux 3.5.2

Not sure if my problem is related, but hope it helps with this issue.

**Comment by zalmoxisus** [comment]
@derekmok9201, that is not related to this issue, but to #114. You're getting that error because you're not specifying action's type parameter somewhere in your code and LogMonitor fails.

**Comment by derekmok9201** [comment]
@zalmoxisus Ahh my bad, you are absolutely right. Thanks for the help!

**Comment by crw** [comment]
@zalmoxisus The error is:

`SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

**Comment by zalmoxisus** [comment]
@crw, thanks for the details.

You should uncheck "Block third-party cookies and site data" in Content Settings, which block access ti localStorage as indicated in [here](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document)

![blockthirdpartycookies](https://cloud.githubusercontent.com/assets/7957859/15465568/d82cf074-20dd-11e6-9221-4f3f1a1e6c94.png)

We use localStorage there to memorize the last selected monitor.

**Comment by molily** [comment]
> “Block third-party cookies and site data”

Thanks! This was the cause of my problems as well.

If I understand your change 493a4cc correctly, it will be possible in the next version to block third party cookies while using the Redux dev tools tab. Correct?

**Comment by crw** [comment]
Thanks, that fixed my issue. Question, is there a way to add an exception (in Manage Exceptions) for extensions?

**Comment by zalmoxisus** [comment]
@molily, thanks for confirming that it was the cause.

> If I understand your change 493a4cc correctly, it will be possible in the next version to block third party cookies while using the Redux dev tools tab. Correct?

Exactly, and I just published it in `1.4`, so it shouldn't break the extension anymore, but of course selected monitor will not be memorized.

Feel free to reopen the issue if there are still any troubles with that.

**Comment by zalmoxisus** [comment]
@crw, you're welcome, thank you as well for helping with tis issue.

> Question, is there a way to add an exception (in Manage Exceptions) for extensions?

On `chrome://extensions/` page check `Developer mode`, and then find the extension and click on `background page` link and you'll be able to inspect the extensions script (except what is in Chrome DevTools panel).

**Comment by igorsantos07** [comment]
I'm getting a similar issue in my setup... Every once in a while the DevTools tab works fine, but in most cases it just flicks for a brief second and then shows the "no store found" message. It works just fine from the toolbar button, for instance.
Just to be safe, I verified third-party site data: it's enabled as expected.

How could I help debug that?
Should I open a new issue instead, or you would reopen this one?

**Comment by zalmoxisus** [comment]
@igorsantos07, according the current issue, the devpanel page was blank due to an exception. In your case the data is not sent to the extension. As it flicks, most likely the url is changed.

Could you please share an example to reproduce the problem (a github repo or jsfiddle snippet)?

**Comment by yuffiy** [comment]
Hi, I got the same issues when use redux-devtools-extensions on vivlida browser or some nw.js wrapped app with `--load-extensions` argument.

All the panel works fine, but DevTools's tab still blank.

![foo](https://raw.githubusercontent.com/yuffiy/diff-redux-root/master/redux-devtool.png)

**Comment by zalmoxisus** [comment]
@yuffiy, great to see that at lest it works in panels there :) 

I'll try later to install Vivaldi and see how it works. Do you install it from Chrome Store there or it ha sits store? If Vivaldi use the same Chrome panel, you can click on those "3 dots" at the end and undock it in a separate window. Then you press Cmd + Opt + I (on Mac) or F12 / Ctrl + Shift + I (on Windows) and can debug the extension's panel to see which exception occurs. It could be some unsupported Chrome API.

About nw.js, could you please provide a simple repository I could run to reproduce the issue? I'm not familiar with it.

**Comment by zalmoxisus** [comment]
As expected, Vivaldi doesn't support full Chrome API, specifically `chrome.devtools.inspectedWindow.tabId`. I fixed that, and published in `2.13.2`. Hope that will fix `nw.js` as well.

**Comment by yuffiy** [comment]
❤️ @zalmoxisus 

Great works! Devtools tab works fine with 2.13.2.

Thanks :)

**Comment by Venryx** [comment]
I'm getting the same issue as @igorsantos07. The extension shows for a half second, then disappears, showing the "No store found. Make sure to follow the instructions." message.

Here's a screen capture: http://i.imgur.com/D2n27UG.gifv

What's especially odd is that the tab works at first, showing the data and letting you click! But then it reverts or breaks or something and then says the store isn't set up.

Also, it used to work fine a few weeks ago. I don't know when it stopped working, unfortunately...

**Comment by Venryx** [comment]
Oh, when I right click inside the Redux dev-tools tab and press Inspect, it opens another dev-tools window showing the debug info for the extension. Going to the Console tab shows this error:
```
devpanel.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'dispatch' of undefined
    at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/devpanel.bundle.js:52:22466
```

**Comment by lakesare** [comment]
@Venryx, right click and 'Reload frame' finally worked for me. It was loading indefinitely otherwise.
