### ISSUE TITLE
Save actions for re-use in the 'dispatcher'

### ISSUE THREAD

**Issue by Koleok** [zalmoxisus/redux-devtools-extension#117]
It would be awesome to either have `favorites`, or even a `history` of manually dispatched actions that you could click to re-run since repetition is in the nature of using this tool.

**Comment by zalmoxisus** [comment]
That would be really useful. It should be implemented on the [Dispatcher Monitor](https://github.com/YoruNoHikage/redux-devtools-dispatch), which we're using for that.

**Comment by jrullmann** [comment]
DispatchMonitor does a have a feature that could address this pain. You can pass it an array (or object) of action creators, and it will then let you select from that list through the tool. So you could, for example, give it the list of your existing action creators. You'll get a nice form to fill in for all of your action creators. I've tested this with redux-devtools directly and it works well.

However, I haven't figured out a way to pass an argument to Dispatcher Monitor when using redux-devtools-extension. Is that possible?

cc @YoruNoHikage

**Comment by zalmoxisus** [comment]
@jrullmann, thanks for the details. I'm aware of this functionality, but it's not that easy to implement here, as the monitors are decoupled from the application. Technically, we should serialize those functions and send them to the monitor on initialization. If someone wants to implement that here, it would be very welcome. 

Though, the current proposal for extending the Dispatcher Monitor to save the dispatched actions and replay them like in a terminal would be useful as well.

**Comment by zalmoxisus** [comment]
Implemented in [`v2.4.0`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.4.0).
