### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by oliverbienert** [zalmoxisus/redux-devtools-extension#118]
Hi,

I get the above error in the following project: [ol3-react-example](https://github.com/oliverbienert/ol3-react-example), which I forked from [pka/ol3-react-example](https://github.com/pka/ol3-react-example) and updated it to work with react 15.
When I try to use the devtools-extension, I get the above error. I guess it has something to do with an array of features that comes from [openlayers](http://openlayers.org/) and which is a deeply nested tree of stuff:
```
stringify               @   VM1887:986
stringify               @   VM1887:16
relaySerialized         @   VM1887:21
relay                   @   VM1887:21
handleChange            @   VM1887:24
(anonymous function)    @   VM1887:24
dispatch                @   createStore.js:186
dispatch                @   VM1887:1289
updateVisiblePlaces     @   index.js:64
c                       @   ol.js:23
Fb.b                    @   ol.js:25
l.xo                    @   ol.js:408
(anonymous function)    @   ol.js:394
```
The example works but I'm not able to use the devtools to look into my store. As I am at the beginning of setting up a react/openlayers project, it would be nice if there were a solution to this problem. I read somewhere else that the devtools already handle such circular references?

Regards Oliver

**Comment by zalmoxisus** [comment]
Hi,

Under `places[...].geometry` you have an infinite self reference that cannot be stringified, and obviously it wouldn't be possible to show on the monitors:
<img width="307" alt="screen shot 2016-05-21 at 10 22 46 pm" src="https://cloud.githubusercontent.com/assets/7957859/15450383/be4975f6-1fa2-11e6-97e0-4aa7f1c562c7.png">

I will add an option to filter data, so you'll be able just exclude them.

**Comment by oliverbienert** [comment]
I see..
A filter option would be good. In my own project, however, I'll try to avoid putting the whole tree to the store if possible.
Thank you. The devtools is a very useful extension!

**Comment by zalmoxisus** [comment]
Implemented in `v1.4`.  You can use it like this:
```js
window.devToolsExtension({
      actionsFilter: (action) => (action.places ? Object.assign(action, { places: [] }) : action),
      statesFilter: (state) => (state.places ? Object.assign(state, {places: [] }) : state)
}) 
```

Of course you can filter not the whole state/action.places, but only `places[n].geometry`.

**Comment by oliverbienert** [comment]
Great!
Thank you.

**Comment by vupham-zingbox** [comment]
I've tried to use window.devToolsExtension with stateFilter but doesn't seem like it does anything !?

**Comment by zalmoxisus** [comment]
Yes, `statesFilter` was renamed to `stateSanitizer ` and `actionsFilter` to `actionSanitizer`.
