### ISSUE TITLE
The `chorme.runtime.on{event name}` is not defined

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/redux-devtools-extension#119]
Just a reminder, the `chorme.runtime.on{event name}` sometimes not defined, so sometimes the Background script doesn't work. (https://bugs.chromium.org/p/chromium/issues/detail?id=601559)

It will fix in Chrome 51.

**Comment by zalmoxisus** [comment]
@jhen0409, thanks for bringing it up. I was able to experience this only when reloading the extension. So, I think, it shouldn't be a problem for regular users, who don't load it in the Developer Mode.

Anyway, thanks a lot for the details, I was searching for some fixes before, and didn't find any information!

**Comment by jhen0409** [comment]
@zalmoxisus I can get this problem in production, it causes context menu doesn't work. :\

**Comment by zalmoxisus** [comment]
@jhen0409, we could catch this and reload the extension when it happens, but it would be better to get it fixed in Chrome.

**Comment by jhen0409** [comment]
Chrome 51 is released.
