### ISSUE TITLE
bug for Time travel 

### ISSUE THREAD

**Issue by kinop112365362** [zalmoxisus/redux-devtools-extension#120]
![Uploading image.png…]()
When I use time travel, the progress bar will not make a corresponding change, but it has been effective

**Comment by kinop112365362** [comment]
![image](https://cloud.githubusercontent.com/assets/5856661/15497298/a0d2311c-21cc-11e6-9199-bef42aa1f337.png)

**Comment by zalmoxisus** [comment]
Thanks for reporting this! Fixed in `1.4.1`, which will be available on Chrome Store in about an hour.
