### ISSUE TITLE
Displaying Map in state

### ISSUE THREAD

**Issue by chroth7** [zalmoxisus/redux-devtools-extension#124]
Problem:

I have multiple `Maps` (ES2015) in my redux state, and when I inspect them in your awesome extension, it seems to think that it's an `Object` (without keys), and I cannot expand the details (see screenshot).

<img width="157" alt="screenshot 2016-05-26 11 43 53" src="https://cloud.githubusercontent.com/assets/6230368/15570586/2a3e8b1a-2337-11e6-8e37-034a0a9270a1.png">

Idea:
Best case: expand the `Map`
Alternative: open the `Map` in the `console`...?

**Comment by zalmoxisus** [comment]
Thanks for the report. There should be one of two reasons:

1. [`jsan`](https://github.com/kolodny/jsan) doesn't serialize them. You can try to `import jsan from 'jsan'` and do `jsan.parse(jsan.stringify(pathMap))` inside your application. Also, `jsan.parse(jsan.stringify(pathMap, null, null, true))`. If the first doesn't work, and the latter solves the issue than we can use it. If not, it should be implemented there.
2. [`react-json-tree`](https://github.com/alexkuz/react-json-tree) doesn't support them and should be implemented there.

**Comment by chroth7** [comment]
Thanks for the quick reply - I just ran:
    
    console.log(pathMap);
    console.log(jsan.parse(jsan.stringify(pathMap)));
    console.log(jsan.parse(jsan.stringify(pathMap, null, null, true)));

and as you suspected, that gave me (chrome):

    >> Map {"[0]" => "xyz", "[0,0]" => "abc",…}
    >> Object {}
    >> Object {}

So if I understand correctly, due to this fact, we cannot see it?
Do you want me to raise an issue at https://github.com/kolodny/jsan?

**Comment by zalmoxisus** [comment]
Thanks for the details. Yes, it will be great to investigate it there.

**Comment by kolodny** [comment]
weird, it seems to work for me. You may need to be using the latest version of jsan which used the `.toJson` method https://github.com/kolodny/jsan/blob/master/lib/cycle.js#L41-L43

Try this:

```bash
$ cd /tmp/map-jsan
$ npm init -y
$ npm install immutable jsan
$ echo " var map = require('immutable').Map({a: 1});\n console.log(map);\n console.log(require('jsan').stringify(map));" > index.js
$ node index.js
Map { "a": 1 }
{"a":1}
$
```

**Comment by zalmoxisus** [comment]
@kolodny, thanks for chiming in. As I understood, the issue is not with the immutable library, but with the native `Map` structure.

**Comment by kolodny** [comment]
Oh, this was about [Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). Ok, I think I need to spend some more time to make that work

**Comment by kolodny** [comment]
Hmm, thinking about the problem, I'm not sure I want to implement this in jsan. Extending `Map.prototype.toJSON` is probably the correct way to go. How would you stringify this?

```js
var isAnA = {toString: () => 'a'};
var obj1 = {};
var ob2 = {};
var map = new Map([
  ['a', 1],
  [isAnA, 2],
  [obj1, 3],
  [obj2, 4],
]);
```

Best bet would be to add something like this to your app:

```js
if (process.env.NODE_ENV !== 'production') {
  Map.prototype.toJSON = function() {
    var obj = {};
    this.forEach((value, key) => obj[key] = value);
    return obj;
  }
}
```

**Comment by zalmoxisus** [comment]
@kolodny, I see.

I guess just including a polyfill like [this](https://www.npmjs.com/package/map.prototype.tojson) in the app should solve the issue. @chroth7, could you check?

**Comment by chroth7** [comment]
Awesome, thanks for the super quick feedback and input.

Added the polyfill you mentioned and look at that:
<img width="188" alt="screenshot 2016-05-26 21 55 48" src="https://cloud.githubusercontent.com/assets/6230368/15588110/aead5c96-238c-11e6-8d6e-b2bfebca05cf.png">

Perfect! Thanks, very much appreciated!
(I will close this issue and the one in the other repo)

**Comment by jdavault** [comment]
import { legacy_createStore as createStore, applyMiddleware } from "redux";
import reducers, { initialState } from "./reducers";
import thunkMiddleware from "redux-thunk";
import { composeWithDevTools } from "@redux-devtools/extension";

const composeEnhancers = composeWithDevTools({ serialize: true });

export const store = createStore(
  reducers,
  initialState,
  composeEnhancers(applyMiddleware(thunkMiddleware))
);

//WORKED FOR ME ....
