### ISSUE TITLE
“No store found” 

### ISSUE THREAD

**Issue by Borisboky** [zalmoxisus/redux-devtools-extension#126]
I have the following code in my configureStore.js file :

````
import {createStore, applyMiddleware} from 'redux';
import rootReducer from '../reducers/index';
import thunk from 'redux-thunk';

export default function configureStore(initialState){
  return createStore(
    rootReducer,
    initialState,
    applyMiddleware(thunk),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  );
}
````

The code whera I use Provider and pass the store to provider is : 

```
import 'babel-polyfill';
import React from 'react';
import {render} from 'react-dom';
import {Router, browserHistory} from 'react-router';
import routes from './routes';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import './assets/sass/main.scss';
import '../node_modules/font-awesome/css/font-awesome.css';

import {loadCourses} from './actions/courseActions';
import {loadAuthors} from './actions/authorActions';
import {Provider} from 'react-redux';
import configureStore from './store/configureStore';

const store = configureStore();
store.dispatch(loadCourses());
store.dispatch(loadAuthors());

render(
  <Provider store={store}><Router history={browserHistory} routes={routes}/></Provider>, document.getElementById("app")
);
```

But when I run redux extension I see "No store found".

**Comment by zalmoxisus** [comment]
`createStore` takes only 3 parameters, the third is the enhancer. That said it should be used like that:

```js
import {createStore, applyMiddleware, compose} from 'redux';
import rootReducer from '../reducers/index';
import thunk from 'redux-thunk';

export default function configureStore(initialState){
 return createStore(
 rootReducer,
 initialState,
 compose(
   applyMiddleware(thunk),
   window.devToolsExtension ? window.devToolsExtension() : f => f
 )
);
}
```

Note that I also imported `compose` from `redux`.

**Comment by Borisboky** [comment]
It worked. Great. Thanks.

**Comment by falltodis** [comment]
I meet this too and  has tried @zalmoxisus 's suggestion , but it doest not work!
![image](https://cloud.githubusercontent.com/assets/7006864/17168771/d1eb50ea-5416-11e6-846d-f20e408006b6.png)

**Comment by zalmoxisus** [comment]
Hey @falltodis,

Maybe you are using an older version of Redux. Passing enhancer as the 3rd parameter is supported only for redux@>=3.1.0. For older version you should use it [like so](https://github.com/zalmoxisus/redux-devtools-extension/blob/v0.4.2/examples/counter/store/configureStore.js#L7-L12).

If not, please provide an example repo or jsfiddle to reproduce the problem.

**Comment by falltodis** [comment]
Tks!
The project is based on [snowflake](https://github.com/bartonhammond/snowflake) and the only change I make is a file named configureStore.js I fork that repo and  have pushed my changes. The new repo is [this](https://github.com/falltodis/snowflake) . Sorry for cant privied an example in jsfiddle.

**Comment by zalmoxisus** [comment]
The extension is meant to be used in the browser, so it could inject the script in web page. For React Native you need [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools), which would send data to the extension.
