### ISSUE TITLE
Stopped working after update to 2.0.3 

### ISSUE THREAD

**Issue by lapanoid** [zalmoxisus/redux-devtools-extension#129]
Hi, thanks for your awesome work!
I recently got autoupdated and redux-devtools-extension stopped work - I just see empty log, and no errors.
How can I debug this, or is there any way to install older version and forbid autoupdate?

**Comment by zalmoxisus** [comment]
Hey. Thanks for the report. It would be great if you could share a simple example to reproduce that problem.

**Comment by zalmoxisus** [comment]
Any updates on this? I suppose whether https://github.com/zalmoxisus/redux-devtools-extension/commit/02614ed8d60bde8ba63233372183476a3f72a6fd or https://github.com/zalmoxisus/redux-devtools-extension/commit/06afa52ecd817e5a1a496841d481f365532f76a2 could be the reason, but they are published before `2.0.3`.

You can use specific version without autoupdates just downloading a specific [release](https://github.com/zalmoxisus/redux-devtools-extension/releases) right from this repository and [build the extension](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension), Chrome autoupdates new releases. Anyway, it would be great if you could help me replicate the problem, so I could fix it.

**Comment by lapanoid** [comment]
@zalmoxisus Sure I will try and give you feedback.
Question: If I build the extension, I still can be autoupdated by Chrome later, right? In such case, I can not be sure at any time that my version is fixed and will not be changed randomly in an unexpected way. So don't have stable dev environment - that bother me a lot if I want to use redux-devtools-extension and spread it in my team. Please comment on that.

**Comment by zalmoxisus** [comment]
No, it won't. Chrome autoupdates only extensions from Chrome store.

**Comment by lapanoid** [comment]
My bad it was project issue: 
redux version was changed to 3.0.4 from ^3.0.4 that, with 3.0.4 extension is not working.
I updated to 3.3.1 and it works like a charm.
Thanks for your time!

**Comment by zalmoxisus** [comment]
@lapanoid, thanks for the details. It works with older versions of Redux, just probably that version doesn't support newer API of applying enhancer.
