### ISSUE TITLE
Chrome Extension, actions to hide is not saved

### ISSUE THREAD

**Issue by fbacker** [zalmoxisus/redux-devtools-extension#131]
Choose options for the extension and in the textarea 'Actions to hide from DevTools (from new line):' I input an event that I don't want to see (e.g. TIME_UPDATE). Close the window and open again and my change is not saved. Also tried to enter the value and in another window run my app, the event is still shown.

**Comment by zalmoxisus** [comment]
Thanks for the report! Fixed in `2.0.0.4`. Please reopen the issue if still there are any troubles with this.
