### ISSUE TITLE
Has anyone had any luck making use of extension in a typescript project

### ISSUE THREAD

**Issue by leighghunt** [zalmoxisus/redux-devtools-extension#134]
Thanks for this great extension.

I'm having an issue getting the extension working in a typescript project - and can't find any other instances of anyone combining redux, redux-devtools-extension, and typescript.

I'm wondering if it's supported?

Specifically, I'm having typescript complain when I try to update my call to ````createStore````.

See my [issue](https://github.com/jaysoo/todomvc-redux-react-typescript/issues/8) on [jaysoo/todomvc-redux-react-typescript](https://github.com/jaysoo/todomvc-redux-react-typescript) for more information and code to replicate the issue.

I'm new to TypeScript, so may be missing something stupid.

**Comment by zalmoxisus** [comment]
It doesn't seem related to the extension. That project doesn't support the third argument of `createStore`but only old redux API, which will not be supported since Redux 4.

For now you can use it like that:
```js
const enhancer = window['devToolsExtension'] ? window['devToolsExtension']()(createStore) : createStore;
const store: IStore<any> = enhancer(rootReducer, initialState);

```

**Comment by leighghunt** [comment]
Thank you so much - that works! :-)

**Comment by ryanrain** [comment]
hello all, just in case this is useful to others, i personally found this middleware-less code quite explicit:

```ts
const store = createStore(
  rootReducer,
  initialState,
  (window as any).__REDUX_DEVTOOLS_EXTENSION__ &&
    (window as any).__REDUX_DEVTOOLS_EXTENSION__()
);
```
note that you many need to set `no-any` to false in your tslint.json file

**Comment by shoter** [comment]
I made it working by using following code: (similar to @zalmoxisus code)

```

const enhancer = (<any>window)['devToolsExtension'] ? (<any>window)['devToolsExtension']()(createStore) : createStore;

const store = enhancer(applicationReducer, applyMiddleware(
    WindowsLogic
));

```
