### ISSUE TITLE
Support Electron ^1.2.1 devtools extension

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/redux-devtools-extension#135]
Electron ^1.2.1 is supported more `chrome.*` API for DevTools extension, [this is known supported extensions](https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md#supported-devtools-extensions), I think it's possible to support it here, but maybe only devpanel.

/cc @chentsulin @davej

**Comment by zalmoxisus** [comment]
That's a great news that it was [added support for extension background page](https://github.com/electron/electron/pull/5711/commits/edd8210ae5e38cfa023b0bbca50ce40e876a3454)!

**Comment by LestaD** [comment]
Support for https://github.com/GPMDP/electron-devtools-installer ?
@chentsulin @davej @zalmoxisus

**Comment by zalmoxisus** [comment]
@LestaD, thanks a ton for implementing this in `electron-devtools-installer@1.1.3 `!

@jhen0409, @chentsulin, what do you think, would it be enough or should we also have the extension on npm to add it like `require('redux-devtools-extension').install()`?

**Comment by zalmoxisus** [comment]
Up in `v2.1.0`.
