### ISSUE TITLE
Devtool is less friendly than before and won't work too

### ISSUE THREAD

**Issue by DWboutin** [zalmoxisus/redux-devtools-extension#137]
Hi!

Since the last update of the extension, my collegue and i have some big problems with it.

First, it's very less friendly to use, so much click for the same actions. My collegue, the extension won't work at all on it's computer, it's a blank tab now.

Is it possible that we revert to the last version?

Thank you! The extension rocks, but i just don't understand the new changes with way more clicks. I loved the last one ;)

**Comment by zalmoxisus** [comment]
Hi.

> Since the last update of the extension, my collegue and i have some big problems with it.

It's an opensource project, so feel free to improve it, at least by explaining what goes wrong or even better to provide an example to reproduce the problem.

> First, it's very less friendly to use, so much click for the same actions.

Could you please elaborate. What exactly do you have to click? Nothing in the UI wasn't change in 3.0.

> Is it possible that we revert to the last version?

Yes. You can [build](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension) the desired [version](https://github.com/zalmoxisus/redux-devtools-extension/releases) instead of installing it from Chrome store.

> Thank you! The extension rocks, but i just don't understand the new changes with way more clicks. I loved the last one ;)

Thanks for the feedback :) I still don't get what more do you have to click comparing to the earlier versions.

**Comment by DWboutin** [comment]
The clicks, we have to select an event and don't just scroll to it. We get lost very quickly here! We work with it everyday. We loved the scrolling section without to have to select the event manually.

I just understand the pin function, it can be great! I was lost this morning, i clicked on it and i wasn't able to return to the full state.

I speak here about the V.2, we run actually the 2.0.1 from the Google store.

**Comment by zalmoxisus** [comment]
Just click again on that event (action) and it will not be pinned.

Anyway, if you like Log Monitor more than Inspector Monitor (which is by default now), you can use it like before, just select it from the top dropdown:
<img width="607" alt="redux_devtools" src="https://cloud.githubusercontent.com/assets/7957859/16034541/0dfcc406-321b-11e6-9440-666355be5891.png">

Please let me know if that was the issue.

**Comment by DWboutin** [comment]
Ho yeah!

It's that! Thank you so much

2016-06-14 3:31 GMT-04:00 Mihail Diordiev <notifications@github.com>:

> Just click again on that event (action) and it will not be pinned.
>
> Anyway, if you like Log Monitor more than Inspector Monitor (which is by
> default now), you can use it like before, just select it from the top
> dropdown:
> [image: redux_devtools]
> <https://cloud.githubusercontent.com/assets/7957859/16034541/0dfcc406-321b-11e6-9440-666355be5891.png>
>
> Please let me know if that was the issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zalmoxisus/redux-devtools-extension/issues/137#issuecomment-225801572>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABQsFli8M1SS-jhBx8ItaEZmn6irvkVhks5qLljIgaJpZM4I0W5l>
> .
>



-- 
*Mikaël Boutin*
*Développeur **web **"front-end"*
*Twitter :* @DWboutin <http://twitter.com/#%21/DWboutin>
Github : DWboutin <https://github.com/DWboutin>
LinkedIn: https://ca.linkedin.com/pub/mikael-boutin/27/732/b47

*(581) 999-1252*

**Comment by zalmoxisus** [comment]
You're welcome!

If you still have any problems there, feel free to open an issue and provide some details on how to reproduce that:
> My collegue, the extension won't work at all on it's computer, it's a blank tab now.
