### ISSUE TITLE
Is there a safe way to switch the config  between development and production mode?

### ISSUE THREAD

**Issue by handane123** [zalmoxisus/redux-devtools-extension#138]
I  have to remove the code in store when  in the production mode by hand, Is there a way to config 
between different mode?

**Comment by zalmoxisus** [comment]
Could you please elaborate or provide an example of what you're are trying to do?

**Comment by handane123** [comment]
![1](https://cloud.githubusercontent.com/assets/7983700/16022571/0ecc1d8a-31eb-11e6-83c2-a986b43c8ca0.PNG)

**Comment by handane123** [comment]
What I want is that when the project is under production mode, how to comment the code which used to
connect the chrome devtools extension without doing it by hand. Instead, I can config it using webpack or any  other available ways?

**Comment by zalmoxisus** [comment]
A good practise (for other libraries as React as well) is to have a global variable set in webpack config, which indicates the environment like
```js
globals: {
    'process.env': {
      NODE_ENV: '"production"'
    }
  }
```

and you can use the extension as follows:
```js
export default function configureStore(preloadedState) {
  const store = createStore(reducer, preloadedState,
    process.env.NODE_ENV !== 'production' &&
    typeof window !== 'undefined' && window.devToolsExtension &&
    window.devToolsExtension()
  );
  return store;
}
```

**Comment by handane123** [comment]
Thanks!
