### ISSUE TITLE
Redux-devtools suddenly not working

### ISSUE THREAD

**Issue by rasmuswoelk** [zalmoxisus/redux-devtools-extension#141]
Hi

I'm a big fan of the redux-devtools extension but lately I have noticed that it stopped working.

It has always worked without problems but now it only shows the @@INIT action when opening the devtools in Chrome. Once I dispatch an action it doesn't record it. The redux actions are functioning correcly.

**This is my setup:**
- Chrome Version 52.0.2743.33 beta (64-bit)
- Redux  3.5.2
- Redux DevTools 2.0.1
- Recently switched to webpack (could that have an impact?)

I have set it up through my store file like this:

```
	export default function configureStore(initialState) {
	  const store = createStore(
	    reducers,
	    initialState,
		compose(	applyMiddleware(PromiseMiddleware, ThunkMiddleware, LoggerMiddleware),
		window.devToolsExtension ? window.devToolsExtension() : f => f
		));

	  return store
	}
```

I have absolutely no idea what is going on since it has always been working fine.
Has anyone else experienced this or could someone maybe point me in a direction. That would be great, thanks!

PS. Great work on the extension. Saves me for a lot of dev hours! 8-]

**Comment by zalmoxisus** [comment]
Thanks for the feedback and the details. The configuration looks fine.

Please check if it works with [our demos](https://github.com/zalmoxisus/redux-devtools-extension#demo) to see if it is related specifically to your app. Also try changing the monitor from the top of the extension's window.

**Comment by rasmuswoelk** [comment]
Hi again

Thanks for the answer :-)

So it is working with the demos. Weird.

Do you mean changning from the Log Monitor to the Chart or what do you mean when you say changing monitor? 

The redux-logger is logging just fine. So weird.

**Comment by zalmoxisus** [comment]
> Do you mean changning from the Log Monitor to the Chart or what do you mean when you say changing monitor?

Yes, also try to select instances explicitly (from the second select).

**Comment by zalmoxisus** [comment]
If you could share an example to reproduce, I'd look into it. Or you can [run the extension in dev mode](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension). And debug it. It's not that hard because you have to inspect only [`pageScript.js`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js), which should send changes to the extension's background script.

**Comment by rasmuswoelk** [comment]
Hi again

I have tried running the extension in dev mode - still not working. Also I tried other computers with other versions of Chrome - same problem.

It's something with my system and I will try to debug it when I have time. I will return if I find anything.

How do I inspect pageScript.js? Can I do it from console?

**Comment by zalmoxisus** [comment]
@rasmuswoelk, thanks for the details. Most probably it is related to Promise Middleware.

Try to [update the store after creating it](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#windowdevtoolsextensionupdatestorestore-instanceid) by adding:
```js
if (window.devToolsExtension) window.devToolsExtension.updateStore(store);
```

**Comment by zalmoxisus** [comment]
Just tried [simple](https://github.com/pburtchaell/redux-promise-middleware/tree/master/examples/simple) and [complex](https://github.com/pburtchaell/redux-promise-middleware/tree/master/examples/complex) examples of [`redux-promise-middleware`](https://github.com/pburtchaell/redux-promise-middleware) and it works as expected. If you're sure you don't mutate the state somewhere (you can check it by [adding `redux-immutable-state-invariant` middleware](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/counter/store/configureStore.js#L3)), it would be useful if could fork one of that examples and try to reproduce the issue.

**Comment by rasmuswoelk** [comment]
Hi again

I was mutating the state in my actions by accident and the `redux-immutable-state-invariant` found the issue for me.

**It is now working!** 

Thanks for your extensive support and great package for debugging these issues!

**Comment by brambow** [comment]
Just wanted to comment that I experienced an issue with DevTools exhibiting this same behavior, but the problem wasn't mutating the store.  The offending application uses Apollo to connect to a graphql server, and a large request/response from that seems to mess with this extension.  Removing the specific apollo query appears to have the extension working properly again.

**Comment by afisher88** [comment]
I had this issue (just seeing the @@init) and it turned out I had accidentally created another store instance which the instances dropdown was defaulting to instead of the instance associated with my actions. Removing this solved my problem.

**Comment by sziebertAu** [comment]
Hi everyone,
I just want to share my experience with people in the future who fight with the same issue.
My problem was i accidentally left some deleted constants in the `actionsBlacklist`. So there was some `undefined` in the array.
As i removed them, all the actions became visible after the @@INIT.

**Comment by 3DEsprit** [comment]
I just had this happen as well after using the devtools successfully on an app for some time. The only thing that changed was an update to redux-form and react-redux, and upgrading from 2.4.1 to 2.5.0 fixed the issue.

**Comment by tonymedrano** [comment]
Right click Redux DevTools (not inspect) and bam!

**Comment by MohammedAlabd** [comment]
Hi all, I was experiencing the same error here, and after hours of debugging I figured out that someone is creating an extra store somewhere in the code, when I removed it everything back to work correctly, 
so maybe check the code to see if you are creating another redux store somewhere

**Comment by ackvf** [comment]
Interesting, for me, the devtools would stop logging any events right on the moment I added `logger` into the middlewares array. With hot module replacement, the effect would be after first dispatched action.

Maybe related, I just implemented `redux-persist` and then added `redux-logger`. I am not sure if I would observe the same behavior just with `redux-logger` without `redux-persist`.

<details>
  <summary>store.ts</summary>
  
```ts
import type { Reducer } from '@reduxjs/toolkit'
import { configureStore, combineReducers } from '@reduxjs/toolkit'
import { persistStore, persistReducer, PersistConfig, PersistorAction, PersistorState, PersistorSubscribeCallback, Persistor as OriginalPersistor } from 'redux-persist'
import * as rp from 'redux-persist'
import storage from 'redux-persist/lib/storage'
import hardSet from 'redux-persist/lib/stateReconciler/hardSet'
import logger from "redux-logger";

import createCollectionForm from './slices/CollectionFormSlice'
import auth from './slices/AuthSlice'
import { ENABLE_REDUX_LOGGER } from '../constants'

console.debug('ENABLE_REDUX_LOGGER', ENABLE_REDUX_LOGGER)

const persistConfig: PersistConfig<CombinedState> = {
  key: 'root',
  storage,
  stateReconciler: hardSet, // Rewrite all state with persisted state.
  version: 1,
  blacklist: [], // List of slices to not persist (compare `whitelist`).
}

type CombinedState = typeof rootReducer extends Reducer<infer U, any> ? U : never

const rootReducer = combineReducers({
  auth,
  createCollectionForm,
})

const persistedReducer = persistReducer(persistConfig, rootReducer)

export const store = configureStore({
  reducer: persistedReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: {
        ignoredActions: [rp.FLUSH, rp.REHYDRATE, rp.PAUSE, rp.PERSIST, rp.PURGE, rp.REGISTER],
      },
    // }).concat(...[ENABLE_REDUX_LOGGER && logger].filter(def => def)),
    }).concat(logger),
})

export const persistor: Persistor = persistStore(store)


export type RootState = ReturnType<typeof store.getState>
export type AppDispatch = typeof store.dispatch


/**
 * A persistor is a redux store unto itself, allowing you to purge stored state, flush all
 * pending state serialization and immediately write to disk
 *
 * *note: Overriding the original interface because of missing JSDoc comments.*
 *
 * https://github.com/rt2zz/redux-persist
 */
interface Persistor extends OriginalPersistor {
  /** immediately writes all pending state to disk and returns a promise */
  flush(): Promise<any>
  /** purges state from disk and returns a promise */
  purge(): Promise<any>
  /** pauses persistence */
  pause(): void
  /** resumes persistence */
  persist(): void
}
```
</details>

**Comment by captainjmac** [comment]
Just thought I'd chime in to say that I had a similar problem with the redux not working on any site. Removing & re-adding the redux dev tools extension seemed to get things working again
