### ISSUE TITLE
Support for Symbol action types

### ISSUE THREAD

**Issue by avraam-mavridis-sociomantic** [zalmoxisus/redux-devtools-extension#142]
Some folks define their actions like

`Symbol.for('DO_SOMETHING_ACTION')`

Instead of

`const DO_SOMETHING_ACTION = "DO_SOMETHING_ACTION";`

In that case the logged action is empty:

![screen shot 2016-06-20 at 14 05 10](https://cloud.githubusercontent.com/assets/14922483/16193531/10693cae-36f0-11e6-9d8b-685dfb84c05d.png)

Any plan for supporting/logging Symbol based action types?

**Comment by zalmoxisus** [comment]
The reason for this is that the result of `JSON.stringify({type: Symbol.for('DO_SOMETHING_ACTION')})` is `{}`.

To support it use [`serializeAction` property](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#windowdevtoolsextensionconfig) as following:
```js
window.devToolsExtension({
  serializeAction: (key, value) => {
    if (typeof(value) === 'symbol') return String(value);
    return value;
  }
})
```

We cannot have it by default as it will slow the serialization, unless @kolodny has any ideas on how to better support it in `jsan`.

**Comment by avraam-mavridis-sociomantic** [comment]
it's just a matter of wrapping the type with `Symbol.keyfor` ?

Like

Symbol.for("DO_SOMETHING_ACTION"); // create a new global symbol
Symbol.keyFor(Symbol.for("DO_SOMETHING_ACTION"); ); // "DO_SOMETHING_ACTION"

**Comment by zalmoxisus** [comment]
@avraam-mavridis-sociomantic, I think it's easier to show the extension how to serialize symbols than changing your code. You can use `Symbol.keyFor` in `serializeAction` parameter's function instead of `String`.

**Comment by zalmoxisus** [comment]
Implemented in `v2.8.5`, just set `serializeAction` parameter to `true` and they will be serialized. Optionally `serializeState` could be set to `true` as well.

**Comment by CameronFletcher92** [comment]
We are having problems with this new API. Initially we tried setting both `serializeAction` and `serializeState` to `true`, end ended up with the following console error:

`VM55116:2 Uncaught TypeError: Cannot read property 'toJS' of null(…)`

Our action types just look like this:
```javascript
export const SET_CONTEXT = Symbol('SET_CONTEXT');
```

So we then tried to manually serialize symbols by overriding both `serializeAction` and `serializeState` with the following function:

```javascript
const serializeSymbols = (key, value) => {
        if (typeof value === 'symbol') {
            return value.toString();
        }

        return value;
};
```

This resulted in our state/diffs being munged with references to $jsan...
![image](https://cloud.githubusercontent.com/assets/1721120/19955128/6bac2b4c-a1d2-11e6-9ddc-3959764d1c9b.png)

**Comment by zalmoxisus** [comment]
@CameronFletcher92 thanks for the detailed report. Setting just `serializeAction` to `true` (without setting `serializeState`) should help.

Could you please provide an example or steps to reproduce those 2 bugs? I tried to replace [this line](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/counter/actions/counter.js#L14) with `type: Symbol('SET_CONTEXT')` and in both case (setting `serializeAction` to `true` and to `serializeSymbols`) it works as expected (I get that stringified symbol).

**Comment by zalmoxisus** [comment]
@CameronFletcher92 could you please provide the stack trace for the exception you've got, [it shouldn't happen when the value is null](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/api/index.js#L12)

**Comment by nponiros** [comment]
Hi there,

I also have issues with symbols not being displayed properly. I use version 2.11.1 of the chrome extension.
I tried using `serializeAction: true` with `Symbol('foo')` and `Symbol.for('foo')` and in both cases no name was displayed for the action. In the action tab the `type` was `Symbol('foo')` (in both cases). When I use a function for `serializeAction` all works as expected.

If you need any more info just let me know.

PS. I did not try `serializeState`

**Comment by zalmoxisus** [comment]
Hey @nponiros,

Thanks for the report! In recent versions we delegated that part to [`jsan`](https://github.com/kolodny/jsan/pull/9), and are getting the symbols back on teh extension part (instead of the stringified value).

However, it seems that Inspector Monitor doesn't support symbols. For now, you can stringify them as you did, or can use Log Monitor instead which support symbols.

**Comment by nponiros** [comment]
Hi @zalmoxisus thanks for the info. I will just stringify them :)

**Comment by anisometropie** [comment]
more up to date way to configure serialization in redux-devtools :
https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/API/Arguments.md#serialize
