### ISSUE TITLE
API for checking whether the monitor is open

### ISSUE THREAD

**Issue by rybon** [zalmoxisus/redux-devtools-extension#145]
Is it possible to call a method on `window.devToolsExtension` to determine whether the DevTools monitor is currently open or closed? I'd like to use that information to conditionally disable side effects. As far as I know we can only check whether `window.devToolsExtension` is available.

**Comment by zalmoxisus** [comment]
There's no such method in our API, but it wouldn't be hard to implement (the only problem is when having more instances in one tab).

Could you tell me about your user case? Maybe better to provide a way to check when a monitor action is applied (toggling, moving, back and forth, importing actions...) to prevent side effects in this case?

Also related to #140.

**Comment by rybon** [comment]
You're right, a more granular way of disabling side effects would indeed be preferable.

Starting with opening and closing the monitor seems to be the easiest and quickest way for now however. I'm currently using redux-saga and my idea is to combine that functionality with a hook in redux-saga to conditionally disable the processing of side effects. In redux-saga, side effects are not executed immediately, instead they are declared using descriptor objects that are then processed at a later stage. Wrapping all side effects in sagas means one has more control over them, as they can now be intercepted and optionally cancelled.

**Comment by zalmoxisus** [comment]
Could you share a snippet of how you want to integrate it in sagas?

If you prevent all side effects when the extension's monitor is open, that means you'll not be able to use it for logging and remote control, only for dispatching monitors actions.

**Comment by rybon** [comment]
In redux-saga you have the option to add a SagaMonitor as part of initializing the saga middleware. In my local fork of redux-saga I've just added another method to the monitor that is invoked in `runEffect`. The method just returns a boolean and short-circuits the `runEffect` method accordingly. This means I have control over the processing of the side effects. I just need a way to dynamically return that boolean based on some state, for example the DevTools being open or not. Relevant: https://github.com/gaearon/redux-devtools/issues/167#issuecomment-192750660.

Of course, a better solution would be what Cerebral does and that is to keep track of which side effect caused what output, and only replaying the output instead of the side effects when time travelling. A proper solution is still under discussion however, see https://github.com/yelouafi/redux-saga/issues/5 and https://github.com/yelouafi/redux-saga/issues/22.

For now though, a hook would do the trick until we have found a better way.

**Comment by zalmoxisus** [comment]
@rybon, I was thinking about this, and adding a function like `window.devToolsExtension.isMonitoring` to the API would cause conflicts for multiple instances (stores). A solution would be to get this function when invoking the enhancer like
```js
const sagaMiddleware = createSagaMiddleware();
let isMonitoring;
const store = createStore(
  reducer,
  compose(
    applyMiddleware(sagaMiddleware),
    window.devToolsExtension && window.devToolsExtension({ isMonitoring })
  )
);
sagaMiddleware.run(rootSaga, isMonitoring);
```

Anyway, we want to monitor sagas as well (which I want to implement in the nearest future), so such a solution wouldn't be viable. Better to have something like `isTimeTraveling` or/and `isMonitorAction` instead of `isMonitoring`.

What do you think?

**Comment by rybon** [comment]
Looks alright to start with. I presume `isMonitoring` will be set to true or false by `devToolsExtension`? Wouldn't it be better to wrap it in a callback, so that can be invoked inside redux-saga to fetch the latest `isMonitoring` value? See https://github.com/yelouafi/redux-saga/pull/410 for an example.

**Comment by zalmoxisus** [comment]
Yes, it would be a function, which returns `true` or `false`.

Can we just use `isTimeTraveling` instead of `isMonitoring`? Are other cases when we want to disable side effects?

**Comment by rybon** [comment]
Sure, `isTimeTraveling` is fine with me. Regarding other cases, I suppose I'd also want to disable side effects when replaying a Redux log in a test suite, for example based on `process.env.NODE_ENV === 'test'`. But that would be a static value that wouldn't change at runtime.
In my redux-saga PR, I added a hook so developers can decide for themselves when side effects should be disabled.

**Comment by zalmoxisus** [comment]
Implemented in `v2.3.0`. See [the description](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.3.0) and [the example of usage](https://github.com/zalmoxisus/redux-devtools-extension/commit/352f0797f041866cf1d73ed5bf1008a6096813ea).

A PR with a recipe or an example of usage with sagas would be much appreciated.

**Comment by rybon** [comment]
Thanks! An example with my forked redux-saga repo will be forthcoming.

**Comment by zalmoxisus** [comment]
There's a better way now to prevent side effects from middlewares like redux-saga. [See the post](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83) for details on how to get it.
