### ISSUE TITLE
Building error when trying to build extension with v2.2.0

### ISSUE THREAD

**Issue by jbleuzen** [zalmoxisus/redux-devtools-extension#147]
I'm trying to build the extension to embed it in an Electron application and when I try to build v2.2.0 I have this error :
```
ERROR in ./src/app/containers/App.js
Module not found: Error: Cannot resolve module 'remotedev-app/lib/components/TestGenerator' in [...]/redux-devtools/src/app/containers
 @ ./src/app/containers/App.js 56:21-74
```

No problem with version v2.1.0...

**Comment by zalmoxisus** [comment]
It works now using `remotedev-app@alpha-2`, though without the "Test" tab till https://github.com/alexkuz/redux-devtools-inspector/pull/38 gets merged.

We're running tests on Travis and Appveyor now to prevent such cases.

Thanks a lot for the report!
