### ISSUE TITLE
Chrome extension broke today.. blank page

### ISSUE THREAD

**Issue by born2net** [zalmoxisus/redux-devtools-extension#150]
see here:

![image](https://cloud.githubusercontent.com/assets/5090936/16436292/904fa568-3d51-11e6-8687-b10882770c23.png)

**Comment by nickw444** [comment]
Also having the same issue. Won't load on the sample github.io pages either.

**Comment by born2net** [comment]
Is there a way to lock out updates?
I really would rather stay with a stable version and not be "pushed" updates

**Comment by nickw444** [comment]
I just checked out 2.1.0, and built the extension and installed as a unpacked extension for now.

**Comment by born2net** [comment]
ok tx.. I'll wait for the fix

**Comment by yarcub** [comment]
@zalmoxisus: What do you think on having some sort of different channels (stable vs "canary") for the extension? Maybe publish the *canary* one as unlisted so that anyone searching through the chrome web store doesn't install a not stable version.

That way we could have feedback, from people who actively follow this project and opt-in for it, if there was some breaking changes. 💭

**Comment by wnewby** [comment]
... broken here too. Built and running 2.10

**Comment by nickw444** [comment]
Saving a the time of others who may need to build this. Here is a zip of the unpacked build of 2.10

[extension.zip](https://github.com/zalmoxisus/redux-devtools-extension/files/338322/extension.zip)

**Comment by j-** [comment]
Also experiencing this problem (v2.2.0.2). Console has the following error:

![screenshot from 2016-06-29 10 52 41](https://cloud.githubusercontent.com/assets/590992/16437139/823ed4c6-3de7-11e6-91ec-54beed024627.png)

**Comment by pcanterini** [comment]
Looks like a [typo](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/containers/App.js#L37) in `App.js`

```
localStorage.getItem('monitor' + monitorPosition])
------------------------------------------------^
```

But I've also had some issues with the [remotedev-app](https://github.com/zalmoxisus/remotedev-app) package when trying to build this version of the redux-devtools-extension. For one it's failing linting on `prepublish`

**Comment by yoongfook** [comment]
Same here - breaking ...

**Comment by andrewmclagan** [comment]
ouch 4 hours later... :-(

**Comment by jasan-s** [comment]
@nickw444  the build only work in external window not in the chrome dev panel. is that chrome thing for unpacked extentions?

**Comment by xyc** [comment]
+1

**Comment by tedscape** [comment]
+1

**Comment by zalmoxisus** [comment]
Sorry about that.

@tomchentw fixed it in #151 also added ESLint prebuilt tasks to avoid such cases.

`2.2.0.3` is published on Chrome Store and should be available in about an hour.

**Comment by zalmoxisus** [comment]
@born2net,
> Is there a way to lock out updates?
Yes, you can clone this repository and [build it](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension).

@yarcub,
> @zalmoxisus: What do you think on having some sort of different channels (stable vs "canary") for the extension? Maybe publish the canary one as unlisted so that anyone searching through the chrome web store doesn't install a not stable version.
> That way we could have feedback, from people who actively follow this project and opt-in for it, if there was some breaking changes. 💭

Extensions from Chrome store are autoupdated by Chrome automatically. There's a way to make a new release available only for a randomly selected amount of people, to get the feedback, which should help in such cases. Though much better would be to have good tests here, so I wouldn't have to check manually every PR.

**Comment by andrewmclagan** [comment]
@zalmoxisus again thanks for all your work
