### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#153]
It was procrastinating for such a long time, and I am feeling guilty for [such cases](https://github.com/zalmoxisus/redux-devtools-extension/issues/150) 😨

We need to

- [x] test [the react component](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/containers/App.js) with enzyme;
- [x] add e2e tests for the extension's window;
- [x] add e2e tests for the injected page script.

Don't know if it is possible to test Chrome/Electron devtools panel. Maybe @jhen0409 could help here?

**Comment by jhen0409** [comment]
I can try for test Electron devtools panel (https://github.com/zalmoxisus/redux-devtools-extension/pull/149#issuecomment-229300096), and I don't know how to test devtools panel on Chrome. :\

**Comment by zalmoxisus** [comment]
@jhen0409, since we'll have tests for the extension's window which is almost the same, the test Electron devtools panel. If it's possible to implement, would be very welcome.
