### ISSUE TITLE
Make the serialization faster

### ISSUE THREAD

**Issue by mrdanimal** [zalmoxisus/redux-devtools-extension#159]
Since the last update, as soon as I open the extension my app will hang. After about a minute, I get an error in the console: `Uncaught RangeError: Invalid string length`, then the app is responsive again. I'm working on a fairly large app and the extension had been getting less responsive recently prior to this bug, so I think there was already something in my app that's causing a conflict. Here's the full error:

```
Uncaught RangeError: Invalid string length
stringify @ VM55:6214
toContentScript @ VM55:6522
relay @ VM55:128 
onMessage @ VM55:158 
(anonymous function) @ VM55:6551
handleMessages @ VM55:6549 
```

Let me know if there's any other info that would be helpful or if you have any thought about what types of stuff in an app could cause this error. Thanks!

**Comment by zalmoxisus** [comment]
Thanks for the detailed report! It shows that it hangs in [`jsan`](https://github.com/kolodny/jsan) stringify function. The point is that your state object is very large and / or have circular references there, so the serialisation takes a lot of time.

You can check it simply by running `store.liftedStore.getState()` inside your app and try to import `jsan` and execute `jsan.stringify(store.liftedStore.getState())`.

In case you just have a very big object there (for example some blobs), you can strip them as following:
```js
const actionsFilter = (action) => (
  action.type === 'FILE_DOWNLOAD_SUCCESS' && action.data ?
  { ...action, data: '<<LONG_BLOB>>' } : action
);
const store = createStore(rootReducer, window.devToolsExtension && window.devToolsExtension({
  actionsFilter,
  statesFilter: (state) => state.data ? { ...state, data: '<<LONG_BLOB>>' } : state)
}));
```
More details in [the docs](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#windowdevtoolsextensionconfig).

If there's nothing to strip, then you can just set a lower value for `actions history limit` in settings.

Please let me know whether it helps.

**Comment by mrdanimal** [comment]
Thanks for the help! I was able to quickly get it to be functional by lowering `actions history limit`. Offhand, I don't think there's anything I can strip out of my store, but I'll do some investigating and see if I can improve the situation more.

**Comment by zalmoxisus** [comment]
@mrdanimal, thanks for the details. BTW, if you don't use circular references and Immutable library, you can disable serialization at all in the settings, but I guess it's not the case otherwise it shouldn't be so slow.

I'd like to make serialization in `jsan` faster (I tried also other libraries before), but not sure it's possible. If you'll have time to investigate further why [that function](https://github.com/kolodny/jsan/blob/master/lib/index.js#L3) is hanging when calling `jsan.stringify(store.liftedStore.getState())`, it would help a lot.

**Comment by zalmoxisus** [comment]
@mrdanimal the performance was increased significantly in `v2.9.0`. See [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.9.0) for more details. If you're still experiencing this, feel free to reopen the issue.
