### ISSUE TITLE
Prevent from automatically opening (default hidden state)

### ISSUE THREAD

**Issue by samwalshnz** [zalmoxisus/redux-devtools-extension#160]
Is there a way to initialise the devtools panel without it automatically opening (i.e. staying hidden until shortcut or extension button is pressed)?

**Comment by zalmoxisus** [comment]
Actually, it does. It is not initialised until you open it (click on the panel's name). You can see it loading when first open it.

There's other problem, if you open it and then switch to other tab (Elements, Console...) it will be still active until you close Chrome devtools panel at all. There's no way to catch such event, and the same problem is for React devtools. There's no such problem when you use devtools from the extension window, it's the recommended way and it works much faster then using it from Chrome devtools panel. Also, there're [shortcuts](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/FAQ.md#keyboard-shortcuts) for this case.

**Comment by samwalshnz** [comment]
No longer having this issue anymore. devtools extenion is now working without having to run the `open` method. You can close this issue, thank you :)
