### ISSUE TITLE
Ignore/collapse particular actions

### ISSUE THREAD

**Issue by dallonf** [zalmoxisus/redux-devtools-extension#163]
I have no idea how this would work, so I'll just describe my use case and maybe that can start an interesting discussion of how to do this...

In my app, I have an action that is triggered on mouse move. Needless to say, there are a _lot_ of these and it significantly impacts both performance in dev (to the point where the app may hang while DevTools are open) and makes the DevTools much less useful (because the action I actually want to see is lost in the flood of mouse moves).

In addition, in this particular case, all the reducer does in response to this reducer is set a value that is a direct function of the action (that is, not dependent on previous state - basically, it's just setting the mouse coordinates). So if, say, all but the most recent occurrence of this action were pruned from the log, the behavior of the app would be virtually identical.

What might be a good way to solve this problem? I'd imagine it could come up in a lot of other use cases as well.

**Comment by zalmoxisus** [comment]
You can filter specific actions whether by specifying them on the extension's options page (click Settings button) or by adding [`actionsBlacklist` array](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#windowdevtoolsextensionconfig).
