### ISSUE TITLE
DevTools interferes with the work of middleware crashReporter

### ISSUE THREAD

**Issue by brusherru** [zalmoxisus/redux-devtools-extension#165]
In my project, I have to catch errors in the reducers and handle it on my own. I had used DevToolsExtension for Chrome to make development handy. And I discovered a bug: exceptions won't be caught by middleware if DevToolsExtension is turned on. And exception just falls into a console (and devtools) and an application won't work anymore.
But if I turn off DevToolsExtension (or remove it from `compose`) middleware works fine!
As the basis of middleware, I took a `crashReporter` from Redux Documentation.

Here is my code:
```
// middleware.js
import { compose, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';

const crashReporter = store => next => action => {
  try {
    console.log('crashReporter');
    return next(action);
  } catch (err) {
    console.error('Caught an exception!', err);
  }
};

const devTools = (
  typeof window === 'object' &&
  typeof window.devToolsExtension !== 'undefined' ?
  window.devToolsExtension() :
  f => f
);
export const EditorMiddleware = compose(
  applyMiddleware(crashReporter, thunk),
  devTools
);

// app.jsx (line from constructor method)
this.store = createStore(Reducers, initialState, EditorMiddleware);
```

Now I turned off DevTools Extension and switched to the redux-devtools (container and DevTools.instrument() in `compose`). And this works fine.

If I do something wrong and there is no bug — please tell me how I can fix it.
Thanks.

**Comment by zalmoxisus** [comment]
Thanks for the report. Yes, it works in `redux-devtools` as you get the latest version of the instrumentation, where [it was implemented](https://github.com/zalmoxisus/redux-devtools-instrument/issues/5). It will be possible to turn error catching off in the next version of the extension as well.

**Comment by zalmoxisus** [comment]
Now you can disable that just by unchecking `Show errors` option in the settings.
