### ISSUE TITLE
Logic behind "not serializable" state

### ISSUE THREAD

**Issue by grifotv** [zalmoxisus/redux-devtools-extension#166]
What is the logic behind the "not serializable" state?

![screen shot 2016-07-11 at 12 01 55](https://cloud.githubusercontent.com/assets/435351/16728621/664f8eb4-475f-11e6-9c7c-07390d0ade0a.png)

At the moment I have a long object with an array of objects.

Thanks

**Comment by grifotv** [comment]
Ops, this should be logged in the Redux Devtools https://github.com/gaearon/redux-devtools

Appologies :)

**Comment by zalmoxisus** [comment]
Hey @grifotv,

Thanks for the report. Fixed in https://github.com/romseguy/d3-state-visualizer/pull/5

**Comment by grifotv** [comment]
Thanks!

**Comment by zalmoxisus** [comment]
@grifotv, yes, if you're using it from Chrome Store, the addition will come automatically when we release the next version (will try to do it tomorrow). In case you're building the extension from the sources, you still need that PR to be merged.
