### ISSUE TITLE
Angular 1

### ISSUE THREAD

**Issue by matt328** [zalmoxisus/redux-devtools-extension#167]
I'm not able to get time travel working with an Angular 1 app using ng-redux.  The vanilla dev tools embedded in the page works just fine.  I set up a logging middleware and the extension doesn't seem to be changing the store at all.

**Comment by zalmoxisus** [comment]
Thanks for the report. Could you provide a project I could clone and run or an example on jsfiddle to reproduce the issue? I've tried [the official example from there](https://github.com/angular-redux/ng2-redux/tree/master/examples/counter) but it shows errors not related to the extension and cannot run.

**Comment by matt328** [comment]
Upon further inspection I discovered the problem is with redux-ui-router, and not devtools-extension.  I'm trying to set up Angular 1, ng-redux, redux-ui-router, and redux-devtools-extension, too many cooks in the kitchen.

**Comment by zalmoxisus** [comment]
@matt328, if this middleware changes the store you can add
```js
if (window.devToolsExtension) window.devToolsExtension.updateStore(store)
```
as indicated in [the troubleshooting](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#extension-ignores-redux-saga-or-other-store-enhancers-which-change-the-store-object).
