### ISSUE TITLE
Option for width/height

### ISSUE THREAD

**Issue by quicksnap** [zalmoxisus/redux-devtools-extension#17]
I'd love to make the devtools popup larger. Will Chrome allow for that? I haven't worked in extension-land in a while.

If you can provide some pointers, I could maybe get some time for a PR.

Thanks!

**Comment by zalmoxisus** [comment]
Hey, @quicksnap.

Yes, it's just css, set [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/views/window.jade).

Why only popup? The popup has 300px witdth, and the window 320px.

**Comment by quicksnap** [comment]
Annnd now I see that you can open it as a window. And resize it.

Perhaps I should alter my PR to provide a link to open it as a window in the popup =)

**Comment by quicksnap** [comment]
Also, this kicks ass.

**Comment by zalmoxisus** [comment]
Yes, a maximize button in the popup would be amazing. I [planned it](https://github.com/zalmoxisus/redux-devtools-extension/issues/6), but ended just with adding the instruction in the README, as I'm not so good in design.

With today's release, it would be easy to implement. To open the window we may just call `window.devToolsExtension.open()`.

**Comment by zalmoxisus** [comment]
Hey, @quicksnap. I extended popup width to `350px` in `0.4.3`. It should be enough the most of cases. Since the window is resizable, I figure we do not need it configurable.

I will add an 'expand' button to the action page (popup) in `0.5.0`. Till then, I'll keep this issue open.

**Comment by quicksnap** [comment]
Cool! Yeah, I'm satisfied with it as-is for now, just knowing I can detach the window. More options are always cool, too =)

**Comment by zalmoxisus** [comment]
Implemented in `v1.0.0-beta1`.
