### ISSUE TITLE
Overly-aggressive string formatting in Diff output

### ISSUE THREAD

**Issue by vdh** [zalmoxisus/redux-devtools-extension#172]
```
value(pin):'2016-07-29T14:…0:00' => '2016-07-29T14:…0:00'
```

When an ISO8601 string (`2016-07-29T14:10:00+10:00`), a mere 25 characters, is long enough to trigger string truncation (down to 19…?), the Diff panel quickly becomes useless for non-trivial data.

**Comment by zalmoxisus** [comment]
@vdh, agree. Would you like to submit a PR to [`redux-devtools-inspector`](https://github.com/alexkuz/redux-devtools-inspector) with the limits you consider optimal? If I'm not mistaken, it's just [this line](https://github.com/alexkuz/redux-devtools-inspector/blob/master/src/tabs/JSONDiff.jsx#L12) to change.

**Comment by vdh** [comment]
@zalmoxisus If I have the time I'll see if I can get a PR put together. I think a CSS solution with [`text-overflow: ellipsis`](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) and perhaps some flexbox would let the browser handle truncation within the window width available, rather than length-based truncation inside the JS.

**Comment by zalmoxisus** [comment]
A solution was suggested in https://github.com/alexkuz/redux-devtools-inspector/issues/18. Better to continue the discussion there.

**Comment by zalmoxisus** [comment]
Now we take into account the window's width, and, when it's in wide mode, there's more data. Also there's a `Raw` view with all the data. See [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.11.0) for more details.

If you think it can be done better, feel free to reopen the issue.
