### ISSUE TITLE
Replay Actions

### ISSUE THREAD

**Issue by ccorcos** [zalmoxisus/redux-devtools-extension#173]
it would be great if we could import an array of actions to pull up a slider and replay the app. the states should be reproducible and this way, we could save tracking data thats captured from elsewhere and replay exactly what happened.

I was poking around and it looks like we'd need to add something here:

https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/api/importState.js

but im not sure how it would really work. I think we just want to reset the app, then dispatch all the actions in a row to generate the states. then we can go straight into the replay mode... what do you think?

**Comment by zalmoxisus** [comment]
Actions are already replayed (states are recomputed), so it should be easy to implement. It would be indeed useful, if you could send a PR [here](https://github.com/zalmoxisus/redux-devtools-instrument). We could just add this implementation if `Array.isArray(nextLiftedState)` for [`IMPORT_STATE ` action](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L324), then there's no need to change anything on the extension's side. Also please add [tests](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/test/instrument.spec.js#L555).

Just curious form where you export an array of actions?

**Comment by ccorcos** [comment]
I created some middleware that sends all user actions to elasticsearch so we can do user analytics. I can query for a session, export all the redux actions into an array, checkout the proper release of the application, and replay the user's experience. :)

**Comment by ccorcos** [comment]
I'll get on that PR soon. Thanks for pointing me in the right direction :)

**Comment by zalmoxisus** [comment]
Hey @ccorcos,

Did you have a chance to check if that works? Those changes should be merged in the extension last week.

**Comment by ccorcos** [comment]
Not yet -- will do soon though.

**Comment by zalmoxisus** [comment]
@ccorcos, BTW, @timarney already tried it and even implemented in a [lib](https://github.com/timarney/redux-trackjs-logger).
