### ISSUE TITLE
Can't get dev tools to stop opening in a new window

### ISSUE THREAD

**Issue by davecarlson** [zalmoxisus/redux-devtools-extension#174]
I'd like to only use the extension as part of the web inspector window, however, on every page load it opens up an additional popup as well, even if web inspector is open in the redux tab. 

Is there a setting I need to change ?
I've Attached shots of the current config. FYI, I'm running Version 52.0.2743.82 (64-bit)
<img width="1265" alt="screen shot 2016-08-04 at 09 04 50" src="https://cloud.githubusercontent.com/assets/299702/17394717/864fe0d0-5a22-11e6-9452-210feba1ccc8.png">
<img width="1440" alt="screen shot 2016-08-04 at 09 04 20" src="https://cloud.githubusercontent.com/assets/299702/17394718/8655446c-5a22-11e6-8198-57fdcb914710.png">

**Comment by zalmoxisus** [comment]
The extension doesn't open the window, unless you do it from context menu, using the shortcut or by calling `window.devToolsExtension.open`. Most likely you have the latter, which is not intent to be used like that.

**Comment by zalmoxisus** [comment]
Any updates on this? Was it happen because of having that function call?

**Comment by davecarlson** [comment]
yes,  it was in the code from another imported package!

**Comment by wangytangy** [comment]
@davecarlson Hi I'm having this issue as well and can't seem to locate the problem code!

Would you mind pointing out which imported package is doing this or how you were able to find that out? That would be super helpful!
