### ISSUE TITLE
Action payloads are sometimes Immutable structures and sometimes not

### ISSUE THREAD

**Issue by alisman** [zalmoxisus/redux-devtools-extension#175]
I implemented deserialize and serialize handlers in dev tool instantiation, but am running into an issue where some of my action payloads are immutable and some not.   When I deserialize action, there is no way I can know.  Any good ideas here?  I suppose I could implement a serializeAction function which tags the item as a serialized from Immutable so I can then know in deserialize?  
Incidentally, is it poor form to have Immutable data in action payloads?  Perhaps they should always be POJOs?

**Comment by zalmoxisus** [comment]
You should have either immutable data for specific action types or for specific object keys, then you can process them correspondingly in the `deserializeAction` function.

Even though `deserializeAction` and `serializeAction` sounds similar, they have different purpose. The latter is intended for those cases when action's payload cannot be serialized with `JSON.stringify` when sending data to the monitor, which is not a problem for Immutable.js. 
`deserializeAction` is used when importing data from a file or when persisting the state. When parsing the file you cannot know if it was originally immutable.

**Comment by alisman** [comment]
So, deserialize state is not also called when skipping between states using slider or action selector?  I thought perhaps you were storing past states in serialized form.

**Comment by zalmoxisus** [comment]
No. On the extension part they are stored serialized (for showing on the monitors). On the app part they are stored as is (so it will not mess up the states). When you close the monitor window, it will free the memory, and will serialize everything again when you open the monitor.

Could you please describe what is exactly the problem you experience if there's any.
