### ISSUE TITLE
Animate updated nodes in graph view

### ISSUE THREAD

**Issue by jumpinjackie** [zalmoxisus/redux-devtools-extension#180]
It would be nice if an action updates node values, that the affected nodes blink/flash/animate-in-some-way in the graph view as a visual indicator that some part of the state got updated.

To use the redux counter example. If I'm in graph view, when I hit + or -, it would be great if the `counter` node (whose value was updated by the increment/decrement actions) blinks/flashes/animates in the graph view.

**Comment by zalmoxisus** [comment]
Thanks for the suggestion. It would be awesome indeed. If you can send a pull request to the [chart monitor](https://github.com/romseguy/redux-devtools-chart-monitor) it would be much appreciated by the community.

**Comment by zalmoxisus** [comment]
Implemented in `v2.8.0`.
