### ISSUE TITLE
Position and docking

### ISSUE THREAD

**Issue by terencechow** [zalmoxisus/redux-devtools-extension#182]
Hi,

I have 2 monitors and in my project I have `window.devToolsExtension.open()` which auto opens it every time I start my project.

That's great as I naturally will open it when developing anyways. 

However when I select pin to right (third button from the bottom left), it will pin to the right side of my main monitor instead of the right side of my second monitor even when the chrome window is in the second monitor. Note that my second monitor is left of my first monitor. Also when I click pin to the left side (first button in the bottom left), it will pin to the left side of my main monitor so I can't do that either. 

Wondering if there is a quick fix for this? Simple question, but I think it's relevant as most developers have multiple monitors.

**Comment by zalmoxisus** [comment]
I don't have a second monitor, to test now, but [the code we're using for that](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/background/openWindow.js#L38) is just:
```js
params.left = window.screen.availWidth - params.width;
```

If you could find a better formula it would be much appreciated.

**Comment by zalmoxisus** [comment]
BTW, you could use `window.devToolsExtension.open('right')` if you prefer having the window on the right side. Or better not to use that function at all, and open the window when needed from context menu or with a [keyboard shortcut](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/FAQ.md#keyboard-shortcuts).

**Comment by terencechow** [comment]
Thanks. I've made a pull request and the code is shown below. 

https://github.com/zalmoxisus/redux-devtools-extension/pull/184/commits/93e9903f029efd7dfc3dccb5cd63ac513c207e58

**Comment by zalmoxisus** [comment]
Thanks a lot for the contribution! I published the change to Chrome store, Chrome will autoupdate the extension in several hours. Feel free to reopen the issue if it doesn't work as expected.
