### ISSUE TITLE
State output shows null when store state is not null

### ISSUE THREAD

**Issue by dkoontz** [zalmoxisus/redux-devtools-extension#183]
I'm seeing a lot of states that show null for various properties when the state is not null. I tested this with `jsan.stringify` and I'm getting good state there as well so I'm rather confused why the devtool is showing null.

Here is an example, the `ui` property of the state shows null.

![screen shot 2016-08-18 at 4 42 51 pm](https://cloud.githubusercontent.com/assets/7493/17794274/d80d5948-6562-11e6-8e33-bd16838db90b.png)

If I got to the console and serialize that property

![screen shot 2016-08-18 at 4 37 32 pm](https://cloud.githubusercontent.com/assets/7493/17794226/63509d36-6562-11e6-913d-2fd1baa7a480.png)

it correctly shows the values for `ui`.

When I installed jsan to test with I got version 3.1.3 in case that's relevant.

**Comment by zalmoxisus** [comment]
Thanks for the detailed report! Do you have the same problem with Log Monitor or it's specific to the Inspector? If it works well on Log Monitor, then the problem should be with [`javascript-stringify`](https://github.com/blakeembrey/javascript-stringify), which Inspector is using, most likely with [this PR](https://github.com/blakeembrey/javascript-stringify/pull/5).

**Comment by zalmoxisus** [comment]
Increased `maxValues` limit for [`javascript-stringify`](https://github.com/blakeembrey/javascript-stringify). If the problem still occurs please provide a minimal repo or a jsfiddle to reproduce the issue.

**Comment by dkoontz** [comment]
I'm not sure I understand. The issue link is to `javascript-stringify` but the devtools use `jsan` which does not depend on `javascript-stringify`. Did you want me to test using the latest version of one of those libs?

As for your other question about the LogMonitor I am seeing incorrect output there as well.

![screen shot 2016-08-19 at 1 01 32 pm](https://cloud.githubusercontent.com/assets/7493/17822840/3201a304-660e-11e6-9c07-3babcae240fc.png)

And here I've `console.log`'d the state right before returning it from the only reducer for the `ProfileLoaded` action.

![screen shot 2016-08-19 at 1 03 03 pm](https://cloud.githubusercontent.com/assets/7493/17822859/46107a14-660e-11e6-8711-78e0c6c0efcb.png)

I'm not sure if this is relevant, but I noticed that jsan's output does not include keys who's values are `undefined`.

I'll work on a minimal repro case.

**Comment by zalmoxisus** [comment]
Yes, jsan doesn't include `undefined` and functions by default, as JSON.serialize doesn't, anyway that shouldn't be the issue.

The extension doesn't use `javascript-stringify` directly, but `redux-devtools-inspector` uses it. Anyway, if it happens for `redux-log-monitor` as well, then it's not the problem.

Could you please also check if in the extension settings (click the Settings button on the bottom) `Serialize the state` is checked?

**Comment by dkoontz** [comment]
Alright I have some more info. This issue seems to only happen in Electron.

This is what happens in a browser

![screen shot 2016-09-01 at 1 49 01 pm](https://cloud.githubusercontent.com/assets/7493/18183831/0863713e-704b-11e6-95b9-28b42b83803e.png)

And with the exact same store/reducer/dispatch in Electron

![screen shot 2016-09-01 at 1 48 47 pm](https://cloud.githubusercontent.com/assets/7493/18183809/f57e4d32-704a-11e6-9a8b-1ce5b01836b4.png)

I have the Electron and browser test projects here: https://github.com/dkoontz/redux-devtool-testcase

Both projects need `npm install` and then `npm run start`

Main file for browser: `src/app.jsx`
Main file for electron: `renderer/index.js`

Both projects dispatch the 3 messages seen in the screenshots in their main files and are using the exact same file for the store, reducer, and my utility `set` function.

**Comment by Vlemert** [comment]
Hi, I'm running into the same problem as described above. Only in Electron as well. As far as I can tell it only happens when more than one dispatch is called at the same time. If we add a timeout of 250+ ms on consecutive dispatches the issue doesn't appear to happen.

What's interesting is that when the issue arises, it retroactively changes the state in previous dispatches.

Initial state:
![screen shot 2016-09-02 at 10 31 04](https://cloud.githubusercontent.com/assets/343610/18197684/d121c6e0-70f8-11e6-83ba-e62c12fa1716.png)

After one dispatch:
![screen shot 2016-09-02 at 10 31 35](https://cloud.githubusercontent.com/assets/343610/18197685/d122d10c-70f8-11e6-8ced-a8004106ade3.png)

After a double dispatch:
![screen shot 2016-09-02 at 10 32 01](https://cloud.githubusercontent.com/assets/343610/18197686/d12d0f6e-70f8-11e6-8a8f-6773beb6d398.png)

If we dispatch another action after the double dispatch, the output seems to restore from that point onward.

store.liftedStore.getState().computedStates shows the correct state after each dispatch.

**Comment by zalmoxisus** [comment]
@dkoontz, thanks for the repo, but I cannot seem to reproduce it there :-/

<img width="1087" alt="screen shot 2016-09-02 at 2 05 43 pm" src="https://cloud.githubusercontent.com/assets/7957859/18202077/92269132-7116-11e6-9a8f-64e5f1689949.png">

Maybe updating the extension could help (like [here](https://github.com/chentsulin/electron-react-boilerplate/pull/263/commits/f2b9b3eaa84e8f235d5d8b56ed6c72295d1305ca))?

**Comment by zalmoxisus** [comment]
@Vlemert, yes, to prevent flooding, [if dispatching occurs more frequently than once in 200ms](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/service/Monitor.js#L26-L36), the actions a batched in one request. However, if that's the issue, you should reproduce it also when having monitor actions (for example when skipping / toggling actions).

**Comment by zalmoxisus** [comment]
> As for Serialize the state being set, it is in the browser and I'm unable to load up the chrome extensions in Electron. I tried opening chrome://extensions/ in a new Electron window but that fails. Is there a way I can access that setting to check it?

It could be the issue, serialization should be `true` by default, but it seems that configuration object is empty on electron. Checking `devToolsOptions.serialize !== false` instead should help.

**Comment by zalmoxisus** [comment]
Published the fix in `2.5.1.8`. It should be available in about an hour on Chrome Store. Please give it a try.

**Comment by Vlemert** [comment]
Thanks for the quick response! We'll keep an eye on the store and retry with the updated version.

**Comment by Vlemert** [comment]
Ok so I went on vacation and my colleagues never checked on this, but the issue seems to persist.

I tested typing `window.devToolsOptions.serialize = true` in the console and that definitely fixes the issue. Even doing this works: `window.devToolsOptions.serialize = 'lala'`. Looked around your code but can't seem to find why this would make a difference.

**Comment by Vlemert** [comment]
Whoops, it appears that the extension was never reinstalled in electron, so I was still running the old version. The latest version works like a charm. Thanks!

**Comment by dkoontz** [comment]
This is fixed for me as well.
