### ISSUE TITLE
Firefox: Chart does not show the props of the state nodes

### ISSUE THREAD

**Issue by Akronix** [zalmoxisus/redux-devtools-extension#187]
Hi!

I'm opening up a local webapp and inspect it with Redux devtools Firefox extension. I go to the chart option and I see the state tree but I can't see the props content of any of the state nodes.
Here's a snapshot:
![screenshot from 2016-08-22 18-30-20](https://cloud.githubusercontent.com/assets/2631430/17862722/c0cb14b4-6896-11e6-889b-30681b821b6c.png)

However, I can see it under chrome with the same webapp.

I'm running Firefox 48 under Ubuntu 16.04

**Comment by zalmoxisus** [comment]
Thanks for the report. It's a styling issue, fixed in the current version, will publish it on AMO soon, but it will take about a week to be reviewed. So, if you need it just now, can [build it manually](https://github.com/zalmoxisus/redux-devtools-extension#12-for-firefox).

**Comment by zalmoxisus** [comment]
`v2.5.1` is available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/remotedev/), which includes the fix for this issue. Please let me know if you experience any other troubles there.

**Comment by Akronix** [comment]
Yeah, I've already got it.

Thank you folks!
