### ISSUE TITLE
Warning: Failed prop type: Required prop `monitorState.position` was not specified in `DockMonitor`.

### ISSUE THREAD

**Issue by suweya** [zalmoxisus/redux-devtools-extension#188]
When i use window.devToolsExtension() there is a Warning: Failed prop type: Required prop `monitorState.position` was not specified in `DockMonitor`.

**Comment by zalmoxisus** [comment]
Most likely, you're having both [vanilla Redux DevTools](https://github.com/gaearon/redux-devtools) and our extension. You should include only the extension, which is [just one line of code](https://github.com/zalmoxisus/redux-devtools-extension#21-basic-store), without any monitors needed (especially `DockMonitor`).

**Comment by suweya** [comment]
Thanks I'am fixed it according to your advice
