### ISSUE TITLE
A state mutation was detected inside a dispatch error when extention is enabled

### ISSUE THREAD

**Issue by BostjanSkok** [zalmoxisus/redux-devtools-extension#189]
Error: A state mutation was detected inside a dispatch, in the path: `actionsById.1`. Take a look at the reducer(s) handling the action {"type":"PERFORM_ACTION","action":{"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/","search":"","hash":"","state":null,"action":"POP","key":"hm6zpr","query":{},"$searchBase":{"search":"","searchBase":""}}},"timestamp":1471971130067}. (http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)

dependencies:
 "object-assign": "4.1.0",
    "react": "15.3.1",
    "react-dom": "15.3.1",
    "react-redux": "4.4.5",
    "react-router": "2.7.0",
    "react-router-redux": "4.0.5",
    "redux": "3.5.2",
    "toastr": "latest",
    "redux-thunk": "2.1.0",
    "validator": "5.5.0",
    "redux-immutable-state-invariant": "1.2.3",

**Comment by zalmoxisus** [comment]
Could you please share your store setup?

**Comment by BostjanSkok** [comment]
my configureStore.dev.js 
```python
import {createStore, compose,applyMiddleware} from 'redux';
import rootReducer from '../reducers';
import reduxImmutableStateInvariant from 'redux-immutable-state-invariant';
import thunk from 'redux-thunk';

export default function configureStore(initialState) {
  const store = createStore(rootReducer, initialState, compose(
    // Add other middleware ovn this line...
    window.devToolsExtension ? window.devToolsExtension() : f => f,// add support for Redux dev tools
    applyMiddleware(thunk, reduxImmutableStateInvariant())
    )
  );

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextReducer = require('../reducers').default; // eslint-disable-line global-require
      store.replaceReducer(nextReducer);
    });
  }

  return store;
}
```
my root reducer
```python
import {combineReducers} from 'redux';
import user from './userReducer';
import ajaxCallsInProgress from './ajaxStatusReducer';
import header from './headerReducer';


import {routerReducer} from 'react-router-redux';

const rootReducer = combineReducers({
  user,
  header,
  ajaxCallsInProgress,
  routing: routerReducer
});

export default rootReducer;
```

It's a modified version of React Slingshot

**Comment by zalmoxisus** [comment]
The extension's store enhancer should be always the last in the `compose`. Please confirm whether it was the problem.

**Comment by BostjanSkok** [comment]
Looks like that fixed it now the extension works.
Thanks

**Comment by vincent1988** [comment]
I have some issue. also , it is not work?

**Comment by devssh** [comment]
I am getting this problem with 

```
import {createStore, applyMiddleware} from 'redux';
import reduxImmutableStateInvariant from 'redux-immutable-state-invariant';
import thunk from 'redux-thunk';
import {combineReducers} from 'redux'
import {inFilterReducer} from "./reducers";
import {composeWithDevTools} from 'redux-devtools-extension';
createStore(
    rootReducer,
    initialState,
    composeWithDevTools(  
      applyMiddleware(
        thunk,
        reduxImmutableStateInvariant()
      )
    )
  )

```
How do I fix it?
