### ISSUE TITLE
Bug with middleware from redux official site

### ISSUE THREAD

**Issue by rmgpinto** [zalmoxisus/redux-devtools-extension#190]
I'm getting a bug because some of my actions don't have the 'type' variable but rather 'types' as proposed in redux official site: [http://redux.js.org/docs/recipes/ReducingBoilerplate.html](url)

Example:
```javascript
export function loadPosts(userId) {
    return {
        // Types of actions to emit before and after
        types: ['LOAD_POSTS_REQUEST', 'LOAD_POSTS_SUCCESS', 'LOAD_POSTS_FAILURE'],
        // Check the cache (optional):
        shouldCallAPI: (state) => !state.posts[userId],
        // Perform the fetching:
        callAPI: () => fetch("url"),
        // Arguments to inject in begin/end actions
        payload: { userId }
    }
}
```
Is there any way I can fix this?

**Comment by zalmoxisus** [comment]
That's something new. Does that work without the extension? Did you added also the `callAPIMiddleware`? What error message do you get?

**Comment by zalmoxisus** [comment]
Could you please share a simple example on jsfiddle or even better to send a pr to our examples? So, we could maintain this use case in future.

**Comment by yarcub** [comment]
@rmgpinto, could it be the order of the enhancers (middleware and devtools)? In what order are they composed?

**Comment by rmgpinto** [comment]
@zalmoxisus It works without the extension. Error message: `Error: Actions may not have an undefined "type" property. Have you misspelled a constant?`

@yarcub my store is created in the following way:
```javascript
store = createStore(
    rootReducer,
    applyMiddleware(
        callAPIMiddleware
    ),
    window.devToolsExtension ? window.devToolsExtension() : f => f
);

**Comment by rmgpinto** [comment]
I forgot to compose the middleware with the devToolsExtension. 
```javascript
store = createStore(
    rootReducer,
    compose(applyMiddleware(
        callAPIMiddleware
    ),
    window.devToolsExtension ? window.devToolsExtension() : f => f)
);
