### ISSUE TITLE
Remote DevTools loses connection to RN app

### ISSUE THREAD

**Issue by scarlac** [zalmoxisus/redux-devtools-extension#193]
I've got a React Native iOS app with `import devTools from 'remote-redux-devtools'` and added the enhancer (`devTools()`) as well. Everything is working with the extension - graph, inspector, etc.

But when the app is reloaded, the devtools wipes the information clean and never re-connects (it probably detects a disconnect but isn't able to connect for whatever reason).

The workaround is to reload the devtools window by focusing it and pressing CMD+R on Mac. It'll reload the devtools and reconnect to the store and the entire action history is then shown.

Expected behavior:
DevTools window reloads or reconnects when React Native app is reloaded as well.

**Comment by zalmoxisus** [comment]
Thanks for the report. Yes, I can reproduce the issue. It was introduced, with the latest changes. Will fix ASAP.

**Comment by zalmoxisus** [comment]
Fixed in `2.5.1.5`. It should be available in few minutes in Chrome Store. Chrome will autoupdate th extension in several hours.

**Comment by scarlac** [comment]
Wow, well done @zalmoxisus! I'll check it out when it updates - thanks :)

**Comment by scarlac** [comment]
Fix confirmed. Closing.
