### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by toranb** [zalmoxisus/redux-devtools-extension#195]
I just wanted to leave a quick comment saying how truly awesome this project is! I've been using this w/ my ember projects for the past few months and couldn't thank you enough for building and maintaining such a powerful tool!

thank you !!!

**Comment by zalmoxisus** [comment]
Hey, thanks for the feedback. Glad the work here is appreciated.

BTW, You did a great job for `ember-redux` as well! I've included it in the [Integrations](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Integrations.md).

For everybody, feel free to leave feedbacks on [Chrome Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).

**Comment by toranb** [comment]
@zalmoxisus awesome! glad to be a part of the wider community you've built up around this amazing tool! 

I just submitted a [PR](https://github.com/zalmoxisus/redux-devtools-extension/pull/300) to update the integration you linked to above (we moved it under a true GH organization now/ etc)
