### ISSUE TITLE
redux-devtools with the new rxjs/store

### ISSUE THREAD

**Issue by ritox842** [zalmoxisus/redux-devtools-extension#196]
Hey all.

I've installed the new beta version of ngrx/store.
In the new version there isn't any "createStore", but some code that should be insert into the ngModule.
Because I dont have the "createStore", I cant implement the redux-dev-tools..
Did anyone manage to use it?

This is the ngModule code:

`    StoreModule.provideStore({bet: betReducer }),`

I've tried to put it inside the provideStore but the window isn't recognized .

**Comment by zalmoxisus** [comment]
Hey @ritox842,

You have to use [`ngrx/store-devtools`](https://github.com/ngrx/store-devtools), which includes the extension. If you have troubles with it, better to continue the discussion [here](https://github.com/zalmoxisus/redux-devtools-extension/issues/77).
