### ISSUE TITLE
State not updating after moving forward in slider

### ISSUE THREAD

**Issue by BTMPL** [zalmoxisus/redux-devtools-extension#198]
Hello

I've a somehow big, proprietary app so I can't share the source, but I've got a productReducer, that holds an array of products and has an action:

    case actions.PRODUCT_UPDATED:
      return state.map(product => {
        if(product.productId == action.productId) {
          return objectMerge(product, action.payload);
        }
        return product;
      });

objectMerge is just:

    export default function objectMerge(obj1, obj2) {
      let returnObject = Object.assign({}, obj1)
      Object.keys(obj2).forEach(function (key) {
        if (typeof obj2[key] !== "object" || !obj2[key]) {
          returnObject[key] = obj2[key];
        }
        else {
          if (!returnObject[key]) {
            returnObject[key] = obj2[key];
          } else {
            returnObject[key] = objectMerge(returnObject[key], obj2[key]);
          }
        }
      });
      return returnObject;
    }

Now, when I update a product (change name) it will update OK. When I use the time-travel to step back it changes the name to the old value, when I then step forward the original value stays and doesn't reflect the change. Odd thing is if I export and import the state it works as expected.

Sorry for the vague description, but maybe someone came across a similar issue or can spot an error in my logic.

Best regards

**Comment by zalmoxisus** [comment]
Thanks for the report. Do you experience this problem on Chrome devtools panel or from the extension's window? If first, please try also to open it in a window (just click the first button from the bottom) and also open the chrome console (Cmd+Alt+I) to see if there's an error there.

**Comment by BTMPL** [comment]
I'm using the extension window (eg. right click on icon > to left). I've opened the extension window developer tools pane (right click in the extension window > inspect) but sadly there are no errors reported.

**Comment by zalmoxisus** [comment]
Unfortunately, cannot replicate it with our examples. A simple repo or jsfiddle to reproduce the issue would help.

**Comment by BTMPL** [comment]
Ok, I've made a quick example of an issue I'm experiencing, though this one doesn't even navigate back :(

http://anfo.pl/tmp/react/

You can add new accounts an navigate back/forward just right, but when you change (add amount, change name) an account, you can't navigate between the states.

The bundle has a map file so you should be able to access the original source - it might be an error on my end. The most interesting part is probably the reducer, so I'll include it here:

  import accountActions from "../actions/account.js";

  const accountReducer = (state = [], action) => {
  if(action) switch(action.type) {
    case accountActions.ACCOUNT_ADDED:
      return [...state, action.payload];

    case accountActions.ACCOUNT_REMOVED:
      return state.filter((item) => {
        return item.id != action.id;
      });

    case accountActions.ACCOUNT_UPDATED:
      return state.map((item) => {
        if(item.id == action.id) {
          item = Object.assign(item, action.payload);
        }
        return item;
      });
  }

    return state;
  };

  export default accountReducer;

**Comment by zalmoxisus** [comment]
Thanks for the example. I see time traveling works, just the state value is not updating, which is a client side problem. Most likely, you're mutating the state. To prevent this, just add `redux-immutable-state-invariant` middleware (make sure to have it only in development, not to slow down the production build). Also, some middlewares could be the problem (if so, please provide the store configurartion).

**Comment by zalmoxisus** [comment]
The problem is only with `ACCOUNT_UPDATED` action, it should be probably 
```js
if(item.id == action.id) {
          return Object.assign(item, action.payload);
}
```
instead of 
```js
if(item.id == action.id) {
          item = Object.assign(item, action.payload);
}
```

**Comment by BTMPL** [comment]
Thank you - you were right, the state was mutating but in the different way.

It should be:

    return Object.assign({}, item, action.payload);

This solves the issue in the example I've provided, and will probably solve the error in my original code, and as such I'm closing this issue.

Thank you for your help and recommending `redux-immutable-state-invariant"`

Cheers
