### ISSUE TITLE
No Drop-down menu after clicking "Autoselect Instances"

### ISSUE THREAD

**Issue by mocheng** [zalmoxisus/redux-devtools-extension#199]
Mac OSX El Capitan 10.11.6 (15G31)
Chrome Version 52.0.2743.116 (64-bit)
Redux DevTools 2.5.1.6

After read this [blog](https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f#.dzg2f62ch), I tried to create store for my component in additon to the "global" redux store. However, I cannot switch between two stores. This makes multiple instances un-debuggable.

![image](https://cloud.githubusercontent.com/assets/239291/18114339/faf17c18-6f68-11e6-8871-a4ae3df95628.png)

I tried to name store instances by `win.devToolsExtension({name: 'main', instanceId: '123'}) `. It still doesn't work.

I tried the offical[ counter sample](https://github.com/zalmoxisus/redux-devtools-extension/tree/master/examples/react-counter). Still it has same issue. It must not be specific to my applicaiton.

**Comment by zalmoxisus** [comment]
Thanks for the report! It happens only when there's no `document.title` on the inspected page and no `name` parameter provided explicitly. I fixed it yesterday in https://github.com/zalmoxisus/redux-devtools-extension/commit/f25c7cb5b755f23011c994cd4c3afd4176dbc78a, will publish it on Chrome Store today.

**Comment by zalmoxisus** [comment]
`v2.5.1.7` is available on Chrome Store. Chrome should update it in several hours, but you can remove and install extension again if want to try it right now.

Please let me know if you experience any other troubles with this.

**Comment by mocheng** [comment]
It works  in `v2.5.1.7`. Thanks for the effort!

Now I can add `name` by applying devToolsExtension as enhancer to redux.
 ```
win.devToolsExtension({name: 'main redux'})
```
But, to create a store by the enstesion, there is no clear documentation about it. The first and second argument is reducer and initial state respectively. It ried to add config as third argument, but it doens't work. 
```
      this.store = win.devToolsExtension(this.reducer, this.state, {name: this.displayName});
```
How to config name in this situation?

![image](https://cloud.githubusercontent.com/assets/239291/18152568/4ce687d2-7029-11e6-9e35-b3cc35e0d620.png)

**Comment by zalmoxisus** [comment]
@mocheng,  yes, [`config` is the third argument](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#windowdevtoolsextensionreducer-preloadedstate-config). You're doing everything right.  Maybe `this.displayName` is an empty string or is defined after you call `win.devToolsExtension`?

Just tried to replace [this line](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/react-counter/components/Counter.js#L30) with
```js
this.store = window.devToolsExtension(reducer, {}, { name: 'hi' });
```
and I'm getting `hi` as instance name on the monitor.

**Comment by mocheng** [comment]
Cool! It works!
Thanks
