### ISSUE TITLE
Use with freezer-js

### ISSUE THREAD

**Issue by arqex** [zalmoxisus/redux-devtools-extension#2]
Hi @zalmoxisus 

Thanks for this great extension, will it be in the extension store soon?

I have created a [binding to use redux-devtools with a freezer-js](https://github.com/arqex/freezer-redux-devtools) app and I think this extension would be much better for freezer developers than including all redux libraries needed in order to make the devtools work.

So I am trying to build a binding to your extension, but it is not working so far. Currently I am creating the redux store like:

```js
       Redux.compose(
		FreezerMiddleware( State ),
		window.devToolsExtension || function(f){ return f }
	)(Redux.createStore)( function( state ){ return state } );
```

Inside FreezerStoreEnhancer I get the main app store like:
```js
store = next( reducer )
```

For standard devTools I have a store that have the `devToolsStore` attribute inside that I hijack to make the communication between the devtools and freezer.

For the extension I find I have the `liftedStore` attribute, that I expected to be the same, but it never dispatches the `@@INIT` action, so the extension is not playing well with the binder.

Do you see something I am doing wrong? Can you explain the differences between standard `devToolsStore` and yours `liftedStore`? Is there a way of loading your extension in a dev mode to see the code unminified and makes debug easier?

Cheers

**Comment by zalmoxisus** [comment]
Hey, @arqex.

Actually, it's not my liftedStore :) The new Redux DevTools (3.0.0-beta-3) uses it, and there are a lot of breaking changes there. So, if your app will work with Redux DevTools 3.0.0, it will work with the extension as well.

We may use different versions of the Redux DevTools in the extension, but it make it too complex so I want to be sure that people need it.

Thanks for the kind words and for the suggestions! If you found some reasons not to update the DevTools, we may work in this direction to extend it.

I do want support as much user cases as possible, and of course it will be on Chrome Webstore (as indicated in the [Roadmap](https://github.com/zalmoxisus/redux-devtools-extension#roadmap)).

**Comment by zalmoxisus** [comment]
The code is in the `./src/app` and `./src/browser/extension`.
Use `npm start` (after the `npm install`) to start in the dev mode, and load the `./dev` folder instead of `./build/extension`.
Or you may build it with `npm build:extension`. I should add it to the readme.

**Comment by arqex** [comment]
Thanks for the prompt reply.

No problem I will adapt the library to support the new version of redux-devtools, it shouldn't be difficult with you instructions. Don't worry about supporting other redux versions, I think your app would work well with any of them, it is my library that hacks redux a bit, the one to adapt.

I will give it a try this afternoong and let you know.

**Comment by arqex** [comment]
Finally I got the freezer app working with redux-devtools chrome extension!! :)

http://freezer-redux-devtools.divshot.io/

Runing the extension in dev mode helped a lot, thanks!!

**Comment by zalmoxisus** [comment]
Awesome! It even works with persist state: http://freezer-redux-devtools.divshot.io/?debug_session=test (use the extension in dev, click then refresh and you will not lose the devtools' history).

**Comment by zalmoxisus** [comment]
Added your implementation to the [README](https://github.com/zalmoxisus/redux-devtools-extension#implementation).

Feel free to open this ticket or open another one if something goes wrong.
