### ISSUE TITLE
Displaying (new) Error objects.

### ISSUE THREAD

**Issue by luisherranz** [zalmoxisus/redux-devtools-extension#200]
I'm loving the devtools so far.

The only problem I found is that when the app catches an error and pass it to the action, devtools doesn't display that object.

With redux-saga is usually something like this:

```javascript
try {
  const data = yield fetch('http://someapiurl...');
  yield put({ type: 'FETCH_SUCCEED', data });
} catch (error) {
  yield put({ type: 'FETCH_FAILED', error });
}
```

If I debug the app in that point, the `error` is fine. I can print it in the console. For example:
```
TypeError: Cannot read property 'something' of undefined
```
But in the devtools panel, the error object of that action is empty:
![screen shot 2016-08-31 at 13 24 58](https://cloud.githubusercontent.com/assets/3305402/18127053/642cb336-6f7e-11e6-8290-53ea6e216fc3.png)

Is there a way the devtools can display error objects (coming from `new Error`)?

**Comment by zalmoxisus** [comment]
Yes, I noticed it as well. The problem is that the Error object cannot be serialized, so you should construct it directly from your app like `{ error: error.message }`.

I have in mind a solution to pass the data to the extension without serializing it via shared workers, but not sure it will work. I'll leave this issue open till get a change to check that approach.

**Comment by luisherranz** [comment]
Ok, thanks! We'll use the workarounds until then.

**Comment by zalmoxisus** [comment]
In `2.8.4` it's possible now to serialize dates, regexes, undefined, error objects, and functions. Just set `serializeState` parameter to `true`. See [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.8.4) for details.

**Comment by luisherranz** [comment]
Awesome, thank you!

**Comment by dorian-marchal** [comment]
Is there a way to use `serializeState` and `serializeAction` with `composeWithDevTools` ?
Also, I don't find documentation for `serializeState` and `serializeAction` other than https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.8.4.

**Comment by dorian-marchal** [comment]
Found it. This option is now named `serialize` and can be used like that:

```js
const composeEnhancer = composeWithDevTools({
  serialize: { replacer: (key, value) => /* newValue */ },
});
const store = createStore(reducer, composeEnhancer(applyMiddleware(/* middlewares */)));
```

As documented here: https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize
