### ISSUE TITLE
Unable to "Select Instance" from the Chrome Dev Tools Panel

### ISSUE THREAD

**Issue by OddEssay** [zalmoxisus/redux-devtools-extension#201]
When I look at the Redux tab in the Chrome Dev Tools, I don't have the "Select Instance" drop down, but if I trigger the tool by either clicking on the icon in the menu bar, or detaching a remote redux inspector, everywhere else the option to change instance shows up as expected.

![noinstanceselectioninchromedevtools](https://cloud.githubusercontent.com/assets/837227/18130167/ddc224a4-6f85-11e6-9144-5209e63117cb.png)

Using version Redux DevTools  2.5.1.7, Chrome Version 52.0.2743.116 (64-bit) on a Mac.

Is this expected behaviour or a limitation in that particular view, or a bug somewhere?

Any insight would be helpful, cheers.

**Comment by zalmoxisus** [comment]
Thanks for the report. Before by instances we meant tabs, so that's why it wasn't intended to be selected from Chrome DevTools Panel (which corresponds to the current tab), but only from the extension's window. Now that we support multiple stores in the same app, it makes sense to add the selector there as well.

**Comment by OddEssay** [comment]
Thanks @zalmoxisus :) - Yeah, I only noticed it because Intercom use Redux for their widget state etc and leave the devtools hook switched on, so even though I only use a single store myself, every time the Intercom state updates focus switches to their store, not my own. 🤔

**Comment by atrauzzi** [comment]
Would love to see this update pushed to the chrome app store so that I don't have to keep a window popped out.

**Comment by zalmoxisus** [comment]
Just published `v2.6.0`, where it's possible to select instances from devpanel. Moreover, the current tab's instance will be selected by default.
