### ISSUE TITLE
Inspector's state tab doesn't refresh immediately after timeline change

### ISSUE THREAD

**Issue by mzygmunt** [zalmoxisus/redux-devtools-extension#204]
Hello,
I noticed that the inspector's state tab doesn't refresh immediately after timeline change or when I skip some previous actions in its window.

![image](https://cloud.githubusercontent.com/assets/13297558/18241637/8e4b9efc-7352-11e6-93d2-2c3cf5b6649d.png)

**Comment by zalmoxisus** [comment]
Thanks for the report. The monitor updated when it receive a response from the app. In case you have large payloads in action or state objects, serializing the response can take a while.

A current solution would be to either set a lower number for `Limit the action history to` in Settings or, in case you have a very big object there (for example some blobs), you can strip them as following:
```js
const actionsFilter = (action) => (
  action.type === 'FILE_DOWNLOAD_SUCCESS' && action.data ?
  { ...action, data: '<<LONG_BLOB>>' } : action
);
const store = createStore(rootReducer, window.devToolsExtension && window.devToolsExtension({
  actionsFilter,
  statesFilter: (state) => state.data ? { ...state, data: '<<LONG_BLOB>>' } : state)
}));
```

I'm inspecting options for getting rid of serializations.

**Comment by mzygmunt** [comment]
Thanks for quick response! It works for me.

**Comment by zalmoxisus** [comment]
Now the serialization is way faster. In case you're still experiencing signifiant delays, feel free to reopen the issue, and we'll investigate it further.
