### ISSUE TITLE
Replaying Actions doesn't work in an iFrame

### ISSUE THREAD

**Issue by siirila** [zalmoxisus/redux-devtools-extension#209]
We have our Redux store inside an iFrame. The Redux devtools are able to see the actions and store state without issue, but when I try to replay the actions through the slider they are not affecting the application. If I run the same application outside of the iFrame the replay works correctly.

After looking into this a little more I found that if I am using the DevTools tab replay is not working, but if I am using the dialog window replay seems to work.

**Comment by zalmoxisus** [comment]
Just published `2.6.1`, where it's supporting iframes from the devpanel. Please let me know if you're still experiencing any problems there.
