### ISSUE TITLE
Support for Cordova apps

### ISSUE THREAD

**Issue by oskarer** [zalmoxisus/redux-devtools-extension#21]
I'm currently developing a Cordova app which I have to run the app in an emulator/phone all the time, due to database dependencies etc. I would then like to attach the developer tool (from chrome://inspect on my desktop) to the phone and see the Redux Devtools from there.

Obviously this doesn't work as of now since the Chrome extension injects properties to the window variable. However, wouldn't it be possible to do this manually in the Cordova app and get it to work? If so, which part of the source do I need to run?

**Comment by zalmoxisus** [comment]
Hey @oskarer,

There is another problem, you cannot communicate with the extension from there. I tried to implement it before, but unfortunately Chrome extensions aren't ready for such communications yet using just the extension API. 

It could be done by using [debugger-protocol](https://developer.chrome.com/devtools/docs/debugger-protocol), but it would be too hacky (we have to open chrome with a special flag and communicate with the app via a websocket port). There's a [chrome.debugger API](https://developer.chrome.com/extensions/debugger), but it's still very limited. We can only send commands to the remote app, but not to communicate directly. Still there are some open tickets to extend it. If so happens, it would be easy to implement it, not soon though.

I have a solution, but it's not trivial and would be a separate project for a Chrome / Electron app not extension. Will try to do my best to support Cordova and React Native apps.

**Comment by oskarer** [comment]
Thanks for the info @zalmoxisus! Seems like it wasn't so easy I expected, closing.

**Comment by zalmoxisus** [comment]
Hey @oskarer,

I've implemented this in [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools).

**Comment by oskarer** [comment]
Wow, really impressive! Works really well.

One question, say you're several developers working on the same network with the same or different apps.. I guess that doesn't work as of now, but it would be possible if https://github.com/zalmoxisus/remote-redux-devtools/issues/2 is solved?

**Comment by zalmoxisus** [comment]
Yes, it is not possible for now, as indicated [here](https://github.com/zalmoxisus/remote-redux-devtools#limitations).

There would be 2 options: to work separately or synchronously (so it would be possible to inspect some troubles together on the different machines).
