### ISSUE TITLE
Getting error when running redux-saga. Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by badtant** [zalmoxisus/redux-devtools-extension#210]
So,

I have an app that didn't use redux-saga before. Dev tools was working great.
I've then started to test some saga code and I ran into problems with the dev tool. 

```
_ctx.js:18 Uncaught TypeError: Cannot convert undefined or null to object(anonymous function) @ 
utils.js:191 uncaught at countdown 
TypeError: Cannot convert undefined or null to object
    at toJSON (native)
```

As long as dev tools is closed it's working so I don't have much clue except for trying to ask here. Does anybody have any clue what this is about?

Oh, and I'm using webpack and hot reloading.

Thanks

**Comment by zalmoxisus** [comment]
Make sure you didn't uncheck the serialization option in the Settings.

According to the error message, you have something in the states that `window.postMessage` cannot pass, which should be handled if the serialization option is enabled.

**Comment by badtant** [comment]
Hmm, not quite sure what setting you mean. Is this the one?
window.devToolsExtension.connect({ shouldStringify: false })

Or any of the ones specified here? http://zalmoxisus.github.io/redux-devtools-extension/API/Arguments.html#windowdevtoolsextensionconfig

**Comment by zalmoxisus** [comment]
If that option is checked, could you please provide more details about the app? About reducers and the state types you're using. At least the value of that variable for which `toJSON`fails.  It seems that it throws from `jsan`.

**Comment by badtant** [comment]
Thanks, I'll have a look first thing tomorrow!

**Comment by badtant** [comment]
The serialization option was checked but I got the same error both with checked and unchecked. Anyway, I found what was not serializable in my state and fixed it so it's working now.

Thanks for your help!
