### ISSUE TITLE
In 2.6.0 I can't time travel in the chrome devtools tab

### ISSUE THREAD

**Issue by bdwain** [zalmoxisus/redux-devtools-extension#213]
If i open the chrome dev tools and click an action in the redux tab, it doesn't rewind it. It works if I open redux devtools in a chrome panel though. And the changes are then reflected in the devtools tab.

**Comment by zalmoxisus** [comment]
This should be fixed in `2.6.1`. Please give it a try (remove the extension on `chrome://extensions/` and install again from [chrome store](https://chrome.google.com/webstore/developer/dashboard) or wait several hours till Chrome will autoupdate it), and let me know whether the problem persists.

**Comment by bdwain** [comment]
All good now. Thanks for fixing that so quickly!
