### ISSUE TITLE
Error: The previous state received by the reducer has unexpected type of "Function"

### ISSUE THREAD

**Issue by dht** [zalmoxisus/redux-devtools-extension#214]
I followed the installation instructions and changed my store creation method to this:

`const store = createStore(holoApp, applyMiddleware(timestamp, ReduxThunk), window.devToolsExtension ? window.devToolsExtension() : f => f); // logger , firebase, recorder ,autosave`

Yet I am getting an error:
<img width="758" alt="error" src="https://cloud.githubusercontent.com/assets/137832/18624281/087d3288-7e4f-11e6-9172-8456a9f823a5.png">
And things don't seem to work properly, specifically the React Dev Tools extension works but the app doesn't. Any idea?

**Comment by jeescu** [comment]
I got the same error, not until I switched place the `window.devToolsExtension`  as the second arg of the `createStore`. It shows up but forever loading. Help

**Comment by zalmoxisus** [comment]
It should be:
```js
const store = createStore(holoApp, compose(applyMiddleware(timestamp, ReduxThunk), window.devToolsExtension ? window.devToolsExtension() : f => f));
```
`compose` is imported from redux along with `applyMiddleware`.
