### ISSUE TITLE
redux-devtools cannot find store (On demo site and my own)

### ISSUE THREAD

**Issue by talolard** [zalmoxisus/redux-devtools-extension#215]
Hello,
Thanks for this fantastic tool. Unfortunately I've realized how important to em it's become now that it's not working for me. 
I get a message 

> No store found. Make sure to follow the instructions.

This happens both on my site as well as on the demo sites.  [Screenshot of demo site](http://imgur.com/a/2brDE)
I'm running it on Chrome. My Chrome version details are
`

> Google Chrome	48.0.2564.103 (Official Build) (64-bit)
> 
> Revision	cc2c23a615e1c898bc58b1fb818c41f214f509d8-refs/branch-heads/2564@{#657}
> 
> OS	Linux 
> 
> Blink	537.36 (@cc2c23a615e1c898bc58b1fb818c41f214f509d8)
> 
> JavaScript	V8 4.8.271.18
> 
> Flash	22.0.0.209
> 
> User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) 
> Chrome/48.0.2564.103 Safari/537.36
> 
> Command Line	/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
> 
> `
> 

Thanks for taking a look

**Comment by joeruello** [comment]
I was having a similar issue, but on chrome 52, I just updated to 53 (latest as of this post) and it's working again.

**Comment by zalmoxisus** [comment]
Should be fixed in `2.6.1.1`. Feel free to reopen the issue if still something goes wrong.
