### ISSUE TITLE
[firefox] Create a tab for redux devtools panel on developter tools

### ISSUE THREAD

**Issue by rougeth** [zalmoxisus/redux-devtools-extension#216]
When I use redux devtools on Firefox, a new window is opened and it would be much better if I could have it fixed on the developer tools, just like on Chrome. I couldn't figure out if there's an option to have this behavior.

Awesome work on this, thank you folks!

**Comment by zalmoxisus** [comment]
Thanks for the feedback! We're using the new WebExtension API, where [it's not possible yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1211859). As soon as that issue is fixed, will add the monitor on Firefox DevTools panel.

Closing in favour of #9.

**Comment by rougeth** [comment]
thanks @zalmoxisus!
