### ISSUE TITLE
Notification popups can't be disabled

### ISSUE THREAD

**Issue by chrylis** [zalmoxisus/redux-devtools-extension#217]
The extension fires a native notification every time there's an error in the application, **with no way to turn it off**.

**Comment by zalmoxisus** [comment]
Did you try to uncheck `Show errors` checkbox on the extension's option page (click `Settings` button to open it)?

**Comment by zalmoxisus** [comment]
I tried it now, disabling the notification from the setting works as expected. In case I misunderstood the problem or it still doesn't help, feel free to reopen the issue.

We could disable it by default for better UX (especially in production), though it shouldn't annoy as we've implemented an kind of [anti-flooding system](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/api/notifyErrors.js#L4-L17).
