### ISSUE TITLE
Warn when window.devToolsExtension is undefined

### ISSUE THREAD

**Issue by olalonde** [zalmoxisus/redux-devtools-extension#219]
I have the extension installed in Chrome but `window.devToolsExtension` is undefined.

**Comment by olalonde** [comment]
Oh just noticed I only have this issue with `file:///` URLs.

**Comment by olalonde** [comment]
If this can't be fixed, maybe the redux tab in devtools could show a warning instead of "store not found".

**Comment by zalmoxisus** [comment]
Doesn't [this](https://github.com/zalmoxisus/redux-devtools-extension/pull/186/commits/ade9d941d3d8df9180480fdb509287bff45735c9) help?

**Comment by olalonde** [comment]
I suppose it does, but it would be more helpful if that message showed up in the extension itself if there's any way to detect that you're in a `file:///` URL.

**Comment by zalmoxisus** [comment]
@olalonde, could you please provide more details? I don't see why it shouldn't work by default. Just checked on Chrome 53 and Canary on MacOS and don't see any issues with opening urls with `file:///`. Maybe an Windows issue?

**Comment by zalmoxisus** [comment]
Weird that checking that box is required only when the extension is installed from Chrome Store, that's why I wasn't able to replicate it before.

We should add the warning with the link to the docs, and this gif there:
<img width="746" alt="extensions" src="https://cloud.githubusercontent.com/assets/7957859/19075220/a0fad99e-8a4c-11e6-8b87-757f2dc179cb.png">

**Comment by eric-burel** [comment]
Hi, do you know how to do this programmaticaly ? So that I can guarantee a consistent dev environment in my applications ?

**Comment by zalmoxisus** [comment]
Hey @eric-burel. The best way is to use a dev server like webpack instead of opening the file directly. Otherwise, you should check that box as being introduced for security reason by Chrome.
