### ISSUE TITLE
Deprecating `window.devToolsExtension`

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#220]
`window.devToolsExtension` is being deprecated in favour of `window.__REDUX_DEVTOOLS_EXTENSION__` and `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`. See [the README](https://github.com/zalmoxisus/redux-devtools-extension#1-with-redux) on how to use them and [the post](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83) about why we added the second function.

Also there's [`redux-devtools-extension` npm package](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm) to make things easier.

Now we don’t have the order’s and noop functions’ confusion, also the shared window namespace isn’t too vague anymore. The deprecation warnings will come in the next versions and there will be also more sugar for the npm package.

**Comment by vdh** [comment]
I had a really frustrating morning today wondering why `window.__REDUX_DEVTOOLS_EXTENSION__` was undefined because of this. It's all well and good to deprecate a feature, but it doesn't help if the documentation (which is linked to directly from 2.6.1.1) is updated well before Chrome eventually gets around to updating the actual extension to 2.7.0 ☹️

**Comment by zalmoxisus** [comment]
@vdh, Chrome should update the extension 2 days ago. Maybe you disabled autoupdating extensions somewhere in Chrome settings? Though I didn't know it's possible to disable it.

**Comment by vdh** [comment]
Sadly, for some reason Chrome's extension auto-updating isn't so auto, I had to manually force an update.

It might be nice to have a "in 2.7.0" or "as of 2.7.0" note on the deprecated part in the instructions as a hint to check one's plugin version?

**Comment by zalmoxisus** [comment]
@vdh, I added a note in the README. Anyway, we need autoupdating, as we're moving really fast here and still want to change / improve a lot of things. Hope it was just a temporally problem of Chrome as we didn't experience it before. If you'll the problem with autoupdating will still persist, please open an issue, so we'll add a button to check if the extension is up to date and update it manually.

**Comment by oyeanuj** [comment]
@zalmoxisus I was a little confused while upgrading to the latest, around the usage of `window.devToolsExtension`. My code today looks like this:
```javascript
const { persistState } = require('redux-devtools');
const DevTools = require('../containers/DevTools/DevTools');
store = createStore(
  reducer,
  initialState,
  compose(
    applyMiddleware(...middleware),
    window.devToolsExtension ? window.devToolsExtension() : DevTools.instrument(),
    persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))
  )
);
```

Now with the new changes that you announced and deprecation of `window.devToolsExtension`, I changed my code to this:

```javascript
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
store = createStore(
  reducer,
  initialState,
  composeEnhancers(
    applyMiddleware(...middleware),
    window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : DevTools.instrument(),
    persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))
  )
);
```

but get the following error:
```
Uncaught Error: DevTools instrumentation should not be applied more than once. Check your store configuration.
```

I assume this error is because I can't use `composeEnhancers` with `window.__REDUX_DEVTOOLS_EXTENSION`. In that case, what is the best way to set it up to still be able to use standard old non-extension devtools & `persistState` as a backup?

Many thanks on your work on this!

**Comment by zalmoxisus** [comment]
@oyeanuj, yes you shouldn't use both. Best way would be:
```js
let enhancer;
if (window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) {
  enhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__(
    applyMiddleware(...middleware)
  );
} else {
  enhancer = compose(
    applyMiddleware(...middleware),
    DevTools.instrument(),
    persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))
  );
}
store = createStore(
  reducer,
  initialState,
  enhancer
);
```

New method, `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`, offers the ability to lock enhancers and middlewares (when the corresponding button is clicked) and to dispatch remote actions through other enhancers. See [the blog post](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83) for more details. If you don't need those features, you can just replace `window.devToolsExtension` with `window.__REDUX_DEVTOOLS_EXTENSION__`.

Also note that the extension already includes `persistState`.

**Comment by oyeanuj** [comment]
@zalmoxisus great, thank you for the detailed answer!

**Comment by dfrho** [comment]
Redux dev tools is an awesome tool - Thanks for the great work on it!

**Comment by akata01** [comment]
For any one who is looking for exactly what to write to make redux dev tools work - 
`import { createStore, applyMiddleware, compose } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";

import thunk from "redux-thunk";
import rootReducer from "./reducers";
import { persistState } from "redux-devtools";
import DevTools from "redux-devtools";

const middleware = [thunk];
const initialState = {};
let enhancer;
if (window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) {
  enhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__(
    applyMiddleware(...middleware)
  );
} else {
  enhancer = compose(
    applyMiddleware(...middleware),
    DevTools.instrument(),
    persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))
  );
}



const store = createStore(rootReducer, initialState, enhancer);

export default store;
`

**Comment by yairEO** [comment]
### This is how I use it (working fine):

    const store = createStore(reducer, initialState, window.devToolsExtension && window.devToolsExtension() );

**Comment by Rachomir** [comment]
@yairEO I am using it the same way, however I am not sure if its correct?

**Comment by zalmoxisus** [comment]
I think 2 years is enough for everybody to rename `window.devToolsExtension` to `window.__REDUX_DEVTOOLS_EXTENSION__` in their apps. We'll add a deprecation warning in `2.15.5` and remove the variable in `3.0`.

**Comment by ramsesls** [comment]
You could try like this

`const middlewares = [thunk];
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

export default function configureStore(initialState) {
  return createStore(
    reducer,
    initialState,
      composeEnhancers(applyMiddleware(...middlewares))
  );
}`

**Comment by Methuselah96** [comment]
Removed in 3.0.
