### ISSUE TITLE
Problem with ionic framework

### ISSUE THREAD

**Issue by gperdomor** [zalmoxisus/redux-devtools-extension#221]
Hi...

Is possible use this with ionicframework?

i use <code>StoreDevtoolsModule.instrumentOnlyWithExtension()</code>, but the redux extension show nothing.

I´m running the app inside the browser, not in iOS or Android simulator

**Comment by zalmoxisus** [comment]
@gperdomor, could you please provide more details? Does `window.devToolsExtension` exist there? If not, maybe it's `file:///` problem (you should allow it as described [here](https://github.com/zalmoxisus/redux-devtools-extension/issues/219#issuecomment-251382565)).

**Comment by gperdomor** [comment]
I run the app in the browser with <code>ionic serve</code> command.

I use the same configuration in a angular 2 project and works fine, but i try to do the same thing with a ionic 2 project without success :(

![screen shot 2016-10-05 at 9 36 33 am](https://cloud.githubusercontent.com/assets/371939/19113277/46ca5696-8adf-11e6-8b43-a8556d452d16.png)

**Comment by zalmoxisus** [comment]
As the extension's icon is grey, it doesn't receive anything from your application. As I understand, you're using `ngrx/store-devtools`. Maybe @MikeRyan52 has any suggestions. Anyway, a repo to reproduce would be welcome.

**Comment by gperdomor** [comment]
@zalmoxisus you can use this repo which have a basic ngrx configuration https://github.com/gperdomor/now-mobile-ionic/tree/feature/ngrx-store

**Comment by gperdomor** [comment]
I don't know how or why, but it's working now

**Comment by zalmoxisus** [comment]
Hey @gperdomor,

I finally got a chance to check your repo. It works for me (after skipping the intro). Checked on Firefox, Chrome and Canary.

Maybe changes in `2.8.0` regarding serializations addressed this issue as well.

Closing for now. If you're still experiencing this problem, feel free to reopen the issue with more details.
