### ISSUE TITLE
window.__REDUX_DEVTOOLS_EXTENSION__ is undefined

### ISSUE THREAD

**Issue by legomushroom** [zalmoxisus/redux-devtools-extension#222]
Hi, I have `window.__REDUX_DEVTOOLS_EXTENSION__` undefined. Strangely, I do have `Redux` tab in the `chrome dev tools`. Thanks in advance!

**Comment by legomushroom** [comment]
Found that the `Allow access to file URLs` should be checked in extension settings.

**Comment by zalmoxisus** [comment]
Thanks for the report anyway! It will be addressed in #219.
