### ISSUE TITLE
Slider effect to the Chart

### ISSUE THREAD

**Issue by DiMoNTD** [zalmoxisus/redux-devtools-extension#224]
Hi. First of all, thanks for that tool!

I'm interesting, could chart updating in time-travel, when I'm sliding steps?

I've recorded mutation of my state

![slider_chart](https://cloud.githubusercontent.com/assets/1331473/19156959/580b63d8-8bec-11e6-96e2-8429a1803c3b.gif)

I slide backward, and state in chart remains the same, but my app is travelling in time. This is a bug or feature? :)

Sorry for my English

**Comment by zalmoxisus** [comment]
Thanks for the suggestion :)

Yes, the Chart Monitor isn't aware of time travelling. It's something we want to have, but not implemented yet.

**Comment by DiMoNTD** [comment]
@zalmoxisus already in devtool!! thank you very much! Amazing thing!

**Comment by zalmoxisus** [comment]
@DiMoNTD, published just few minutes ago :)
Thanks for the suggestion!
