### ISSUE TITLE
Test Button?

### ISSUE THREAD

**Issue by m-lautenbach** [zalmoxisus/redux-devtools-extension#225]
I have a weird test button. Clicking it will break the extension.
![bildschirmfoto 2016-10-06 um 17 25 17](https://cloud.githubusercontent.com/assets/2509770/19158696/fe47e36e-8be9-11e6-98a9-d8ee3689a8b7.png)

**Comment by zalmoxisus** [comment]
It should generate tests for the currents state like so:
<img width="1284" alt="screen shot 2016-08-14 at 5 00 16 pm" src="https://cloud.githubusercontent.com/assets/7957859/17649551/fdf49830-6240-11e6-87f0-ea5d62b4d0a5.png">

There were a bug of codemirror causing the freeze, but should be fixed. 

Could you please try if it crash the extension for [our demo](http://zalmoxisus.github.io/examples/counter/) as well?

If not, than something inside the state causing `jsan`, `javascript-stringify` or `simple-diff` to hang. The source is [here](https://github.com/zalmoxisus/redux-devtools-test-generator). Maybe you could add [a test](https://github.com/zalmoxisus/redux-devtools-test-generator/blob/master/test/assertions.spec.js) to reproduce that?

**Comment by m-lautenbach** [comment]
I see.
It works for me in the demo.
I'd assume, that our state is probably just quite bit and that's why.
And it's based on Immutables.
I don't really have the time for testing this more.
It's not a feature we would use, although I see how it could be useful.
Thank you for your answer.

**Comment by zalmoxisus** [comment]
Hey @m-lautenbach,

This issue should be fixed now in `2.8.0`. Please confirm when you get a chance to check it.

**Comment by m-lautenbach** [comment]
Confirmed, looks good now 👍
