### ISSUE TITLE
Performance regression in latest

### ISSUE THREAD

**Issue by mattkrick** [zalmoxisus/redux-devtools-extension#226]
Huge fan, and thank you so much for your work!
Just wanted to point out a performance regression:
![screen shot 2016-10-07 at 9 54 26 am](https://cloud.githubusercontent.com/assets/5514175/19198444/167a0072-8c74-11e6-9f5e-5badcb075e7d.png)

I apologize I haven't kept up with all the internal changes (this is one of those extensions that is so darn magical & always works so well I've never had to dig any deeper :smile:), but using it with redux-form causes it to lag so badly that I have to disable it. 

If I can help, lemme know!

**Comment by zalmoxisus** [comment]
Hey @mattkrick,

I'm also a fan of meatier. Thanks for the report and kind words!

Unfortunately, I don't see where the perf bottle neck is here. I just tried [our example](http://zalmoxisus.github.io/examples/router/) (click on `AutoTodo`) and don't see any significant perf issues.

Did you notice this with `2.7.0` or it could be affected earlier? Do you have a perf issues even if you don't open the extension window? It shouldn't affect the perf in this case only the instrumentation. If it affects, try to add only [the instrumentation's enhancer](https://github.com/zalmoxisus/redux-devtools-instrument) to see if it can be replicated:
 ```js
import instrument from 'redux-devtools-instrument';
const store = createStore(reducer, instrument(undefined, {}));
```

Do you use the new `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`? If not the latest changes shouldn't affect the performance at all. You can dig it [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js).

**Comment by mattkrick** [comment]
I don't think the example hits it hard enough. In the application I'm testing on, I use redux-form & don't run it through a throttle function, so it's dispatching 2 actions per keystroke and it's fine up to about 60WPM, after that the lag is noticeable. (https://github.com/parabolinc/action). 
The bottleneck still occurs if the perf window is closed.
However, if I disable the extension & restart the browser, all good.
Similarly, running in incognito also runs great. 
No new stuff, same ol `global.devToolsExtension`.
It could have occurred in an earlier version. The last time I really focused on throughput was about 2 weeks ago, so anything since then could possible be the culprit.
I _really_ hope it's not chrome 😨 
I'll clone a few older versions & see if I can narrow it down.

**Comment by zalmoxisus** [comment]
@mattkrick, thanks a lot for the details, it was helpful enough to spot the problem. The changes in `2.7.0` broke global limit of actions, so they are stored infinitely now. A temporal solution would be to add `maxAge` parameter:
```js
const store = createStore(
  reducer,
  global.__REDUX_DEVTOOLS_EXTENSION__ &&
  global.__REDUX_DEVTOOLS_EXTENSION__({ maxAge: 30 })
);
```

**Comment by mattkrick** [comment]
no change in performance 😕

**Comment by zalmoxisus** [comment]
@mattkrick, I tried `Action` and don't get any noticeable perf problems even with the opened extension's window. Providing some steps to reproduce would be welcome.

I see there some `store.replaceReducer` which could cause problems as Redux DevTools uses reducer replacement as a signal of hot reloading, and recompute all the history when it happens (in the latest [there's a way to disable that](https://github.com/zalmoxisus/redux-devtools-extension/issues/205#issuecomment-251428885)). Could you please check if that's the issue?

Didn't notice anything else. If you close the extension window (in case you opened it from Chrome devpanel then close the panel as well), the extension's injected script [won't do anything](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L132). However, [redux devtools instrumentation enhancer](https://github.com/zalmoxisus/redux-devtools-instrument) keeps to store changes, which shouldn't affect cpu only ram. It could also be disabled by setting [`shouldRecordChanges` parameter](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#parameters) to `false`.

Also please take a look if you see some exception in the extenson's background page console (enable `Developer mode` on `chrome://extensions/` and click `background page` bellow the extension).

**Comment by mattkrick** [comment]
wow, thanks for digging in! I'll try this out in a bit & report back tonight or tomorrow.

**Comment by mattkrick** [comment]
@zalmoxisus i'm gonna file this one under unexplained mysteries... went to try out what you suggested, then tried it out bone stock & it worked like a charm. Now the CPU profiler didn't even call `backend.js` & it's back to running lightning fast. No chrome update, no update to the project I'm working on, I'm just stumped.

Thanks for sticking with me & providing all the venues to explore!

**Comment by zalmoxisus** [comment]
@mattkrick, no probs, feel free to reopen if it happens again.
