### ISSUE TITLE
`Uncaught TypeError: Cannot set property 'liftedStore' of undefined`

### ISSUE THREAD

**Issue by andykenward** [zalmoxisus/redux-devtools-extension#231]
If you don't want to allow the extension in production and you have the extension installed I get this error in chrome console

`Uncaught TypeError: Cannot set property 'liftedStore' of undefined`

I even get this if I totally remove any reference to redux-devtools in my code.

And it totally breaks my site. Only way to fix is to uninstall the extension. Which is very worrying. Surely the extension shouldn't have this effect if you arent even using it in your code?

Chrome `53.0.2785.143`
Mac `10.12`
Redux DevTools Extension version `2.8.2.1`

**Comment by zalmoxisus** [comment]
Could you please share the store config code?

**Comment by andykenward** [comment]
Yes, it is here [`store.js`](https://github.com/andykenward/bob/blob/903f3a6d5b53476e7ed51a778c635f107f74f41c/app/store.js).

It is an old implementation using `window.devToolsExtension` instead of the new `window.__REDUX_DEVTOOLS_EXTENSION__`.

But I have tried implementing most the examples from the latest [`README.md`](https://github.com/zalmoxisus/redux-devtools-extension/blob/3bbee506d39fa48dd19c341f0aa09a5f97c490a4/README.md) that checks the `process.env.NODE_ENV` so it doesnt run in `production`.

The develop branch of my repo deploys to [https://bob-andykenward-develop.herokuapp.com/](https://bob-andykenward-develop.herokuapp.com/)

**Comment by zalmoxisus** [comment]
Thanks for the details. As I see, [you're getting `undefined` from your `configureStore` function](https://github.com/andykenward/bob/blob/44c9365b3414bfd15f1d7522740f4c7cebe5c423/app/app.js#L31) then [trying to update the extension's store with `undefined`](https://github.com/andykenward/bob/blob/44c9365b3414bfd15f1d7522740f4c7cebe5c423/app/app.js#L39).

**Comment by andykenward** [comment]
argh. I am an idiot. Thank you for getting back to me so quickly.

removing [this](https://github.com/andykenward/bob/blob/44c9365b3414bfd15f1d7522740f4c7cebe5c423/app/app.js#L39) in production solved it.

**Comment by zalmoxisus** [comment]
@andykenward, no problems.

You cannot use [`window.devToolsExtension.updateStore` without the extension's enhancer](https://github.com/andykenward/bob/blob/44c9365b3414bfd15f1d7522740f4c7cebe5c423/app/app.js#L39).

However, `updateStore` is being deprecated, so you don't need that anymore, just use the new [`window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`](https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup). Also [we have a helper](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm) you can install and it will also strip the extension from production.
