### ISSUE TITLE
[Suggestion] Highlight recent action in inspector when using slider

### ISSUE THREAD

**Issue by Machiaweliczny** [zalmoxisus/redux-devtools-extension#234]
The only useful feature I could use from this redux-devtools is timeline(slider), which could allow me to debug flow of application, but it's not even highlighting which action I'm on when I move slider - which makes this slider feature unsuitable for debugging purposes. I suggest that actions we are currently on in slider is higlighted in inspector.

Another useful feature for debuging would be adding "jump to state" in inspector. Now only possibility is to skip 20 actions to get to state you want to be in - not practical at all.

Those are my suggestions which would make this tool really useful and shouldn't be too hard to implement. Maybe I will make a PR with it but if I don't please consider adding it anyway :)

**Comment by zalmoxisus** [comment]
Highlighting currently is only [implemented for Log Monitor](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.5.0). If youwant to submit a PR to [Inspector Monitor](https://github.com/alexkuz/redux-devtools-inspector), you can consider [mine](https://github.com/gaearon/redux-devtools-log-monitor/commit/5198c1bcd67e7cfbe9f8481625c97545737c8a7b) as an example of implementation.

A "jump to state" button in inspector would be nice to have. Also there's a [pr for shift toggle](https://github.com/gaearon/redux-devtools-log-monitor/pull/47) not to skip actions one by one.

**Comment by zalmoxisus** [comment]
Implemented in [`v2.12.0`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.0).
