### ISSUE TITLE
Add option to expand latest state

### ISSUE THREAD

**Issue by jiayihu** [zalmoxisus/redux-devtools-extension#236]
After the latest release all states are collapsed by default, but I think that leaving the latest expanded is more helpful and time-saving. At least I would recommend an option to enable the expansion.

**Comment by zalmoxisus** [comment]
I see. I also don't like this, but it was a workaround due to some changes in the latest `react-json-tree`.

Leaving the latest action expanded would be great indeed. What do you think should we expand the whole object or just the root as it was before?

**Comment by jiayihu** [comment]
Just the root should be enough and requires less space when there is a huge state. Most of the time I expand the latest state looking for a specific property to see if an action is working as expected. I believe it's the most common usage.

**Comment by zalmoxisus** [comment]
@jiayihu, I tried to implement this, but there are 2 problems on`react-json-tree` side:
- the previous objects aren't rerendered for performance reason;
- if you expand a state object to investigate it, you wouldn't want it to be collapsed when there's a new action recorded.

So, I just went out and restored the old behaviour - all objects root are expanded now. In case you figure how to address the problems above, feel free to reopen the issue.
