### ISSUE TITLE
v2.8.4 partially broken for ngrx/store-devtools

### ISSUE THREAD

**Issue by deini** [zalmoxisus/redux-devtools-extension#238]
I believe `v2.8.4` is partially broken for `ngrx/store-devtools` it can display the state and actions, etc. However clicking on things like `commit` or `skip` on an action is not working.

Reverted to `v2.8.3` and works fine.

This is literally my first try trying `ngrx/store-devtools` and this extension so I might be totally wrong or this could be just my bad luck.

**Comment by MikeRyan52** [comment]
Fixed in v3.2.0 of @ngrx/store-devtools.

**Comment by deini** [comment]
Thanks @MikeRyan52

**Comment by MikeRyan52** [comment]
@deini If you run into any trouble feel free to open an issue in ngrx/store-devtools

**Comment by zalmoxisus** [comment]
@MikeRyan52, just curious what was the problem. There shouldn't be any breaking changes in the latest.

**Comment by MikeRyan52** [comment]
@zalmoxisus There was a legitimate bug on our end and just to be sure I went ahead and addressed zalmoxisus/redux-devtools-extension#220

**Comment by zalmoxisus** [comment]
This one should be fixed in `2.8.5` of the extension.
