### ISSUE TITLE
keyboard shortcuts?

### ISSUE THREAD

**Issue by mmahalwy** [zalmoxisus/redux-devtools-extension#24]
Is there a shortcut to open and close it?

**Comment by zalmoxisus** [comment]
Hey @mmahalwy,

I thought there's no need for that as it is in another window, but, actually, it is a good proposal and easy to implement.

**Comment by mmahalwy** [comment]
Yes! It'd be awesome!

**Comment by mmahalwy** [comment]
I am really excited for this @zalmoxisus! When will 0.5.0 come out?

**Comment by zalmoxisus** [comment]
There's [a lot of work](https://github.com/zalmoxisus/redux-devtools-extension/milestones/v0.5.0) in order to get 0.5.0 released.

I was thinking to have 5 shortcuts: 4 depending on the position of the window and another one for open it as [a chrome panel](https://github.com/zalmoxisus/redux-devtools-extension#how-to-keep-devtools-window-focused-all-the-time-in-a-chrome-panel).

Better, I'll add for now the current implementation (a shortcut for opening the window on the left side) in 0.4.6.

**Comment by zalmoxisus** [comment]
Implemented in `0.4.6`. Chrome should autoupdate the extension in few hours. If you want to get it now, just remove and install it again from Chrome store.

Use Alt + Shift + Arrow left / right / bottom to show the window in the corresponding position or arrow up to open DevTools in Chrome panel.

I'll keep this issue open till I add the instruction about shortcuts in README.

**Comment by huang47** [comment]
I believe this cause a problem which suppress the default behavior(select a range a text) on mac

**Comment by zalmoxisus** [comment]
Hey @huang47,

Thanks for the report. Actually, the extension's shortcuts are customizable ("Keyboard shortcuts" option is on the bottom of the `chrome://extensions/`), but if there're better keys to use as default, so they will not conflict with anything else and, at the same time, be easy to remember (as for now just to left, right, bottom), we may change them globally. The keys should be used with Alt or Command.

**Comment by mmahalwy** [comment]
You can do CMD + CTRL + SHIFT?

**Comment by wesbos** [comment]
Just came here to say the same - `Alt` + `Shift` + `←` takes over the default select and jump by word shortcut on OSX. Can I turn this off?

**Comment by zalmoxisus** [comment]
@mmahalwy, sure, good suggestion. Maybe just  CMD + CTRL + Arrows for Mac? And ALT + SHIFT + Arrows for other OS.

**Comment by zalmoxisus** [comment]
@wesbos,  sure, the extension's shortcuts are customizable ("Keyboard shortcuts" option is on the bottom of the `chrome://extensions/`), you may change them or turn specific shortcuts off. As for my above comment, I'll change default shortcuts for mac today.

Thanks, guys, for the heads up!

**Comment by zalmoxisus** [comment]
Fixed in `v0.4.7`. Chrome should autoupdate the extension in few hours. If you want to get it now, just remove and install it again from Chrome store.

If still something goes wrong, feel free to reopen the issue.

**Comment by wesbos** [comment]
Thanks @zalmoxisus :) Great extension

**Comment by LL782** [comment]
@zalmoxisus Any way to turn the shortcuts of in Firefox?

**Comment by zalmoxisus** [comment]
@LL782 shortcuts were removed in `2.15.3`.

**Comment by LL782** [comment]
@zalmoxisus awesome!

**Comment by taylor-edwards** [comment]
@zalmoxisus For Firefox, the add on page is still showing the latest version is 2.13.1 (looking at https://addons.mozilla.org/en-US/firefox/addon/remotedev/). Do I need to build from source to get the fix?
