### ISSUE TITLE
"Serialize the state" available in Firefox but not in Chrome

### ISSUE THREAD

**Issue by maxime1992** [zalmoxisus/redux-devtools-extension#241]
Hi,

I'm usually developing my apps using Chrome.

I've seen that in order to use timetravel, undo, redo it's necessary to serialize the state.

In Firefox app, we do have the option : 
![image](https://cloud.githubusercontent.com/assets/4950209/19806464/6a37757a-9d1b-11e6-9fab-a34a21dbabb5.png)

In Chrome this option is missing : 
![image](https://cloud.githubusercontent.com/assets/4950209/19806491/9eb124d6-9d1b-11e6-9fbc-db67ad30e034.png)

How can we use ImmutableJs with Redux when working on Chrome ?

**Comment by zalmoxisus** [comment]
Hey @maxime1992,

There's just difference in versions, updates on Firefox comes with delay as they are reviewed about a week.

That options was confusing, it had nothing in common with `deserializeState` you want to pass (which should work without it). The purpose was to gain some performance by disabling serialization, but in practice it was even slower.

That said, now the state is always serialized before sending to the extension.

Back to the problem you're expecting. I just checked and seems to work as expected, here's [an example](https://github.com/zalmoxisus/ToDo-react-redux-immutable). The problem I guess is that `store-devtools` doesn't implement `deserializeState` parameter, so it shouldn't work in the earlier versions as well. Or does it work on Firefox for you?

**Comment by maxime1992** [comment]
Thanks for clarification! =) 
Yes it's working on Firefox but not on chrome.

**Comment by zalmoxisus** [comment]
@maxime1992, then it should be a regression on our side for sure. Related to #238. Will look into it.

**Comment by zalmoxisus** [comment]
Fixed in `2.8.6`. It should be available on Chrome Store in about an hour.
