### ISSUE TITLE
2.8.5 not up on npmjs

### ISSUE THREAD

**Issue by willdevelops** [zalmoxisus/redux-devtools-extension#242]
Latest version isn't up on npmjs .. is this intended?  (I ended up using the v2.8.5 off of github)

..only v1.0.0 shows up on npmjs
https://www.npmjs.com/package/redux-devtools-extension

**Comment by zalmoxisus** [comment]
Hey @willdevelops,

Yes. I know it's confusing, but here you see the version of browser extension, while [npm package](https://github.com/zalmoxisus/redux-devtools-extension/tree/master/npm-package) is `1.0.0`, which is just a helper as described [here](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm).

I'll add a description there to avoid confusion.

**Comment by willdevelops** [comment]
ah... thanks for the clarification.. my apologies!  👍
