### ISSUE TITLE
State view word wrapping makes state harder to read

### ISSUE THREAD

**Issue by adailey14** [zalmoxisus/redux-devtools-extension#244]
I always use redux devtools in a "column" layout off the the side of the browser. For the last few releases, something changed the way state is displayed that caused the word wrapping behavior seen in this screenshot. It's much harder now to read the state tree.

See screenshot attached.

![screen shot 2016-10-31 at 10 11 51 am](https://cloud.githubusercontent.com/assets/1168689/19859215/80a64e24-9f52-11e6-9263-59cfb15bff8c.png)

Could be fixed with css - some overflow: auto with white-space: nowrap would probably do it.

**Comment by zalmoxisus** [comment]
@adailey14, adding this style [here](https://github.com/alexkuz/redux-devtools-inspector/blob/9ce7985f16af9205013bac0b87e0fbe9a62aef55/src/utils/createStylingFromTheme.js#L248) could be a solution.

Though showing only `[...]` / `{...}` when there's not enough space would be way better. It could be done by modifying [`getText` function](https://github.com/alexkuz/redux-devtools-inspector/blob/9ce7985f16af9205013bac0b87e0fbe9a62aef55/src/utils/createStylingFromTheme.js#L248) or, even better, via css to show only first and last character with `...` separator.

If you want to contribute to [`redux-devtools-inspector`](https://github.com/alexkuz/redux-devtools-inspector) it would be welcome.

**Comment by adailey14** [comment]
@zalmoxisus Sorry I'd like to help but no time at the moment - maybe somebody else can take it on.

**Comment by zalmoxisus** [comment]
Implemented in the latest. Thanks a lot for the pointing it out! Let me know if you're still experiencing any troubles with it.
