### ISSUE TITLE
stateSanitizer breaks when called from startingFrom

### ISSUE THREAD

**Issue by tomxtobin** [zalmoxisus/redux-devtools-extension#246]
[In `app/api/filters.js`, `startingFrom` calls `stateSanitizer` with the state wrapper, instead of the actual state object, so `stateSanitizer` ends up getting `{state: actual_state}`.](https://github.com/zalmoxisus/redux-devtools-extension/blob/cc9c889853e0febaab34655879e0160f6a10a5d2/src/app/api/filters.js#L127) This ends up breaking `stateSanitizer`.

The call to `stateSanitizer` should pass `currState.state`, instead.

(I didn't submit a PR since I've never worked on a Chrome extension, and have no idea what I might miss in terms of tests or whatnot.)

**Comment by zalmoxisus** [comment]
Yes, and `actionSanitizer` should take `currAction.action` as well (as for [predicate](https://github.com/zalmoxisus/redux-devtools-extension/blob/cc9c889853e0febaab34655879e0160f6a10a5d2/src/app/api/filters.js#L117)). 

And yes we need better contribution guides to help with that. I'll publish a patch on Chrome store with the fix in a while.

**Comment by zalmoxisus** [comment]
Fixed in `2.9.0.2`. Thanks for the report and the solution!
