### ISSUE TITLE
Extension injects window.devToolsExtension on all pages irregardless of config

### ISSUE THREAD

**Issue by zerkms** [zalmoxisus/redux-devtools-extension#25]
Chrome: Version 47.0.2526.80 m

In config the "Inject in all pages" is not checked

The list of regexes contains these 2 expressions:

    ^https?://localhost|0\.0\.0\.0:\d+
    ^http://192\.168\..*

but still the `window.devToolsExtension` is injected to literally every page.

Additionally to that the address bar icon only appears on first page load: that is, only the very first page ever opened in a browser has it till the first page reload. After that the address bar icon never appears again.

The chrome dev tools "Redux" tab works fine though.

**Comment by zalmoxisus** [comment]
Hey @zerkms,

Thanks for you report! Regarding page reload, It seems I broke it yesterday in https://github.com/zalmoxisus/redux-devtools-extension/commit/5821cf656a47a62e47424e1ccac33ccc473c104f, will fix ASAP.

About injecting `window.devToolsExtension` even if it is exclude in options, it is intended, added to fix #22. When it is called, we check whether it is allowed or not.

**Comment by zerkms** [comment]
@zalmoxisus sorry I didn't provide any technical details - I reported few minutes before I left the office. Tomorrow I'll try to make even a small research.

**Comment by zalmoxisus** [comment]
@zerkms, ok. Anyway, thanks a lot for pointing me out with the issue with page reload. I've fixed it already. Will push it today in `v0.4.7`.
