### ISSUE TITLE
Imports with remotedev_report do not show expected actions in ReduxDevTools

### ISSUE THREAD

**Issue by jrullmann** [zalmoxisus/redux-devtools-extension#251]
I'm trying to test this extension with redux-devtools and having trouble. 

To reproduce:

1. Install DevTools extension, configure the settings with the host and port of where remotedev-server is running
1. Add `redux-remotedev` to a redux app. Configure it to send a report to remotedev-server whenever a specific action is dispatched. I called mine `SEND_BUG_REPORT`
1. Dispatch some action. I called mine `LOGIN`
1. Dispatch `SEND_BUG_REPORT` to create a report
1. Retrieve the report ID
1. Reload the page with `remotedev_report` param set to the retrieved report ID

Expected: Redux DevTools shows  `@@INIT`, `LOGIN`, and `SEND_BUG_REPORT`)
Actual: ReduxDevtools shows `@@INIT`

I've confirmed that the report is retrieved from the server:
![screen shot 2016-11-05 at 10 21 16 am](https://cloud.githubusercontent.com/assets/1865328/20032185/63342656-a342-11e6-822c-1f0417d2c9de.png)

But Redux DevTools doesn't show the report's actions:
![screen shot 2016-11-05 at 10 21 28 am](https://cloud.githubusercontent.com/assets/1865328/20032189/67bc207a-a342-11e6-8759-cfb14cc544df.png)

Sorry I can't provide the code I'm using to test, the company I work for doesn't let me open source any code without approval.

Browser: Chrome Version 54.0.2840.71 (64-bit)
Redux DevTools Extension Version 2.9.1

Report retrieved from the server:

`
{
	"id": "d2f7cb0f-83cf-49cb-9e7b-95d7c8e129f5",
	"type": "ACTIONS",
	"action": "SEND_BUG_REPORT",
	"payload": "[{\"type\":\"LOGIN\",\"username\":\"test@test.com\",\"password\":\"abc\"},{\"type\":\"SEND_BUG_REPORT\"}]",
	"preloadedState": "{\"loggedInUserName\":null}",
	"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36",
	"isLog": false,
	"added": 1478366400026
}
`

**Comment by zalmoxisus** [comment]
It seems to be a regression introduced in [`2.6.0`](https://github.com/zalmoxisus/redux-devtools-extension/releases?after=v2.6.1), so [`window.store.liftedStore.importState` function](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/background/logging.js#L17) doesn't exist anymore.

**Comment by zalmoxisus** [comment]
@jrullmann, fixe in `v2.9.2`. It will be available on Chrome Store in about an hour.

I should have to check that before, sorry about that. Let me know if you have any other troubles with that.

**Comment by jrullmann** [comment]
@zalmoxisus awesome! I don't see v2.9.2 in the Chrome Store yet - is it typical to take this long?

**Comment by zalmoxisus** [comment]
@jrullmann, I'm sorry, there were a server error when uploading, and I didn't notice :-/
It's available now.

**Comment by jrullmann** [comment]
Woot, it works!!
