### ISSUE TITLE
Problems displaying action objects

### ISSUE THREAD

**Issue by luisherranz** [zalmoxisus/redux-devtools-extension#253]
We are having troubles reading our action objects from redux-dev-tools since a week or so. 

Sometimes the action object is ok:
![screen shot 2016-11-02 at 17 11 14](https://cloud.githubusercontent.com/assets/3305402/20174211/19aa5efc-a73d-11e6-8c34-cca3c1020ad0.png)
But sometimes the action object is somehow displayed incorrectly:
![screen shot 2016-11-02 at 17 11 03](https://cloud.githubusercontent.com/assets/3305402/20174226/2c248e04-a73d-11e6-99cd-12bbbae9e2a1.png)

This seems to be happening randomly, even with the same actions, like in the images. It didn't happen before, for example the action of the images is quite old, so definitively is something which has changed lately.

We'd love to help so if we can do any test or something let me know. We are running Chrome v56 and Redux DevTools Extension v2.9.2.

**Comment by zalmoxisus** [comment]
Yes, we are not showing circular references now by default, for performance reason. If you want to see circular structures in the extension's monitors (instead of the simplified path) just set `serializeState` parameter to `false`:

```diff
import { createStore, applyMiddleware, compose } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
import thunk from 'redux-thunk';
import rootReducer from './reducers/reducers';

+ const composeEnhancers = composeWithDevTools({
+   serializeState: false
+ });

export const store = createStore(
    rootReducer,
-    composeWithDevTools(applyMiddleware(thunk))
+    composeEnhancers(applyMiddleware(thunk))
);
```

**Comment by zalmoxisus** [comment]
In case you didn't intend to have circular references in your states and it happen accidentally, [here's how you can spot it](https://github.com/gaearon/redux-devtools/issues/323#issuecomment-258139062).

**Comment by luisherranz** [comment]
Thanks for your answer @zalmoxisus.

We don't use `composeWithDevTools` and `thunk`. We use this:
```javascript
compose(
    reduxReactRouter({ createHistory: require('history').createHistory }),
    applyMiddleware(sagaMiddleware),
    typeof window !== 'undefined' && window.devToolsExtension ? window.devToolsExtension() : f => f
  )
```

I'll try to update our code to `composeWithDevTools` to see if that helps.

**Comment by luisherranz** [comment]
It didn't work with either `composeWithDevTools` or `composeEnhancers`.

**Comment by luisherranz** [comment]
The errors seems quite random:
![screen shot 2016-11-10 at 14 13 33](https://cloud.githubusercontent.com/assets/3305402/20178052/e8d2d260-a74f-11e6-89fc-91707dc8cb81.png)
![screen shot 2016-11-10 at 14 13 37](https://cloud.githubusercontent.com/assets/3305402/20178063/efb10980-a74f-11e6-8a84-4111eb412281.png)

The same actions sometimes are fine and sometimes they are not.

**Comment by luisherranz** [comment]
Any other ideas on what to explore?

**Comment by zalmoxisus** [comment]
@luisherranz, sorry, you should set `serializeState` to `true` not to `false`.

It appears random depending of what part of the history was sent to the extension.

Using the npm package is not mandatory. It could be use also as following: 
```js
const composeEnhancers =
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?   
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
        serializeState: true
      }) : compose;

  const enhancer = composeEnhancers(
    applyMiddleware(...middleware),
    // other store enhancers if any
  );
  const store = createStore(reducer, enhancer);
```

**Comment by luisherranz** [comment]
@zalmoxisus thanks.

If I set `serializeState` to true, my app doesn't connect to ReduxDevTools. There is no action or selection available. It's like ReduxDevTools doesn't see it anymore:
![screen shot 2016-11-10 at 15 04 42](https://cloud.githubusercontent.com/assets/3305402/20179561/08b89aea-a757-11e6-81c2-d15e18e69a32.png)

**Comment by zalmoxisus** [comment]
@luisherranz, do you get any errors on the console?

**Comment by luisherranz** [comment]
Oh, sorry. Yes, I'm getting `Uncaught TypeError: Cannot read property 'toJS' of null` when I try to open ReduxDevTools.

**Comment by zalmoxisus** [comment]
@luisherranz, could you please paste the fragment of code which throws? It [shouldn't happen as the value is checked before that](https://github.com/zalmoxisus/redux-devtools-extension/blob/6d5e65c457070efbf6ad6b00980c2158b986ecea/src/app/api/index.js#L12).

**Comment by luisherranz** [comment]
> Update: Didn't know that typeof null is object O_o.

Yeah, that's one of those funny things about JS.

**Comment by luisherranz** [comment]
> @luisherranz, could you please paste the fragment of code which throws? It shouldn't happen as the value is checked before that.

The error kicks in when I click on the ReduxDevTools icon to see the interface:

![screen shot 2016-11-10 at 16 09 01](https://cloud.githubusercontent.com/assets/3305402/20181841/08d1f810-a760-11e6-8207-1ba3624dcabb.png)

**Comment by zalmoxisus** [comment]
It's fixed in `2.10.0.1` (should be available in maximum an hour on Chrome store). Also `{ serializeState: false }` works now, it takes care only of circular references, while setting it to `true` serialize all special types (being much slower).

**Comment by luisherranz** [comment]
Awesome @zalmoxisus :)

I'll try updating Chrome within an hour and I'll let you know.

**Comment by zalmoxisus** [comment]
Should work. If not,  feel free to reopen the issue.

**Comment by luisherranz** [comment]
Yes, confirmed this is working fine again with 2.10.1! Sorry for the lack of feedback, I've been out of the office these days.
