### ISSUE TITLE
Respect serialization parameters when doing export

### ISSUE THREAD

**Issue by minedeljkovic** [zalmoxisus/redux-devtools-extension#255]
[New serialization options](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.8.4) are really helpful when actions and/or state contain not JSON.stringify-friendly values like dates and errors.

Could these parameters also affect serialization on export?
(I believe it is [here](https://github.com/zalmoxisus/remotedev-app/blob/16f9035c0da289680ce804cc1bc67cb4ea91ea36/src/app/components/buttons/ExportButton.js#L22))

It is needed to be able to round-trip dates, errors, etc. during export/import.

**Comment by zalmoxisus** [comment]
Good point. We just need to pass that parameter from the client part as we do for action creators.

**Comment by minedeljkovic** [comment]
I tried to play with this and come up with a problem with `jsan.stringify`.

Checks with `instanceof` that are made [here](https://github.com/kolodny/jsan/blob/9b37cebc85c5a5cbca0b512764b3a8f5511a93b6/lib/cycle.js#L25) and [here](https://github.com/kolodny/jsan/blob/9b37cebc85c5a5cbca0b512764b3a8f5511a93b6/lib/cycle.js#L37), for example, give false negatives in this situation. I believe because of [transfer of values between different contexts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_(e.g._frames_or_windows)).

I am cc-ing @kolodny here, for his opinion on changing `instanceof` to `Object.prototype.toString` checks (exclusively or optionaly).
[Here](https://jsperf.com/instanceof-vs-object-prototype-tostring2) are jsperf results for completeness.

**Comment by zalmoxisus** [comment]
Another solution would be instead of [stringifying the liftedState](https://github.com/zalmoxisus/remotedev-app/blob/16f9035c0da289680ce804cc1bc67cb4ea91ea36/src/app/components/buttons/ExportButton.js#L22) from the extension part, to request it form the client side. The problem here is that we should keep [`handleExport`](https://github.com/zalmoxisus/remotedev-app/blob/16f9035c0da289680ce804cc1bc67cb4ea91ea36/src/app/components/buttons/ExportButton.js#L21) synchronous, otherwise to trigger the download from javascript, which wasn't working well on Firefox when I tested.

**Comment by zalmoxisus** [comment]
@minedeljkovic, I implemented it in https://github.com/zalmoxisus/redux-devtools-extension/commit/a54c2bcb9a68ee61269340bc2b676725546c02c7 and https://github.com/zalmoxisus/remotedev-app/commit/551a10fdde8118d6e61b26626097504fb4d9438b.

It should work in just published `2.10.1`.

**Comment by minedeljkovic** [comment]
This looks great!

I found one small issue.
It seems that `payload` and `preloadedState` values are [stringified](https://github.com/zalmoxisus/redux-devtools-extension/blob/70c28cd2246ebd726cb1126fe83ca64edd1b7dad/src/app/api/index.js#L39) [separately](https://github.com/zalmoxisus/redux-devtools-extension/blob/70c28cd2246ebd726cb1126fe83ca64edd1b7dad/src/app/api/index.js#L40), but [parsed together](https://github.com/zalmoxisus/redux-devtools-extension/blob/70c28cd2246ebd726cb1126fe83ca64edd1b7dad/src/app/api/importState.js#L7) (root object containing `payload` and `preloadedState` keys).
This messes up [jsan's reference handling paths](https://github.com/kolodny/jsan/blob/master/lib/cycle.js#L57).

**Comment by zalmoxisus** [comment]
I see. Thanks a lot for the investigations! Fixed in `2.10.1.1`.

Feel free to reopen the issue if it still goes wrong.
