### ISSUE TITLE
Option to disable alt+shift+arrow keybinding?

### ISSUE THREAD

**Issue by cloud-walker** [zalmoxisus/redux-devtools-extension#257]
Hi, I use the alt+shift+arrow keybinding for text selection purposes, but the redux devtool pops up instead, is very annoying, It is possible to disable this feature with an extension option for example?

Thanks in advance!

**Comment by zalmoxisus** [comment]
Yes, those shortcuts are disabled by default since [`2.8.2`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.8.2), but I guess you've installed the extension before that.

To set/change the keyboard shortcuts, click "Keyboard shortcuts" button on the bottom of the extensions page (`chrome://extensions/`).

**Comment by cloud-walker** [comment]
![image](https://cloud.githubusercontent.com/assets/1144075/20345281/beb0691a-abf6-11e6-9af4-ff83b3d19c95.png)

Didnt know that! Thanks!

**Comment by mathieux51** [comment]
Hi @zalmoxisus, I have this issue on firefox. What should i do to disable the shortcut ?

**Comment by zalmoxisus** [comment]
AFAIK, it's not possible to customize extension's shortcuts on firefox yet. However, we removed them in `2.15.0`, which is still awaiting review. When it will be available (I think in about a week), there shouldn't be predefined keyboard shortcuts  anymore.

**Comment by lsmoura** [comment]
Sorry about reviving this old issue, but I'm on a Mac with addon version `2.15.2` and I'm still having the "SHIFT+OPTION+ARROW" problem. Is there any way to remove it? Both firefox and redux extensions were installed today.

**Comment by redoPop** [comment]
The latest release of the Firefox add-on (2.15.2) contains `suggested_key` entries for these shortcuts in its manifest.json. For now I've switched to the previous release (2.15.1) [which is available on Mozilla's add-ons page.](https://addons.mozilla.org/en-US/firefox/addon/remotedev/versions/)

Oddly, the manifest.json distributed with 2.15.1 [(copied to a gist here)](https://gist.github.com/redoPop/a2b39feab50aa46108a861cdd44fd232) is substantively different from [any record of that file in this repo's history.](https://github.com/zalmoxisus/redux-devtools-extension/commits/8b3a15db7dd8c819680023621456d63b35ff0bfe/src/browser/firefox/manifest.json) Is it possible some history's been clobbered in the repo?

**Comment by zalmoxisus** [comment]
@lsmoura I've just published `2.15.3` with removed shortcuts. It will be available after a moderator review it.

@redoPop yes, we had the same manifest [as for chrome](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/manifest.json) in `2.15.1`. For chrome it's possible to enable/disable and customize keyboard shortcuts of the extensions. AFAIK it's not possible on Firefox yet.

**Comment by redoPop** [comment]
Just updated to 2.15.3. Thanks for the quick fix & release!

**Comment by Scentle5S** [comment]
I'm sorry to re-open this once more, but I can't for the life of me find the latest version for Firefox :
- Chrome Web Store shows 2.15.3
- Mozilla Add-ons shows 2.13.1 as updated 4 days ago
- Your GitHub shows 2.15.0 in the releases section
- Mozilla's old versions only show 2.13.1

I managed to build and load manually but it only lasts until the next restart.

Am I missing something ?

**Comment by Grsmto** [comment]
I confirm this. Just switched to Firefox yesterday and having this issue.

**Comment by zalmoxisus** [comment]
Last version was removed and downgraded for some reason. New version should be reviewed and hope accepted soon. Let's track the issue in #573.
