### ISSUE TITLE
Multiwindow support

### ISSUE THREAD

**Issue by m-lautenbach** [zalmoxisus/redux-devtools-extension#259]
I tried to compare the Actions of two different windows of our app.
This doesn't seem to be supported, because the two windows seem to share the actions list.
Is this a bug or would that be an improvement or do I just use it wrong?

**Comment by zalmoxisus** [comment]
I'm not sure I understand the problem. Every window has its instance. You should select it:
<img width="348" alt="redux_devtools" src="https://cloud.githubusercontent.com/assets/7957859/20383250/aaa3efd4-acb7-11e6-8032-45407a1a983c.png">

**Comment by m-lautenbach** [comment]
Ok, when I manually select instances, it works.
So autoselect selects the instance from another window?

**Comment by zalmoxisus** [comment]
`Autoselect` means that it will show the instance which dispatched an action (so you'll not miss any new actions). So, when you open the second window, the new instance is dispatching an action and it gets autoselected.


However, I agree that we should get the current window's instance selected by default, which works when opening the extension browser action popup, and used to work when opening from devpanel (but was altered lately).

**Comment by m-lautenbach** [comment]
Thanks for the explanation.
I'd agree to your point, especially because both instances had the same name in my case.

**Comment by zalmoxisus** [comment]
It should select the instance for the current window now when opening devpanel. Thank you for the heads-up!
