### ISSUE TITLE
App failing to load-- VM135:1 Uncaught DataCloneError: 

### ISSUE THREAD

**Issue by bd** [zalmoxisus/redux-devtools-extension#26]
The full error: `VM135:1 Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': An object could not be cloned.`

Clicking the search/url bar icon, I see that it has the correct initial state of the app in the redux-devtools-extension-window, though the route change actions I expect are not there.

This happens on my actual in-development app, running in a Windows 8 VM, if that's relevant. When I get this error, I have state serialization disabled; however, if I enable state serialization, my site the app seems to hang, and often the whole page will crash. Nothing meaningful shows up in the console. The React Devtools never connect. 

I don't have any problem when visiting the example apps. 

I'd love to use this, since it's exactly the solution to my current problem with the basic devtools.

**Comment by zalmoxisus** [comment]
Hey @bd,

The serialization should be enabled in your case as it is required for circular dependencies (probably from redux-router), otherwise javascript cannot send the states via `postMessage` as discussed in #5.

About the issue with crashing and hanging, we have a similar issue in #23, but I wasn't able to replicate it. If you could help me to reproduce it, you publish an example project, I'd be able to fix it.

**Comment by bd** [comment]
hi @zalmoxisus, 

I appreciate your rapid response. I looked over #23, which does appear to be a similar issue. I'd love to help reproduce it, but I'm not exactly sure where to begin. The project is in a client's private repo, and I can't share the code in general. Closed source is a bummer. 

If you give me a general idea of where the issue might be, I could try and construct the minimum example to reproduce it. 

Further detail that I have now: 
The memory in that tab goes through the roof, as well as CPU usage. 
Here is the store config: 

    const createStoreWithMiddleware = compose(
	    // COMMON
	    applyMiddleware(thunkMiddleware, apiMiddleware),
	    reduxReactRouter({ Routes, createHistory }),

	    // DEV ONLY 
	   // devTools(),
	   // trying to get the more useful chrome extension to work...
	    typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ? window.devToolsExtension() : f => f
	)(createStore);

    export default function configureStore(initialState) {
         return createStoreWithMiddleware(reducer, initialState);
        };

**Comment by zalmoxisus** [comment]
I see. You could fork and clone [my boilerplate](https://github.com/zalmoxisus/boilerplate) and see if it happens there (it also include redux router and hmr). If not, then try to make some similar changes to your states structure.

**Comment by zalmoxisus** [comment]
Hey @bd,

Did you try Redux DevTools without the extension? Does the performance issue appear there as well? Just wondering if it could be an issue of Redux Router, if so, better to switch to `redux-simple-router` as @gaeron [recommended](https://github.com/gaearon/redux-devtools/issues/187#issuecomment-164321131).

And please give a try to `v0.4.8`.

**Comment by bd** [comment]
I use Redux DevTools, and don't see the issue there. I've made some changes
in the app since, and haven't had the bandwidth to investigate much since,
so it's possible that my problem was coming from a combinatorial explosion
of jQuery selectors that has since been fixed... I'll look into it and
report back as soon as I'm able. Thanks for your help!

**Comment by zalmoxisus** [comment]
Should work in `v0.4.9` (at least the issue described in the title is fixed). Please let me know whether you still experience performance issues. If yes, let's continue the investigation in #23.
