### ISSUE TITLE
time travel isn't working when using the redux-batched-subscribe store enhancer

### ISSUE THREAD

**Issue by borisirota** [zalmoxisus/redux-devtools-extension#261]
Hi, any idea why the time travel isn't working when using the [redux-batched-subscribe](https://github.com/tappleby/redux-batched-subscribe) store enhancer ?

Thanks

**Comment by zalmoxisus** [comment]
Hi. Could you please provide an example repo or jsfiddle? I'd look into it.

**Comment by borisirota** [comment]
https://github.com/borisirota/redux-batched-subscribe-dev-tools-issue

Thanks !

**Comment by zalmoxisus** [comment]
@borisirota, thanks for the example.

There's no problems with `redux-batched-subscribe`, just the orders of the enhancers matters. So, time travelling actually works, but `redux-batched-subscribe` is not aware of that action (and `react-redux` listener is not called). To get React updated with those changes you have to emit another action.

The solution is not to use `composeWithDevTools`, which assures the extension's enhancer to be the last in `compose` (which is not the case of `redux-batched-subscribe`), but to use it like so:

```js
  const store = createStore(reducer, preloadedState, compose(
    applyMiddleware(thunk),
    window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : noop => noop,
    batchedSubscribe((notify) => notify())
  ));
```

So `redux-batched-subscribe` will be after the extension's enhancer and will be aware of its actions.

Note that you'll not need that `noop` function in the next version of Redux thanks to https://github.com/reactjs/redux/pull/2073.

**Comment by borisirota** [comment]
it works ! great ! thanks a lot !!! 👍

**Comment by zalmoxisus** [comment]
You're welcome. Added a note about it in [Troubleshooting](https://github.com/zalmoxisus/redux-devtools-extension/commit/f8a6edcb442d962fdc8f7b58a4f7a920ce55f112).
