### ISSUE TITLE
Version 2.10.3 is no longer able to import state

### ISSUE THREAD

**Issue by mwlpeeters** [zalmoxisus/redux-devtools-extension#262]
Import of a state does not work in 2.10.3 but is does in 2.10.2

I've tested this on a separate machine with 2.10.2 and on my own machine by loading the 2.10.2 version from disk.

**Comment by zalmoxisus** [comment]
Thanks a lot for the report! Fixed in https://github.com/zalmoxisus/remotedev-app/commit/957a4b75b20b8630901b25f8dd39410833cd9cfb.

Published `2.10.3.1`, which should be available in about an hour on Chrome Store.

**Comment by mwlpeeters** [comment]
Thanks a lot, just installed the latest version of the extension and it now works correctly again.
