### ISSUE TITLE
No store found on chrome 54

### ISSUE THREAD

**Issue by mojim** [zalmoxisus/redux-devtools-extension#264]
Hi 

Thanks for this great tool

Unfortunately, In Chrome 54 I get this error

No store found. Make sure to follow the instructions.

Everything is just fine without any error but don't know how to fix this

Best regards

**Comment by zalmoxisus** [comment]
HI. I am using Chrome 54 as well without any problems. Please share your store config.

**Comment by zalmoxisus** [comment]
Any updates on this?

**Comment by mojim** [comment]
Dear zalmoxisus,
My store configuration was wrong 
It's work
Thanks
