### ISSUE TITLE
Extension stopped working in Firefox Developer Edition (52.0a2)

### ISSUE THREAD

**Issue by blakek** [zalmoxisus/redux-devtools-extension#268]
This extension seems to have stopped working a few days ago on the Firefox Developer Edition channel (but still works on public release Firefox v50).  Other plugins (e.g. Adblock Plus) also seem to be having problems with the latest updates, so perhaps there has been an API update from Mozilla.

Thanks for the awesome plugin!

**Comment by zalmoxisus** [comment]
Do you mean that the context menu disappeared?

I just tried it on Firefox Nightly 53.0a1. And it works well, except there's no  context menu anymore.

**Comment by zalmoxisus** [comment]
The same with Developer Edition 52.0a2. Seems like `runtime.onInstalled` still doesn't work properly on Firefox, so I reverted https://github.com/zalmoxisus/redux-devtools-extension/commit/348d0bbc06291d02c17aa9032b1cb42e44195095, which fixed the issue with the context menu.

Published `2.11.1` on AMO, which will be available once get reviewed (usually takes several days). For now, you can open the windows by clicking the extension icon on the location bar.

**Comment by blakek** [comment]
@zalmoxisus yes, sorry about the poor choice of words.  I couldn't get the context menu or the keyboard shortcut to activate the plugin in 52.0a2.

I am sometimes able to get the keyboard shortcut to activate the plugin, but only if the DevTools are open.  When I press the default keyboard shortcut when the DevTools are closed, Firefox 52.0a2 selects text instead of opening the plugin window.  This could be an Firefox issue but thought I'd bring it up.

Funnily enough, as long as I've used this plugin, I didn't know the location bar button existed because I thought it was one of wappalyzer's icons.

Thanks for pushing the fix for the context menu!

**Comment by zalmoxisus** [comment]
Yes, `Alt` + `Shift` + arrows are also used by Firefox for the selection, and don't always work. We could use other combinations in `3.0`, just I'm afraid of collisions with other extensions, since extensions shortcuts on Firefox cannot be customized (as on Chrome) yet.

**Comment by zalmoxisus** [comment]
`2.12.0` is now available on AMO with all the fixes and updates. Let me know if there are any other issues.

I'm still not sure what to do with shortcuts for Firefox. On Chrome shortcuts are configurable, so we don't set them by default. I think will just remove all shortcuts for opening the monitor windows, and will use only `Ctrl+Shift+E`, which opens the action page popup.
