### ISSUE TITLE
Filter actions in DevTools not working as expected

### ISSUE THREAD

**Issue by haikyuu** [zalmoxisus/redux-devtools-extension#271]
_I suspect this has already been solved, but i couldn't figure out an easy way to achieve it_
_As this has been already discussed here : https://github.com/gaearon/redux-devtools/issues/77_
## Expected behaviour:
Filtered actions are **just** hidden from the inspector.
## Current behaviour
Filtered actions are **totally ignored** by redux devtools

## Use case
I have an action that is triggered every second (timer), and it affects the state of my app (everything revolves around it). 
When the effects of this action are ignored, there is no state to inspect !
I'd like to only hide it in the inspector.
I think it would be very convenient to have this feature in the chrome extension.

What do you think?

**Comment by zalmoxisus** [comment]
Filtered actions are not ignored by redux devtools, they are just not sent to the monitor. In this way they have no perf impact (as there no need to serialize them).

However you can filter actions right in the inspector. Just type a fragment of the action type in the `filter` field. You could group actions by categories adding a prefix (like for example `form/ACTION`). If you want to extend filtering on the inspector monitor part by supporting regex expressions, feel free to contribute [there](https://github.com/alexkuz/redux-devtools-inspector).

**Comment by haikyuu** [comment]
Here is a screenshot when i filter the timer action: (after 10 seconds, the timers are still 0)

![screenshot 2016-12-16 11 05 12](https://cloud.githubusercontent.com/assets/8558836/21260839/bc201254-c37f-11e6-942b-169a165fc16c.png)
And another one when i remove the filter

![screenshot 2016-12-16 11 08 02](https://cloud.githubusercontent.com/assets/8558836/21260874/f13aef9a-c37f-11e6-9b5b-64e34ef6e48b.png)

**Comment by haikyuu** [comment]
Please note that i'm talking about filtering from the options 

![screenshot 2016-12-16 11 09 33](https://cloud.githubusercontent.com/assets/8558836/21260907/25563500-c380-11e6-9e8d-1f53df136f08.png)

**Comment by zalmoxisus** [comment]
Yes, that's expected. Filtered actions are not sent to the monitor part, not to affect the perf. When you dispatch an unfiltered action, you'll get the data.

**Comment by haikyuu** [comment]
I understand now, thanks. 
I'll group actions by categories then 👍

**Comment by zalmoxisus** [comment]
What you wanted to accomplish would lead to inconsistent data, as for each displayed action we want to see the affected state, which also gives the ability to time travel.

In `3.0` we'll have more monitors, including [`filterable-log-monitor`](https://github.com/bvaughn/redux-devtools-filterable-log-monitor), which would work better for your case.
