### ISSUE TITLE
Browser window doesn't reflect changes from Redux Devtools Extension

### ISSUE THREAD

**Issue by johnhamm** [zalmoxisus/redux-devtools-extension#273]
I'm using Redux Devtools Extension  2.11.1.1 and ngrx/store 2.2.1

If I click Skip on an action in Redux DevTools (e.g. USER_LOGOUT), the browser window will still show the user logged in unless I click on the browser window somewhere and then it will update.  This makes it impossible to use the timeline replay feature as the browser window won't update unless I click somewhere in it.

**Comment by johnhamm** [comment]
Some further troubleshooting:

In my app module, I was using:
`
StoreDevtoolsModule.instrumentOnlyWithExtension(),`

to setup support for this (awesome btw) extension.  When I switched to:
`StoreDevtoolsModule.instrumentStore({ monitor: useLogMonitor() }),`

it caused the browser window to refresh correctly now when changes are made to the addon.

**Comment by zalmoxisus** [comment]
@johnhamm it should be fixed in https://github.com/ngrx/store-devtools/pull/37. Make sure to use `ngrx/store-devtools@3.2.2`.

**Comment by johnhamm** [comment]
@zalmoxisus I'm using @ngrx/store-devtools 3.2.2 

I was able to get it working, though, just by including the custom log monitor but not showing it (i.e. still using your amazing addon)

**Comment by zalmoxisus** [comment]
@johnhamm I'm not using `@ngrx/store`, angular and rxjs. So it would be difficult to me to investigate the problem. I just tried [`example-app`](https://github.com/ngrx/example-app) and it works as expected. I added a book to the collection, and skipping `Add Book Success` removes the book. Could you please try this example too and try to dig into `ngrx/store-devtools` to see what is happening in you case?

**Comment by johnhamm** [comment]
@zalmoxisus I just tried the example-app and it works as expected.  I'm not sure why my app requires a click in the browser window for timetravel to work.

**Comment by zalmoxisus** [comment]
@johnhamm, maybe it's about a specific middleware like in #270.

**Comment by pixelypants** [comment]
@zalmoxisus,
 I got my app working with your redux devtools (slider/timetravel) yesterday (Brisbane, Australia) in chrome and today it stopped working. I can get it working in Firefox pointing to the same localhost:4200 endpoint and then I realised that you updated the chrome extension 10 hours ago. 

Is there a way to rollback the extension to test it works on the previous version?

https://github.com/pixelypants/trubet-app

**Comment by zalmoxisus** [comment]
@pixelypants thanks for the report. I've just fixed the issue with @ngrx/store-devtools api in https://github.com/zalmoxisus/redux-devtools-extension/commit/2b249b3aff41ef310bbba5f6e1bcb772bb9f11c6. Will publish a patch in few hours. 

Regarding earlier versions, Chrome doesn't store them. There's an [unofficial archive](https://crx.dam.io/), but don't know whether you can trust it. Also you can download and [build a release](https://github.com/zalmoxisus/redux-devtools-extension#1-for-chrome) right from [github releases](https://github.com/zalmoxisus/redux-devtools-extension/releases). However, I hardly recommend to use the latest version, and if there are any problems there to report here.

**Comment by zalmoxisus** [comment]
Should be fixed in `2.12.2`. Please update it from Chrome Store. Let me know if there are still any issues with that.

**Comment by pixelypants** [comment]
Bingo! working fine now.

Thanks for your work on this, it's a great tool you have given the community ;)
