### ISSUE TITLE
provide session key in config

### ISSUE THREAD

**Issue by gviligvili** [zalmoxisus/redux-devtools-extension#274]
I have a situation that when I use the the devTools "debug_session" feature:
I'm in my home page with debug_session="tal",
change the state and then refresh - everythings fine, it works.
if I go to other route (lets say ./articles), the state is loaded with the articles.
now if I try to refresh I lose my state, that's because the query string is gone (I think) durign the route.

first I would like to ask is there any solutions for this? 

second, I would like to offer my suggestion, as the title says, to provide a session key,
because like that I can check in my localStorage, what was the last key used :)

Thank you for your time ! :)

P.S: I must note, that I tried redux-localstorage and "persistState" of dev-tools, they don't work for me.

**Comment by zalmoxisus** [comment]
Yes, I'm aware about this problem and also noticed your question on SO. We already have all the data from the store on the extension part, and can easily restore it without `persistState`. It would prevent such url issues and also [localStorage quota issues](https://github.com/gaearon/redux-devtools/issues/298). I was planning to implement it after `3.0`, as the `persist` button wouldn't fit in the current UI.

**Comment by gviligvili** [comment]
That's great!,  but is it going to be anytime soon?  Because I'm suppose to wrap this seed up for a big project. 
If not,  is there anything I can do?  hmr is useless without this feature. 

 Thanks! :)

**Comment by zalmoxisus** [comment]
I expect to have it in about a month.

> hmr is useless without this feature.

Ideally, with HMR you shouldn't need to reload the page thus no need for state persisting. When you change something in your reducers, the Redux DevTools enhancer recomputes all the actions from the history, and you get your state modified.

**Comment by zalmoxisus** [comment]
I went ahead and made [a PR for this](https://github.com/zalmoxisus/redux-devtools-extension/pull/276). I'll publish `2.12` these days along with other changes.

**Comment by zalmoxisus** [comment]
Implemented in [`v2.12.0`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.0).
