### ISSUE TITLE
Warning: This synthetic event is reused for performance reasons

### ISSUE THREAD

**Issue by sukazavr** [zalmoxisus/redux-devtools-extension#275]
If `Redux DevTools 2.11.1.1` are enabled, runtime shows the Errors:

![image](https://cloud.githubusercontent.com/assets/2406951/21516248/750451e6-cd11-11e6-899a-7b6cffbbab12.png)
etc...

### Versions of packages
```
Redux DevTools 2.11.1.1
react@15.4.1
redux@3.6.0
redux-saga@0.14.0
```

### Use case
```es6
import env from 'utils/env'
import { createStore, applyMiddleware, compose } from 'redux'
import createSagaMiddleware from 'redux-saga'

const sagaMiddleware = createSagaMiddleware()

const middleware = [ sagaMiddleware ]

let composeEnhancers = compose

// Support Redux DevTools Extension
if (env.isDev && typeof window === 'object') {

	const RDTEC = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__

	if (RDTEC) {

		composeEnhancers = RDTEC({
			// Specify here name, actionsBlacklist, actionsCreators and other options
		})
	}
}

const enhancer = composeEnhancers(
	applyMiddleware(...middleware),
	// other store enhancers if any
)

export default (rootReducer, preloadedState) => {

	rootReducer = rootReducer || function (state) { return state }
	preloadedState = preloadedState || {}

	const store = createStore(rootReducer, preloadedState, enhancer)

	return {
		...store,
		runSaga: sagaMiddleware.run
	}
}
```

# How to fix it?

**Comment by zalmoxisus** [comment]
The extension doesn't affect React components in any way, so the problem is certainly elsewhere. Maybe you're including also [vanilla Redux DevTools component](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md)? Could you provide a minimal repo or to modify [our example](https://github.com/zalmoxisus/redux-devtools-extension/tree/master/examples/saga-counter) to replicate the issue?

**Comment by zalmoxisus** [comment]
@sukazavr, any update on this?

**Comment by sukazavr** [comment]
@zalmoxisus i'll take a look on the issue after 5th January :-)

**Comment by NGuldager** [comment]
I just had this problem myself. I found that my issue was that I passed the synthetic event directly in my action payload.

**Comment by zalmoxisus** [comment]
@NGuldager thanks for the clarification.

In this case we're accessing the event to show it in the monitor. As stated in the error message from React, the synthetic event cannot be reused for performance reason.

If you still need to pass it to an action, you can override this key of the stringified payload in your action creator by adding a custom `toJSON` function:

```js
function increment(event) {
  return {
    type: INCREMENT_COUNTER,
    event,
    toJSON: function (){
      return { ...this, event: '[Event]' };
    }
  };
}
```

Note that it shouldn't be arrow function as we want to have access to the function's `this`.
