### ISSUE TITLE
Impossible install on latest Chrome Canary

### ISSUE THREAD

**Issue by cef62** [zalmoxisus/redux-devtools-extension#28]
Hi @zalmoxisus, first of all thanks for this extension!

I've no problem with normal chrome but I'm not able to install it on Chrome Canary 49.0.2594.0 on OSX.
[Here](https://dl.dropboxusercontent.com/u/3162797/redux-devtools-chrome-canary.png) you can see a screenshot  of the error.

Do you have any suggestions?

**Comment by zalmoxisus** [comment]
It seems that the manifest specs was changed a bit in new Chrome Canary. I've found the problem and will push tomorrow a new release.

Thanks a lot for the report!

**Comment by cef62** [comment]
Thanks to you!

**Comment by zalmoxisus** [comment]
Should work now in `v0.4.10`. Thanks again for the heads-up!

**Comment by cef62** [comment]
Thanks!  Now I've been able to install it.
