### ISSUE TITLE
getState() returns old state for multiple dispatchs on replaying actions

### ISSUE THREAD

**Issue by narak** [zalmoxisus/redux-devtools-extension#281]
Not sure if this should go in devtool-instrument or, devtools or devtools-extension repo.

I tried debugging it, to check if there is some issue with my code. What I figured was that currentStateIndex isn't incrementing to the latest value and continues returning the old state.
To make it clear, this only happens when I'm trying to replay actions using the devtools extension.

*Here is what I'm doing:*
I'm not using any middleware or any package other than `redux` itself.
Following is what my code more or less looks like, its untested but it represents what I'm trying to do more or less accurately:

#### Container component
```
...
getState = () = {
    const { store } = this.context,
    const state = store.getState();
    if (!state.users['id1']) {
        store.dispatch({type: 'USERS_GET', isPending: true});
        getUser('id1', function(error, response) {
            store.dispatch({type: 'USERS_GET', isPending: false, error, response});
        });
    }
    return  { user: state.users['id1'] };
}
constructor() {
    this.state = this.getState();
}
componentWillRecieveProps() {
    this.setState(this.getState());
}
...
```

#### Reducer
```
function usersReducer(state = {}, action) {
    if (action.type === 'USERS_GET') {
        const id = action.filters.id;

        if (action.isPending) {
            state = {
                ...state,
                [id]: { isPending: true }
            };
        } else {
            state = {
                ...state,
                [id]: action.response
            };
        }
    }
    return state;
}

const store = createStore(
    combineReducers({users: usersReducer}),
    composeWithDevTools()
)
```

This works fine as long as I'm not replaying actions. When I replay actions from the beginning, the store.getState() returns the initial `users = {}` state even when the reducer has successfully returned `users = {id1: {isPending: true}}` and when I debug through it, I see the combineReducers successfully updates the state.

When I step into store.getState(), I reach the following instrumented code
```
    function s(t) {
        var e = t.computedStates
          , n = t.currentStateIndex
          , r = e[n].state;
        return r
    }
```
Here the values of e contain the newer values. But since currentStateIndex === 0, it keeps returning the old state.

Am I missing some 'switch' or config somewhere? I feel like I'm missing some trivial setting option which I should be seeing in the docs.

**Comment by zalmoxisus** [comment]
That's how time travelling works. If we'd return the current state instead of the one selected from the slider, what would be the purpose of this functionality?

Just make sure to jump to the latest state in order to move into the "present" state.

**Comment by narak** [comment]
Yeah, not saying its a bug. Just wondering if there is a way to configure devtools so that it doesn't trigger the same action endlessly because the overridden getState is constantly returning the old state.

**Comment by zalmoxisus** [comment]
Maybe I misunderstood the issue. If you go back to the last action (drag the slider to the end), doesn't it show the current states again?

If it will show the current state in case of time travelling, then jumping back and forth will have no effect at all, so it will be unusable.
