### ISSUE TITLE
Import is not working

### ISSUE THREAD

**Issue by et1975** [zalmoxisus/redux-devtools-extension#284]
Chrome extension  2.12.2.1

I don't know if I'm doing something wrong, but clicking import and submitting the previously exported JSON does nothing. 

I see these errors appearing periodically in the extension console logs, but nothing else:

> window.bundle.js:22 WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by zalmoxisus** [comment]
The monitor actions work out of the box only for Redux apps as they are instrumented with [`redux-devtools-instrument` enhancer](https://github.com/zalmoxisus/redux-devtools-instrument). So, in you case you have to implement [the monitor actions](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js).

In case of import, you can just get the last state from the received payload like [here](https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/monitorActions.js#L76-L82). And we could provide this part out of the box in `3.0` to make it easy. However, in Redux we're recomputing all the actions while importing a state, which is much better. So, if you change something in your reducers and import a saved state, you'll get it accordingly to the the changes.

**Comment by et1975** [comment]
I'm confused... I assumed the import would load the history back into the extension UI, are you saying that instead the import sends the actions to the app and there would be nothing in the UI to indicate that import took place, unless the app handles the monitor's commands?

**Comment by zalmoxisus** [comment]
I know it's confusing, but the history should be first recomputed on the client part. Of course, if you don't want that, you can just extract the state and send it back to the monitor as is (like in [that example](https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/monitorActions.js#L76-L82)). 

However, it's rather useful to recompute the actions. Say you have a bug, you shared the history with your team, and work together to fix it. If you don't have the ability to recompute actions (on hot-reloading, persisting and importing), that means you have to execute all that sequence of actions again, and DevTools is useless in this case. Actually, this part was the most valuable part @gaearon introduced, without that moving back and forward is just a fancy but not practical feature. See https://twitter.com/dan_abramov/status/761549682178916352.

**Comment by et1975** [comment]
That's certainly an interesting angle, although...
> I know that no stray AJAX request will mess up my state, that everything is completely predetermined by the scenario (actions) I recorded.

"stray AJAX request" is exactly what's going to happen if I start feeding the app the actions imported. I'm going to have to think on this... thanks.

**Comment by zalmoxisus** [comment]
That's why you have to implement also `LOCK_CHANGES` action, which the monitor sends after you click on `Lock` button.

There are lots of useful features here, apart from jumping back and forth, you might want to implement. Not sure how we can make this part available out of the box in a non-redux context, unless you'll interpret monitor actions on your part.

**Comment by Amareis** [comment]
I'm trying to import the state and get an error "state.update is not a function". Should I integrate "redux-devtools-instrument"? How?
