### ISSUE TITLE
window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ not available on moz-extension:// pages

### ISSUE THREAD

**Issue by Noitidart** [zalmoxisus/redux-devtools-extension#285]
I am trying to use this with a webextension in Firefox. My html page is at moz-extension:// but `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` is not available:

Screenshot http://i.imgur.com/xK15rRC.png

Do you know if this is an issue on my side, or is there a way I can use the devtools with moz-extension://?

**Comment by zalmoxisus** [comment]
For chrome extensions you could include an additional script for that. See [how to include it in chrome apps and extensions](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/FAQ.md#how-to-include-it-in-chrome-apps-and-extensions).

However, it's not possible in Firefox as `runtime.onMessageExternal` is not implemented implemented yet in WebExtension. So, a webextension is not able to listen for messages from another one. You should track this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1213473.

You could either debug in Chrome or use [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools).

**Comment by Noitidart** [comment]
Oh shoot. Thanks @zalmoxisus for the quick reply!

**Comment by zalmoxisus** [comment]
Closing since there's nothing we can do on our side and there's no ETA of implementing this in Firefox ([status is NEW](https://bugzilla.mozilla.org/show_bug.cgi?id=1213473)). Thanks for the report anyway!

**Comment by Noitidart** [comment]
Makes sense, thanks brother!

**Comment by clarkbw** [comment]
According to http://arewewebextensionsyet.com/#runtime and the [MDN page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Runtime/onMessageExternal) the `onMessageExternal` event is supported in Firefox
