### ISSUE TITLE
State tree collapses automatically

### ISSUE THREAD

**Issue by born2net** [zalmoxisus/redux-devtools-extension#286]
State tree collapses automatically
version:  2.12.2.1
I return a state like I normally / always have
no errors
and yet when I open a leaf in the dev tool state tree, and dispatch new action, it closes up :(

(correct me if I am wrong, but state tree is suppose to be persistent across dispatches ?)

can someone investigate?

Regards,

Sean

**Comment by zalmoxisus** [comment]
Thanks for the report! It was broken in [`react-json-tree@0.10.1`](https://github.com/alexkuz/react-json-tree). Most likely in https://github.com/alexkuz/react-json-tree/pull/61. Could you please open an issue there and maybe a pr to fix that. You can try it with the demo from [`redux-devtools-inspector`](https://github.com/alexkuz/redux-devtools-inspector).

**Comment by born2net** [comment]
ha good, I thought it was just me :)
FYI I use angular so no expireince with react.
I will open a bug on alexuz repo.

**Comment by leonprou** [comment]
Is this possible to install an older version for now?

**Comment by zalmoxisus** [comment]
I've downgraded `react-json-tree` and published `2.12.2.2` to Chrome Store.

**Comment by zalmoxisus** [comment]
Closing since it works in the latest version of the extension and should be fixed in upstream. Thanks for the investigation and filing the issue there! Let me know if something still goes wrong.
