### ISSUE TITLE
Passing a redux_report param fetches the report, but does not load it

### ISSUE THREAD

**Issue by jrullmann** [zalmoxisus/redux-devtools-extension#291]
Passing a redux_report param fetches the report, but does not load it.

Here's what I'm doing:

1. Use the redux-remotedev library to create a report
2. Pass the report id from the above step as a window argument to the running application
3. Verify in Charles that the report was fetched
4. Redux DevTools extension window is opened automatically

Expected: See the actions from the report in ReduxDevTools window
Actual: Don't see the report actions - see the same actions I would see for my app if I hadn't passed a remotedev_report as a param

**Comment by jrullmann** [comment]
I think this issue may have been introduced in PR #276.

Note here that instanceId can be an integer: https://github.com/zalmoxisus/redux-devtools-extension/blob/0cd6226eba8f6edfcbf6dd4516b0698a363e7e9a/src/app/api/generateInstanceId.js#L4

But later it is assumed to be a string with `replace` available: https://github.com/zalmoxisus/redux-devtools-extension/pull/276/files#diff-b624b14e102cec54bde4a4988d5feb76R36

When the `replace` throws an exception it is caught by the try/catch wrapped around the dispatch here: https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/background/logging.js#L28

The catch handler writes a console warning, but because this is a background thread, it never appears in the user's browser.

**Comment by zalmoxisus** [comment]
Hey @jrullmann,

Sorry about the regression and thanks a lot for the detailed investigation! I've just published `2.12.3` on Chrome store with the fix. It will be available in about an hour.

**Comment by jrullmann** [comment]
Works great, thanks for the quick response!
