### ISSUE TITLE
Can't use with yarnpkg

### ISSUE THREAD

**Issue by sbking** [zalmoxisus/redux-devtools-extension#297]
I am trying to create an npm module that uses the redux-devtools-extension npm module as a dependency. When I do a `yarn install` on my project that includes my npm module, it installs the root of this repo into my `node_modules`, as opposed to the `npm-package` subdirectory. When I do an npm install, everything works fine.

Why do both this root directory project and the npm package project have the same name in the package.json files? I feel like that has something to do with it not playing nicely with yarn.

**Comment by zalmoxisus** [comment]
Hey @sbking,

Thanks for this report! I published earlier this repo by mistake, and unfortunately npm doesn't allow unpublishing. Please do `yarn add redux-devtools-extension@2.0.0` or `yarn add redux-devtools-extension@latest`.

**Comment by zalmoxisus** [comment]
I just published `redux-devtools-extension@2.13.0`, so the issue should be fixed.

I'll rename the main repo to avoid such confusions in the future.

**Comment by sbking** [comment]
@zalmoxisus Thanks!

**Comment by ShahzaibMunawar** [comment]
Thanks
