### ISSUE TITLE
Action types as numbers

### ISSUE THREAD

**Issue by NickLydon** [zalmoxisus/redux-devtools-extension#299]
I've been using numbers as action types (TypeScript enum values) and it's worked fine previously. Today I panicked because I thought our production site wasn't working. It seems the devtools are turning the action type into a string, which means none of the reducers's switch case statements matched. 

Action types aren't required to be strings are they?

**Comment by zalmoxisus** [comment]
Surely, action type can be anything except `undefined`.

Could you please provide some details about your store config? I just tried to dispatch `0` and `1` and don't seem to get any issues.

**Comment by zalmoxisus** [comment]
Ah, I got it. It's due to https://github.com/zalmoxisus/redux-devtools-instrument/commit/fa1b7769688fb549626e703f6cf37f860befa40c. I'll fix that. You can set `serialzie` parameter to `true` for now.

Sorry about that!

**Comment by zalmoxisus** [comment]
I've published a fast fix in `2.13.0.1`. It should be available on Chrome Store within an hour. Please let me know when you get a chance to check it.

**Comment by NickLydon** [comment]
Looks good! Thanks

**Comment by zalmoxisus** [comment]
Thank you for reporting it!
