### ISSUE TITLE
ImmutableJS compatability

### ISSUE THREAD

**Issue by CompuIves** [zalmoxisus/redux-devtools-extension#30]
Hey,

I first would like to say that I really like your extension, especially the ignore option. I would like to comment on something though.
You decided to nuke the serialize option in release v0.4.9 (https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v0.4.9). This may work great in many cases, but ImmutableJS by Facebook doesn't throw an error when you try to use unserializable data. This means I cannot see what my data is except for some cryptic ImmutableJS objects.

My suggestion would be to re-enable the option to force serialize, but keep it disabled by default. I could make a PR for this if you agree.

**Comment by zalmoxisus** [comment]
Thanks for the feedback!

OK, I'll bring it back if there's no way to detect it implicitly.

I'll do it by myself as there were a lot of changes in https://github.com/zalmoxisus/redux-devtools-extension/commit/3ab3724c5f8311adc320b357149c69b475697353 and I want to reassure that nothing is broke up.

**Comment by zalmoxisus** [comment]
Implemented in `v0.4.11`. Thanks again for the proposal!

**Comment by CompuIves** [comment]
Ah super!! Thank you very much for the really fast response!
