### ISSUE TITLE
JSON.parse error from postmessage on "INIT_INSTANCE" message

### ISSUE THREAD

**Issue by mdurling** [zalmoxisus/redux-devtools-extension#301]
The INIT_INSTANCE message `data` object contains a `payload` property which is `undefined`. This causes a `JSON.parse` error in `postmessage` that is logged to the console. This is not service affecting, but it does unnecessarily clutter our console log and inhibits debugging. 
<img width="731" alt="screen shot 2017-02-04 at 12 20 11 pm" src="https://cloud.githubusercontent.com/assets/3439869/22620229/376a6294-ead5-11e6-96f6-1ed5ccdf8fa0.png">

**Comment by zalmoxisus** [comment]
I'm not sure I follow the issue. You're parsing the extension's messages inside your app? Or it's an integration apart from Redux you're using?

**Comment by mdurling** [comment]
@zalmoxisus We use `seamless` to communicate between a parent window and a child iframe. `seamless` uses `postmessage` as a wrapper for `window.postMessage`. `postmessage` is complaining that it can't parse the data because of the `payload: undefined`. I will likely open an issue with `postmessage`, but I just thought you might like to be aware that this happens. If you sent payload as null or not at all, I suspect this would not occur. Thanks.

**Comment by zalmoxisus** [comment]
Well, I'll exclude the `payload` key, but, anyway, `seamless` should parse only its messages. Apart from `INIT_INSTANCE`, we're sending Redux actions and states, parsing of which would affect the performance significantly.

We're marking our messages by setting `source` to `@devtools-page` (as seen in your screenshot). Similarly, they should sign their messages to parse only them.

**Comment by mdurling** [comment]
@zalmoxisus I totally agree. I don't think it's a `seamless` thing. It seems `postmessage` is parsing every message regardless if it was sent via `postmessage` or via `window.postMessage` ... I think `postmessage` should sign/parse only the messages sent and received via their package as you suggested. Thanks.

**Comment by zalmoxisus** [comment]
You mean [`ender-postmessage`](https://github.com/thomassturm/ender-postmessage)? Could you please point me to that part of code?

**Comment by mdurling** [comment]
[See Here](https://github.com/daepark/postmessage/blob/master/postmessage.js#L211)

**Comment by zalmoxisus** [comment]
So, `payload` key has no influence here. The whole [message `data`](https://github.com/daepark/postmessage/blob/master/postmessage.js#L208) is parsed there. It's expected to be a string but we're sending an object. Anyway, even if it was, it would throw after that.

**Comment by mdurling** [comment]
I don't disagree, but this is effectively what's happening in `postmessage`

<img width="556" alt="screen shot 2017-02-04 at 1 18 11 pm" src="https://cloud.githubusercontent.com/assets/3439869/22620563/890f2c5e-eadc-11e6-9e3b-9e1c16f74676.png">

I think the bigger issue is that `postmessage` is attempting to parse messages which it wasn't used to send. I get similar warnings when I run `webpack-dev-server` which also uses `window.postMessage` ... I have opened an issue against `postmessage` ... feel free to close this one.

**Comment by zalmoxisus** [comment]
As the lib wasn't updated since 2011, a quick fix would be to fork it and add `if (typeof e.data !== 'string') return` [there](https://github.com/daepark/postmessage/blob/master/postmessage.js#L207) (as most of other libs would send objects).

**Comment by mdurling** [comment]
Thanks @zalmoxisus BTW, the Redux Devtools extension is awesome!
