### ISSUE TITLE
README.md has diffs still in markup

### ISSUE THREAD

**Issue by marcelshields** [zalmoxisus/redux-devtools-extension#304]
Project homepage README.md still has highlighted diffs in code.

**Comment by marcelshields** [comment]
Seeing that may be intentional

**Comment by zalmoxisus** [comment]
Yes. I think it's easier for users to see what it's need to be changed in this was as [it was before](https://github.com/zalmoxisus/redux-devtools-extension/tree/v2.12.1#1-with-redux).
