### ISSUE TITLE
macOS / chrome extension - open devtools on correct desktop/monitor

### ISSUE THREAD

**Issue by comatory** [zalmoxisus/redux-devtools-extension#307]
I have my browser on secondary desktop in macOS, when I open the devtools via extension button and select "To left...", devtools are opened on my primary desktop. It would be nice if it was displayed where my browser is.

**Comment by zalmoxisus** [comment]
I don't have a second monitor to test, but "to left" should open on the first monitor, and to right - on the second monitor. Which sounds ok for me. If not, feel free to add this functionality, similarly to https://github.com/zalmoxisus/redux-devtools-extension/pull/184. It's [just javascript](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/background/openWindow.js#L37).
