### ISSUE TITLE
Actions / thunks with inner function not recognized

### ISSUE THREAD

**Issue by leobudima** [zalmoxisus/redux-devtools-extension#309]
I'm trying something like this:

```
const actionExample = (payload) => (dispatch, getState) => {
    console.log(payload, dispatch, getState);
};

dispatch(actionExample('test'));
```

so that I can access state when needed, and dispatch other actions from within the action creator (of course AC and the dispatch call are separated in real scenario, dispatch is made from a component). 

My store is configured as:

```
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const enhancer = composeEnhancers(
    applyMiddleware(thunk)
);

createStore(
    rootReducer,
    initialState,
    enhancer
);
```

While the action gets dispatched properly, inner function runs and logs all 3 parameters, it simply doesn't get picked up anywhere in the extension. 

In contrast:

```
const actionExample = (payload) => {
    console.log(payload);
};
```

works correctly, and gets logged in the extension, so it seems like thunks are otherwise working...

Am I doing something wrong? :)

**Comment by zalmoxisus** [comment]
A repo or jsfiddle to run would help. From what I see, you're passing `dispatch` to `actionExample`, but aren't calling it.

You can look into [`counter example of using thunks`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/counter/actions/counter.js#L31-L37), it's available also [as a demo](http://zalmoxisus.github.io/examples/counter/). Alternatively, you can fork the repo, modify the example adding an action you think isn't working and send a pr.

**Comment by leobudima** [comment]
Huh, I feel really, really stupid now...In context of your example, I somehow expected to see incrementAsync logged - I still haven't put all the blocks in place in my head (new to Redux), with difference between calling dispatch on:

- an action
- an action creator which returns an action (same)
- and action creator, which, thanks to redux-thunk, is executed, but doesn't need to have anything with actions, i.e. things that your component tracks :)

Sorry for wasting your time. However, many compliments on an excellent project, great code and examples. And also thanks for replying so quickly!

**Comment by zalmoxisus** [comment]
No problem :)
