### ISSUE TITLE
Basic store setup not working

### ISSUE THREAD

**Issue by ArunMichaelDsouza** [zalmoxisus/redux-devtools-extension#319]
I am trying to setup the extension with a basic store, but it always gives a "No store found" error.

Please check the config here - https://github.com/ArunMichaelDsouza/redux-foundations/blob/master/js/src/app.js#L10

I am using redux ``3.6``

Thanks.

**Comment by zalmoxisus** [comment]
I tried your repo, it works. Just don't forget to [allow the extension to access your local filesystem](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#access-file-url-file).

**Comment by ArunMichaelDsouza** [comment]
Yes it works now. Thanks @zalmoxisus!
