### ISSUE TITLE
Duplicate actions when starting up

### ISSUE THREAD

**Issue by neverfox** [zalmoxisus/redux-devtools-extension#32]
I have a couple of actions that fire when my app starts (via redux-simple-router and redux-responsive) and the Chrome extension version of devtools shows two copies of each action, if my developer tools window is already open when I refresh the app. Only one copy shows up (as expected) on the regular, in-window version of devtools, or if I open developer tools after refreshing the app. Furthermore, the two phantom actions don't respond to being reverted. If you revert the first copy, the phantoms disappear. They also disappear if I switch tabs and come back.

Chrome 47.0.2526.106 (64-bit)
OS X 10.11.2 (15C50)
Redux DevTools 0.4.12

**Comment by zalmoxisus** [comment]
Thanks for reporting this!

Fixed in `v0.4.13`. Chrome should update the extension in few hours. If you want to get it now, remove and install the extension again from Chrome store.

Feel free to reopen the issue or open another one if something goes wrong.
