### ISSUE TITLE
Shortcut conflict!

### ISSUE THREAD

**Issue by mnemanja** [zalmoxisus/redux-devtools-extension#322]
I've actually never used the shortcut CTRL+SHIFT+E to open the extension options in chrome, but I do use it for Confluence and it conflicts when I'm trying to use it there.

Could you please disable/change or provide an option regarding that shortcut?

Thanks a bunch!
Nemanja

**Comment by zalmoxisus** [comment]
Yes, you can change or disable it. See [Keyboard shortcuts](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/FAQ.md#keyboard-shortcuts).

**Comment by mnemanja** [comment]
I've totally missed that info. 

Thanks for the info.
