### ISSUE TITLE
Documentation: SSR support

### ISSUE THREAD

**Issue by mschipperheyn** [zalmoxisus/redux-devtools-extension#324]
For SSR purposes, I recommend making a small change to the README.md

    const composeEnhancers = (typeof window !== 'undefined' && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) || compose;

**Comment by zalmoxisus** [comment]
There's [a note about universal ("isomorphic") apps](https://github.com/zalmoxisus/redux-devtools-extension#11-basic-store), but feel free to send a PR improving the README.

**Comment by nik72619c** [comment]
Is someone still working on this ?

**Comment by nik72619c** [comment]
@zalmoxisus please assign it to me if its free to work on

**Comment by nik72619c** [comment]
![15703620125329125964271807352681](https://user-images.githubusercontent.com/30630904/66268574-39733e80-e85c-11e9-9fa7-31020d659c2a.jpg)



I believe its after the isomorphic sentence right there

**Comment by nik72619c** [comment]
@zalmoxisus am I thinking in the right direction ?

**Comment by nik72619c** [comment]
#692 @zalmoxisus please have a look and suggest changes if any :)

**Comment by zalmoxisus** [comment]
Looks good, thanks for the contribution, @nik72619c!
