### ISSUE TITLE
ruducer 里面的 state不会更新

### ISSUE THREAD

**Issue by GaryChangCN** [zalmoxisus/redux-devtools-extension#325]
我需要使用 `Object.assign({},state)` 去拷贝一个新的state，然后再在这个新的state上更改属性并且返回新的state才可以有更新。否则的话state不会有变化，而且插件的 diff panel也不会变化。

Using `Object.assign()` method to make a new object and change property on this object .

```javascript
function reducer(state={username:"gary"},action){
    switch(action.type){
        case 'EXAMPLE':
             var tmp=Object.assign({},state);
             tmp.username="chang";
             return tmp;
    }
}
```

 but I want to use in follow correct way!

```javascript
```javascript
function reducer(state={username:"gary"},action){
    switch(action.type){
        case 'EXAMPLE':
             state.username="chang";
             return state;
    }
}
```
```

**Comment by zalmoxisus** [comment]
I don't see how it's related to the extension.

In terms of Redux you're not allowed to mutate the state, so the reducer should return a new object, thus the second example isn't correct.

If you find mutating the state better for your use case, you can use MobX. It's possible to [use the extension for it as well](https://github.com/zalmoxisus/mobx-remotedev).

**Comment by GaryChangCN** [comment]
sorry! My mistake.
