### ISSUE TITLE
.init(state) does not serialize with jsan

### ISSUE THREAD

**Issue by kevmo314** [zalmoxisus/redux-devtools-extension#329]
The initial state provided via `.init()` does not seem to be serialized with jsan, therefore serializing a state like `{someKey: new Set()}` gets coerced to `{someKey: {}}` in json, which is an incorrect representation on deserialization.

I think the fix is to change [this line](https://github.com/zalmoxisus/redux-devtools-extension/blob/15aecb19bae446f32251607d1262688f08c6ac15/src/app/api/index.js#L224) from 

```
payload: stringify(state),
```

to

```
payload: stringify(state, config),
```

**Comment by zalmoxisus** [comment]
It's up in  `2.14.3`. Thanks again for the contribution!
