### ISSUE TITLE
State always appears to have initial values

### ISSUE THREAD

**Issue by burtyish** [zalmoxisus/redux-devtools-extension#33]
I've been using (and enjoying!) the extension successfully on our app for a while. 
After a recent (big) change I discovered that it displays the app state as if it is _always_ in the initial state.

I tried both `redux-logger` and `redux-devtools-log-monitor`. Both show the correct state, which leads me to believe it's an issue with the devtools chrome extension and something in the latest changes made on the app.

The app is too big for me to share it here but I will answer questions about it's structure as best I can.

I Would love to hear any suggestions as well as if someone has seen this behavior.

**Comment by zalmoxisus** [comment]
Hey @burtyish, 

Do you use ImmutableJS? On the options page (find Redux DevTools on `chrome://extensions/` and click the Options link) check `States serialization`. It should help.

**Comment by burtyish** [comment]
No, I'm not using ImmutableJS. I tried to check `States serialization` anyway but it didn't help. 
Can you recommend a method for debugging the issue?

**Comment by zalmoxisus** [comment]
That's strange. Are the states changed when you toggle an action on the monitor? If not, it's probably an issue of jsan, and we can fix it by [forcing serializing self references (non-circular)](https://github.com/kolodny/jsan#note).

Also, please check [our demos](https://github.com/zalmoxisus/redux-devtools-extension#examples) to see if this happen there.

**Comment by burtyish** [comment]
The extension works fine with your demos as it does for other apps I've built.
Back on my problematic app, if I try to toggle an action, it fails with an exception: `Uncaught TypeError: Cannot read property 'action' of undefined`.
From debugging, I've found that the exception happens while dispatching the action with type `TOGGLE_ACTION`.

**Comment by zalmoxisus** [comment]
@burtyish, that's interesting. Could you share your store configuration?

**Comment by burtyish** [comment]
Sure, I don't mind sharing. 
I'll note that a similar configuration is used successfully in a different app.
```
import { createStore, applyMiddleware, compose } from 'redux';
import thunkMiddleware from 'redux-thunk';
import analyticsMiddleware from '[...]/scripts/redux/middleware/analytics.js';
import rootReducer from '../reducers/reducers.js';

let store = null;

const middleWare = [
  thunkMiddleware,
  analyticsMiddleware
];

const devFuncs = [
  window.devToolsExtension ? window.devToolsExtension() : f => f // See https://github.com/zalmoxisus/redux-devtools-extension
];

export default function configureStore(initialState) {

  if (!store) {
    if (process.env.NODE_ENV === 'production') {
      store = applyMiddleware(...middleWare)(createStore);
    }
    else {
      store = compose(
        applyMiddleware(...middleWare),
        ...devFuncs
      )(createStore);
    }
  }

  return store(rootReducer, initialState);
}
```

**Comment by burtyish** [comment]
Here's where the error is triggered
```
function a(e, t, n, r, a, i, u) {
                        if (t >= e.length && e.length === i.length)
                            return e;
                        for (var s = e.slice(0, t), l = t; l < i.length; l++) {
                            var c = i[l]
                              , p = a[c].action // <--- This is where the error is triggered. Line #656
                              , d = s[l - 1]
                              , f = d ? d.state : r
                              , h = d ? d.error : void 0
                              , v = u.indexOf(c) > -1
                              , m = v ? d : o(n, p, f, h);
                            s.push(m);
                        }
                        return s;
                    }
```
`c` is `undefined`.
`a[0]` is `Object {type: "PERFORM_ACTION", action: Object, timestamp: 1451935154498}`

**Comment by zalmoxisus** [comment]
Thanks! Could you also specify versions of `redux` and `redux-thunk`?

**Comment by burtyish** [comment]
redux v 3.0.5
redux-thunk v 0.1.0 (wow, maybe it's time to upgrade)
I'll run the new version locally tomorrow and get back to you with the results.

Meanwhile, I just want to say thanks for the swift response and support. I really hope I can help get to the bottom of this issue so my team and I can continue using your awesome extension.

**Comment by burtyish** [comment]
OK, here are my results.
1. I still have the same issue where the state always appears to have it's initial values (in redux-devtools-extension only).
2. Clicking on the last action to roll it back still triggers an error. Here's a description of the state that causes the error:
* `createStore.dispatch` is called with `currentState.currentStateIndex: 1` and `currentState.computedStates` that contains only one item containing `state` with initial values. Also, `currentState.actionsById` has only one action: `"@@INIT"`
* In [liftReducerWith:213](https://github.com/gaearon/redux-devtools/blob/10319e16e3e6b384dfeb1dd6a32b0afe7df65bec/src/instrument.js#L213) `minInvalidatedStateIndex` is set to `-1` since `actionId` isn't found.
* That `-1` is was causes the error in [recomputeStates:108](https://github.com/gaearon/redux-devtools/blob/10319e16e3e6b384dfeb1dd6a32b0afe7df65bec/src/instrument.js#L106) since `actionId` is set `undefined`

It appears redux-devtools always uses a history of actions with only the `@@INIT`

**Comment by zalmoxisus** [comment]
Thank you for the details, that clarifies a lot. It appears that actions aren't relayed at all.

Could you investigate it [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L88) by commenting the conditions bellow, adding a `console.log` to see what it tries to relay? Just edit the file, and Webpack will update everything, you'll have only to refresh your app's page.

**Comment by burtyish** [comment]
`state` is always an empty object, it's default value.

**Comment by zalmoxisus** [comment]
That's right, the `state` variable is the monitor's state, which, yes, is always `{}`.

I'm wondering if it goes through all the conditions and relay the store's state, which is transmitted from `relay('ACTION', store.getState(), action, actionsCount)`.

**Comment by burtyish** [comment]
There first bunch of actions that happen when the app starts do not pass the [1st condition](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L89) and are not relayed.

**Comment by zalmoxisus** [comment]
Thanks. That clarifies everything. Could you remove that condition and check whether it fix the issue?

I added it few days ago to fix #32.

**Comment by burtyish** [comment]
Mmmm not sure it clarifies everything 😕
I removed the `lastTime > action.timestamp` condition. All the actions are relayed but the state still appears to have initial values in the devtools and what I described [here](https://github.com/zalmoxisus/redux-devtools-extension/issues/33#issuecomment-168926864) is still true.

**Comment by zalmoxisus** [comment]
OK, then the condition is good, and those actions should be already related.

A good point to find from where the issue comes would be to compare the extension's liftedStore (thet we construct by relying new actions) with the app's liftedStore.

To do that, open the extension's console as follows:
![extensions](https://cloud.githubusercontent.com/assets/7957859/12112023/67938bf0-b3a2-11e5-8b14-0020813f4757.jpg)
And do: `store.liftedStore.getState()`.
To check, in your app page do the same, but first expose the store globally (`window.store = store`) from [the extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L140) or from your app after the `configureStore` (doesn't matter).

So you will be able to inspect when the actions / states go wrong.

**Comment by zalmoxisus** [comment]
Now on the bottom of the DevTools window you can find a `Sync` button. Click it and check if it helps. If yes, then we'll know that the problem isn't with serialization, but because somehow we miss a state. Additionally, if it helps try to dispatch more actions to see if the problems occur only initially.

**Comment by zalmoxisus** [comment]
An update: I delegated most of restoring lifted state functionality to [remotedev-app](https://github.com/zalmoxisus/remotedev-app). As a result, you may test the functionality just integrating [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools) store enhancer in your app, which will be much easier to debug, as [the code is pretty simple](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/devTools.js) (comparing with the extension).

**Comment by burtyish** [comment]
Cool, I'll take a look as soon as I get the chance. Thanks for the update!

**Comment by burtyish** [comment]
I've spent some time trying to debug with no success so far.
As you can see below devTools' state is not affected by any actions after initialization, even though the actions are relayed.
![screen shot 2016-01-13 at 4 18 29 pm](https://cloud.githubusercontent.com/assets/4200728/12296588/5b7a7b4c-ba11-11e5-9483-7200395534ca.png)

**Comment by zalmoxisus** [comment]
I think I figured it out. Could you please try he extension again? Don't forgot to pull the changes from repository and do `npm i` (as `remotedev-app` was also updated).

**Comment by burtyish** [comment]
Yup, that did the trick. Works like a charm!
Thank you!

**Comment by zalmoxisus** [comment]
Thank you for helping to figure it out! The changes should appear on Chrome store in few hours.

Feel free to reopen the issue if you notice any troubles there.

**Comment by amok** [comment]
I'll just leave it here for those inattentive, as I was (:

```
  const store = createStore(
    rootReducer,
    preloadedState,
    compose(
      applyMiddleware(createMiddleware(socket), reduxRouterMiddleware),
      devTools // <--- after moving code around don't forget 
               // to put devTools after middlewares  :)
    )
  )
```
