### ISSUE TITLE
Adding remotedev_report param does not load report 

### ISSUE THREAD

**Issue by jrullmann** [zalmoxisus/redux-devtools-extension#331]
I can't quite put my finger on the exact problem, but the remotedev_report feature is broken. To reproduce:

1. Create a remote redux report
2. Load an application and add 'remotedev_report=' with the ID of your created report into the browser

Expected: Redux Devtools extension is opened, report is retrieved and loaded
Actual: Redux Devtools extension is opened, report is retrieved but not loaded

The report is not loaded because an exception is thrown in remotedev-app. Specifically at [this](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/utils/monitorActions.js#L23) line of code.

The problem is that `instances` has a single object with an id of 1/2, but `instanceId` is set to 1. So `options` is undefined and when the code tries to execute `options.features` it throws the exception.

What I can't figure out is why `instanceId` and the object don't match. I see a couple of places that are setting the instance id using `/` but they don't seem to be executed in my example. Maybe I'm just missing it. Here are the two places: [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/middlewares/api.js#L126) and [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/middlewares/api.js#L172).

**Comment by zalmoxisus** [comment]
Hey @jrullmann,

Thanks a lot for detailed investigation. I published a quick patch as `2.14.3` on Chrome Store. Let me know if if there are still any problems.

I'm feeling guilty of not finishing it and breaking this with every update. I'll do my best to have `3.0` in May :-/
