### ISSUE TITLE
Inspector queue/history length

### ISSUE THREAD

**Issue by ksnyde** [zalmoxisus/redux-devtools-extension#334]
In the Inspector view I am wondering if there's anyway to configure the number of transactions the extension keeps. I guess I'm assuming that it has a fixed number for memory reasons. 

Anyway, I have a ton of records being inserted, each is a action event and therefore the events that come before are falling off the queue. When I reload my browser I see the events I'm interested for a fraction of a second -- so they are indeed firing -- and the state too indicates that these events and corresponding reducers have been employed but by the time i'm able to type anything into the "filter" dialog those earlier events are already cleared.

**Comment by zalmoxisus** [comment]
Yes, that number was called [`maxAge`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#maxage) and it's `50` by default.

**Comment by ksnyde** [comment]
Thanks!
