### ISSUE TITLE
error:  Unexpected dangling '_' in '__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'  no-underscore-dangle

### ISSUE THREAD

**Issue by rahul-desai3** [zalmoxisus/redux-devtools-extension#338]
[As per the docs](https://github.com/zalmoxisus/redux-devtools-extension#usage), I have configured my project to use the redux devtools.

However, with ES Lint in my project, I get this:

`error  Unexpected dangling '_' in '__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'  no-underscore-dangle`

Any pointers on how to fix this?

**Comment by rahul-desai3** [comment]
Sorry, missed the ES Lint part in your docs.

`/* eslint-disable no-underscore-dangle */`

**Comment by torinagrippa** [comment]
You could also add `"no-underscore-dangle": ["error", { "allow": ["__REDUX_DEVTOOLS_EXTENSION__"] }],` to your eslint config.

**Comment by glapsable** [comment]
good :)

**Comment by zalmoxisus** [comment]
For those googling it. The best way is to just use `redux-devtools-extension` npm package as specified in [the README](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm), so no need for using global variable and changing eslint rules.
