### ISSUE TITLE
Doesn't work with Immutable.js

### ISSUE THREAD

**Issue by garretto** [zalmoxisus/redux-devtools-extension#35]
Can't get it to work with Immutable.js. It just shows the raw immutable objects. Similar to this issue:
https://github.com/gaearon/redux-devtools/issues/51

**Comment by zalmoxisus** [comment]
Enabling serialization on the options page should help. Find Redux DevTools on the extensions page (`chrome://extensions/`) and click the Options link to customize everything. Please let me know whether it solves the issue.

**Comment by tow8ie** [comment]
Had the same problem and your solution worked. Thanks!

**Comment by zalmoxisus** [comment]
We'll better turn it on by default to avoid confusion. The point was to gain better performance where it is possible.

**Comment by garretto** [comment]
Ah, that works thanks! I didn't expect this extension to have configurable options, so that's awesome!

**Comment by zalmoxisus** [comment]
From now it is on by default. In `1.0` the options page will be accessible from the extension window.
