### ISSUE TITLE
Minor Google Sheet Interference

### ISSUE THREAD

**Issue by Viral-Inc** [zalmoxisus/redux-devtools-extension#352]
Even when the Redux Chrome Extension options are set to allow access to only localhost + Github addresses,

the extension actively disables/overrides one or more keyboard shortcuts in Google Sheets [command + shift + E]

It's getting a little tiring turning the extension on and off again bouncing between localhost and Google Sheets - is there any easy alternative way to stop the shortcut override?

**Comment by zalmoxisus** [comment]
Yes, you can [set any shortcut you want or disable it at all](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/FAQ.md#keyboard-shortcuts). If there's a suggestion for more unique shortcut to use by default, let me know.
