### ISSUE TITLE
Application inside dynamically created iframe?

### ISSUE THREAD

**Issue by PolarbearDK** [zalmoxisus/redux-devtools-extension#357]
I'm having a problem with redux devtools not connecting to my application when it is in an iframe, but works fine when not in iframe.

I'm forced to run my angular4 application inside an iframe created dynamically inside a jquery modal. The modal is created when user presses a button (long after "document ready"). 

The iframe is on a different domain that the application creating the iframe.

I'm not sure exactly why this is not working, as I can see that others has had success with iframes. 
Is there any way i can get devtools up and running in this exotic scenario?

**Comment by zalmoxisus** [comment]
I've just run without problems
```
    <div id="root">
    </div>
    <script>
      setTimeout(() => {
        document.getElementById('root').innerHTML = '<iframe src="http://zalmoxisus.github.io/examples/counter/" />';
      }, 3000);
    </script>
```

Are you using redux or ngrx?

**Comment by PolarbearDK** [comment]
I'm using @angular-redux/store which uses redux.

I've tested using your snippet, and none of my applications work with devtools in an iframe :(
So it is not a devtools problem.

FYI: I'm initializing the store like this: 

@NgModule({
  imports: [NgReduxModule],
})
export class StoreModule {
  constructor(
    public store: NgRedux<IAppState>,
    devTools: DevToolsExtension,
  ) {
    store.configureStore(
      rootReducer,
      <IAppState>{},
      [],
      devTools.isEnabled() ? [devTools.enhancer()] : []);
  }
}

**Comment by PolarbearDK** [comment]
The sample app at: https://github.com/angular-redux/example-app has the same problem.
