### ISSUE TITLE
DevTools "tab switching" shortcut hijacked

### ISSUE THREAD

**Issue by mladenp** [zalmoxisus/redux-devtools-extension#358]
In Chrome devtools you can do _cmd + number_ to switch to different devtools tabs. 
But when you switch to redux devtools tab that keyboard shortcut stops working.

**Comment by zalmoxisus** [comment]
I don't see this shortcut in [the docs](https://developers.google.com/web/tools/chrome-devtools/shortcuts), and it doesn't work for me from any other tabs either (it switches Chrome tabs, not DevTools ones). I guess it's an extension, which offers this feature? Does it work from other custom devtools tabs like React DevTools?

**Comment by mladenp** [comment]
There is an option in chrome devtools settings (press F1) to check **Enable ⌘ + 1-9 shortcut to switch panels**
But you are right, this shortcut also doesn't work when i am in React extension tab.
I guess i'll have to use ⌘ + [] to switch devtool tabs.

**Comment by zalmoxisus** [comment]
Thanks for the clarification.

I guess it won't be possible to reimplement it from our side. We could only catch the keyboard shortcut, but:
1. We don't have the information if the shortcut to switch panels is enabled.
2. We don't know the order of the tabs and which custom tabs are present.
3. We're allowed to switch only to several tabs (like sources).

It would be worth discussing it in chromium issues.
