### ISSUE TITLE
persist doesn't work

### ISSUE THREAD

**Issue by rubycut** [zalmoxisus/redux-devtools-extension#364]
Steps to reproduce:

1.  Navigate to: http://zalmoxisus.github.io/examples/counter/
2. Press + buttton on the web page
3. Press "Persist button in the extension"
4. Refresh the page
5. Counter is back at zero, state is not persisted.

Am I doing something wrong?

**Comment by zalmoxisus** [comment]
I just followed your steps and it works :-/
Make sure the button is pressed. It is not showed visually till we have https://github.com/zalmoxisus/remotedev-app/pull/30.

**Comment by rubycut** [comment]
Oh, I see, it should be pressed only once. Then it works.
