### ISSUE TITLE
`devToolsExtension` does not accept enhancers

### ISSUE THREAD

**Issue by inxilpro** [zalmoxisus/redux-devtools-extension#365]
The `devToolsExtension` enhancer in `pageScript.js` take three arguments: `reducer`, `preloadedState`, and `config`. This means that if you have an enhancer chain like:

```js
const compose = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__;
const enhancer = compose(
    applyMiddleware(...middleware),
    middlewareThatUsesEnhancers()
);
```

The enhancers passed by `middlewareThatUsesEnhancers` to `createStore` will never get fired. This is the cause of issues like https://github.com/jevakallio/redux-offline/issues/66 — any enhancer that internally calls additional enhancers will not work with redux devtools as the rightmost enhancer.

I'll try to put together a PR shortly, but in the interim, you can add the following to your enhancer chain:

```js
const compose = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__;
const enhancer = compose(
    applyMiddleware(...middleware),
    middlewareThatUsesEnhancers(),
    // Add this to the end of your enhancer chain:
    (createStore) => (reducer, preloadedState, enhancer) => enhancer(createStore)(reducer, preloadedState)
);
```

**Comment by inxilpro** [comment]
It looks like if you pass a configuration object, it does accept reducers, but otherwise it does not.

**Comment by zalmoxisus** [comment]
> It looks like if you pass a configuration object, it does accept reducers, but otherwise it does not.
Yes, it's as intended, but we could just throw an error in the previous case, see https://github.com/zalmoxisus/redux-devtools-extension/issues/310#issuecomment-279648427.
