### ISSUE TITLE
Extension causing reducer dispatch errors

### ISSUE THREAD

**Issue by neverfox** [zalmoxisus/redux-devtools-extension#37]
With 0.4.14, I eventually start getting several `Unhandled promise rejection Error: Reducers may not dispatch actions.` when the extension is enabled. For example, I'll be typing in a form field and suddenly everything stops and the errors appear on every action thereafter. Everything is fine without the extension and I'm definitely not dispatching actions in my own reducers.

**Comment by tikotzky** [comment]
I am seeing this behavior on react v0.14.6 as well.

The action that is causing the error seems to be:
`{type: "COMMIT", timestamp: 1453066780832}`

**Comment by neverfox** [comment]
Glad it's not just me. To be clear, the version number I was referring to is the version number of this extension.

**Comment by tikotzky** [comment]
ah ok. 
It seems like this error is triggered when the "maximum actions" is reached...

It looks like the call to `isLimit` on [this line](https://github.com/zalmoxisus/redux-devtools-extension/blob/bbfe9f676c69af40b1e8f56c0d5448f122ec355e/src/browser/extension/inject/pageScript.js#L115) triggers an action from the reducer

**Comment by neverfox** [comment]
I was going to say that [this commit](https://github.com/zalmoxisus/redux-devtools-extension/commit/1e74e13b4bec1c628c4dd88ee4a0441d3a477519) was probably the culprit, which includes that line.

**Comment by tikotzky** [comment]
I think all that needs to happen is [this line](https://github.com/zalmoxisus/redux-devtools-extension/blob/bbfe9f676c69af40b1e8f56c0d5448f122ec355e/src/browser/extension/inject/pageScript.js#L81) needs to get wrapped in a `setTimeout(fn , 0)`

**Comment by hsrobflavorus** [comment]
Yep, 0.14.4 introduced this bug today. If you need to continue working, just build and load the extension in developer mode for now.

**Comment by zalmoxisus** [comment]
Thanks, guys, for reporting this. Yes it is related to that commit and it happens when the limit of maximum actions is reached. Just set the limit to `0` (unlimited) for now.  Find Redux DevTools on the extensions page (chrome://extensions/) and click the Options link to customize everything.

I'll get to it today.

**Comment by hsrobflavorus** [comment]
:+1: Thanks @zalmoxisus !

**Comment by gaearon** [comment]
Any reason you're not using `store.subscribe`? This is where it's safe to trigger side effects.

**Comment by zalmoxisus** [comment]
@gaearon, agree. I was planning to make `remote-redux-devtools` as a monitor, but it was a wrong direction, which influenced the extension as well. We'll certainly move to the `store.subscribe` on both projects. Thanks a lot for your help!
