### ISSUE TITLE
[feature-request] What about a pie chart screen to monitor the size of the store ?

### ISSUE THREAD

**Issue by iamdey** [zalmoxisus/redux-devtools-extension#371]
Just had this idea; I didn't see if someone else already had this idea after a quick search.

What do you think ?

**Comment by zalmoxisus** [comment]
It's a great idea. Something similar was suggested in https://github.com/gaearon/redux-devtools/issues/341 and I added there some ideas of how to implement it. Would you like to create a Redux DevTools monitor for that?

**Comment by iamdey** [comment]
Oh yes nice, I submitted on the bad repository. I close this issue.

**Comment by zalmoxisus** [comment]
@iamdey no probs, it's not a bad repository (the indicated issue was in bad one). However all monitors are independent:
- https://github.com/gaearon/redux-devtools-log-monitor
- https://github.com/alexkuz/redux-devtools-inspector

You either add this functionality to one of them or create a new monitor, which we can include in the extension.
