### ISSUE TITLE
Apply error when running Jests tests with the Redux devtools code

### ISSUE THREAD

**Issue by leongaban** [zalmoxisus/redux-devtools-extension#373]
https://stackoverflow.com/questions/44523873/why-are-these-jest-tests-failing-typeerror-cannot-read-property-apply-of-und?noredirect=1#comment76039669_44523873

```
const store = createStore(reducers,
    compose(
        applyMiddleware(thunk),
        // window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
    )
);

```

With the `window._REDUX_DEVTOOLS_EXTENSION` code in my store.js my **[Jest tests](https://facebook.github.io/jest/)** will fail out with the following error:

> TypeError: Cannot read property 'apply' of undefined

Is there a way around this? Seems like right now I can either test, or use the Redux Chrome tab.

**Comment by ayushnawani** [comment]
@leongaban  how did you solve it? I am also getting the same issue.
