### ISSUE TITLE
Latest Release 2.15.0 missing in npm

### ISSUE THREAD

**Issue by kreed-rmn** [zalmoxisus/redux-devtools-extension#382]
The latest release of this library is missing from NPM. 

The releases tab in github [here](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.15.0) says the latest is 2.15.0, but NPM is only reporting 2.13.2 as the latest.

Can y'all get the latest release on NPM?

**Comment by jhen0409** [comment]
The [npm package](https://github.com/zalmoxisus/redux-devtools-extension/tree/master/npm-package) is just a 'hepler' that provide extra functionally for the browser extension API, so the version doesn't matched current browser extension version.

See the latest version from [Mozilla Add-ons](https://addons.mozilla.org/en-US/firefox/addon/remotedev) and [Chrome Web Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).
