### ISSUE TITLE
Scrollbar gets cropped when seeing a long list of actions.

### ISSUE THREAD

**Issue by arshdkhn1** [zalmoxisus/redux-devtools-extension#387]
![image](https://user-images.githubusercontent.com/16819670/28401883-7838e0ba-6d3a-11e7-8ff0-ee3c12fedc4c.png)

Hi, you can see in the above picture that scroll bar is getting cropped. It is probably due to overflow property of container element of scroll bar element. It is a small css bug that doesn't matter at all but if you guys are interested in getting it fixed, I would like to fix this in my first pr.

**Comment by forWorkAtML** [comment]
@arshdkhn1  can you submit a PR? I develop in firefox and this is really annoying. Would like to see this fixed.  Cheers.

**Comment by victorhqc** [comment]
I'm experiencing same issue. Doing a `PR` soon :)

**Comment by zalmoxisus** [comment]
Guys, sorry about the delay. I'll push a new UI soon.

**Comment by victorhqc** [comment]
I was busy too :( so. Is this issue still relevant?

**Comment by der-On** [comment]
+1

**Comment by sergiocolussidev** [comment]
+1 this bug is very annoying. Thanks

**Comment by der-On** [comment]
I've already tried to solve this myself but the problem seems to come from https://github.com/zalmoxisus/remotedev-app

As I'm not experienced in extension development I was unable to find a way of inspecting the DOM of the extension window. If you can give me a hint on how to do that in firefox I might have another try to fix this.

**Comment by victorhqc** [comment]
The problem seems to be coming in this repository
https://github.com/alexkuz/redux-devtools-inspector

I did an ugly patch to it, but then I noticed that in chrome it was broken. So perhaps, this bug is actually a Firefox issue only. I haven't been able to isolate the issue in order to have an issue published unfortunately.

**Comment by ibrahima** [comment]
Are you guys also seeing the list of actions push the bottom toolbar off the screen? That's what's happening to me, and it's pretty frustrating...

**Comment by ibrahima** [comment]
@victorhqc was your ugly patch like [mine](https://github.com/zalmoxisus/remotedev-inspector-monitor/pull/1)? Mine keeps it working in Chrome, but I think it's actually supposed to work without it because it's using flexbox. Not sure why the middle element just pushes out the others...

**Comment by ibrahima** [comment]
By the way, I found the easiest way to debug this is to open up http://remotedev.io/local/ in the inspector and play around with it, since it's the same UI/code (I'm assuming changes there will apply to the devtools extension as well).

**Comment by victorhqc** [comment]
@ibrahima I think I tried the same approach, if it keeps working in chrome then it's better than mine for sure haha.

**Comment by Nevosis** [comment]
I'm bumping this as I recently switched to FFQuantum as my main development browser. But with this issue it's just awfull :s

**Comment by KamiGim** [comment]
can you guy fix it. I want to use firefox as my main development browser but cannot

**Comment by ibrahima** [comment]
There's a workaround in https://github.com/zalmoxisus/redux-devtools-extension/issues/377#issuecomment-359493688 that can be used until this extension is updated.

**Comment by zalmoxisus** [comment]
Fixed in version `2.15.2` of the extension. It's available on AMO. Sorry about the delay!
