### ISSUE TITLE
Persist button with immutable

### ISSUE THREAD

**Issue by tkvw** [zalmoxisus/redux-devtools-extension#389]
If I clone a fresh copy of react-boilerplate, and change the store config from: 
```
  const composeEnhancers =
    process.env.NODE_ENV !== 'production' &&
    typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__: compose;
```
To: 
```
  const composeEnhancers =
    process.env.NODE_ENV !== 'production' &&
    typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
        serialize:{
          immutable: Immutable
        }
      }) : compose;
```
When I click the persist button all actions are recorded and restored on refresh. But if I commit the actions, the state itself is not persisted. This does work with import/export of the json. 
Am I doing something wrong here? I've included a screencast for this issue: 
![2017-07-25_14-11-07](https://user-images.githubusercontent.com/621098/28571480-5e693eac-7143-11e7-819e-68ae658bd227.gif)

**Comment by Xixi20160512** [comment]
same with you, are you fix it yet?
