### ISSUE TITLE
Show errors stops showing activity

### ISSUE THREAD

**Issue by tko** [zalmoxisus/redux-devtools-extension#39]
When show errors is enabled and an exception is thrown presumably while running reducers (https://github.com/gaearon/react-dnd/issues/360) the extension stops showing any further actions.

**Comment by zalmoxisus** [comment]
Hey,

If you fix the error the lost actions reappear? If so, then it is intended, though maybe I am not right and can be discussed here.

**Comment by tko** [comment]
When I change my code to not trigger that exception the code gets hot replaced and more actions get logged to console, but the extension doesn't show them. If I then disable the 'Show errors' in the settings the actions show up in the extension as well.

**Comment by zalmoxisus** [comment]
It seems that our recent changes broke hot-reloading as our reducer isn't updated. We'll move to `store.subscribe` approach and will fix this issue as well. Thanks a lot for the report!

**Comment by zalmoxisus** [comment]
Fixed in `0.4.16`. Chrome will autoupdate the extension in few hours. If you want to get the fixes now, just remove the extension and install again from [Chrome store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).
