### ISSUE TITLE
why use redux's createStore directly instead of the createStore passed by redux?

### ISSUE THREAD

**Issue by obedm503** [zalmoxisus/redux-devtools-extension#393]
Is there a benefit in using redux's createStore directly?

when a store enhancer is passed to redux it is called with `createStore` and then the function returned is called with the `reducer`, `preloadedState` and `enhancer`. so, enhancers follow the signature:
```js
const enhancer = configOrWhatever => createStore => (reducer, preloadedState, enhancer) => {
// ...
}
```
and according to the redux's documentation:
>A store enhancer is a higher-order function that composes a store creator to return a new, enhanced store creator.

following the type signature: 
```ts
type StoreEnhancer = (next: StoreCreator) => StoreCreator
```
so, instead of using the passed store creator function, why use `createStore` imported from redux? [file in question](https://github.com/zalmoxisus/redux-devtools-extension/blob/2942278fd9b29d7dad8d1f64a3118a8f842375e8/src/app/stores/createStore.js#L1)

the problem arose when I was developing something similar to redux (it implements the same api as redux but functions differently inside) and was testing it with different tools from the community to see if they would play nicely. but redux devtools extension failed because it imported it's own `createStore` instead of using the one passed to it.

**Comment by zalmoxisus** [comment]
The idea is to not include Redux in your app if need only devtools. There's a [simple example](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/react-counter/components/Counter.js) and [an article](https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f) about that.

For use case, I think it's better to use [messaging](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#connect). Here's [a simple example](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/react-counter-messaging/components/Counter.js). Also see [the integration with redux](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/logOnly.js).

**Comment by obedm503** [comment]
I ended up writing a connector of sorts that proxies the store. but it's really slow because it wraps the store in another store.

So I guess it was a design decision and not a bug. I would appreciate it if you could point to some documentation that explains what each of the action types coming from devtools is supposed to be. At this point I'm just covering the `"DISPATCH" ` type in my connector since it's the one examples showed

**Comment by zalmoxisus** [comment]
[Here](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md#5-listening-for-monitor-events) are more details about those actions.
