### ISSUE TITLE
Question: Patterns for connecting to a store in a WebWorker

### ISSUE THREAD

**Issue by asciidisco** [zalmoxisus/redux-devtools-extension#40]
Hello,
first of all, thank you for your work. This is a perfect solution for us, who are using redux, but do not run a React based application :)

I still do have a problem though, which is related to the special setup I have: I´m running the complete Redux stack in a WebWorker, including the vDOM diffing part. so the only information my WebWorker is sending back to the main thread are the vDOM patches.
As there is no access the the `window` object in a  WebWorker, Ißm not able to connect my store to the extension. Therefor my question(s) - Did someone managed to connect the extension to a store in a WebWorker? Or did someone manage to assign the extension to the `self` global of a WebWorker yet (don't know if that´s even possible)?

Any hints or help would be appreciated. Thank you. :)

**Comment by zalmoxisus** [comment]
Hey @asciidisco,

Thanks for the feedback. I don't think it would be possible (at least for now) to inject the extension's script in the page's WebWorker and communicate with it from there. But we have a solution for this case - [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools). In `v1.0.0` the extension will have "remote monitoring", and will be able to communicate with it, but for now use the site or the chrome app as [indicated there](https://github.com/zalmoxisus/remote-redux-devtools#remote-monitoring).

**Comment by asciidisco** [comment]
@zalmoxisus Thank you for the quick answer. That is exactly what I´m looking for :)

**Comment by zalmoxisus** [comment]
You're welcome. Someone reported there that he has some issues with sockets from WebWorker's script. Though I wasn't able to reproduce that, we could add long polling as an alternative if that is really an issue.

**Comment by zalmoxisus** [comment]
FYI [it can be used now also with the extension](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v1.0.0-beta2).

**Comment by asciidisco** [comment]
Awesome! Thanks again.
