### ISSUE TITLE
Define instance name or identifier

### ISSUE THREAD

**Issue by phaistonian** [zalmoxisus/redux-devtools-extension#401]
When multiple stores are in use in the dame page, you get lost in too many instances all sharing the same name (document.title).

If there a way to define an identifier or label for a store?

If not, consider this a humble request :)

**Comment by jhen0409** [comment]
The option [`name`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#name) should help you.
