### ISSUE TITLE
Breaks 'unsafe-eval' CSP, when store.replaceReducer is called

### ISSUE THREAD

**Issue by SleepWalker** [zalmoxisus/redux-devtools-extension#405]
Hello,

when I call store.replaceReducers(), the extension breaks 'unsafe-eval' CSP by trying to call `setTimeout(undefined, 0);`. This happens here:

https://github.com/zalmoxisus/redux-devtools-extension/blob/bc4baef181bd87b4e118bb764b440eddb769e677/src/app/service/Monitor.js#L12-L15

Probably there should be a fallback to no-op, when no update function was passed into constructor:

https://github.com/zalmoxisus/redux-devtools-extension/blob/bc4baef181bd87b4e118bb764b440eddb769e677/src/app/service/Monitor.js#L2-L4

Btw. In my case this was not due to hot reloading, but because I've needed to add new reducers dynamically.

**Comment by zalmoxisus** [comment]
Thanks for the report. I might be missing some recent Redux API changes, but what is the purpose of using `store.replaceReducers` without providing any reducers as argument?

**Comment by SleepWalker** [comment]
@zalmoxisus I'm, actually providing them always. An error isn't in my code. My app works as expected and your's extension too, because `setTimeout(undefined, 0);` produce won't break any code. The reason, why this error was found is because my app server sends CSP headers.

I've thought that this should be something obvious for the devs of the extension. If it is not the case, I'll try to provide more info in the next few days

**Comment by zalmoxisus** [comment]
Something inside the reducer is invoking evaluation, which is restricted by extension's manifest. It would help to see a reproduction example. However, if you're using `store.replaceReducers` apart from hot-reloading, you should set `shouldHotReload` to `false`. See [the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#shouldhotreload) for more details.

**Comment by SleepWalker** [comment]
if I set `shouldHotReload: false` it won't work with hot reloading, right?
I'm currently using hot reloading and also use async reducers, e.g.:

```js
export function injectAsyncReducer(name: string, asyncReducer: ReducerFunction) {
  asyncReducers[name] = asyncReducer;

  if (store) {
    store.replaceReducer(createReducer(asyncReducers));
  }
}
```

I can't understand what does means:

> will not recompute the states on hot reloading

Does this means, that it won't catch the state after replacing the reducers?

I have initialized the store with the following code:

```js
const composeEnhancers =
    // Redux Dev Tools store enhancer.
    // @see https://github.com/zalmoxisus/redux-devtools-extension
    // We only want this enhancer enabled for development and when in a browser
    // with the extension installed.
    process.env.NODE_ENV === 'development' &&
    typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
      ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
        shouldHotReload: false,
      })
      : compose;

  const enhancers = composeEnhancers(
    // Middleware store enhancer.
    applyMiddleware(
      // Initialising redux-thunk with extra arguments will pass the below
      // arguments to all the redux-thunk actions
      thunk.withExtraArgument({ request })
    )
  );

  // creating no-op reducers for the case, when some of reducers will be loaded
  // a little bit later using `injectAsyncReducer()`
  const asyncReducersStub = Object.keys(initialState || {}).reduce((acc, key) => {
    acc[key] = (state = {}) => state;

    return acc;
  }, {});
  const reducer = createReducer({ ...asyncReducersStub, ...asyncReducers });
  store = initialState
    ? createStore(reducer, initialState, enhancers)
    : createStore(reducer, enhancers);
```

I've tried the `window.__REDUX_DEVTOOLS_EXTENSION__([options])` variant (because this is the setup I had before) and it seems to have no effect too.

**Comment by joaovieira** [comment]
Just bumped into the same.. didn't know it was the extension until I found this. Using plain `compose` does not trigger any CSP rule, and @SleepWalker's findings do make sense. Using `shouldHotReload` didn't work either. 

@SleepWalker did you manage to work around it somehow?

**Comment by zalmoxisus** [comment]
This seems related to https://bugs.chromium.org/p/chromium/issues/detail?id=749236. It would be useful if someone can provide an example I can run or open to look for a workaround.
