### ISSUE TITLE
'Illegal invocation' error

### ISSUE THREAD

**Issue by sharkinsspatial** [zalmoxisus/redux-devtools-extension#407]
This error has recently started appearing in the Chrome DevTools console when actions are 
emitted from the application.
```
Uncaught TypeError: Illegal invocation
    at derez (<anonymous>:2:5451)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at Object.decycle (<anonymous>:2:6109)
    at Object.e.stringify (<anonymous>:1:9197)
    at tryCatchStringify (<anonymous>:1:18852)
    at stringify (<anonymous>:1:18960)
    at toContentScript (<anonymous>:1:20255)
    at <anonymous>:2:627
```
Further emitted actions are not captured or displayed by redux-devtools-extension. And actions can no longer be selected in the Inspector panel.  Only notable environment change was Chrome update to 61.0.3163.100.

**Comment by zalmoxisus** [comment]
It throws inside [`jsan`](https://github.com/kolodny/jsan) as something cannot be serialized. Could you please provide an example to reproduce the issue?

**Comment by sharkinsspatial** [comment]
You can reproduce with redux-devtools-extension open with this [url](https://coordination.openaerialmap.org/#/requests/59c3eaceeb38a400111f12d4).  The offending slice of state appears to be (stringified) 
````json
{
    "filter": [
        "has",
        "_id"
    ],
    "id": "task-polygons",
    "layout": {
        "visibility": "visible"
    },
    "paint": {
        "fill-color": {
            "property": "status",
            "stops": [
                [
                    "open",
                    "#5ABDCB"
                ],
                [
                    "inprogress",
                    "#D0EC77"
                ],
                [
                    "completed",
                    "#72C97D"
                ]
            ],
            "type": "categorical"
        },
        "fill-opacity": 0.64
    },
    "source": "geojsonSource",
    "type": "fill"
}
````
I apologize for the the reproduction example.  I can create something more minimal if that would be preferable for you.  Just to reiterate, I am not seeing any errors on Chrome 60.0.3112.113 but I am experiencing the issue on 61.0.3163.100.  Thanks.

**Comment by zalmoxisus** [comment]
Thanks for the details. Yes, it works ok on Chrome 60, but I was able to reproduce with your url on Canary.

It throws in [`jsan`](https://github.com/kolodny/jsan/blob/638607199b4dc5385443c6c22af0b2dc7c6e0f09/lib/cycle.js#L87), when calling `value.toJSON()`, where `value` is `DOMRectReadOnly {x: 0, y: 0, width: 875, height: 480, top: 0, …}`. `value.toJSON` is a `function` but it's not allowed to be called. I don't see a solution other than adding a try-catch there and skipping datas, but for some cases (apart from the extension) it won't be good to swallow the exceptions inside `jsan`.

Meanwhile, I'd recommend to strip such parts using `actionSanitizer` / `stateSanitizer` parameters. See [the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer) for more more details.

**Comment by kolodny** [comment]
@zalmoxisus Can you give a more thorough example of the error and how to repro. I'm currently not seeing that error on Chrome Canary:

```
> navigator.userAgent
< "Mozilla/5.0 ...snip... Chrome/64.0.3241.0 Safari/537.36"
> d = new DOMRectReadOnly()
< DOMRectReadOnly {x: 0, y: 0, width: 0, height: 0, top: 0, …}
> d.toJSON('foo')
< {x: 0, y: 0, width: 0, height: 0, top: 0, …}
```

**Comment by vansosnin** [comment]
I reproduced this error while using [sentry](https://sentry.io/) for reporting errors. Check out my issue in their repo: https://github.com/getsentry/raven-js/issues/1170

They [wrap](https://github.com/getsentry/raven-js/blob/master/src/raven.js#L297) all functions and I have a supposal that DevTools cannot handle these wrapped functions in some cases (check out issue above, I described how to reproduce the bug).

**Comment by zalmoxisus** [comment]
Should be fixed in last version as per https://github.com/kolodny/jsan/issues/13. Feel free to reopen the issue if it's still relevant.
