### ISSUE TITLE
Extension error: Uncaught TypeError

### ISSUE THREAD

**Issue by tanepiper** [zalmoxisus/redux-devtools-extension#41]
Whenever I try load this extension, I get a notification error with:

`Uncaught TypeError: Cannot read property 'initialScrollTop' of undefined.`

It seems to cause the window to fail sizing correctly, this is all I'm able to see:

![untitled](https://cloud.githubusercontent.com/assets/376930/12677369/61569ce0-c690-11e5-87d3-d5a03c7fb98f.png)

**Comment by tanepiper** [comment]
Ahh, just after I posted this I think I found the issue.  I still have `<DevTools />` in my Provider JSX, as soon as I removed that it seemed to work correctly - so I suspect there is a conflict happening

**Comment by zalmoxisus** [comment]
Setting `preserveScrollTop` to `false` in `redux-devtools-log-monitor` should help.

A good example of using the extension together with embedded DevTools is [Redux Form example](http://erikras.github.io/redux-form/#/examples/simple?_k=x31mb3) (it uses the extension only if it is installed).
