### ISSUE TITLE
Big store, consist image in Buffer object are crashing redux-devtools

### ISSUE THREAD

**Issue by rezunenko** [zalmoxisus/redux-devtools-extension#410]
I have store with text data and redux-devtools became very slow and was crashing after, when i started saving into it several images (10-20) in format:

![image](https://user-images.githubusercontent.com/16374896/31223102-e8a4b756-a9d1-11e7-8f46-5cf99cda1341.png)

App crashed not in moment of save, but after several minutes of using devtool

**Comment by zalmoxisus** [comment]
You should sanitize that `preview` key using `actionSanitizer` / `stateSanitizer` parameters. See [the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer) for more more details.
