### ISSUE TITLE
Extension only works in Chrome

### ISSUE THREAD

**Issue by rahulthewall** [zalmoxisus/redux-devtools-extension#411]
Hi,

In one of the React projects that I work on, I can't get the redux-devtools-extension to work on Firefox. It works on Chrome. 

The code used is given below:

```
// Redux Dev Tools store enhancer.
	// @see https://github.com/zalmoxisus/redux-devtools-extension
	const reduxDevToolsEnhancer =
		// We only want this enhancer enabled for development and when in a browser
		// with the extension installed.
		process.env.NODE_ENV === 'development'
			&& typeof window !== 'undefined'
			&& typeof window.devToolsExtension !== 'undefined'
			// Call the brower extension function to create the enhancer.
			? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ // eslint-disable-line no-underscore-dangle
			// Else we return a no-op function.
			: compose;

	const epicMiddleware = createEpicMiddleware(createRootEpic(customEpics));

	const store = createStore(
		createReducer(customReducers),
		initialState,
		reduxDevToolsEnhancer(
			applyMiddleware(epicMiddleware),
		),
	);
```

Can someone help me figure out what might be the reason?

Thanks

**Comment by zalmoxisus** [comment]
Hi. What version of Firefox are you using? Do you have `Redux` tab under DevTools panels?

**Comment by rahulthewall** [comment]
Hi @zalmoxisus, the problem persists across various versions of Firefox. And yes, I have the Redux tab under DevTools panel. And the redux extension works on the example project here: http://zalmoxisus.github.io/examples/counter/

So there's something that's wrong with the project setup it seems, but I can't figure out what it is.

**Comment by zalmoxisus** [comment]
Aren't any exceptions in the console? I'd suspect it could be a problem with serializing some native types like in #407. You could try to sanitize some parts of the reducer's object (using `actionSanitizer` / `stateSanitizer`) to see where it comes from. See [the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer) for more more details.

**Comment by KSuttle-cng** [comment]
Maybe related? https://github.com/zalmoxisus/redux-devtools-extension/issues/419#issuecomment-342288323

**Comment by rahulthewall** [comment]
I don't have access to this project any longer. @rodogir - you want to investigate this? :)

**Comment by zalmoxisus** [comment]
Closing in favor of #546.
