### ISSUE TITLE
Dev tools lagging behind actual state in store

### ISSUE THREAD

**Issue by fatso83** [zalmoxisus/redux-devtools-extension#417]
_I realize this issue is a bit thin on details, so I will try and dig up more details if this is a new case (reproducible case or similar), but I'd like to establish if it is a known issue first:_

I was looking at a bug that I couldn't understand by looking at the state in the Redux: the branch the debugger had hit a breakpoint on shouldn't have been possible when looking at the state of the Redux store in the Dev tools pane. I then went up the stack in the debugger until I saw a familiar `dispatch` call. It contained an action that was not yet visible in the list of actions in the Redux Inspector! I would have thought it would have been visible immediately there.

Also, I got hold of the state through a `getState()` call at the point my debugger had stopped and it also showed another state than the dev tools.

This brings me to think that Redux Dev Tools uses a listener, as all the rest do, but that it must have been attached at a later point than the code I was looking at. Therefore, its state had not yet been reflected to the new state of the store.

If that is the case, **is there a way of making sure that dev tools is the first listener to changes in the store**? That would have fixed this issue - given that my analysis is correct.

**Comment by zalmoxisus** [comment]
Not sure it's about subscribing. Could you try setting [`latency`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#latency) to `0` to see if it helps?

**Comment by fatso83** [comment]
So they are batched up in an interval and set with the next tick?! That makes sense, and also fully explains the situation. I will close this, and if I encounter something like this later, I will try with your proposal. In case it doesn't work, I'll reopen it. 

Thank you.
