### ISSUE TITLE
Crash using ngrx routing

### ISSUE THREAD

**Issue by bas-jansen** [zalmoxisus/redux-devtools-extension#423]
http://run.plnkr.co/preview/cj9jxc2ie000d3c5w71bl0my3/
If I start this plunker (in separate window) everything is ok. I can Increment and Decrement and still see the actions and store contents in DevTools (using the button next to the url bar in Google Chrome).
But when I click the Away-link and open de DevTools again. the DevTools has crashed.

Not sure if this is a bug in the Redux DevTools, or in ngrx.
It seems ngrx stores many object references in the store. In our application we have 122937(!) lines of content if I look at the RAW store
Any advice?

**Comment by zalmoxisus** [comment]
Closing in favour of #314
