### ISSUE TITLE
React Inspect Props - Redux DevTools, but for React props

### ISSUE THREAD

**Issue by lucasconstantino** [zalmoxisus/redux-devtools-extension#424]
Hi there

I've just released a simple project made of a single HoC which creates a custom connection to Redux DevTools extension and populates it with every props change happening on the composed component, building kind of a _history debugging tool for component props_.

It allows some of the cool functionality such as action replay (even though actions in this case are fake).

I'm making this issue so people can eventually find this tool, but also to thank you for making Redux DevTools in the form of an API in the first place.

Here it goes: https://github.com/lucasconstantino/react-inspect-props

**Comment by zalmoxisus** [comment]
Added to [Integrations](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Integrations.md#react). Thanks for working on that!
