### ISSUE TITLE
Request: Single updated display of Log monitor

### ISSUE THREAD

**Issue by Mystify** [zalmoxisus/redux-devtools-extension#425]
One of the greatest features I absolutely love about the redux-devtools-extension is the ability to look at my application store in the browser dev tools. I am constantly checking the log monitor to find out the current state of my store and reducers....

However, there is one thing that I wish I had so badly, and that is instead of having a great big honking list of every update that has occurred, I wish I had the exact same view as the log monitor, but a single screen that is automatically updated showing the latest store state.

Don't get me wrong, time traveling with the log monitor is awesome, and definitely useful. But something that irks me almost every time is if I open one of the store reducers to look at it, and more updates occur, I now have to scroll and scroll and scroll and scroll some more to catch up to the bottom. And it doesn't always go back to auto-scrolling when new updates occur.

Every time this happens, I think "man, I wish there was just a single display of the monitor so I don't have to scroll for every update"

I was thinking of forking the project and seeing if this was something I could do on my own, but sadly, my current project deadline doesn't give me a freedom to do such fun things.

I was hoping that something like this would be really easy and _maybe_ an update put out for this?

Thanks for the tool! I love it.
Cheers!
Dave

**Comment by zalmoxisus** [comment]
I think Inspector monitor does that. For log monitor this should be also achieved with setting [`maxAge`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#maxage) argument to `2`. Unless I'm missing something. I'm working on making easier to create monitors and even providing ready components for that. So feel free to reopen it if think this still can be the case for a new monitor.
