### ISSUE TITLE
redux-devtools-extension doesn't work

### ISSUE THREAD

**Issue by WzFFzW** [zalmoxisus/redux-devtools-extension#426]
i don't know why.My application bring it collapse(just once)，but when i change my code to, it also does not work.I have re-install redux-devtools-extentsion.
Surprisingly, it does not work in every page, also include your example page.
plase tell me how to let it work.

Configuration：
chrome-> 61.0.3163.100
redux-> 3.6.0
redux-devtools-extension-> 2.15.1 

After i reinstall chrome, it started working.

My english is poor, if you don't understand my meaning, please tell me. sorry :(

**Comment by amackintosh** [comment]
You will have to post more specific code examples.

Show what your code currently looks like, such as your root component and how you are creating your store. Everyone will have trouble helping you if they cannot see what you are doing.
