### ISSUE TITLE
Commit doesn't work with Immutable.js state

### ISSUE THREAD

**Issue by rixo** [zalmoxisus/redux-devtools-extension#427]
Using Chrome extension v2.15.1.

When using Immutable.js for the state, committed state is lost. Both when clicking the commit button and (most unfortunately) autocommit.

I managed to nail the cause.

At page loading, when the persisted state is restored, at [this line](https://github.com/zalmoxisus/redux-devtools-extension/blob/ce5ea7b89250c69d55509f6a03c163802be8d916/src/app/middlewares/api.js#L178) we have :

    persistedState.committedState === persistedState.computedStates[0].state // true

But commitedState is serialized to:

    { ... "committedState":{"$jsan":"$.computedStates[0].state.data"}}
    // should have been: $.computedStates[0].state

This happens because of [this line](https://github.com/zalmoxisus/remotedev-app/blob/4cb6431ffb904cecc1e505273616ac36663b1ce7/src/app/utils/stringifyJSON.js#L8) in the serializer. It moves the object that is referenced by commitedState (the `value` variable)...

I have confirmed that the problem is fixed by changing the replacer to add the string keys (`__serializedType__`...) directly to the value object instead of creating a new object. And of course changing the reviver accordingly.

Unfortunately, that doesn't seem ideal because that mutates the argument that is passed to stringify. On the other hand, the existing code already does that by deleting the Symbol key `DATA_TYPE_KEY` (but surprisingly not `DATA_REF_KEY`).

## Reproduction

```
import {createStore} from 'redux'
import Immutable, {Map} from 'immutable'
import {composeWithDevTools} from 'redux-devtools-extension'

const compose = composeWithDevTools({
  serialize: {
    immutable: Immutable,
  }
})

const store = createStore(reducer, compose())

function defaultState() {
  return Map({count: 0})
}

function reducer(state, {type}) {
  if (type === 'PLUS') {
    const count = state.get('count')
    return state.setIn(['count'], count + 1)
  } else if (typeof state === 'undefined') {
    return defaultState()
  } else {
    return state
  }
}

// simulate UI
setTimeout(() => {
  store.dispatch({type: 'PLUS'})
  console.log(store.getState().get('count'))
}, 1000)
```

**Steps**

1. First load (prints 1)
1. Open dev tools
2. Click persist
3. Click commit
4. Reload page

Expected: prints 2
Actual: prints 1

**Comment by zalmoxisus** [comment]
Should be related to #540 and fixed in the last version. Feel free to reopen the issue if it's still relevant.
