### ISSUE TITLE
Add option to not show the icon in the adressbar in Firefox

### ISSUE THREAD

**Issue by Pajn** [zalmoxisus/redux-devtools-extension#428]
I think it's nice to keep a clean UI and have hid my extensions in the "More tools" menu but this one still shows up in the address bar.

**Comment by Pajn** [comment]
Hmm, it would be nice to hide it from the right click menu as well. Currently the extension is accessible from four different places which seems quite much.
More tools and from the devtools more than covers the need.

**Comment by zalmoxisus** [comment]
I think there's no option to add it to "More tools", unless it was introduced recently (if you find how, please share). Hiding from context menu was implemented in #535 and will be published in next version.

**Comment by joshhunt** [comment]
Revisiting this @zalmoxisus - It would be great if Redux Dev Tools was shown as a standard toolbar item (like React dev tools!) so the user can choose whether it's always visible or not.

99% of the time I use my browser I don't need to use Redux Dev Tools, so it would be great if it wasn't always visible :)

![image](https://user-images.githubusercontent.com/46142/211541523-13323de8-9bd0-4ad3-87e0-672c880a59a1.png)
