### ISSUE TITLE
Redux 4.0 Uncaught TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by amackintosh** [zalmoxisus/redux-devtools-extension#430]
Greetings, I am just cross reporting this anomaly here:
https://github.com/reactjs/redux/issues/2715

To reproduce from here, you should be able to fire up any app with code similar to mine, and run:

``` bash
npm install --save redux@next
```

If you skim that thread, you should see that there was a similar issue before that involved setting up the initial state. It looks like that issue has manifested again with the newest release of Redux.

**Comment by Patrik-Lundqvist** [comment]
Relates to https://github.com/gaearon/redux-devtools/issues/391

**Comment by zalmoxisus** [comment]
Should be fixed in `2.15.2`.

**Comment by tomspeak** [comment]
@zalmoxisus when is `2.15.2` being released?

**Comment by nilscox** [comment]
Any updates on this?

**Comment by thg303** [comment]
is there any branch/tag for "2.15.0" version or it's just a prophecy?
