### ISSUE TITLE
React Router Failing on initial load - Firefox Quantum

### ISSUE THREAD

**Issue by jvanzella** [zalmoxisus/redux-devtools-extension#431]
I am using Firefox Quantum with version 2.15.1 of the plugin.

When I try and load my application, I get a **_TypeError: routeState.get(...) is null_** error.

It is working in Chrome, with the plugin.
It works when I disable plugin.

I am using React Boilerplate with React Router 4 and the error is being thrown in _containers/App/selectors.js_:

![image](https://user-images.githubusercontent.com/2285857/32984405-da5eee0e-cc5a-11e7-881b-442abd5b29a4.png)

const makeSelectLocation = () => createSelector(
  selectRoute,
  **(routeState) => routeState.get('location').toJS()** // <- right here
);

![image](https://user-images.githubusercontent.com/2285857/32984370-52f0771c-cc5a-11e7-8b4b-a65f1f8a1086.png)

**Comment by zalmoxisus** [comment]
It would be helpful if someone can share an example I can run to reproduce the issue. Feel free to reopen the issue with more details if it's still relevant.
