### ISSUE TITLE
Firefox: Redux action list pushes bottom of devtools off screen

### ISSUE THREAD

**Issue by PeteAndersen** [zalmoxisus/redux-devtools-extension#433]
As the log of Redux actions fills up, it is increasing in size before deciding to scroll which pushes the bottom of the devtools off screen, with no way to reach them except to commit the redux log.

Here's a demo that spams some actions as remote data is received:
![](https://i.imgur.com/MXqPiCM.gif)

**Comment by lparry** [comment]
I'm also seeing this, Firefox Developer edition, 58.0b5 (64-bit)

**Comment by icflorescu** [comment]
Happens on Firefox 57.0 too.

**Comment by Skylsmoi** [comment]
I have the problem too (FF 57, 64-bits, debian 8)
Is there a little workaround for the time it gets fixed please ?

**Comment by datenreisender** [comment]
@Skylsmoi My current workaround is to temporarily switch to the Log monitor or Chart in the top left and press the button there.

**Comment by datenreisender** [comment]
This seems to be a duplicate of #377, thus I suggest we close this one.

**Comment by Skylsmoi** [comment]
thx for the workaround

indeed, it's a duplicate

**Comment by PeteAndersen** [comment]
Thanks for finding duplicate, closing.
