### ISSUE TITLE
How does this work without externally_connectable?

### ISSUE THREAD

**Issue by MrBlenny** [zalmoxisus/redux-devtools-extension#439]
I'm trying to understand the architecture because I have a few changes in mind.

For an injected script to talk to the extension's main thread you usually need to add [externally_connectable](https://developer.chrome.com/extensions/manifest/externally_connectable) in the `manifest.json`. This method is not being used here. How does the IPC comms actually work?

**Comment by zalmoxisus** [comment]
I think it doesn't work with other extensions for more than 2 years already, since some changes were added on Chrome part. So that can be done only by passing actions through a remote server.
