### ISSUE TITLE
Doesn't work with Web3.js Ethereum library 

### ISSUE THREAD

**Issue by willvlad** [zalmoxisus/redux-devtools-extension#449]
When adding redux devtools as per the description, the store no longer gets anything from web3js. Removing redux devtools brings back the web3js variables into the store...
Below is our store.js file. The commented out part is the implementation of the redux devtools that breaks it so had to revert to the code above it.

**Comment by willvlad** [comment]
`import { applyMiddleware, createStore, compose } from "redux"

import logger from "redux-logger"
import thunk from "redux-thunk"
import promise from "redux-promise-middleware"

import reducer from "./reducers"

export default compose(applyMiddleware(promise(), thunk, logger()))(createStore)(reducer);

// const composeEnhancers =
//   typeof window === 'object' &&
//   window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?   
//     window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
//       // Specify extension’s options like name, actionsBlacklist, actionsCreators, serialize...
//     }) : compose;

// const enhancer = composeEnhancers(
//   applyMiddleware(promise(), thunk, logger()),
//   // other store enhancers if any
// );

// const store = createStore(reducer, enhancer);


// export default store;`

**Comment by zalmoxisus** [comment]
The configuration looks right. More information about how reducers/actions interact with web3js would be helpful.
Feel free to reopen the issue with more details if it's still relevant.
