### ISSUE TITLE
Does action filter accept regex?

### ISSUE THREAD

**Issue by x1a0** [zalmoxisus/redux-devtools-extension#45]
It seems using action name as-is works. But regex does not work.

For example I want to filter out all redux-form actions. What I've tried:

- `redux-form/.*`
- `redux-form/*`
- `redux-form\/.*`

**Comment by zalmoxisus** [comment]
It does not, but it's a good feature request I want implement.

**Comment by zalmoxisus** [comment]
Implemented in `v1.0.0.5`.
