### ISSUE TITLE
How to use Redux DevTools in a chrome extension

### ISSUE THREAD

**Issue by sthiago** [zalmoxisus/redux-devtools-extension#450]
Hi there,

I'm developing a chrome extension and the redux-devtools-extension doesn't seem to find the store. The `window.__REDUX_DEVTOOLS_EXTENSION__` (or `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`) are not getting defined, from what I could gather. I'm guessing the problem is that redux-devtools-extensions doesn't work on `chrome-extension://<extensionID>/<page>` urls. Is there a way to fix that?

My configuration is as follows:

```js
// configureStore.js
import { createStore, combineReducers, applyMiddleware, compose } from 'redux'
import thunk from 'redux-thunk'

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose

export default () => {
  const store = createStore(
    combineReducers({
      // my reducers
    }),
    composeEnhancers(applyMiddleware(thunk))
  )

  return store
}
```

```
redux@3.7.2
redux-devtools-extension@2.15.1
```
Thanks!

**Comment by markbiek** [comment]
I'm in the same situation and would love to know if it's possible to use Redux DevTools in a Chrome extension.

**Comment by seyaobey** [comment]
Any advance on this topic? I am having the same problem

**Comment by markbiek** [comment]
@seyaobey I was able to solve it using the following approach

https://viastudio.com/debugging-a-reactjs-chrome-extension/

I also had to run remotedevtools locally: `remotedev --hostname=localhost --port=8000` and change the Settings of the RemoteDev popup to **Use custom (local) server**

**Comment by ackmanx** [comment]
@markbiek Thanks for the blog post! Setting up remote-redux-devtools worked very smoothly.

**Comment by Jayiitb** [comment]
@markbiek @ackmanx Please help me out! I am getting following error.
connected to remotedev-server
`Could not establish connection. Receiving end does not exist.`
Redux logs are printing as usual. But `redux-devtools` is not picking it up.


PFA
<img width="1105" alt="Screenshot 2022-09-05 at 10 04 06 AM" src="https://user-images.githubusercontent.com/835114/188361091-3a52c51f-a511-4883-b77f-735a5a141803.png">
