### ISSUE TITLE
Excessive use of memory and CPU

### ISSUE THREAD

**Issue by lightheaded** [zalmoxisus/redux-devtools-extension#455]
MacOS High Sierra 10.13.2 (17C205)
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Redux Devtools 2.15.1

Every time I inspect any Redux application, it uses up a considerable chunk of CPU and starts leaking memory. 

![screen shot 2018-02-01 at 14 07 01](https://user-images.githubusercontent.com/3413870/35677712-610e0ece-0759-11e8-962d-e36c40d44733.png)

I realise this is not enough information for debugging, but I would appreciate any thoughts on where to look for finding the leak?.

**Comment by jotatoledo** [comment]
Are you setting a limit to the state history?

**Comment by lightheaded** [comment]
Yes, but it also happens when the page is opened and only a few events are
fired (less than 5)

**Comment by zalmoxisus** [comment]
That is happening due to serialization of some huge objects included in the state or action. The solution is to [sanitize them](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer).

**Comment by phil-lgr** [comment]
![image](https://user-images.githubusercontent.com/9644867/42636785-95e5c1e6-85b7-11e8-8e3c-c68d934aa192.png)

I did some profiling and the extension takes 1-2s seconds to finish rendering

**Comment by phil-lgr** [comment]
This was with v2.15.2 from the Chrome store.. i'll keep digging see what's going on

**Comment by phil-lgr** [comment]
thanks @zalmoxisus, ui-router puts some big objects in the reducer, just took what I needed

```
const actionSanitizer = action => {
    const uiRouterActions = /@ui-router.+/g;
    return uiRouterActions.test(action.type)
        ? { type: action.type, transition: sanitizeUIRouterTransition(action.transition) }
        : action;
};
const stateSanitizer = (state: AppState): any => {
    if (state.router && state.router.last && state.router.last) {
        return {
            ...state,
            router: sanitizeUIRouterTransition(state.router.last)
        };
    }
    return state;
};
const sanitizeUIRouterTransition = (transition: Transition): any => ({
    params: transition.router && transition.router.globals && transition.router.globals.params,
    current: transition.router && transition.router.globals && transition.router.globals.current,
    targetState: transition.targetState && transition.targetState().state(),
    from: transition.from && transition.from(),
    to: transition.to && transition.to()
});
const reduxDevtoolsExtensionOptions = {
    actionSanitizer,
    stateSanitizer
};
const composeEnhancers =
    (window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ &&
        window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__(reduxDevtoolsExtensionOptions)) ||
    compose;
```

**Comment by zalmoxisus** [comment]
Thanks for the example! Added it to Troubleshooting.

**Comment by phil-lgr** [comment]
@zalmoxisus do you have a patreon or open collective for redux dev tool, I wish I had time to contribute but I don't, I would happily $ to encourage you, this extension is so important in the redux ecosystem

**Comment by phil-lgr** [comment]
OH, I just saw you have an open collective! I will contribute thanks!

**Comment by zalmoxisus** [comment]
Thanks @phil-lgr! That example is also a contribution. Other contributions are also much appreciated, I'll use them to alloc more time in finishing https://github.com/zalmoxisus/redux-devtools-extension/projects

**Comment by phil-lgr** [comment]
Done, added my monthly contribution, BTW, I would pot the open collective link higher in the README.md, it's long so I didn't noticed it, IMO no need to be shy for some $, put it right on top bro! 🥇

**Comment by zalmoxisus** [comment]
Thanks again!
