### ISSUE TITLE
Feature proposal - replay prod actions

### ISSUE THREAD

**Issue by RaulTsc** [zalmoxisus/redux-devtools-extension#456]
Hi guys,

Nice library! I'd like to propose a new feature.

As this is a debugging helper library, I think it would be very useful if developers could easily save and replay actions users do. 
I did not put much thought into this so I'm open to suggestions as to how this should work but the idea is simple - save the actions somehow and then load & replay them.

Thank you
Raul

**Comment by zalmoxisus** [comment]
Hey @RaulTsc. 

You can use [`redux-remotedev`](https://github.com/zalmoxisus/redux-remotedev) for that or save actions on your side and import them in the extension as a stringified array.
