### ISSUE TITLE
Does not work correctly in Chrome 64

### ISSUE THREAD

**Issue by Tseberechts** [zalmoxisus/redux-devtools-extension#457]
There's a difference between the embedded redux dev tools in chrome dev tools and the one opened from the icon.

In Chrome Dev tools:

<img width="617" alt="screen shot 2018-02-12 at 12 26 49" src="https://user-images.githubusercontent.com/18442053/36094874-2c989f20-0ff0-11e8-813e-7ce8649ec199.png">

Standalone:

<img width="722" alt="screen shot 2018-02-12 at 12 27 01" src="https://user-images.githubusercontent.com/18442053/36094891-3d29172a-0ff0-11e8-883a-54b33c17584c.png">

**Comment by jaunkst** [comment]
I am seeing that 'jumping' / 'time travel' is no longer working. 
I tested both an react redux and a angular redux implementation.

**Comment by nilobarp** [comment]
This caused a great deal of confusion. All the action vanishes and state is reset to `initialState`. I thought there is a bug in code which is forcing my pages to reload.

**Comment by zalmoxisus** [comment]
It would be helpful if someone can provide steps to reproduce with [our example](https://github.com/zalmoxisus/redux-devtools-extension#demo) or providing their example code. Feel free to reopen the issue with more details if it's still relevant.
