### ISSUE TITLE
Update for Redux 4.x

### ISSUE THREAD

**Issue by michaelwalloschke** [zalmoxisus/redux-devtools-extension#460]
See https://github.com/zalmoxisus/redux-devtools-instrument/pull/17

Would be nice if this will be bumped, so that we can use again the Chrome extension from Extension Store without being forced to build it locally.

**Comment by Cryrivers** [comment]
For whoever maintains TypeScript definition, please also take note that `GenericStoreEnhancer` has been removed in Redux 4.0.0-beta.2 🙏

**Comment by michaelwalloschke** [comment]
Any news on this?

**Comment by michaelwalloschke** [comment]
Thanks for the store update!
