### ISSUE TITLE
Native Map isn't displayed in state tree

### ISSUE THREAD

**Issue by Firehed** [zalmoxisus/redux-devtools-extension#461]
Extension version: 3.1.0
Redux: 3.7.2
redux-devtools-extension package: 2.13.2

In my Redux store, I have native `Map` types (_not_ Immutable.js) being stored. This is correctly displayed via `console.log(state)`:
<img width="392" alt="screen shot 2018-02-22 at 10 25 06 am" src="https://user-images.githubusercontent.com/354842/36556651-c3897914-17ba-11e8-9921-6e10b48c13bb.png">

This extension, however, renders the Map as an empty dictionary:
<img width="240" alt="screen shot 2018-02-22 at 10 25 25 am" src="https://user-images.githubusercontent.com/354842/36556665-ce96794c-17ba-11e8-9aa0-dda7e3990560.png">
<img width="385" alt="screen shot 2018-02-22 at 10 25 39 am" src="https://user-images.githubusercontent.com/354842/36556666-cf7af1f8-17ba-11e8-8083-36ff9954d51a.png">

I would expect that a Map in my redux store to be rendered visually similarly to a plain object/dictionary, like how the browser console does.

This also appears to happen with the built-in `Set` type

**Comment by anton6** [comment]
Me too

**Comment by vincenzovitale** [comment]
I saw this other thread:
https://github.com/zalmoxisus/redux-devtools-extension/issues/124

Is this the suggested approach for now?

**Comment by onemeta** [comment]
Pass the {serialize: true} option to composeWithDevTools when you set up your store. The entries will render as { key: [key], value: [value] }.

**Comment by oolleegg55** [comment]
It is really strange but now the option "serialize: true" does not work. And only this old comment can help now:  https://github.com/zalmoxisus/redux-devtools-extension/issues/124#issuecomment-221972997

**Comment by zalmoxisus** [comment]
As mentioned in #540, it should be fixed in the last version. Support for ES6 maps was added in https://github.com/alexkuz/react-json-tree/pull/69. Feel free to reopen if the issue still persists.

**Comment by stefanfrede** [comment]
I had to switch from `@babel/plugin-transform-runtime` and `@babel/runtime-corejs2` to `@babel/polyfill` in my app and now I have the exact same problem.
