### ISSUE TITLE
Tooltip on chart view does not handle HTML entities correctly

### ISSUE THREAD

**Issue by kumar303** [zalmoxisus/redux-devtools-extension#462]
To reproduce:

- Dispatch an action that results in some state like `book.title` where `title` has a value of `cars &amp; trucks`
- Open the Redux devtool
- Go to the chart view
- Navigate the state chart from `book` to `title`
- Hover over `title` so you can see its value

The tooltip incorrectly renders HTML contained within the state value. For example, you'd see something like `cars & trucks` when you should see `cars &amp; trucks`.

If you *click* on `title` to see the table view then the HTML is rendered as expected.

I know this is a minor issue but it just slowed me down when trying to debug an HTML rendering issue in my own app ☹️

**Comment by kumar303** [comment]
Reproducible in Firefox and Chrome.

**Comment by zalmoxisus** [comment]
Thanks for the report. Moved to https://github.com/reduxjs/d3-state-visualizer/issues/19. If someone would like to contribute there, it would be much appreciated.
