### ISSUE TITLE
breaks Redux store.replaceReducer - Last 50 actions RE-APPLIED

### ISSUE THREAD

**Issue by crobinson42** [zalmoxisus/redux-devtools-extension#464]
When you invoke `store.replaceReducer(newReducer)` the last 50 (`maxage` default param) actions are applied/run-through the store.

This has the potential to break a lot of applications, mine in particular where several of the last 50 actions are using http or socket middleware for async actions. During the state of my application I use code-splitting which involved heavy utilization of `store.replaceReducer` anytime a new _module_ is loaded I register a new reducer dynamically thus invocation of `replaceReducer`.

Is this intended to be a feature or a potential bug? Thanks!

**Comment by NaitoKenzo** [comment]
Any update on this one? Happy to help if possible.

**Comment by zalmoxisus** [comment]
When you use `store.replaceReducer` the effect will be the same as for hot-reloading, where the extension is recomputing all the history again. To avoid that set [`shouldHotReload`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#shouldhotreload) parameter to `false`. 

Added this to Troubleshooting.
