### ISSUE TITLE
Synchronisation of your documentation  (Fable)

### ISSUE THREAD

**Issue by ShalokShalom** [zalmoxisus/redux-devtools-extension#469]
4 months ago, somebody fixed the Fable integration link, while your current doc still shows it wrong:
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Integrations.md#fable

In your docs, it says purescript-react-redux

**Comment by zalmoxisus** [comment]
It should be there now. Sorry about the delay on this.
