### ISSUE TITLE
Npm package broken with Redux 4 and TypeScript

### ISSUE THREAD

**Issue by Wraul** [zalmoxisus/redux-devtools-extension#470]
Hello

Now that the extension is compatible with Redux 4 I decided to try it in our project. The project uses TypeScript.

I'm using the npm package to add the middleware to our store, but I get an error about `GenericStoreEnhancer`.
This appears to be an issue with the type definition file.

According to a comment in #460, `GenericStoreEnhancer` is removed in Redux 4.
It appears to have been removed from Redux in this commit reactjs/redux@cbdca6215e1891e97120ac05c971618182455e54

**Comment by Cryrivers** [comment]
Current `master` is still targeted to `redux` 3.7.2. I would create a PR when `redux` 4 is released.

**Comment by TrejGun** [comment]
@Cryrivers It was released :)

**Comment by saostad** [comment]
can you fix the problem?

**Comment by sylvanaar** [comment]
There is a workaround for it [Here](**https://github.com/zalmoxisus/redux-devtools-extension/issues/492**)

**Comment by maryokhin** [comment]
The fix was not published to NPM?

**Comment by jhen0409** [comment]
The npm package is now supported Redux `v4` with TypeScript. :)

**Comment by mmakrzem** [comment]
I can't get redux devTools working with Redux v4.  When I call:
`AppStore._store = createStore( reducers, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__() );`

I get an error in the console:
VM105:2 Uncaught TypeError: Cannot read property 'state' of undefined
    at unliftState (<anonymous>:2:31677)
    at Object.getState (<anonymous>:2:31745)
    at Function.getStoreState (AppStore.ts?a477:71)
    at Function.start (Renderer.ts?7ee2:68)
    at eval (index.ts?7fbc:5)
    at Object../src/renderer/index.ts (renderer.js:2589)
    at __webpack_require__ (renderer.js:680)
    at fn (renderer.js:90)
    at Object.0 (renderer.js:2605)
    at __webpack_require__ (renderer.js:680)
