### ISSUE TITLE
Chrome Extension crashes on launch

### ISSUE THREAD

**Issue by Kamilius** [zalmoxisus/redux-devtools-extension#477]
Trying to run extension against my Angular 5 NGRX application, but when I try to click/activate it, it shows popup with round spinner, then button grays-out. After few seconds Chrome's message stating that extension crashed and proposing to reload it appears.

Is there any way to debug this extension to see errors it throws?

**Comment by Pringels** [comment]
Are you making use of `@ngrx/router-store` by any chance? 

My devtools was also crashing until I implemented the custom router state serializer mentioned here:
https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer

Related issuse:
https://github.com/ngrx/platform/issues/537

I'm not sure why the standard behavior of `router-store` is to dump the entire router state into redux. It seems odd that a library should crash devtools by default. It caused me at least 2-3 hours of frustration and googling. 

I'm sure there was probably a good reason for this decision, however I would have only supplied the essential parts that 99% of users will probably make use of: `url`, `params` and `queryPrams`. 
Then simply allow users who require larger chunks of the router state to supply a custom serializer.

**Comment by rickvandermey** [comment]
When updating the application ngrx versions to latest, the applications crashes upon opening.

```
"@ngrx/router-store": "5.0.1", -> 5.2.0
"@ngrx/store": "5.1.0", -> 5.2.0
"@ngrx/store-devtools": "5.1.0" -> 5.2.0
```

**Comment by Kamilius** [comment]
@Pringels actually yeah, stopped crashing when I’ve disabled router store

**Comment by Pringels** [comment]
@Kamilius If you implement the custom serializer as per the docs it should solve your problem.

I still don't feel this should be default behaviour. Is it fair to assume that most developers who work with `ngrx` make use of the devtools extension?

Maybe we can log a change request with the `router-store` team.

**Comment by rickvandermey** [comment]
I don't know if my issue is related. but updating store-devtools to 5.2.0 from 5.1.0 makes the application crash. not using the custom router state serializer. Will try to implement that first

**Comment by felipealfonsog** [comment]
I wrote this, on my code and it worked fine. ..
```
var store = redux.createStore(reducer, redux.compose(
    redux.applyMiddleware(),
    window.devToolsExtension ? window.devToolsExtension() : f => f
));
```

**Comment by Pringels** [comment]
@felipealfonsog the bug is specific to `ngrx` (RxJS redux clone for Angular2+) and how its router module behaves.

In fact we should probably close this issue and open one against `@ngrx/router-store` :)

**Comment by tolvaly** [comment]
I use it for Angular 6 project, after I open the web page devtool is crashing after approx. 1 minute. I want to mention the fact I don't user route store at all.

Environment:
@angular/core: 6.0.7
@ngrx/store: 6.0.1
@ngrx/store-devtools: 6.0.1
dev-tool extension: 2.15.2
browser: Chrome 67.0.3396.99

Does dev-tools extension have a file/storage where we have logs or crash report?

**Comment by zalmoxisus** [comment]
Closing in favour of #314
