### ISSUE TITLE
Extension settings page "Limit action history" setting has no effect.

### ISSUE THREAD

**Issue by kj800x** [zalmoxisus/redux-devtools-extension#480]
It appears that updating the "Limit the action history" option in the extension settings has no effect.

<img width="603" alt="a55208aa-381a-11e8-82c7-33568a97d66b" src="https://user-images.githubusercontent.com/1657142/38330077-a7f6bfd0-381d-11e8-84d3-0bee15bb789a.png">

Even with this set I'm seeing only 50 actions in my redux devtools.

**Comment by puradox** [comment]
I am also experiencing this bug on `v2.15.2`. What is the status of this issue?

**Comment by puradox** [comment]
Ops! I did not read the text in red; the options panel is being phased out in favor of specifying parameters to `__REDUX_DEVTOOLS_EXTENSION__` or `__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`. 

Refer to the [`maxAge` parameter](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#maxage) to set the action history.

**Comment by zalmoxisus** [comment]
It's fixed in `2.16`, which will land in a day on Chrome Store, but as recommended you should provide them in arguments instead.
