### ISSUE TITLE
Does this support Node.js debugging with `--inspect`?

### ISSUE THREAD

**Issue by Sawtaytoes** [zalmoxisus/redux-devtools-extension#483]
When doing Node.js debugging with `--inspect`, the Redux devtools show up in Chrome, but I'm unable to see the debug Redux in there.

I'm using Redux for a server-side application and want some way of debugging that's different than a bunch of random breakpoints and `console.log`s.

**Comment by jhen0409** [comment]
#181 was a discussion for this.
