### ISSUE TITLE
Using redux-devtools results in a multiple the action call

### ISSUE THREAD

**Issue by budarin** [zalmoxisus/redux-devtools-extension#484]
If I use redux-devtools as described in "1.2 Advanced store setup" - I have some extra calls of dispatch - the number of repetitions of calls of the same action increases during the time.

**Comment by quangv** [comment]
similar thing is happening to me. When I _persist_ or _import_, when i do a new action, it seems to run the old action...

**Comment by CodeJjang** [comment]
Same. Does anyone maintain this repo?

**Comment by zalmoxisus** [comment]
It would be helpful if someone can provide steps to reproduce with [our example](https://github.com/zalmoxisus/redux-devtools-extension#demo) or providing their example code. Feel free to reopen the issue with more details if it still relevant.
