### ISSUE TITLE
Question/FYI - Chrome Automatically Disabling Redux DevTools Extension

### ISSUE THREAD

**Issue by lenards** [zalmoxisus/redux-devtools-extension#485]
I thought I'd note this as a "for your information", or something that might be effecting Windows 10 developers. (_I'm not sure if you know about it ... _)

I was looking to open Redux DevTools and it was missing from my DevTools tab bar. 

When I tried to re-install it from the Chrome Web Store, I noticed that Chrome had automatically disable it (see in details). And checking the DevTools Console showed [a bunch of errors related](https://gist.github.com/lenards/1ae54258706bcb460fceb04690d49b88) to the Chrome Web Store profile for the extension. 

Platform: Windows 10
Chrome: Version 65.0.3325.181 (Official Build) (64-bit)

And, thank you for all the work on this. I really appreciate it. 🙇 

<details>

## Disabled notification "toast" message

![redux-devtools-extension-disabled](https://user-images.githubusercontent.com/5923/38579408-c22202b4-3cbb-11e8-8047-254044a62851.png)

## Errors noted in DevTools Console

Raw text version for the errors here:
https://gist.github.com/lenards/1ae54258706bcb460fceb04690d49b88

![redux-devtools-extension-disabled-console-output](https://user-images.githubusercontent.com/5923/38579417-c7d10408-3cbb-11e8-8ca6-32212e3986c3.png)

</details>

**Comment by lenards** [comment]
Am I the only one hitting this?

**Comment by lenards** [comment]
I'm guessing from the crickets no one is hitting this. I'm still unsure why Chrome is flagging the extension and then allowing me to re-enable it following a restart of the overall Chrome process. 

Closing.

**Comment by damiangreen** [comment]
Also hitting this on a Mac.. was working only yesterday..

**Comment by lenards** [comment]
Huh. I couldn't find any logging in Chrome about what was happening. I suspected it might be related to leaving a debugging session open for _long_ periods of time that might cause larger and larger growth in memory usage. So it wasn't the extension as much as how I was (mis)using it. I have zero proof for this other than I'd seen the "Tick" heatbeat message the application I'm working on grow quite big.

**Comment by douglasnaphas** [comment]
I am also hitting this on a Mac with Chrome version 75.0.3770.142. Redux DevTools is added to Chrome and was working yesterday, but is disabled today.

**Comment by douglasnaphas** [comment]
I closed all my tabs and quit Chrome and started it again, and the Redux DevTools extension is enabled again.

**Comment by chanlawrencet** [comment]
Same issue just happened with my Mac on Chrome 76.0.3809.100. Restarting did solve the issue, though. @lenards might be right because I had left the inspector open overnight (with network disconnects too).

**Comment by lenards** [comment]
:+1:

**Comment by andrewdingcanada8** [comment]
also hitting this on my mac Chrome

**Comment by RenaldMorino** [comment]
I have been having this issue too lately... I just uninstall the extension and reinstall it just after. But its getting tiresome... I had to do this three times just today... 

For reference, I'm currently using Opera GX.
