### ISSUE TITLE
Ducks structure not supported?

### ISSUE THREAD

**Issue by sgarmendia** [zalmoxisus/redux-devtools-extension#486]
I have an architecture with DUCKS in my app and cannot use the tool because it shows a message saying that it cannot detect a store.

**Comment by jhen0409** [comment]
It depends on using [the extension API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/CreateStore.md), shouldn't be related to Ducks pattern. If you have some issues that not mentioned on docs and issues, please open an another issue.
