### ISSUE TITLE
Adding devtools-extension breaks middleware (ngRedux)

### ISSUE THREAD

**Issue by tcjcodes** [zalmoxisus/redux-devtools-extension#489]
The devTools extension seems to be modifying the arguments that's sent to my app's middleware. If I remove the extension the middleware works as expected.

Devtools logs the actions fine:

![image](https://user-images.githubusercontent.com/14832650/38962360-cd52cba2-4321-11e8-9948-3ba4e2e8a4ec.png)

 and then the middlewares fail to receive the correct arguments:
`store` is undefined, `next` is correct, and the original `action` is always wrapped in a `PERFORM_ACTION`:

![image](https://user-images.githubusercontent.com/14832650/38962313-7edeae28-4321-11e8-8dfa-bc004374b2b1.png)

Below is the ngRedux setup:
```typescript
($ngReduxProvider: ngRedux.INgReduxProvider) => {
      let middlewares = [
          customMiddleware,
      ];
      $ngReduxProvider.createStoreWith(rootReducer, middlewares, [
          window['__REDUX_DEVTOOLS_EXTENSION__'] && window['__REDUX_DEVTOOLS_EXTENSION__']()       
       ]);
};
```

where `customMiddleware` just logs:
```typescript
export const customMiddleware = (store) => (next) => (action) => {
    debugger;
    console.log('action', action);
    next(action);
};
```

I'm not sure if this is an ngRedux's setup is not what DevTools is expecting?

versions:
ng-redux@4.0.3
redux@3.7.2

**Comment by kevinmims** [comment]
Just ran in to this same issue using middleware; dev tools seems to be wrapping actions in a 'PERFORM_ACTION' type, creating 
```
action: { 
  action: {...}, 
  type: 'PERFORM_ACTION',
  ...
}
```  

Modifying the config from:
```
$ngReduxProvider.createStoreWith(HelixReducers, [thunk, middleware], window.__REDUX_DEVTOOLS_EXTENSION__ ? [window.__REDUX_DEVTOOLS_EXTENSION__()] : []);
```
to
```
$ngReduxProvider.createStoreWith(HelixReducers, [thunk, middleware]);
```

fixes the issue and passes the correct structure to the middleware and all is well again??

**Comment by tcjcodes** [comment]
Looks like this is being tracked in ng-redux's repo, closing.
https://github.com/angular-redux/ng-redux/issues/196
