### ISSUE TITLE
Uncaught TypeError. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dahei** [zalmoxisus/redux-devtools-extension#49]
When using the extension I get sometimes (not always) an error while initializing my redux/react app.

When disabling the redux-devtools-extension the error does not appear, so it seems to be related.

![image](https://cloud.githubusercontent.com/assets/2070820/12809714/9685def4-cb21-11e5-9934-2d2d26967ab4.png)

As you can see, the exception is thrown in the `isAllowed()` function, which is part of the extension.

So my guess, is that [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/7d02b91a410274c1495b2ccd774aa2a69053acc0/src/browser/extension/options/syncOptions.js#L62-L64) the `localOptions.urls` are not yet initialized.

**Comment by zalmoxisus** [comment]
Do you use the default configuration or changed something in settings (on the option page)?

**Comment by dahei** [comment]
I would say, I use it "out of the box". Here are my settings (have to split it in 2 shots):

![image](https://cloud.githubusercontent.com/assets/2070820/12810141/8383389e-cb24-11e5-89bc-1d77928a04b0.png)

![image](https://cloud.githubusercontent.com/assets/2070820/12810153/92de7c40-cb24-11e5-978c-5c804e257c2f.png)

**Comment by zalmoxisus** [comment]
Wasn't able to reproduce, but yes, if `chrome.storage.sync` has a delay it will throw there. I'll publish the fixes to Chrome storage a bit later. Thanks for the report!

**Comment by dahei** [comment]
Thank's for the fix! :+1:

**Comment by cmmartti** [comment]
Yes, thank you. I was just about to create a new issue for this error.

If I don't wait a few seconds before refreshing the page it gives this exact error. To be sure, I tested it in one of the [example pages](http://zalmoxisus.github.io/redux-devtools-extension/examples/counter/), which exhibits the same behaviour.

**Comment by zalmoxisus** [comment]
Fixed in `v1.0.0.5`.
