### ISSUE TITLE
TypeScript declarations incompatible with Redux 4.0

### ISSUE THREAD

**Issue by codeaid** [zalmoxisus/redux-devtools-extension#492]
Devtools seem to be broken after updating Redux to v4. I am now getting the following error:

```
/path/to/project/node_modules/redux-devtools-extension/index.d.ts
(1,32): Module '"/path/to/project/node_modules/redux/index"' has no exported member 'GenericStoreEnhancer'.
```

So far I haven't found a way to fix it so ended up uninstalling `redux-devtools-extension` to be able to use the latest version of Redux but, obviously, it would be nice to have the tools working again!

**Comment by mfellner** [comment]
I believe the answer is in this issue https://github.com/reactjs/redux/issues/2740. In the meantime you can "patch" the type declarations by adding your own `redux.d.ts`:

```typescript
import * as redux from 'redux';

declare module 'redux' {
  export type GenericStoreEnhancer = any;
}
```

**Comment by codeaid** [comment]
It looks like `GenericStoreEnhancer` was [removed](https://github.com/reactjs/redux/pull/2773/commits/abfc80493e3e4b1fac510f2951ffb00d28d236b0#diff-b52768974e6bc0faccb7d4b75b162c99L245) and reverted to be `StoreEnhancer<N>`.

Sounds to me like this library does need to be updated after all as I don't think they'll bring the deleted type back.

**Comment by codeaid** [comment]
Pushed a pull request #493 to get this sorted quicker.
