### ISSUE TITLE
Redux 4.0 support?

### ISSUE THREAD

**Issue by alexey-pelykh** [zalmoxisus/redux-devtools-extension#499]
Since release of `redux@4.0.0`, there's a
```
warning " > redux-devtools-extension@2.13.2" has incorrect peer dependency "redux@^3.1.0".
```

Is `redux-devtools-extension` compatible with `redux@4.0.0`?

**Comment by ChristianDavis** [comment]
It is not, the current version 2.15.2 for chrome has an issue with INIT

**Comment by iosdev-republicofapps** [comment]
Hi, is there a fix for this?  It's not clear how to use straight react-native-debugger and I was depending on this for redux debugging ... I use middleware and am not sure how to set things up without `composeWithDevTools`.  :-)

**Comment by victoriafrench** [comment]
I am confused on this issue. I am running both redux@4.0.0 and redux-devtools-extension@2.13.2 without any issues. What is not working? My abbreviated setup looks like this:

```
const compose = composeWithDevTools({});
const middleware = compose(
         responseiveStoreEnhancer,
         applyMiddleware(
                thunk,
                promiseMiddleware(),
                getStateMiddleware
         )
);
export default initialState => (createStore(reducer, initialState || defaultInitialState, middleware));
```

**Comment by iosdev-republicofapps** [comment]
@victoriafrench it's a dependency issue - redux-devtools-extension requires an obsolete version of RN  and React.

**Comment by victoriafrench** [comment]
@iosdev-republicofapps yea I get that, but I have paired the two together and am not seeing an issue unless it is a feature I am not using. But it sees all the dispatched messages and lets me navigate through time etc. So I am asking what is actually broken when the dependency is updated.

**Comment by thomas88** [comment]
@victoriafrench This is right of the top of my head, but maybe it can point in the right direction: I was experiencing issues when upgrading to redux v4 in an app based on react-boilerplate. The app was crashing with redux-devtools-extension when navigating to another page.

**Comment by jhen0409** [comment]
The npm package (v2.13.3) is now supported Redux v4. :)
