### ISSUE TITLE
Add iframe support

### ISSUE THREAD

**Issue by pirelenito** [zalmoxisus/redux-devtools-extension#50]
We have a Redux application that needs to run inside an iframe, but the `window.devToolsExtension` is not being populated in its context. Apparently that is only available at the main window.

**Comment by jhen0409** [comment]
You can refer to the Chrome app/extension approaches, it's the same: https://github.com/zalmoxisus/redux-devtools-extension#how-to-include-it-in-chrome-apps-and-extensions

**Comment by zalmoxisus** [comment]
Yes, it's almost the same approach, but, due to Chrome restrictions, a web-page cannot communicate with the extension directly without specifying the page url in the manifest. I will investigate this.

**Comment by jessedijkstra** [comment]
@pirelenito zalmoxisus just merged a PR enabling the Redux DevTools for iFrames, not sure when he'll release it to the Chrome Web Sote.

**Comment by zalmoxisus** [comment]
Just published `1.0.0.6` to Chrome store, should be available in about an hour and Chrome should autoupdate the extension in few hours. Feel free to reopen the issue if something doesn't work as expected. Thanks again, @jessedijkstra, for the fix!

**Comment by pirelenito** [comment]
It works flawlessly! Thanks!
