### ISSUE TITLE
Chrome panel doesn't show any history until some dispatches

### ISSUE THREAD

**Issue by sp3ber** [zalmoxisus/redux-devtools-extension#505]
When i use advanced api for my flux application, actions in chrome tab updates only when i dispatch them with opened chrome developer tools. So there is no history of my actions 
But the separate window of redux dev tools shows all the history.
https://gyazo.com/8f954ed203dc2c10d0d50d67bcf6b4f7

example for reproducing:
https://github.com/sp3ber/redux_dev_extension_bug_ex

**Comment by zalmoxisus** [comment]
Now with #580 the result in chrome developer tools will be the same as in separate window.

**Comment by sp3ber** [comment]
I've checked - indeed it works ok now!
