### ISSUE TITLE
React.Context support?

### ISSUE THREAD

**Issue by jlaustill** [zalmoxisus/redux-devtools-extension#506]
I searched and couldn't find any reference to React.Context.  Is this on anyone's radar?  If not, where would one begin at writing the extension to work with it?

**Comment by jhen0409** [comment]
The [`window.__REDUX_DEVTOOLS_EXTENSION__.connect`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#connect) API can be make any state management solutions works on Redux DevTools Extension. For example, [react-waterfall](https://github.com/didierfranc/react-waterfall/blob/master/src/helpers/devtools.js) has provided the devtools helper.

**Comment by jlaustill** [comment]
@jhen0409 I was actually able to write an entire plugin for react.context and it works by just placing it under the provider and passing in the state and updating state onChange.  My team is now using it.  I'll close this.

**Comment by pedrosimao** [comment]
@jlaustill Would you share the plugin as Open Source project?

**Comment by jlaustill** [comment]
@pedrosimao it is pretty simple, I could do that.  What would be a fitting name?

**Comment by pedrosimao** [comment]
@jlaustill Great! I am not sure about the name, maybe ReactContextDevTools?

**Comment by jlaustill** [comment]
@pedrosimao I will talk to my boss and see what it takes to get it done!

**Comment by MacKentoch** [comment]
@jlaustill Maybe simply just share (*README PR?*) the way to plug a Context Provider state to `devtools`?

I did not suspect it was even possible. That is really nice news to read 👍

**Comment by MacKentoch** [comment]
Alright example already exists [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/react-counter-messaging/components/Counter.js)

> Just apply it to your Context Provider Component

**Comment by antoniojps** [comment]
Is there any example on how to connect with useReducer?

**Comment by trajano** [comment]
@antoniojps I haven't tried it yet but I saw this article https://reactjsexample.com/use-redux-devtools-to-inspect-usestate-and-usereducer/
