### ISSUE TITLE
chrome extension not connecting to instance

### ISSUE THREAD

**Issue by PerspectivesLab** [zalmoxisus/redux-devtools-extension#510]
hi there, i installed the extension on chrome, and added permission to read local files,
then in code i import the npm package : redux-devtools-extension

`import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';`
then 
`let store = createStore(reducer,  composeWithDevTools( applyMiddleware(  mymiddleware  ) ));`

i launch the app, then enable react native debug tools, then go to redux tab:
No store found. Make sure to follow the instructions.

nb: i got react, redux up to date...

why isnt it working ?

**Comment by qqiao** [comment]
Did you use redux 4? This extension is not compatible with 4 yet.

**Comment by PerspectivesLab** [comment]
im using "redux": "3.7.2", im also using redux persist.... maybe this would be the issue ?

**Comment by 1oginov** [comment]
Same here, using Redux v4. Temporary workaround is to push back and use `compose` from `redux` instead of `composeWithDevTools `.

**Comment by zalmoxisus** [comment]
Feel free to reopen the issue if the issue still persists.
