### ISSUE TITLE
Setting Options while calling window.__REDUX_DEVTOOLS_EXTENSION__(reducer)

### ISSUE THREAD

**Issue by joshburgess** [zalmoxisus/redux-devtools-extension#512]
So, I just recently discovered this article: https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f

This details how to create a Redux store right from the extension, which makes syncing with the devtools from non-Redux apps much easier than directly communicating with it and re-implementing all of its functionality.

However, I can't seem to figure out how to do this AND pass it options that influence the devtools extension at the same time. Is this possible?

For example, I'd like be able to pass it a reducer and `{ name: "Some Instance Name" }` so that I can do this on a per component basis, where each component has its own instance name & the instances are shown in the devtools instance drop down to make it easier to navigate.

The first bullet point here https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#options suggests that you can also directly pass this function an Options object, but I'm not sure whether or not that's correct. Is this still true?

If it is true, is it possible to both pass the devtools an options object AND create a store by passing it a reducer without using `window.__REDUX_DEVTOOLS_EXTENSION__.connect` & manually implementing everything?

If this isn't currently possible, I imagine it wouldn't be too difficult to allow, as I saw that passing it the reducer multiple times will create new instances as expected... They just all use `document.title` for the instance name.

**Comment by zalmoxisus** [comment]
Yes, it is possible to pass config argument to `window.__REDUX_DEVTOOLS_EXTENSION__.connect`. That should be better documented, but I didn't see much interest in using that API, was more an experiment.
