### ISSUE TITLE
it's crashed when I try to see a ref via redux-devtools-extention

### ISSUE THREAD

**Issue by dbjina** [zalmoxisus/redux-devtools-extension#513]
I stored two refs of my components to the store. 

The chrome dev tool was crashed  when I tried to see the refs via redux-devtools-extention.

**Comment by zalmoxisus** [comment]
Should be fixed in last version as per https://github.com/kolodny/jsan/issues/13. Feel free to reopen the issue if it's still relevant.

**Comment by ryan-olejnik** [comment]
I am having the same issue using redux-devtools version 2.17.0

It only seems to crash when I store a second ref in the store, the first one works fine.

**Comment by zoffyzhang** [comment]
same crash here, but I don't think the redux-devtools-extention should try to show any message inside  

the DOM, show something like "HTMLElement" would be just fine.
