### ISSUE TITLE
Remember extension UI state (Suggestion)

### ISSUE THREAD

**Issue by vkbr** [zalmoxisus/redux-devtools-extension#516]
Hello

I would like to persist the state of the tabs (Action/State/Diff/Test).

Every time you open the devtool or refreshes the page, the tabs are reset to "Diff". It would be better if we could persist the tab state.

I can also do this if someone provides me some hint (where to start).

**Comment by zalmoxisus** [comment]
Thanks for the heads up! Hope to fix remaining critical issues and move to it. Let's keep this discussion in #577.
