### ISSUE TITLE
"undefined is not a function" error

### ISSUE THREAD

**Issue by gaillota** [zalmoxisus/redux-devtools-extension#517]
Hi,
I recently encountered this error in my Redux Devtools:

<img width="240" alt="screen shot 2018-06-06 at 11 43 37" src="https://user-images.githubusercontent.com/6444106/41030978-d95cb442-697f-11e8-973c-60afe2c4a28e.png">

Is something wrong with my project, or is it an error on the Devtools side ? I never encountered this error before, and I don't know if the Devtools have been updated lately or it's just my project that trigger this error (although I can't see how)

Thank you for your help.
Antoine.

**Comment by zalmoxisus** [comment]
If you're still experiencing that, an example to reproduce that would help.

Closing as nobody reported same issue, feel free to reopen with more details.

**Comment by jcready** [comment]
I'm also having this issue, please re-open.
