### ISSUE TITLE
2.13.3: Generic type 'StoreEnhancer' requires 1 type argument(s)

### ISSUE THREAD

**Issue by himdel** [zalmoxisus/redux-devtools-extension#519]
With 2.13.3, I'm getting this error during webpack:

```
ERROR in [at-loader] ./node_modules/redux-devtools-extension/index.d.ts:159:60 
    TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/redux-devtools-extension/index.d.ts:161:61 
    TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).
```

With 2.13.2, this does not happen.

(Looks like 2.13.3 is not mentioned in releases, so not sure where that's coming from...)

**Comment by himdel** [comment]
(full diff between non-working `yarn.lock` and a working one:

```diff
7423,7425c7423,7425
< redux-devtools-extension@~2.13.2:
<   version "2.13.3"
<   resolved "https://registry.yarnpkg.com/redux-devtools-extension/-/redux-devtools-extension-2.13.3.tgz#a75e9a7288c4849424974ae41b57ad9762ddb0c8"
---
> redux-devtools-extension@2.13.2:
>   version "2.13.2"
>   resolved "https://registry.yarnpkg.com/redux-devtools-extension/-/redux-devtools-extension-2.13.2.tgz#e0f9a8e8dfca7c17be92c7124958a3b94eb2911d"
```
)

**Comment by jhen0409** [comment]
That was changed by https://github.com/zalmoxisus/redux-devtools-extension/commit/658f2f0634dd453efc6cf3b76be97433f1ea3331, it would be better to make the argument optional.

**Comment by jhen0409** [comment]
It should be fixed in #520, published as `v2.13.4`. Feel free to reopen the issue if it still not working.

**Comment by zsgalusz** [comment]
Did something go wrong with the publish? v2.13.4 still installs the wrong type definitions...

**Comment by himdel** [comment]
Indeed, getting the same error with 2.13.4.

@jhen0409 Seems like I can't re-open the issue, can you please? :)

**Comment by jhen0409** [comment]
Sorry I did wrong for publish 🙈, `v2.13.5` should be the new type definitions.

**Comment by ZitaNemeckova** [comment]
Confirming that `v2.13.5` is working :)
