### ISSUE TITLE
Remote devtools pushed to devtools extension?

### ISSUE THREAD

**Issue by chrbala** [zalmoxisus/redux-devtools-extension#52]
It seems like the extension on the Chrome store got mixed up and now uses Remote devtools, which doesn't seem to work for browser apps.

**Comment by zalmoxisus** [comment]
Hey @chrbala,

Just checked, the extension works as expected. You may test it with [our counter example](http://zalmoxisus.github.io/redux-devtools-extension/examples/counter/).

Probably you use the shortcut corresponding to [Remote devtools](https://github.com/zalmoxisus/redux-devtools-extension#keyboard-shortcuts)?

**Comment by chrbala** [comment]
Ah, it looks like Redux Devtools is there and can be accessed with the shortcut. But when I open it like this...
1. Right click on icon in URL bar
2. Open in panel

It defaults to the remote tools and is not clear on how to switch back to the normal devtools. The default used to be the normal devtools, and I don't see a way of easily opening the panel to the normal devtools anymore.

**Comment by zalmoxisus** [comment]
Yes, I just forgot to rename it in the menu. I noticed that there wasn't much interest using the panel and since it is experimental feature of Chrome, decided to nuke it. But if you found it useful, I may bring it back to the context menu.

**Comment by chrbala** [comment]
Ah, yes, that's the way I preferred to use the extension. Thanks!

**Comment by zalmoxisus** [comment]
OK, will get it back then. It's a neat feature, sadly it remains just experimental.

**Comment by chrbala** [comment]
Yeah. That was always the one big benefit of Firefox - they had a lot more customization options as far as panels go.

**Comment by zalmoxisus** [comment]
Added back in `v1.0.0.5`.
