### ISSUE TITLE
Can I use redux-devtools with incognito mode in Chrome?

### ISSUE THREAD

**Issue by ismayilmalik** [zalmoxisus/redux-devtools-extension#521]
Seems all additional extensions are hidden in incognito mode.

**Comment by bowl-of-petunias** [comment]
You can enable specific extensions for incognito mode in the settings (Additional Tools > Extensions > The extension you want > Details).

**Comment by ismayilmalik** [comment]
Yep, that works. Thanks!

**Comment by aaronbeall** [comment]
I did this but now Chrome *only* shows the tools in Incognito... is that how its supposed to work??

**Comment by ismayilmalik** [comment]
> I did this but now Chrome _only_ shows the tools in Incognito, in a regular window they aren't there... is that how its supposed to work?? The same behavior happens with React dev tools.

No, It should work in both mode. In incognito only those extensions which you enabled will be available.
