### ISSUE TITLE
HMR does not works in redux v4

### ISSUE THREAD

**Issue by krailler** [zalmoxisus/redux-devtools-extension#522]
Hi, the hot reload is not working when i upgrade to v4...

**Comment by ChristianDavis** [comment]
This issue was closed recently, but I haven't seen a release for it in the chrome store
https://github.com/zalmoxisus/redux-devtools-extension/issues/499#issuecomment-398785094

**Comment by toranb** [comment]
Anyone know who to contact for a chrome store publish of this extension?

**Comment by ChristianDavis** [comment]
@toranb , @jhen0409 mentioned a release in this PR, but I don't know if there is a clear route to release yet. There are a lot of moving parts ATM https://github.com/zalmoxisus/redux-devtools-extension/pull/490

**Comment by jhen0409** [comment]
It should be fixed by #490 and #533. I've published the new version of Chrome Extension. If you're using Firefox please waiting for @zalmoxisus because I have no permission to do that.
