### ISSUE TITLE
Export from browser console

### ISSUE THREAD

**Issue by shayAlaluf** [zalmoxisus/redux-devtools-extension#523]
hi,
I am running automation tetst.
In case there was a bug i want the option to get your exported file from browser console (i cunt open the devtools extension withe automation)
in order to revert my store state.
I couldn't find any way to do so.

**Comment by zalmoxisus** [comment]
Sorry for the late response, you can do that with `store.liftedStore.getState()`. That was shared in other issues, but we also should add in recipes.
