### ISSUE TITLE
Can I block some actions to display?

### ISSUE THREAD

**Issue by rupav** [zalmoxisus/redux-devtools-extension#528]
There are actions which get fired up frequently and I need to scroll to see if the actions I wanted to see get fired up. There is a filter option, which lets me find which ACTION type I am looking for. But is there a way to ignore some ACTION types from displaying.

**Comment by NetanelBasal** [comment]
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsblacklist--actionswhitelist

**Comment by rupav** [comment]
Thanks... Will try it. I was thinking if this should be in the dev-tools directly as a part of UI. Closing this now.
