### ISSUE TITLE
Hot Module Replacment of Reducers Does Not Cause Actions To Be Re-Fired

### ISSUE THREAD

**Issue by ohearonkg** [zalmoxisus/redux-devtools-extension#531]
When I update my reducers I can see that hey are hot reloaded, however the actions which I have previously dispatched and are visible within the Redux Dev Tools are not re-run. 

Chrome Extension: 2.5.12
Redux: 4.0.0

Code:
https://github.com/ohearonkg/redux-lessons/tree/Hot_Module_Replacement

**Comment by ohearonkg** [comment]
@zalmoxisus ?

**Comment by jhen0409** [comment]
It should be fixed by #490 and #533. I've published the new version of Chrome Extension. If you're using Firefox please waiting for @zalmoxisus because I have no permission to do that.
