### ISSUE TITLE
"No store found" no matter which method I have installed.

### ISSUE THREAD

**Issue by chaintng** [zalmoxisus/redux-devtools-extension#532]
Hi team, I'm not sure if there any bug in it.
But I bootstrap project with `create-react-app`
and follow the instruction throughly.

However, in chrome extension, it's always showing "No store found"

Here is my source code https://github.com/chaintng/cra-redux-dev-tools
It's very simple application

and i use `composeWithDevTools` function
https://github.com/chaintng/cra-redux-dev-tools/blob/master/src/store.js#L17

Could you please advise?

**Comment by BSanass** [comment]
I have the same probleme :(

**Comment by zalmoxisus** [comment]
Thanks for the example, it works now in `2.16`, could be the same issue as in #547
