### ISSUE TITLE
extension hard-codes use of redux "createStore" instead of using the one passed in

### ISSUE THREAD

**Issue by cellog** [zalmoxisus/redux-devtools-extension#536]
This means you can't use it directly with a custom redux-compatible createStore, as it fails to properly initialize.

**Comment by zalmoxisus** [comment]
It would be useful to provide and example to look into. The extension doesn't provide a `createStore`, but a `compose` helper for this reason. You might also look through the logic in [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js). Closing as no messages here for long time, feel free to reopen with more details.
