### ISSUE TITLE
Extension suddenly completely broken

### ISSUE THREAD

**Issue by bkilrain** [zalmoxisus/redux-devtools-extension#537]
About 3 days ago, I noticed the extension behaving very glitchy. 
* The logger component on the left records only the first handful (20-30) of actions my webapp dispatches on init and then stops recording anymore
* Sometimes the logger doesn't event show
* The state view either shows a blanks state or works as expected

I made no changes to anything related to middleware, store enhancers, or store creation logic. It just suddenly stopped working. I noticed there was an update to the extension on July 18th (as reported in the chrome store). Perhaps it is related...

Multiple engineers in my company report seeing the same issues.

Thanks for looking into this.

**Comment by jhen0409** [comment]
Could you make some examples for reproduce it? Thanks!

You can also try to build extension with [the commit](https://github.com/zalmoxisus/redux-devtools-extension/commit/8b3a15db7dd8c819680023621456d63b35ff0bfe) of previous version. I think the new version shouldn't much impact on it.

**Comment by zalmoxisus** [comment]
Closing in favour of #566. I'll add in next version a fix to split the serialized state into batches.
