### ISSUE TITLE
Getting original action in the subscribe callback

### ISSUE THREAD

**Issue by yysun** [zalmoxisus/redux-devtools-extension#538]
I sent to action and state to the monitor.
```JavaScript
devtools.send({type:'a1', payload:{a:1}}, {})
``` 
When click the jump button of the action in the monitor, I couldn't find the original action from the message parameter of the subscribe callback.

Is there a way to get the original action back in the subscribe callback?

**Comment by zalmoxisus** [comment]
You should get the original action as payload in the subscribe callback, see https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/monitorActions.js#L64 as an example.

**Comment by yysun** [comment]
> You should get the original action as payload in the subscribe callback, see https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/monitorActions.js#L64 as an example.

The example you have provided is to retrieve the original state, but I am looking for the original action.

I found the object in message.payload to be something like l {type: "JUMP_TO_ACTION", actionId: 1}, not the original action.

Is it possible to have a message.action property to the subscribe callback?
