### ISSUE TITLE
[typescript] Store & Dispatch are now typed as `any` after using `composeWithDevTools`

### ISSUE THREAD

**Issue by scally** [zalmoxisus/redux-devtools-extension#539]
I am trying to use `composeWithDevTools` like this:

```
composeWithDevTools(
    applyMiddleware(
      thunks as ThunkMiddleware<AppState, Action>
    ),
  ),
```

What I've found is that since the 2.13.5 publish of this repo to NPM, I now see my `store` instance & `store.dispatch` are typed as `any`.

I suspect this is because `StoreEnhancer<any>` introduced in @jhen0409 's PR here: https://github.com/zalmoxisus/redux-devtools-extension/pull/520

I've been able to work around this by creating a new inline typing like this:

```
import { StoreEnhancer } from 'redux'

declare module 'redux-devtools-extension' {
  export function composeWithDevTools<StoreExt, StateExt>(
    ...funcs: Array<StoreEnhancer<StoreExt, StateExt>>
  ): StoreEnhancer<StoreExt, StateExt>
}
```

Redux 4.0.x
Redux-Thunk 2.3.x
Redux-devtools-extension 2.13.5

**Comment by zalmoxisus** [comment]
Would changing it from `<any>` to `<any, any>` fix the issue? Would you like to submit a pr fixing it?

**Comment by scally** [comment]
I think `<any, any>` would still cause anything consuming the result of the function to lose its typings.

PR up here: https://github.com/zalmoxisus/redux-devtools-extension/pull/578

**Comment by scally** [comment]
FWIW, I hadn't submitted a PR previously because I'm not 100% sure this is the best or most comprehensive solution to the problem, was hoping I could get some feedback from other Typescript folks first. It does fix my usage though.
