### ISSUE TITLE
regression in updated jsan version

### ISSUE THREAD

**Issue by minedeljkovic** [zalmoxisus/redux-devtools-extension#540]
Parsing during import, which uses custom reviver as well as `jsan` builtin types, stopped working as of 2.15.3 because of [https://github.com/kolodny/jsan/issues/24](https://github.com/kolodny/jsan/issues/24)

**Comment by minedeljkovic** [comment]
This is [fixed](https://github.com/kolodny/jsan/issues/24#issuecomment-435678002) in `jsan@3.1.11`

**Comment by zalmoxisus** [comment]
Thanks for working on that @minedeljkovic! I published `2.15.4` on Chrome Store now and should be available in an hour. Firefox extension published few days ago already includes this update.

**Comment by zalmoxisus** [comment]
Looks like it's not fixed.

**Comment by zalmoxisus** [comment]
Fixed in https://github.com/kolodny/jsan/pull/26.
