### ISSUE TITLE
Cannot install extension on Chrome 65.0.3325.181

### ISSUE THREAD

**Issue by amagee** [zalmoxisus/redux-devtools-extension#541]
After being able to use the extension without issue for some time, a new version of Chrome came around and it stopped working. I don't remember the precise details of that, but it led me to try removing the extension to see if reinstalling it would work. Now when I try to install the extension, the installation page just hangs on "CHECKING..." and the entire browser becomes unresponsive and I have to kill everything. I'm no longer able to install the extension at all.

Chrome: Version 65.0.3325.181 (Official Build) (64-bit)
Ubuntu 17.10

![selection_070](https://user-images.githubusercontent.com/1762255/43239018-fceff4e8-90d3-11e8-867e-c01b598acf7e.png)

**Comment by zalmoxisus** [comment]
Is the problem still persisting in the latest versions of the extension and Chrome? It was working with reinstalling other extensions?

**Comment by zalmoxisus** [comment]
Closing as a lot was changed on both sides. Feel free to reopen if you experience that again.
