### ISSUE TITLE
Message length exceeded maximum allowed length

### ISSUE THREAD

**Issue by mbtts** [zalmoxisus/redux-devtools-extension#543]
I am seeing this error (“Message length exceeded maximum allowed length”) when the panel is initialising in Chrome.

There are similar issues posted for other plugins:

- [Spector.js](https://github.com/BabylonJS/Spector.js/issues/69)
- [vue-devtools](https://github.com/vuejs/vue-devtools/issues/515)

<img width="1262" alt="message length exceeded maximum allowed length" src="https://user-images.githubusercontent.com/7728605/43519154-32312cf6-9586-11e8-87ee-935afc1c6641.png">

It does work in Firefox.

Chrome version: 68.0.3440.75
Redux Dev Tools version: 2.15.3

**Comment by go-sk** [comment]
me too

**Comment by mbtts** [comment]
If possible the workaround is to try and reduce the size of your store, either by [normalizing it](https://redux.js.org/recipes/structuringreducers/normalizingstateshape) or only storing a ref/key in the store and keeping the large objects in another state variable outside of redux.

The second is more dramatic and maybe not even possible depending on your use case.

I guess the long term fix is to do what the spector author did and [split the messages up into chunks and re- assemble on the other side](https://github.com/kenrussell/Spector.js/commit/ba97116adf5acfcedfb5862e64fd89e81920c5ec).

**Comment by zalmoxisus** [comment]
Thanks for the details and offered solutions! We could go with splitting the messages in future, but there's a reason why Chrome imposed this limit in last versions. Having large states will make the extension slow and will freeze/crash at some point. So not sure we should support that.

I added a warning with [the link](https://git.io/fpcP5) on how to use sanitizers to fix that in case the message has more than 16 MB. Open for discussions if someone still thinks we should support that.

**Comment by zalmoxisus** [comment]
I added splitting messages in #582.`2.16` should land in a day on Chrome Store. Thanks again for investigating this!
