### ISSUE TITLE
[Feature Request] Exclude url settings

### ISSUE THREAD

**Issue by mikdatdogru** [zalmoxisus/redux-devtools-extension#544]
need to exclude URLs we want in chrome redux-devtools-extension settings like image of bottom.

**for example:** 
while open the swagger and my project in different tabs on the same chrome window, 
the redux screen does not know which one to shown

> (so "very thank you" for the swagger they did not closed redux devtool in production!!)

I am trying to resolve this problem by excluding the swagger's page URL

when I open every window, selecting instance will return to after a while it is tortured

![image](https://user-images.githubusercontent.com/10121255/43521476-0b163fc6-959f-11e8-9c9c-dc05c77f3068.png)

**Comment by zalmoxisus** [comment]
There was an issue with injecting option from option page and `Allow to run` has no effect. I fixed that in`2.16`. You can exclude an url adding it there like so:
```
^(?!https?://url).*$
```

**Comment by mikdatdogru** [comment]
@zalmoxisus it's working. thank you for support
