### ISSUE TITLE
Latest Chrome not serializing action types

### ISSUE THREAD

**Issue by sillero** [zalmoxisus/redux-devtools-extension#548]
Tried all the options for serialization. It's broken for more than a month I think.

Top is Chrome, bottom is Firefox
![image](https://user-images.githubusercontent.com/628355/44274076-3c057580-a20f-11e8-9adf-2e4d8ef05a41.png)

**Comment by zalmoxisus** [comment]
It was a regression on JSAN part. It was downgraded and it should be fixed in `2.16`, which will land in a day on Chrome Store.
