### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pedrosimao** [zalmoxisus/redux-devtools-extension#551]
I was using redux devtools extensions without any problem and suddenly I am not able to do it anymore.
My app freezes after opening and after I wait like 30s I receive this message: Uncaught RangeError: Maximum call stack size exceeded
I think I haven't done anything out of the ordinary with my store and reducers.
I think there might be a compatibility issue with Realm db, but I am not sure.
I have tried changing many things in my code but I still have no clue about what causes the issue.
For the moment I am obliged to completely suppress the devtools extension from my app, which makes debugging much longer.

**Comment by zalmoxisus** [comment]
Should be fixed in last version as per https://github.com/kolodny/jsan/issues/13. Feel free to reopen the issue if it's still relevant.
