### ISSUE TITLE
@@INIT action resets the state of the app

### ISSUE THREAD

**Issue by cnexans** [zalmoxisus/redux-devtools-extension#552]
Hello, well first of all I've been using this tool for a while now and it's been really useful so thank to all developers giving a hand on this project.

I have a source code that uses React, Redux and Redux Observable, and it has this flow:

App renders a component that initializes the state of the app, so that <InitializeApp data={data}/>, so that when this component is mount it dispatches an action that "initializes" the state. This is almost the same as just fetching data inside componentDidMount and dispatching something.

Then, the project fires some other actions in consequence. The log would look like this

```
REDUX_INIT
REDUX_PROVE_UNKNOWN
InitializeState
CustomAction
CustomAction2
```

But when the configure store is injected with the compose, the log looks right and it flickers to an @@INIT action, other actions dissapear and the state of the app is the default state in reducers. This doesn't happen when I have the extension closed.

I don't know if this is intended and therefore, in some way, the side effects should be adjusted. Any help would be well appreciated

**Comment by nik-john** [comment]
@cnexans Did you figure out why this was happening? I'm facing the same issue

**Comment by petervavro** [comment]
The same here.

**Comment by petervavro** [comment]
Wow, I spent quite a while by solving the issue, I guess I found it. Simply, add : `latency: 0` to your options. [More about options here.](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#latency)

I think it has something to do with machine performance. I am experiencing this issue on all high performance computers.

**Comment by zalmoxisus** [comment]
@@INIT action is used internally when the application is hot reloaded. So if that is the issue, setting [`shouldRecordChanges`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#shouldrecordchanges) to `false` should help. See #351.
