### ISSUE TITLE
[Feature] Add LogMonitor Buttons to Inspector.

### ISSUE THREAD

**Issue by Industrial** [zalmoxisus/redux-devtools-extension#555]
It took me a week to find out that in the topleft dropdown there is `Inspector`, `Log` `Monitor` and `Chart`. The `Inspector` **ONLY** has the buttons `Sweep` and `Commit` and does not have the `Reset` button.

The `LogMonitor` does have **ALL** of the buttons.

I could not reset my devtools state. This was a real problem for me and I ended up uninstalling the extensions because I could not continue my work.

Please add the Reset button to the `Inspector`. Thanks a lot.

**Comment by zalmoxisus** [comment]
Buttons will be moved out of monitors in the new ui and be available regardless of the selected monitor.

**Comment by Industrial** [comment]
Sorry, closed by accident. I was mass-cleaning my tickets.
