### ISSUE TITLE
composeWithDevTools: Infinite recursion when used with enhanced getState

### ISSUE THREAD

**Issue by danhart** [zalmoxisus/redux-devtools-extension#556]
Here's a very basic, valid, store enhancer that essentially wraps the store's original `getState` in a new `getState` function:

```JS
const basicStoreEnhancer = (createStore) => (...args) => {
  const store = createStore(...args);

  return {
    ...store,
    getState: () => store.getState(),
  };
};
```

When used with Redux's `compose`, this enhancer works perfectly with no impact at all. However, when used within a `composeWithDevTools`, it results in a `RangeError: Maximum call stack size exceeded`.

This is because of this line, which mutates the store causing our `getState` call to become infinitely recursive:
https://github.com/zalmoxisus/redux-devtools-extension/blob/dc39a63648c34b55ffcc5c9a606b5cdcb6540f4a/src/browser/extension/inject/pageScript.js#L310

It's possible to work around the issue like this:
```JS
const basicStoreEnhancer = (createStore) => (...args) => {
  const store = createStore(...args);
  const originalGetState = store.getState;

  return {
    ...store,
    getState: () => originalGetState(),
  };
};
```

These issues seem relevant:
https://github.com/zalmoxisus/redux-devtools-extension/issues/248
https://github.com/zalmoxisus/redux-devtools-extension/issues/551

**Comment by zalmoxisus** [comment]
Thanks for the details and for investigation! That mutation was introduced for enhancers which change the store after our enhancer was applied (as in #133). But I tried now with saga example and it seems unnecessary now, a lot was changed since then.

**Comment by zalmoxisus** [comment]
It should work in `2.16`, which will land in a day on Chrome Store. Thanks again for debugging it!
