### ISSUE TITLE
Redux devtools may crash with "browser is not defined" error

### ISSUE THREAD

**Issue by hajdun** [zalmoxisus/redux-devtools-extension#563]
Redux devtools may crash with "browser is not defined" error AND kill the app itself if "pause on caught exception" is set in developer  tools of Chrome.
I need that setting for developer purposes.

The app is using  Next.js  (Server-side rendering)
  "next": "^5.1.0",
 "react": "^16.3.1",
  "redux": "^4.0.0",

Redux devtools
2.15.3

Chrome
Version 70.0.3538.67 (Official Build) (64-bit)

Error source: webpack:///./node_modules/invariant/browser.js?72b5 and / or  polyfill.js
function shouldWrapAPIs()
    try    {      return !(browser.storage.local.get([]) instanceof Promise);    }
    catch (error)    {    }

Can you please handle it in a more next.js -friendly way?
Or advise on how should I handle it?

**Comment by zalmoxisus** [comment]
I'm not sure I understand the issue, but it should be excluded on server side rendering, some examples can be found in https://github.com/zeit/next.js/issues/698. Feel free to reopen if you have more questions.
