### ISSUE TITLE
Chrome extension stops listing actions - update to chrome 70

### ISSUE THREAD

**Issue by avilao** [zalmoxisus/redux-devtools-extension#566]
After listing about 10 actions nothing else happens. Issue started happening after upgrading to Chrome 70.

**Comment by AmyScript** [comment]
Having this issue too but it's after listing > 10 actions.  It always get stuck at the same spot and no longer displays dispatched actions and the updated state.  Verified that the code and state is working from logging out the redux state.

**Comment by avilao** [comment]
Yes, still happening to me also :(

**Comment by zalmoxisus** [comment]
Cannot reproduce the issue. Tried in Chrome 70.0.3538.102 (Official Build) (64-bit) and in 72.0.3611.0 (Official Build) canary (64-bit).

Tried in both ways:
1. First open http://zalmoxisus.github.io/examples/counter/, click `Auto increment` then open extension's devpanel.
2. First open devtools then click `Auto increment`.

By default it should be limited to 50 actions, but that can be increased/decreased as [specified in the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#maxage).

Please check my example and if possible provide an example to reproduce.

**Comment by avilao** [comment]
It has nothing to do with the action limit I guess. From what I have been able to dig it might have something to do with the size of the message. The extensions seems to stop working after throwing this error message:

```
Failed to send message Error: Message length exceeded maximum allowed length.
```

My app did not change. Maybe the limit of the sendMessage msg size has been reduced?

**Comment by zalmoxisus** [comment]
Thanks for debugging it. Seems that Chrome added a limit on sent message to 32MB. The state over time increases and as soon as it reaches that limit isn't able to send updates, so the data on monitor remains unchanged.

I'll think on the solution, probably we'll have to split messages into chunks. However, the fact that it is serializing more than 32MB isn't good, it will affect the app performance significantly and if continues to increase, at some point, it will freeze. A recommended approach is to strip some not necessary data using [actionSanitizer / stateSanitizer](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer).

**Comment by avilao** [comment]
I would favor splitting the messages. Even though 32mb seems much, I don't think it's that much of a size for complex apps. 

At least in my case, the extension never broke even if the state got big. But I see your point, if someone is careless about the state management then the app will probably crash somewhere on the way.

**Comment by zalmoxisus** [comment]
I added splitting messages in #582. It should work in`2.16`, which will land in a day on Chrome Store. Thanks again for all the details!
