### ISSUE TITLE
Firefox extension breaks JS on some websites.

### ISSUE THREAD

**Issue by urkle** [zalmoxisus/redux-devtools-extension#567]
Specifically in this case Woopra breaks when I have the redux devtools extension enabled and trying to use their "new" interface (written in react/redux).

URL of issue:  https://app.woopra.com/login
Browser: Firefox 62
Extension version: 2.15.3

What happens:
When the extension is enabled a blank page is rendered and the browser JS error console shows that there was an error in a reducer.

![image](https://user-images.githubusercontent.com/101123/47523916-39ef1100-d867-11e8-9584-183579bbaf2d.png)

What should happen:
the web site login page should show up. (which when disabling the extension does show up).

![image](https://user-images.githubusercontent.com/101123/47524006-6e62cd00-d867-11e8-8677-5b9709576ae5.png)

**Comment by alicanerdogan** [comment]
The same problem is also occurring on the production build of the project we are working on. We are using dynamic imports for also dynamically adding specific reducers and middlewares on the go. It looks like that logic is somehow broken, but could not find any leads yet.

url: www.zalon.de/style
Browser: Firefox 63
Extension version: 2.15.3

**Comment by ferfabricio** [comment]
Same here

Browser: Firefox 63.0.1
Extension version: 2.13.1 (last available in add-ons page)

**Comment by hdwilber** [comment]
Same issue:
Brower: Firefox 63.0.1
Ext version: 2.13.1 (last available)
I got this error: `TypeError: e[n] is undefined`. The error varies among applications.

**Comment by frankcalise** [comment]
> 
> 
> Same issue:
> Brower: Firefox 63.0.1
> Ext version: 2.13.1 (last available)
> I got this error: `TypeError: e[n] is undefined`. The error varies among applications.

I get this same error in my application as well.

**Comment by ljayz** [comment]
> Same issue:
> Brower: Firefox 63.0.1
> Ext version: 2.13.1 (last available)
> I got this error: `TypeError: e[n] is undefined`. The error varies among applications.

I get the same error as well. Error occur when using react-redux

**Comment by zalmoxisus** [comment]
Last version was removed and downgraded for some reason. New version should be reviewed and hope accepted soon. Thanks for reporting, let's track the issue in #573.

If you can reproduce it in the last version by [building the extension](https://github.com/zalmoxisus/redux-devtools-extension#2-for-firefox), feel free to reopen.
