### ISSUE TITLE
Firefox Add-on page: Sorry, but we can't find anything at the address you entered.

### ISSUE THREAD

**Issue by mcchrish** [zalmoxisus/redux-devtools-extension#568]
Visit the link https://addons.mozilla.org/en-US/firefox/addon/remotedev/ and it says "Sorry, but we can't find anything at the address you entered." for firefox.

**Comment by nstaeger** [comment]
Any update on this? I am experiencing the same error.

**Comment by Daniel-Pichlmeier** [comment]
FYI: If you follow the instructions the plugin can still be installed manually. Worked just fine for me (clone, build, load in ff)

**Comment by willdurand** [comment]
Hi, we (Mozilla) restored a previous version of this add-on: https://addons.mozilla.org/en-US/firefox/addon/remotedev/. We checked with our reviewers. There are problems with some of the recent versions but we can't get in touch with the developer after many attempts over a long period.

**Comment by mcchrish** [comment]
Issue was created before https://github.com/zalmoxisus/redux-devtools-extension/issues/360

Let's see if we can just have this reopened.
