### ISSUE TITLE
Integration into Chrome devtools

### ISSUE THREAD

**Issue by glebmachine** [zalmoxisus/redux-devtools-extension#569]
Could you please add intergration right into chrome devtools (like Augury, and other Chrome DevTools Extension).

It is much more usable, then standalone window or dropdown view.
It will be very appreciated by community.

**Comment by zalmoxisus** [comment]
It should be available there as well, not only as a window and dropdown:
![image](https://user-images.githubusercontent.com/7957859/48558100-1876c780-e8f1-11e8-9075-d064b8b9d34e.png)

Or you mean as a panel in Elements tab?

**Comment by glebmachine** [comment]
@zalmoxisus exactly.
And it's magically appears) Thanks)
