### ISSUE TITLE
Uncaught TypeError: Cannot read property 'initialScrollTop' of undefined

### ISSUE THREAD

**Issue by guocheng** [zalmoxisus/redux-devtools-extension#57]
I got this error:

```
LogMonitor.js:120  Uncaught TypeError: Cannot read property 'initialScrollTop' of undefined.
```

The code that is causing this error is in `LogMonitor.js` at line 120:

```
node.scrollTop = this.props.monitorState.initialScrollTop;
```

I have tested the same code without using devtools-extension (using devtools instead )and there is no error. so I don't know if this is LogMonitor's error or an incompatibility issue with devtools-extension.

**Comment by zalmoxisus** [comment]
It should be an extension issue as LogMonitor doesn't receive any props. Do you use the extension from Chrome store? Any changes you made in settings? Can you reproduce it if you test [our examples](https://github.com/zalmoxisus/redux-devtools-extension#examples)? Can you share an example to reproduce it?

**Comment by guocheng** [comment]
>Do you use the extension from Chrome store? 
Yes.

>Any changes you made in settings?
No.

>Can you reproduce it if you test our examples? Can you share an example to reproduce it or at least copy here your store configuration?
Will try it next Monday. It's on my work machine. 

Thanks for the extension BTW, love it :+1:

**Comment by ashwinvandijk** [comment]
Same issue here. Can't reproduce with the examples on the site, so my guess is that it has something to do with the different (newer) versions of some libraries i'm using. I'm using react-redux 4.4.0, while the examples use 4.0.0. Tried installing that version but that didn't fix the issue for me. Also tried redux 3.1.5. from the examples while I had 3.3.1, which also didn't fix it...

**Comment by zalmoxisus** [comment]
@ashwinvandijk, could you please share your store configuration?

**Comment by ashwinvandijk** [comment]
Sure, here is my complete file:

```javascript
import { applyMiddleware, compose, createStore, combineReducers } from 'redux'
import { persistState } from 'redux-devtools';

import { syncHistory, routeReducer } from 'react-router-redux'
import { browserHistory } from 'react-router'

import invariant from 'redux-immutable-state-invariant';
import DevTools from 'containers/devtools';
import thunk from 'redux-thunk';

import * as reducers from 'reducers';

const syncMiddleware = syncHistory(browserHistory);
const middleware = [ syncMiddleware, thunk, invariant() ];

const rootReducer = combineReducers({
  ...reducers,
  routing: routeReducer
});


const enhancer = compose(
  applyMiddleware(...middleware),
  window.devToolsExtension ? window.devToolsExtension() : DevTools.instrument(),
  persistState(
    window.location.href.match(
      /[?&]debug_session=([^&]+)\b/
    )
  )
);

export default function configureStore(initialState) {
  const store = createStore(rootReducer, initialState, enhancer);
  syncMiddleware.listenForReplays(store);

  if (module.hot) {
    module.hot.accept('reducers', () =>
      store.replaceReducer(require('reducers').default)
    );
  }

  return store;
}
```

I found out that I rendered my DevTools somewhere, which means it should get displayed in my browser window. I changed this line to ```{!window.devToolsExtension ? <DevTools /> : null }``` which fixed it for me.

**Comment by zalmoxisus** [comment]
> I found out that I rendered my DevTools somewhere, which means it should get displayed in my browser window. I changed this line to {!window.devToolsExtension ? <DevTools /> : null } which fixed it for me.

Thanks for clarifying this. We don't include logmonitor in the app's page (it is included only on the extension's page). BTW, you also don't need to include `persistState` in your enhancer as the extension already include it (though it should'n lead to any errors, just the changes will be persisted twice).

@guocheng, could you confirm that you also tried to render DevTools?

**Comment by guocheng** [comment]
@zalmoxisus Yes, I did rendered the DevTools.

**Comment by zalmoxisus** [comment]
Actually, even if we include the monitor from the extension, it wouldn't be rendered in that component. Anyway this error doesn't stop the extension to work properly, but it would be better to have a warning only.
