### ISSUE TITLE
Firefox no devpanel in settings or Open in Panel has no settings option in the devtools

### ISSUE THREAD

**Issue by AddictArts** [zalmoxisus/redux-devtools-extension#571]
New install of Firefox and Firefox Developer Edition along with the add-on from mozilla.org. React has a panel and a setting in for addition devtools created by add-ons, but redux does not. Note: It appears in the address bar. Thanks

**Comment by zalmoxisus** [comment]
It was downgraded for some reason. Thanks for reporting, let's track the issue in #573
