### ISSUE TITLE
Firefox add-on version is outdated

### ISSUE THREAD

**Issue by GhislainLeitz** [zalmoxisus/redux-devtools-extension#572]
Hello.

Today, I wanted to install the redux devtool extension on Firefox Developer Edition (64.0b5) and suprisingly, the version available in the Firefox add-ons market is the 2.13.1. I discovered this because in this version keyboard shorcuts are enabled and it's just the hell on a mac.

According to the market, the version has been updated the 27th October 2018 but when I checked on the version history, it's indicated that the version 2.13.1 has been released the 6th Feb. 2017.

<img width="476" alt="capture d ecran 2018-11-01 a 22 55 36" src="https://user-images.githubusercontent.com/17830022/47882640-7ce25300-de2a-11e8-98b6-b61ae2b3fe2b.png">

_Here is a screenshot of the Firefox add-ons market_

**Comment by chrisfromredfin** [comment]
See #573

**Comment by GhislainLeitz** [comment]
I close the issue, because a discussion started on #573.
