### ISSUE TITLE
The Firefox Add-on breaks my site...

### ISSUE THREAD

**Issue by pingshunhuang** [zalmoxisus/redux-devtools-extension#573]
I downloaded Firefox 63 and did a clean installation with this add-on in MacOS, and it just somehow breaks the site... Disable the add-on, and everything is back to business.

The same extension works like a charm in Chrome, so there is no setup issues. I'm lost...

![image](https://user-images.githubusercontent.com/32624534/47896865-81a71580-dec3-11e8-8661-9c73685fb632.png)

**Comment by nghtstr** [comment]
I was getting the same error as well. Took me almost 5 hours of work to figure out it was this plugin.

**Comment by GhislainLeitz** [comment]
The version currently available in the Firefox add-on catalog is outdated. Like you, I have to install recently a fresh firefox with this add-on and I encountered some problems.
In fact, the current version available is the 2.13.1 while I have another old firefox and I have the version 2.15.3 installed...

**Comment by elboletaire** [comment]
I'm here because this happened to a teammate just today, and I also have version 2.15.3 of this widget (that's why it was working for me), what I don't get is where does that version come from. I don't even see the tags created on the repository :confused: 

![imatge](https://user-images.githubusercontent.com/153305/48070108-6562eb80-e1d7-11e8-96b3-8e73c27259fc.png)

**Comment by chrisfromredfin** [comment]
Same here. Works for me with the magical 2.15.3 that I have installed, teammate installed fresh and she got 2.13.1 and the e[n] is undefined issue also. 

I hate to say it, but was the extension compromised in some way?

**Comment by Frozenfire92** [comment]
Also experienced this with a simple react-redux app

**Comment by sardaukar** [comment]
@humphrey the packaged addon by @elboletaire fixed the problem for me

**Comment by zalmoxisus** [comment]
I resubmitted the last version as `2.15.4` as the previous one was removed, hope it will be accepted soon. Added more instructions this time for reviewers in case they'll have issues with the archive again. Also granted @jhen0409 the rights to upload it in future if I wouldn't be able to react fast.
It's odd that it was removed after several months.

**Comment by AddictArts** [comment]
@zalmoxisus That install does not work. I turned off signing and it still will not work with Firefox dev. There appears to be a missing META-INF?

**Comment by zalmoxisus** [comment]
@AddictArts yes, sorry about that, devtools panel was ignored, I fixed that in https://github.com/zalmoxisus/redux-devtools-extension/commit/bddc7f3241110d33cef0d8b8aa142d9a46e996f4. But `./build/extension` folder used for chrome is compatible with firefox as well. Anyway, I uploaded the build in [the release](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.15.3) and we should follow this practice.

The issues and delays with reviewing are do to the fact that bundle files are too big and we have to uglify (minify/obfuscate) them. Should add code splitting so we could keep original code to make it easier for reviewers.

**Comment by zalmoxisus** [comment]
`2.15.4` is now available for download in at https://addons.mozilla.org/addon/remotedev/ . Please let me know if you still experience these issues.

**Comment by alexeyoganezov** [comment]
Looks like everything works fine now. Thank you. 
It was hard to work without this extension in Firefox :)

**Comment by zalmoxisus** [comment]
Closing as resolved, thanks for reporting and checking it!
