### ISSUE TITLE
New UI, theming and persisting extension's monitors states

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#577]
As many issues are related to this, I'm posting it here that it's finished in https://github.com/zalmoxisus/remotedev-app/pull/30 and planned for `3.0` version of the extension. I'll work on critical issues for [`2.15.5`](https://github.com/zalmoxisus/redux-devtools-extension/projects/2), then will come back to this. We'll remove planned futures which are not finished (like reports) to move it forward. 

Bellow is a sneak peek of implementing it to `react-native-debugger` and also it was already implemented for Visual Studio plugin.
![image](https://user-images.githubusercontent.com/7957859/48663602-3aac4900-ea9b-11e8-921f-97059cbb599c.png)

And white color scheme with default theme (that above is Material UI):
<img width="710" alt="screen shot 2017-01-31 at 4 51 38 pm" src="https://cloud.githubusercontent.com/assets/7957859/22470089/d0b0285a-e7d6-11e6-974e-0433ea4514ff.png">

There are not only different color scheme, but also themes (there's default and Material UI). It should be much easier to implement new monitors. The buttons are extracted from monitors and all actions are persisted, so you'll not have to select every tab/subtab everytime after refresh.

You can try the playground on https://zalmoxisus.github.io/devui/

**Comment by AuthorProxy** [comment]
any news?

**Comment by chumga01** [comment]
> Hello

**Comment by Methuselah96** [comment]
Released in 3.0.
