### ISSUE TITLE
Cannot read property match of undefined (v2.16.0)

### ISSUE THREAD

**Issue by albertogasparin** [zalmoxisus/redux-devtools-extension#591]
After updating the extension I have this error triggered when I manually call `send()`:

![image](https://user-images.githubusercontent.com/84136/49135222-2e957680-f33a-11e8-89cd-daa74433c062.png)

The code that calls send is available here: 
https://github.com/albertogasparin/react-adone/blob/master/src/enhancers/devtools.js

The issue appeared today, with v2.16.0

**Comment by saadbinsaeed** [comment]
There is a bug in 2.16.0 you can revert it back to the previous version v2.15.5 

- Download [redux-devtool-extension](https://github.com/zalmoxisus/redux-devtools-extension/releases/download/2.15.5/extension.zip)
- Extract the zip
- Type `chrome://extensions` into the url
- toggle on developer mode on the top right of the page.
- Click on the **Load Unpacked** button. After clicking the button, Select the extracted folder.

Hope it will help :)

**Comment by pawelas** [comment]
@zalmoxisus `2.16.1` seems to fix the issue for me

**Comment by zalmoxisus** [comment]
@albertogasparin thanks for the example, I enabled the extension and the commits above fixed the issue. However after reloading the app, it ignore the extension. Could you please try if [`2.16.3`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.16.3) fixes the issue before I ship it to Chrome Store? Unzip `extension.zip`, type `chrome://extensions` and turn on developer mode from top left and then click on `Load Unpacked` and select the extracted folder for use.

**Comment by zalmoxisus** [comment]
Published `2.16.3` which includes the fix for this issue, and it's available now on [Chrome Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).
