### ISSUE TITLE
Map() in State no longer being displayed

### ISSUE THREAD

**Issue by tschwartz** [zalmoxisus/redux-devtools-extension#595]
I'm not sure which version but recently Map() is no longer being displayed properly in state as seen in the following screenshot.

![image](https://user-images.githubusercontent.com/1513268/49166016-5dcec800-f2e7-11e8-89f3-bd75f00cd254.png)

**Comment by zalmoxisus** [comment]
Could you please try if [`2.16.3`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.16.3) fixes the issue before I ship it to Chrome Store? Unzip `extension.zip`, type `chrome://extensions` and turn on developer mode from top left and then click on `Load Unpacked` and select the extracted folder for use.

**Comment by tschwartz** [comment]
Thank you, unfortunately this patch release doesn't address this issue.

**Comment by tschwartz** [comment]
Apologies but I haven't been able to look into this any further but will when I get a chance.

**Comment by tschwartz** [comment]
@zalmoxisus adding `serialize: { options: { map: true }}` fixed the issue, thanks!

**Comment by VenomFate-619** [comment]
where to add this ?
