### ISSUE TITLE
v. 2.16.2 (Chrome, MacOS) breaks the react / redux apps when extension is enabled

### ISSUE THREAD

**Issue by alex-sobolev** [zalmoxisus/redux-devtools-extension#596]
Details:
React/redux app:
redux-devtools-extension: "^2.13.7"
Redux DevTools: 2.16.2 (Chrome, MacOS)

`composeWithDevTools` breaks the app. If either a call of `composeWithDevTools` is removed from a project or `Redux DevTools` is disabled in Chrome, both of these seem to fix an issue.

 the following error occurs if both - `composeWithDevTools` and `Redux DevTools` - are enabled:
```
redux.js?00d8:106 Uncaught Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
    at Object.getState (redux.js?00d8:106)
    at B (<anonymous>:1:28201)
    at <anonymous>:1:37657
    at Object.dispatch (redux.js?00d8:205)
    at dispatch (<anonymous>:1:40300)
    at Object.eval [as dispatch] (middleware.js?3dfa:66)
    at dispatch (<anonymous>:1:30679)
    at Object.getUserInfo (App.js?db58:23)
    at App.componentDidMount (App.js?db58:10)
    at commitLifeCycles (react-dom.development.js?61bb:15961)
```

**Comment by zalmoxisus** [comment]
Could you please try if [`2.16.3`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.16.3) fixes the issue before I ship it to Chrome Store?

**Comment by alex-sobolev** [comment]
@zalmoxisus , I've just tested it. It seems it's back to normal. Please ship it. Thank you!

**Comment by zalmoxisus** [comment]
@alex-sobolev thanks for looking into it. I guess `2.16.2` from [Chrome Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) should work as well. Most likely it threw in `2.16.0` before it was updated.

**Comment by Friss** [comment]
@zalmoxisus I'm still seeing issues with 2.16.2 while 2.16.3 fixes the issue for our apps.

**Comment by alex-sobolev** [comment]
it was still visible on on `2.16.2`, and no sign of it on `2.16.3`

**Comment by zalmoxisus** [comment]
Published `2.16.3` and it's available now on [Chrome Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd). Please let me know if that works.

**Comment by benwiggins** [comment]
`2.16.3` fixes the issue for me, thank you.

**Comment by Friss** [comment]
Looking good for me as well. Thanks!
