### ISSUE TITLE
Add hint on how to open as window?

### ISSUE THREAD

**Issue by peteruithoven** [zalmoxisus/redux-devtools-extension#6]
I was having problems finding how to open the extension as a separate window (instead of a automatically closing popup). 
It was possible by right clicking on the extension icon and selecting the second Redux DevTools. 
Is there a way we can make this easier to find? Maybe add it to the Readme?

**Comment by zalmoxisus** [comment]
Thanks for the suggestion! It could be a solution to just specify it in the README, but I expect that the most of users will download the extension from Chrome WebStore and they will not read the description.

It would be great to extend the DevTools, adding there a button for opening it in a new window and maybe for the option page (settings).

BTW, any reasons you find having the DevTools in a new window better than from the dev panel?

**Comment by peteruithoven** [comment]
That would be much clearer indeed. 
Changing the name in the right click menu would also help slightly. 

Well imagine having the regular Chrome developer tools behind a popup... Would be kind of a drag to keep reopening it right? I'm not saying that the panel doesn't have a purpose, it probably does. 

Why wasn't it added as a developer tools tab btw?

**Comment by zalmoxisus** [comment]
I see. I intend to extend it, so our extension will have other tabs.
