### ISSUE TITLE
Support non-JSON values

### ISSUE THREAD

**Issue by alexkuz** [zalmoxisus/redux-devtools-extension#60]
The extension serializes state with `jsan`, losing values like `undefined` or `function`.

The way to fix this is to use `node-stringify` / `eval`, instead of `jsan.stringify` / `jsan.parse`.
(there is probably a better option than `eval`, I'm not sure) :)

**Comment by zalmoxisus** [comment]
I guess `node-stringify` will not support circular references. Before `jsan` we als used `circular-json` and `json-stringify-safe`, but `jsan` seems to be faster than competitors.
 
I think we better fix that in `jsan` as @kolodny [already uses our extension](https://github.com/zalmoxisus/redux-devtools-extension/issues/23) and will accept a PR.

**Comment by alexkuz** [comment]
Oh, that seems better, indeed.

**Comment by kolodny** [comment]
@zalmoxisus @alexkuz I wrote a helper function to do this, let me know if it solves your use case

https://github.com/kolodny/jsan/issues/1#issuecomment-188349049

**Comment by zalmoxisus** [comment]
@alexkuz, you can try it in `1.0.0.8`. Also added `redux-devtools-inspector` monitor in #64.

**Comment by alexkuz** [comment]
@zalmoxisus thank you!

**Comment by zalmoxisus** [comment]
@alexkuz, unfortunately, I've temporally reverted it due to #67.

**Comment by zalmoxisus** [comment]
Should work well now. Thanks to everybody working on this!
