### ISSUE TITLE
extension always detect redux library in every page

### ISSUE THREAD

**Issue by vitomanu96** [zalmoxisus/redux-devtools-extension#600]
the extension icon is always lighting up for every page I visit.

**Comment by ChrisYGarcia** [comment]
Having this same issue; the extension icon is always lighting up for every page I visit.

**Comment by zalmoxisus** [comment]
Thanks for clarifying that it's about the icon. Yes, I've seen it in Canary that page action icon is not faded (grayed) anymore by Chrome in latest version, however it's still inactive. I rechecked `chrome.pageAction.show` is not called from our side when not needed.

Not sure if it's a bug or a feature in new versions of Chrome. What is strange is that it is still grayed out on `about-blank` and `chrome://` pages.

A solution would be to provide our gray icon and change it from our side, same as React DevTools does (the difference is that they use browser action, not page action, which wasn't faded before).
