### ISSUE TITLE
Test coverage when using enhancer?

### ISSUE THREAD

**Issue by RaedsLab** [zalmoxisus/redux-devtools-extension#603]
How would one go about testing adding this enhancer with jest?

I have this example ([link](https://coveralls.io/builds/20536662/source?filename=src%2Fredux%2Fstore.js#L24))

something like this: 
  ```js
if (process.env.NODE_ENV === 'development') {
  const devToolsExtension = window['__REDUX_DEVTOOLS_EXTENSION__'];
  if (typeof devToolsExtension === 'function') { // this line
    enhancers.push(devToolsExtension()); // and this line 
  }
}
```

**Comment by zalmoxisus** [comment]
You can include [`redux-devtools-extension` npm package](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm) instead, so there will be no need to test the globals. The test should just check if `devToolsEnhancer` returns a noop function. Or in case of `composeWithDevTools` it returns the same function as `require('redux').compose`.

**Comment by RaedsLab** [comment]
If we just need to check that the store exists, I think this should be enough? 

https://github.com/RaedsLab/showcase-react/blob/master/src/redux/store.test.js
https://github.com/RaedsLab/showcase-react/blob/master/src/redux/store.js

**Comment by zalmoxisus** [comment]
Yes, just there will be not much difference in development. You could also try to add [our instrumentation enhancer](https://github.com/zalmoxisus/redux-devtools-instrument) (maybe we could also export the other parts) and check if `dispatch` and `getState` doesn't break anything, but I guess for most of cases that's not necessary.
