### ISSUE TITLE
Clearing the action log

### ISSUE THREAD

**Issue by monfera** [zalmoxisus/redux-devtools-extension#614]
I'm often interested only in the actions pertaining to the specific user interaction (click, drag&drop, menu etc.) and not the entire history since initial page load. When a user interaction can lead to multiple actions, it's super hard to know what the new actions are. So I'd like to be able to erase the action log, eg. with Ctrl-K, similar to how the dev console can be erased.

Having said that, I'm surprised it's not avaliable aready, given the level of convenience it'd bring, so maybe I'm doing something wrong. Admittedly I believe it's best if a user action leads to a single action for the store, which is almost like an unspoken redux principle, and I even agree with it, but sometimes one has to work with preexisting code, to be refactored later.

**Comment by zalmoxisus** [comment]
The difference with logs from dev console is that here we should also be able to recompute actions to get the exact state, and by excluding/erasing certain actions there could be an inconsistency. What we provide as an alternative is to just hide them (while they are still stored in the history). For browser extension add `actionsBlacklist` / `actionsWhitelist` or `predicate` option (see [the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsblacklist--actionswhitelist)).

**Comment by monfera** [comment]
Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @monfera Sign out
257
10,328 736 reduxjs/redux-devtools
 Code  Issues 41  Pull requests 8  Insights
Clearing the action log #421
 Closed	monfera opened this issue 2 hours ago · 2 comments Comments
Assignees
No one assigned
Labels
None yet
Milestone
No milestone
Notifications
You’re receiving notifications because you authored the thread.
2 participants
@monfera
@zalmoxisus
@monfera
 
monfera commented 2 hours ago
I'm often interested only in the actions pertaining to the specific user interaction (click, drag&drop, menu etc.) and not the entire history since the initial page load. When a user interaction can lead to multiple actions, it's super hard to know what the new actions are. So I'd like to be able to erase the action log, eg. with Ctrl-K, similar to how the dev console can be erased.

Having said that, I'm surprised it's not avaliable aready, given the level of convenience it'd bring, so maybe I'm doing something wrong. Admittedly I believe it's best if a user action leads to a single action for the store, which is almost like an unspoken redux principle, and I even agree with it, but sometimes one has to work with preexisting code, to be refactored later.

 @zalmoxisus
 Collaborator
zalmoxisus commented 43 minutes ago
The difference with logs from dev console is that here we should also be able to recompute actions to get the exact state, and by excluding/erasing certain actions there could be an inconsistency. What we provide as an alternative is to just hide them (while they are still stored in the history). For browser extension add actionsBlacklist / actionsWhitelist or predicate option (see the API). If you're including it as a component, then the same can be achieved with redux-devtools-filter-actions or redux-devtools-filterable-log-monitor.

 @zalmoxisus zalmoxisus closed this 42 minutes ago
@monfera
 
monfera commented 31 seconds ago
Thanks for the answer! Btw. I wasn't looking for excluding past actions in any sense other than just not viewing past actions that no longer matter to me, not sure where I gave that impression (maybe "erase the action log" should've been "hide/remove from the view the rendered rowa of the action log").

I don't understand the part about inconsistency, or what functionality would be jeopardized by not showing old actions. (Or even, by not storing old actions - if I'm not interested in the history then there won't be functions requiring these past actions, unlike when filtering certain action types, maybe I'm overlooking something.) Even if there's functionality tied to keeping around old actions (or specifically, all the states associated with these old actions, going beyond Redux itself, eg. undoing actions which afaik Redux Dev Tools doesn't support afaik) my suggestion was about simply not showing actions prior to a specific action, which feels like a view question.

The way Redux works is conducive to modeling it as a starting state and a subsequent series of actions that make new states, and what the starting state is, is arbitrary. Especially when it comes to debugging - coders can decide that they're simply not interested in viewing anything prior to whatever action. Even the name "Redux" may have come from it, it's basically a reducer.

The otherwise useful functionality of hiding specific action types is orthogonal to the original suggestion, although seems analogous. If that's useful, possible and allowed, then eliding historical actions could be as well.

Btw. please don't interpret any of this other than a feature suggestion simply based on what I'd find useful and analogous with similar Ctrl-K things in Dev Console and console logs, these are well used features for the same reason: allowing the developer to focus on what matters.

 @monfera
   
 
 
 
Leave a comment
Attach files by dragging & dropping, selecting them, or pasting from the clipboard.

 Styling with Markdown is supported
© 2018 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details. monfera commented just now Thanks for the answer! Btw. I wasn't looking for excluding past actions in any sense other than just not viewing past actions that no longer matter to me, not sure where I gave that impression (maybe "erase the action log" should've been "hide/remove from the view the rendered rowa of the action log"). I don't understand the part about inconsistency, or what functionality would be jeopardized by not showing old actions. (Or even, by not storing old actions - if I'm not interested in the history then there won't be functions requiring these past actions, unlike when filtering certain action types, maybe I'm overlooking something.) Even if there's functionality tied to keeping around old actions (or specifically, all the states associated with these old actions, going beyond Redux itself, eg. undoing actions which afaik Redux Dev Tools doesn't support afaik) my suggestion was about simply not showing actions prior to a specific action, which feels like a view question. The way Redux works is conducive to modeling it as a starting state and a subsequent series of actions that make new states, and what the starting state is, is arbitrary. Especially when it comes to debugging - coders can decide that they're simply not interested in viewing anything prior to whatever action. Even the name "Redux" may have come from it, it's basically a reducer. The otherwise useful functionality of hiding specific action types is orthogonal to the original suggestion, although seems analogous. If that's useful, possible and allowed, then eliding historical actions could be as well. Btw. please don't interpret any of this other than a feature suggestion simply based on what I'd find useful and analogous with similar Ctrl-K things in Dev Console and console logs, these are well used features for the same reason: allowing the developer to focus on what matters.

**Comment by zalmoxisus** [comment]
> Btw. please don't interpret any of this other than a feature suggestion simply based on what I'd find useful and analogous with similar Ctrl-K things in Dev Console and console logs

Ah, sorry, that "clear the console" shortcut is identical with our "Commit" button, and that's not only hiding them from the view (monitor component). It's also freeing the memory of that actions history and related states, that's why it's called "Commit" (not "clear"), because it's squashing them into one INIT action with the last state till there.

Thought you want to exclude only specific actions, for which the mentioned options should do the trick.

> undoing actions which afaik Redux Dev Tools doesn't support afaik
That's supported. In the Inspector monitor, there's "Skip" button for that. For Log Monitor you can click on the action to "undo" it. [Here](https://github.com/gaearon/redux-devtools-log-monitor#features)'s an explanation of all buttons. The documentation is still poor and lacks a lot of features description.

**Comment by monfera** [comment]
> Ah, sorry, that "clear the console" shortcut is identical with our "Commit" button, and that's not only hiding them from the view (monitor component). It's also freeing the memory of that actions history and related states, that's why it's called "Commit" (not "clear"), because it's squashing them into one INIT action with the last state till there.

Awesome, thanks @zalmoxisus, this is just as fine for my use!
