### ISSUE TITLE
[bug]: initial state is undefined after having r/devtools open and refreshing

### ISSUE THREAD

**Issue by iamclaytonray** [zalmoxisus/redux-devtools-extension#616]
### Steps to reproduce

Have chrome dev tools open and select the redux tab. Play around with some state (dispatch an action or something). Refresh. State in devtools is now `undefined`.

It's also important to note that while the dev tools shows state as `undefined`, my application works fine. I'm able to dispatch actions and see data updated. I'm able to get data from state. It just doesn't show 

### Specs

- MacOS Mojave 10.14.2
- Chrome 71.0.3578.98 (Official Build) (64-bit)
- All redux-related deps are the latest and greatest.
- I don't use redux devtools (the deps). I just use the one liner because I'm lazy like that

I haven't used Redux in several months but it was working properly last time. Unfortunately, because I haven't used Redux (and thus, redux devtools), I'm not sure when this bug was released. Sorry!

<img width="1440" alt="screen shot 2018-12-20 at 12 58 30 pm" src="https://user-images.githubusercontent.com/16495816/50302108-1d321c80-0457-11e9-918b-7bfe1b62ced4.png">

But if I close chrome devtools, refresh the page, open up chrome devtools again, and go to the redux tab, I have my state back. I can share a screenshot if needed.

**Comment by zalmoxisus** [comment]
Thanks for the report! Can you reproduce it with [http://zalmoxisus.github.io/examples/todomvc/)? If not. a demo I could run to reproduce (on jsfiddle, codesandbox... or repo) would be helpful to look into. It also uses [one-liner](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/todomvc/store/configureStore.js#L6-L7). I tried the specified steps and it doesn't lose the state there.
