### ISSUE TITLE
How to pass an action sanitizer into composeWithDevTools

### ISSUE THREAD

**Issue by hally9k** [zalmoxisus/redux-devtools-extension#626]
I got one of the new (awesome) error messages about using an actionSanitizer to avoid the chug from big actions being serialised etc.

But...

How do i pass the `actionSanitizer` and other options as described here:
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#excessive-use-of-memory-and-cpu

Into `composeWithDevtools` in my app here:
```
export const configureStore: * = (): ReduxStore => {
    const preloadedState: AppState = makeAppState()
    const middleware: * = configureMiddleware()
    const enhancer: * = composeWithDevTools(applyMiddleware(...middleware))

    return createStore(reducers, preloadedState, enhancer)
}
```

**Comment by zalmoxisus** [comment]
As specified in [the README](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm) and in [the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#options):
```js
const composeEnhancers: * = composeWithDevTools(options)
const enhancer: * = composeEnhancers(applyMiddleware(...middleware))
```

**Comment by hally9k** [comment]
Ah, apologies, I had trouble working that out for some reason. Yes I'll do that.
