### ISSUE TITLE
script injected into non-html pages

### ISSUE THREAD

**Issue by TimNN** [zalmoxisus/redux-devtools-extension#63]
To reproduce visit a non-html website such as a styled xml document (example: https://whois.nic.swiss/feed/atom.xml)

Result: 

<img width="1273" alt="screen shot 2016-02-25 at 10 45 26" src="https://cloud.githubusercontent.com/assets/1178249/13315735/efc42a3e-dbac-11e5-8fa4-8634547ed302.png">

**Comment by zalmoxisus** [comment]
That doesn't happen in dev mode as we remove the script after being executed. I will fix the production version.

**Comment by zalmoxisus** [comment]
Fixed in `1.0.0.7`.
