### ISSUE TITLE
npm shows latest version as 2.13.7

### ISSUE THREAD

**Issue by mmakrzem** [zalmoxisus/redux-devtools-extension#632]
I've been struggling to get redux 4.x working with this devtools extension.  Just now I realized that I am using v2.13.7 which is what is available from npm: https://www.npmjs.com/package/redux-devtools-extension

However the latest version as of Jan 17, 2019 is 2.17.0.  I believe you submitted a fix for redux 4.x in v2.15+ ?

Could you please update the npm repo so that I can pull the latest version down?

**Comment by zalmoxisus** [comment]
`2.13.7` is the latest version of npm package as seen [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/package.json). NPM package is a helper for working with browser extension. Browser extension is published on Chrome Store and is different, its version is `2.17.0`. 

For Electron `electron-devtools-installer` should download the latest version from Chrome Store.

**Comment by mmakrzem** [comment]
@zalmoxisus, the https://www.npmjs.com/package/redux-devtools-extension site says v2.13.7 and the github repo it points to is https://github.com/zalmoxisus/redux-devtools-extension, but that says it is v 2.17.0  This is so confusing!

**Comment by zalmoxisus** [comment]
@mmakrzem agree it's confusing. NPM package helper was released years later after we started this repo. There will be no more confusion with packages when we'll finish migrating everything to [monorepo](https://github.com/reduxjs/redux-devtools/issues/412).

**Comment by Methuselah96** [comment]
Resolved.
