### ISSUE TITLE
Dependency housekeeping

### ISSUE THREAD

**Issue by mum-viadee** [zalmoxisus/redux-devtools-extension#643]
npm audit currently reports 93 vulnerabilities. Most of them (nearly 80) are inherited from gitbook-cli, which seems to be deprecated and is not longer under active development. But there are a few other things, that could be done. For example updating to gulp 4.0.0 and Babel 7 would be handy to get rid of many of the vulnerabilities.

> found 93 vulnerabilities (11 low, 61 moderate, 19 high, 2 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details

Maybe it is time for a "housekeeping" release to get rid of technical debt?  :grin:

**Comment by Methuselah96** [comment]
Tracking in https://github.com/reduxjs/redux-devtools/issues/667.
