### ISSUE TITLE
Unable to load DiffMonitor

### ISSUE THREAD

**Issue by oyeanuj** [zalmoxisus/redux-devtools-extension#66]
Hi @zalmoxisus, thanks for your work on this extension!

As per your comment in #31, I tried using DiffMonitor with the chrome extension but it was still showing only the LogMonitor. Not sure if this is a noob error but here are the relevant bits:

```javascript
#Redux: create.js

if (__DEVELOPMENT__ && __CLIENT__ && __DEVTOOLS__) {
	const { persistState } = require('redux-devtools');
	const DevTools = require('../containers/DevTools/DevTools');
	finalCreateStore = compose(
		applyMiddleware(...middleware),
		window.devToolsExtension ? window.devToolsExtension() : DevTools.instrument(),
		persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))
	)(_createStore);
} else {
	finalCreateStore = applyMiddleware(...middleware)(_createStore);
}
```

In the extension option, I have set both left and right monitors to Diff Monitor. Any pointers on what I might be doing wrong?

**Comment by zalmoxisus** [comment]
Hey @oyeanuj,

To open left or right monitor, click the corresponding button or do right click on the page to select it from the context menu. Additionally you can [use keyboard shortcuts](https://github.com/zalmoxisus/redux-devtools-extension#keyboard-shortcuts). Please let me know whether it was the issue.

Also you shouldn't include `persistState` enhancer as it is already including by the extension. Anyway, it shouldn't cause any errors.

**Comment by oyeanuj** [comment]
>To open left or right monitor, click the corresponding button or do right click on the page to select it from the context menu. Additionally you can use keyboard shortcuts. Please let me know whether it was the issue.

Ah, that worked. I was looking at the 'Redux' tab in the DevTools for this to show up. This might be a totally noob question but is that controlled by the extension as well. If yes, how do I get it to show up there given the code below?

```javascript
import React from 'react';
import { createDevTools } from 'redux-devtools';
import LogMonitor from 'redux-devtools-log-monitor';
import DockMonitor from 'redux-devtools-dock-monitor';
import FilterableLogMonitor from 'redux-devtools-filterable-log-monitor';
import DiffMonitor from 'redux-devtools-diff-monitor';

export default createDevTools(
	<DockMonitor  toggleVisibilityKey = "ctrl-h"
				changePositionKey = "ctrl-q"
	>
		<DiffMonitor theme='tomorrow' />
	</DockMonitor>
);
//<DiffMonitor theme='tomorrow' />
//
```

> Also you shouldn't include persistState enhancer as it is already included by the extension. Anyway, it shouldn't cause any errors.

Got it, thank you!

**Comment by zalmoxisus** [comment]
I don't get the question. Do you want to have a docked monitor, not in a new window?

**Comment by zalmoxisus** [comment]
Closing as I don't see what we could do here. If you have any suggestions or experience any issues related to this, feel free to reopen.
