### ISSUE TITLE
Dispatcher tab is missing

### ISSUE THREAD

**Issue by pxtnpxtn** [zalmoxisus/redux-devtools-extension#669]
Hi everyone, 

I have been using Redux DevTools for quite some time now, and with the recent UI changes, I'm not able to find where the dispatcher tab is, allowing me to fire actions and change the state from within the extension. This is a really important tool. I've looked around and simply can't find it. Could someone please point out where it is?

Thank you for your time.

**Comment by pxtnpxtn** [comment]
Bump.

Anyone? The dispatcher tab wasn't removed entirely, was it? That would be pretty unfortunate.

**Comment by pxtnpxtn** [comment]
UI has been updated again. Dispatcher is available.

**Comment by villesau** [comment]
This actually happens to me too. It varies depending on redux instance selected. Some times the dispatcher is there and some times it's not. There is nothing on UI indicating why the dispatcher is sometimes lacking.

**Comment by ip4422** [comment]
I had the same issue with missed dispatcher. There is a button `>_` called 'Hide dispatcher'. Probably it unchecked

**Comment by murilogtoloni** [comment]
Any news here? I'm having the same issue.
