### ISSUE TITLE
What do the numbers mean in dev tools

### ISSUE THREAD

**Issue by Brianzchen** [zalmoxisus/redux-devtools-extension#673]
Hey there, sorry if I've missed some reading in the docs but where can I find information to what the number next to the action type mean? `+00:XX:XX`

<img width="722" alt="Screen Shot 2019-07-22 at 8 37 35 am" src="https://user-images.githubusercontent.com/12436524/61598342-b16b9880-ac5f-11e9-96f8-6122fc73a883.png">

**Comment by hansifer** [comment]
Did you ever get an answer to this?

**Comment by chrisharrison** [comment]
I'd like an answer to this too.

**Comment by Brianzchen** [comment]
> I'd like an answer to this too.

I've realised since I made this comment. It just means the time since the previous actioned was triggered
