### ISSUE TITLE
[Docs] github readme suggests installing package as devDependency

### ISSUE THREAD

**Issue by DimaDK24** [zalmoxisus/redux-devtools-extension#681]
From github README:

> To make things easier, there's an npm package to install:
> `npm install --save-dev redux-devtools-extension`

User is told to install it as dev dependency. But it definitely should be *prod* dependency as it's referenced in the code, which launches in production. And npm docs suggest installing as simple dependency:

From npm docs:
> `npm install --save redux-devtools-extension`

**Comment by oren-l** [comment]
I agree, this would fail the build when trying to build with --production flag
