### ISSUE TITLE
Js Map is showed as empty object

### ISSUE THREAD

**Issue by GenrikhFetischev** [zalmoxisus/redux-devtools-extension#684]
If I update a redux store with js Map in an action and in a store empty object showed instead of Map while a store updates with a right value indeed

Expect: See Map representation in redux dev tools
Current behavior: An empty object is showed instead of Map

**Comment by DimaDK24** [comment]
Redux is intended to use only with plain objects and arrays. This is required for devtools to correctly serialize action.
See [these docs](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state)
