### ISSUE TITLE
Guidelines of how to play nice with time travel debugging

### ISSUE THREAD

**Issue by Ziriax** [zalmoxisus/redux-devtools-extension#685]
We are using `react-connected-router`, and in our react page components, we fetch state from the server, and dispatch actions to update the Redux state (we are just using hooks, no thunks nor saga middleware).

However, when we use the redux devtools for time travel debugging, the component will dispatch actions again when we rewind to the corresponding state...

I don't want to dispatch new actions when doing time travel debugging.

To be honest, I never want to do anything but rendering in my components, I typically do async fetches in event handlers (like click), but this approach doesn't work with React Router. Ideally when the browser history is changed by the user, some event should be fired, and async fetches should be done by handling that event, and not when rendering the page component, but I can't find documentation of how to do that. 

My general question is, how does one write code that plays nicely with the devtools time travel debugger, so that new actions are not dispatched when just replaying state? 

As far as I understand, middleware like Redux thunk or saga doesn't solve this problem either, unless the devtools would completely ignore Redux thunks being dispatched when doing time travel debugging.

Any help would be very welcome, thanks a lot!

**Comment by Ziriax** [comment]
I'm not yet sure how to do this cleanly and in a general way, but I looked at the source code of `connected-react-router`, and adapted it a bit to make my own custom connected react router that exposes if time-travelling debugging has taken place, or if the browser history was actually changed by the user.

I use it in my page components as follows:
```js
  const shouldLoad = useIsBrowserHistoryChange();

  useEffect(() => shouldLoad && fetchData(args),
    [shouldLoad, args]);
```

This is the TypeScript code of this custom component (not tested very well!)

```ts
import React, { useContext, useEffect, PropsWithChildren } from "react";
import { getLocation, onLocationChanged, RouterActionType } from "connected-react-router";
import { Router } from "react-router"
import { History, Location } from "history";
import { useStore } from "react-redux";

type IsHistoryChange = true | undefined;

const TimeTravelContext = React.createContext<IsHistoryChange>(true);

interface OwnProps {
  history: History;
}

type Props = PropsWithChildren<OwnProps>;

/** 
 * Returns true when the browser history was changed (by the user or some other external system).
 * Returns undefined if the history was just synched with the current state (as in time travel debugging)
*/
export const useIsBrowserHistoryChange = () => useContext(TimeTravelContext);

function TimeTravelRouter({ children, history }: Props) {

  const [isHistoryChange, setHistoryChange] = React.useState<IsHistoryChange>(true);

  const store = useStore();

  useEffect(() => {

    let isTimeTravelLocationChange = false;

    const handleLocationChange = (location: Location, action: RouterActionType, isFirstRendering?: boolean) => {
      // Don't dispatch actions when doing time travel!
      if (isTimeTravelLocationChange) {
        isTimeTravelLocationChange = false;
      } else {
        store.dispatch(onLocationChanged(location, action, isFirstRendering));
        setHistoryChange(true);
      }
    }

    // Listen to history changes
    const unlisten = history.listen(handleLocationChange);

    // Subscribe to store changes to check if we are in time travelling
    const unsubscribe = store.subscribe(() => {
      // Extract store's location
      const {
        pathname: pathnameInStore,
        search: searchInStore,
        hash: hashInStore,
      } = getLocation(store.getState())
      // Extract history's location
      const {
        pathname: pathnameInHistory,
        search: searchInHistory,
        hash: hashInHistory,
      } = history.location

      // If we do time travelling, the location in store is changed but location in history is not changed
      if (pathnameInHistory !== pathnameInStore || searchInHistory !== searchInStore || hashInHistory !== hashInStore) {
        // Don't handle history change when synching history with state!
        isTimeTravelLocationChange = true;

        setHistoryChange(undefined);

        // Update history's location to match store's location
        // TODO: Is push the right method to call here? Shouldn't we call replace?
        history.push({
          pathname: pathnameInStore,
          search: searchInStore,
          hash: hashInStore
        });
      }
    })

    // Dispatch a location change action for the initial location.
    // This makes it backward-compatible with react-router-redux.
    // But, we add `isFirstRendering` to `true` to prevent double-rendering.
    handleLocationChange(history.location, history.action, true);

    return () => {
      unsubscribe();
      unlisten();
    }
  }, [history, store]);

  return (
    <TimeTravelContext.Provider value={isHistoryChange}>
      <Router history={history} children={children} />
    </TimeTravelContext.Provider>
  )
}

export default React.memo(TimeTravelRouter);
```

**Comment by Ziriax** [comment]
The code above doesn't seem to work very well.

But it turns out the devtools have a `Lock Changes` button especially for this scenario!

https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83

So this is a non-issue, it seems perfectly fine to dispatch actions as side-effects, the `Locked Changes` button will stop these from being dispatched at all.

I would like to see an option to automatically enable this option when doing time travel debugging, import, replay, etc though...

**Comment by krisdover** [comment]
Thanks @Ziriax, the *Lock Changes* button was exactly what I needed. My issue was similar whereby I was dispatching actions on-mount via the `useEffect()` hook. Replaying the mount state in the time time-travel debugger was annoyingly generating new actions while debugging. The *Lock Changes* button stops this.
