### ISSUE TITLE
__REDUX_DEVTOOLS_EXTENSION_COMPOSE__  stopping vscode chrome debugger from loading with TypeError

### ISSUE THREAD

**Issue by maplion** [zalmoxisus/redux-devtools-extension#690]
I'm utilizing the following code to blacklist certain actions during development that become spammy:

```typescript
        let composedEnhancers: StoreEnhancer<unknown, {}>;
        if (environment.developmentOptions.reduxDevToolsBlacklistActions) {
            const composeEnhancers =
                (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
                    actionsBlacklist: environment.developmentOptions.actionsBlacklist
                }) || compose;
            composedEnhancers = composeEnhancers(...enhancers);
        } else {
            composedEnhancers = composeWithDevTools(...enhancers);
        }
```

My issue is that when I try to load the Chrome Debugger in VSCode, it doesn't load with the error: `TypeError: window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ is not a function` .

Is there a way to utilize this function without crashing the chrome debugger?

**Comment by maplion** [comment]
Moving this to main redux-devtools repo: https://github.com/reduxjs/redux-devtools/issues/489

**Comment by zekehernandez** [comment]
Before calling that function, check that it's there and that it is a function.

**Comment by maplion** [comment]
Since my attention was drawn back to this by a useless comment, I figured I would share the workaround I use for the benefit of others:

```typescript
// This conditional addresses chrome debugger TypeError issue
            // not seeing __REDUX_DEVTOOLS_EXTENSION_COMPOSE__ as a function
            if ((window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) {
                const composeEnhancers =
                    (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
                        actionsBlacklist: this.envService.developmentOptions.actionsBlacklist
                    }) || compose;
                composedEnhancers = composeEnhancers(...enhancers);
            } else {
                composedEnhancers = composeWithDevTools(...enhancers);
            }
```

**Comment by zekehernandez** [comment]
Given that your workaround was more or less what I suggested, I don't see how my comment was useless, and it certainly didn't warrant such a rude response.

**Comment by maplion** [comment]
@zekehernandez apologies, it was 3 AM and I misinterpreted your comment as obvious/rude.
