### ISSUE TITLE
Devtools are no longer working since Electron 7

### ISSUE THREAD

**Issue by TomTomB** [zalmoxisus/redux-devtools-extension#694]
## Issue

Clicking the Redux tab inside Chrome Devtools in an Electron 7 app throws the following error:
`[15656:1027/154530.726:ERROR:CONSOLE(2153)] "Uncaught Error: Connect to unknown extension [object Object]", source: electron/js2c/sandbox_bundle.js (2153)`
This didn´t happen before Electron 7.
To install the extention, electron-devtools-installer is used.

## Reproduction steps

1. git clone https://github.com/TomTomB/electron-ngrx-redux-issue.git
2. Run npm i && npm start
3. Inside Chrome Devtools click the Redux tab
4. Look inside your console

## System infos

- Windows 10 Pro x64 Build 1903
- Electron 7.0.0
- electron-devtools-installer 2.2.4

**Comment by emiacc** [comment]
Same issue on macOS Catalina version 10.15

**Comment by daeteck** [comment]
Same issue in macOS Mojave

**Comment by romanpod** [comment]
Updating Electron to 7.0.1 fixed the issue for me.

**Comment by TomTomB** [comment]
Agree. The issue has been fixed with Electron 7.0.1

**Comment by belak** [comment]
Yep, this is related to https://github.com/electron/electron/issues/20677
