### ISSUE TITLE
No store found. Make sure to follow the instructions.

### ISSUE THREAD

**Issue by mishindmitry95** [zalmoxisus/redux-devtools-extension#697]
This is my store. After the page is loaded. I have the problem 'no store found'
Can you help please?

`import rootReducer from '../reducers/index';`

`import thunk from 'redux-thunk';`

`import {createStore, applyMiddleware} from 'redux';`

`import {composeWithDevTools} from 'redux-devtools-extension';`
`

`const initialState = {
    photos: []
};`

`export default function configureStore() {`
    `const store = createStore(`
       ` rootReducer,`
       ` initialState,`
       ` composeWithDevTools(`
           ` applyMiddleware(thunk),`
       ` ));`
   ` return store`
`}`

/containers/root.js

`import React, {Component} from 'react';`
`import ReactDOM from 'react-dom';`
`import configureStore from '../configureStore/index.js';`
`import AsyncApp from './AsyncApp.js'`
`import {Provider} from 'react-redux';`
`import { render } from 'react-dom';`

`const store = configureStore();`

`export default class Root extends Component {`
 ` render() {`
    `return (`
    `  <Provider store={store}>`
       ` <AsyncApp />`
     ` </Provider>`
 `   )`
`  }`
`}`

index.js 

`import React from 'react'
`import { render } from 'react-dom'`
`import Root from './containers/Root.js'`

`render(`
  `<Root />,`
 ` document.querySelector('.fixed-container')`
`);`

**Comment by mishindmitry95** [comment]
I'm closing this issue because the problem was in Chtome DevTools settings

**Comment by xdlgj** [comment]
@mishindmitry95 ，how to set chrome devtools?
