### ISSUE TITLE
Microsoft Edge extension

### ISSUE THREAD

**Issue by biiiipy** [zalmoxisus/redux-devtools-extension#699]
Very low priority - there should be an extension version for soon to be released Chromium based Microsoft Edge browser.
But it's possible to enable installing extensions from other stores (chrome web store), so it's fine.

**Comment by stevebeauge** [comment]
There is one : https://microsoftedge.microsoft.com/addons/detail/redux-devtools/nnkgneoiohoecpdiaponcejilbhhikei

However, the last update time isn't same as the one in the chrome web store. Not sure if it's maintained.

**Comment by Methuselah96** [comment]
Resolved.
