### ISSUE TITLE
Chrome extension package is invalid

### ISSUE THREAD

**Issue by andrew-codes** [zalmoxisus/redux-devtools-extension#7]
![2015-10-28 11_13_35-redux devtools - chrome web store](https://cloud.githubusercontent.com/assets/1578436/10792897/03c2a408-7d65-11e5-8982-8f0f83565449.png)

**Comment by zalmoxisus** [comment]
Sorry about that. Uploaded the next version to Chrome Store, but it is still publishing. 
If you want to test it now, just run run `npm i & npm build` and [load the extension's folder](https://developer.chrome.com/extensions/getstarted#unpacked) `./build/extension`.

Thanks a lot for reporting it!

**Comment by zalmoxisus** [comment]
Fixed. Thanks again for the report!

**Comment by andrew-codes** [comment]
Sure, of course! Cool extension. I downloaded it and have used it for a few days. Great work!
