### ISSUE TITLE
Getting error when applying the devtools

### ISSUE THREAD

**Issue by timothyjlaurent** [zalmoxisus/redux-devtools-extension#70]
`e.apply isn't a function .`

If I un-minify the source with the `{}` button I get an error on line 1703

![image](https://cloud.githubusercontent.com/assets/2000204/13516007/fc7720c4-e16a-11e5-877e-a8e102fba151.png)

Not sure what is going on.

**Comment by zalmoxisus** [comment]
Please [run the extension in dev mode](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension) to see more meaningful error messages.

**Comment by timothyjlaurent** [comment]
Thanks,

So it looks like this is happening here:

![image](https://cloud.githubusercontent.com/assets/2000204/13546435/0bf3a3da-e263-11e5-9315-c29707f56d63.png)


It is downstream from applyMiddleware's compose.
![image](https://cloud.githubusercontent.com/assets/2000204/13546439/214b8932-e263-11e5-93e7-fc0bcdba7809.png)

**Comment by zalmoxisus** [comment]
The extension should be applied as a store enhancer not a middleware. So it should be:
```js
const store = createStore(
  reducer,
  compose(applyMiddleware(
    thunkMiddleware,
    reduxRouterMiddleware,
    socketMiddleware,
    socketEventTranslationMiddleware,
    sagaMiddleware,
    loggerMiddleware),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )
)
```
As indicated [here](https://github.com/zalmoxisus/redux-devtools-extension#2-use-with-your-favorite-flux-implementation). Just don't forget to also import `{ compose }` from `redux`;

**Comment by timothyjlaurent** [comment]
Thanks for the help
