### ISSUE TITLE
Convert NPM package source to actual ES modules

### ISSUE THREAD

**Issue by markerikson** [zalmoxisus/redux-devtools-extension#718]
The NPM package files appear to currently be committed using the output of some build tool:

```js
"use strict";

var compose = require('redux').compose;

exports.__esModule = true;
exports.composeWithDevTools = (
  typeof window !== 'undefined' && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ :
    function() {
      if (arguments.length === 0) return undefined;
      if (typeof arguments[0] === 'object') return compose;
      return compose.apply(null, arguments);
    }
);
```

This appears to be causing Webpack to bail out of tree shaking optimizations, per https://github.com/reduxjs/redux-toolkit/issues/78#issuecomment-453734877 .

I would suggest that it would be worth converting the package code to just be written in TypeScript directly, and publish artifacts based on that.

Hopefully, the improved package contents would then allow RTK to tree-shake properly.

**Comment by Methuselah96** [comment]
Resolved in https://github.com/reduxjs/redux-devtools/pull/948 and https://github.com/reduxjs/redux-devtools/pull/997.
