### ISSUE TITLE
onbeforeunload handle throws error

### ISSUE THREAD

**Issue by jcblw** [zalmoxisus/redux-devtools-extension#73]
I have been getting errors every time I try to navigate to the another page because of this code.

```javascript
...
        "undefined" != typeof window.onbeforeunload && (window.onbeforeunload = function() {
            (0,
            s.isAllowed)() && r.postMessage({
                                        ^
                type: "PAGE_UNLOADED"
            })
        }
...
```

The error is 

```diff
- TypeError: Cannot read property 'postMessage' of undefined at undefined.window.onbeforeunload.window.onbeforeunload (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/content.bundle.js:1:4176)
```

I was going to patch this myself but could not find the code in the codebase, that was creating the error. Maybe it was deployed without pushing it to github?

**Comment by zalmoxisus** [comment]
Yes, it was removed in https://github.com/zalmoxisus/redux-devtools-extension/commit/297850f1405317a26091075d0fa8225bfd7810de, but not published to Chrome store yet. This exception doesn't affect the functionality, right?

**Comment by jcblw** [comment]
no it does, not but i have pause on exception on for my own codebase, and its been persistently reminding me that this is here. I just thought I would float this out here. I can install via the version in the repo for now.

Thanks for the extension btw :beers:

**Comment by zalmoxisus** [comment]
In [new scenario](https://github.com/zalmoxisus/redux-devtools-extension/pull/72), we don't open any connections before it is required. I will add few other minor changes and will publish a new version with these fixes by tomorrow. Thanks for the report!

**Comment by jcblw** [comment]
awesome thanks!
