### ISSUE TITLE
Can I change the monitor shown in the Chrome developer tools?

### ISSUE THREAD

**Issue by anyong** [zalmoxisus/redux-devtools-extension#74]
The Chrome Developer Tools window Redux tab shows the log monitor, so I always need to keep the inspector monitor open in a new window. Can I change the Redux tab to display the inspector monitor? Thanks!

**Comment by zalmoxisus** [comment]
Will implement this after we get #54 as I don't want to have conflicts there. Thanks for the suggestion!

**Comment by anyong** [comment]
Great, thanks!

**Comment by zalmoxisus** [comment]
Just released `v1.3.0`, and it's possible now to select monitors directly in the monitor window, Chrome devtools panel or browser action popup. Feel free to reopen the issue if you have other troubles or suggestions about this.
