### ISSUE TITLE
Redux DevTools disappeared from Google Chrome DevTools Panel

### ISSUE THREAD

**Issue by rndm2** [zalmoxisus/redux-devtools-extension#740]
I am not sure if I am in correct place, but after recent Chrome update Redux DevTools disappeared from Google Chrome DevTools Panel and I can't find any settings to bring them back 
![Screenshot 2020-05-28 at 14 24 51](https://user-images.githubusercontent.com/6842505/83111587-0c2b1780-a0ef-11ea-84d2-89520a295094.png)

Does anybody know how to fix this? And which product this problem is related to?

**Comment by bsarran-easyflyer** [comment]
Hi rndm2, I updated Chrome to version 83 and I have exactly the same problem (even React Dev Tools doesn't appear anymore).

Anyone have a solution ?

**Comment by albertfdp** [comment]
Uninstall & Reinstall worked for me ¯\_(ツ)_/¯

**Comment by lilbumblebear** [comment]
Uninstall and reinstall did NOT work for me

**Comment by akuji1993** [comment]
Also having this issue as of today, also on Chrome 83.0.4103.61, Windows 10 Pro.

**Comment by rndm2** [comment]
Looks like bug in Chrome.

**Comment by DoronovIV** [comment]
Right click on it's icon => Manage extension => *turn it off and back on* => close and open devtools

may be I have just closed it's tab accidently, but that chain of actions has brought it back for me
