### ISSUE TITLE
Freezes when using chrome extension

### ISSUE THREAD

**Issue by bobmonteverde** [zalmoxisus/redux-devtools-extension#75]
In the past few weeks I have been having serious issues when using the devTools extension on one of my projects.  The strange thing is, I have 2 projects using the dev tools in the exact same manor, one works one does not (though it did previously work).  The one that doesn't work is a much larger project with A LOT of data in the state, beyond that I can't identify any other major differences.

Also, when I disable the extension, and embed the devtools into my project directly, the dev tools works without an issue, it's only the extension that causes my CPU to spike at 100% on the tab, and the tab becomes completely unresponsive until I use chrome's task manager to force quit.

I'll try to investigate more, and if possible create an example that I can release publicly.

**Comment by zalmoxisus** [comment]
Thanks for the report. More likely it should be related to the serialization that we introduced in #60 and #67. I disabled it in `1.0.0.16`, which should appear on Chrome store in about an hour. Please give it a try. Alternatively, if you don't use Immutable.js and don't have circular references, try to disable serialization at all on the settings page.

**Comment by bobmonteverde** [comment]
Yes, that fixed it.

And to give a little more detail, I was using Immutable for my state (well the top level isa normal JS object, but each reducer is an Immutable Map and contained Maps, Sets, and Lists.  On top of that, I had a few very large lists... between 5k and 100k records (with about 10 keys of strings/numbers each)... between 2 and 4 of these sets in my state.

**Comment by zalmoxisus** [comment]
Thanks for the details! That's really a lot of processing when doing deep serializing. Great that simple serialization works smoothly with such amount of data, so we'll keep it as default.

**Comment by mikedevita** [comment]
this is happening to me now, not sure why, im using immutable for global stores it just hangs randomly and crashes.. whats the work around ?

**Comment by zalmoxisus** [comment]
@mikedevita, do you set any extension's parameters like `serializeAction` / `serializeState`? If so, please try without them.

What's specific about those cases? Are the state huge or actions dispatched often?

**Comment by mikedevita** [comment]
I use davezuko's starter kit not 100% sure I don't have the code in front of me at the moment..

**Comment by zalmoxisus** [comment]
@mikedevita in `v2.9.0` the performance was improved significantly. Let me know if you're still experiencing this issue.

**Comment by mikedevita** [comment]
Thanks it seems like the issue went away on its own.  Not sure if it's because of update or not.
