### ISSUE TITLE
Any thoughts on removing racial-sensitive language?

### ISSUE THREAD

**Issue by johannalee** [zalmoxisus/redux-devtools-extension#753]
I was wondering if the author is interested in removing racial-sensitive language in the repo.
For example, whitelist and blacklist are used in the repo and they can be replaced with allowlist and denylist. 

👀 Looking forward to hearing some updates on this.
Thank you :)

**Comment by david-shortman** [comment]
Allowlist and blocklist are unambiguous and require no cultural reliance on colors (white/black or green/red as a proposed alternative).

While conversations about language and race were greatly contentious when stirred last summer, they stirred a broader notion- that some of the language we use in computing can be made more accessible and obvious for everyone.

I think it's a win-win to shape our vocabulary to be more straightforward and globally inclusive.

**Comment by Methuselah96** [comment]
Resolved in https://github.com/reduxjs/redux-devtools/pull/851.
