### ISSUE TITLE
Position of panels in chrome debugger

### ISSUE THREAD

**Issue by wkw** [zalmoxisus/redux-devtools-extension#76]
This isn't an issue with the project, but relevant.

When I'm working with a react/redux project, my OCD dictates that I move the react and redux Chrome dev panels to the left because those two, tend to be the ones I'm looking at mostly, followed by Elements  and Network panels. Yet extension debugger panels seem to be relegated to the end of the queue. Thus the query:
I suppose I should add: it's typical that my browser is on the laptop screen -- limited real estate -- and my terminal and editor on the Trump-sized monitor. So 2/3ds of the browser is project, the remaining gets debug/inspector space.

![image](https://cloud.githubusercontent.com/assets/1691220/13896782/e48f5a06-ed6f-11e5-8acb-edd05b9a4db8.png)

Is there a hack that can keep chrome extension debugger panels where you last put them? Or something we can add to this and the React debugger that would give them a higher default ordering? I've done cursory Googling on this but didn't come up with anything yet.

![image](https://cloud.githubusercontent.com/assets/1691220/13896757/b733ee4c-ed6e-11e5-9fe4-2faa6522fa05.png)

**Comment by zalmoxisus** [comment]
Yes, Just checked in Chrome 49, and it keep the order of the panels after you drag and drop clicking the React/Redux title of the panel.

Anyway, I highly recommend to use windows instead of devtools panel, as it works faster (no need to relay data to the chrome devtools script), and usually you want to have the console (or Elements/React inspecting panel) there.

**Comment by wkw** [comment]
OK, good advice. thanks

**Comment by ondrejrohon** [comment]
Chrome on mac: Version 66.0.3359.139 (Official Build) (64-bit)
and it's not working :/
I reorder React and Redux tabs to the left (OCD) I close&open dev tools and they loose their position :(
