### ISSUE TITLE
Autodetect remote devtools hosts

### ISSUE THREAD

**Issue by nevir** [zalmoxisus/redux-devtools-extension#78]
I'm unsure if this is possible (but seems likely?)

I'd prefer to have a setup where:

* I'm doing react native development, both in simulator _and on device_ (over wifi)
* I'm running my own `remotedev` server locally
  * Run like `remotedev --hostname=MY_LOCAL_IP --port=8000` so that actual (iOS) devices can connect to it
* I have "Debug in Chrome" enabled in the app

Ideally, the Redux devtools tab should "Just Work" in this situation

---

Now, the challenges:

* Can the extension look at the active web workers and poke around their JS context?  (i.e. `$debuggerWorker.js` in the RN Debugger environment)
* If so, `remote-redux-devtools` could expose the host/port/name of the `remotedev` server it's connected to
* At which point, it seems plausable to have the extension load itself up in the devtools tab, and point to that remotedev server, and focus on the app that's being run in that context

**Comment by zalmoxisus** [comment]
Thanks for the suggestion. Unfortunately, React Native Debugger knows nothing about this and don't expose anything globally (so the extension can catch it).

Actually, you can just open `localhost:8000` in another tab and will have the monitor configured with your host and port.

**Comment by zalmoxisus** [comment]
It was implemented on [`remotedev-server`](https://github.com/zalmoxisus/remotedev-server)
