### ISSUE TITLE
redux-devtools-extension 2.13.9

### ISSUE THREAD

**Issue by randdusing** [zalmoxisus/redux-devtools-extension#787]
Is there a changelog for this version? I don't see any reference to it in this repo.

**Comment by leethree** [comment]
looks like new version is moved to this repo: https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-extension

see #412

**Comment by randdusing** [comment]
Thanks. It looks like they didn't update their package.json to point to the new repo hence the confusion.

**Comment by Methuselah96** [comment]
Resolved.
