### ISSUE TITLE
v2.17.1 is last verison but 2.13.9 at npm 

### ISSUE THREAD

**Issue by N1ck0lay** [zalmoxisus/redux-devtools-extension#789]
Hello, I can't install latest verion because it is not published to npm, can you fix it?

https://www.npmjs.com/package/redux-devtools-extension

**Comment by dzienisz** [comment]
have the same problem here :(

**Comment by fastfedora** [comment]
[This comment](https://github.com/zalmoxisus/redux-devtools-extension/issues/632#issuecomment-455576861) appears to state there are two different `redux-devtools-extension` packages:

- A browser extension (whose version is currently 2.17.1)
- A helper for working with the browser extension (whose version is currently 2.13.9)

The one published to `npm` is the second one. So if you are using it within an app to connect to the browser extension, you are on the latest version of that package.
