### ISSUE TITLE
Chrome extension URL broken

### ISSUE THREAD

**Issue by saikiran9** [zalmoxisus/redux-devtools-extension#794]
I can no longer add this extension to chrome. Can you please look into this?

**Comment by AndrewEvansDev** [comment]
I'm having the same issue. At the exact wrong time too.

**Comment by joecabezas** [comment]
confirmed (੭ˊ꒳ˋ)੭

**Comment by david24995** [comment]
Me too 😢

**Comment by shjeong92** [comment]
I also had the same issue, and found a solution.
you could install  Redux DevTools by following the steps below.

1. Download extension.zip from the link below and unzip it.
https://github.com/zalmoxisus/redux-devtools-extension/releases/download/2.17.0/extension.zip
2.  go to chrome extension url
[chrome://extensions/](url)
3. turn on developer mode from top right.
4. Click **_Load Unpacked_** and select the extracted folder(extensions) for use

**Comment by Dervisevic** [comment]
> I also had the same issue, and found a solution.
> you could install Redux DevTools by following the steps below.
> 
> 1. Download extension.zip from the link below and unzip it.
>    https://github.com/zalmoxisus/redux-devtools-extension/releases/download/2.17.0/extension.zip
> 2. go to chrome extension url
>    chrome://extensions/
> 3. turn on developer mode from top right.
> 4. Click **_Load Unpacked_** and select the extracted folder(extensions) for use

We had a new developer onboard yesterday and after it didn't work via the store he tried this method but encountered the issue below, anyone else that has run into this, and any found a workaround?

<img width="517" alt="Screenshot 2021-05-04 at 15 22 40" src="https://user-images.githubusercontent.com/541475/117120595-d0cfa900-ad93-11eb-9b51-0c56146106fe.png">

**Comment by shjeong92** [comment]
I tried the latest version which is 2.17.1 , but it didn'work

It should work with the version 2.17.0 there is link in my comment

happy hacking

**Comment by Dervisevic** [comment]
> I tried the latest version which is 2.17.1 , but it didn'work
> 
> It should work with the version 2.17.0 there is link in my comment
> 
> happy hacking

Ah, i guess that could be the issue with the chrome store as well, thank you so much!

happy hacking

**Comment by simonebosio91** [comment]
I also tried the 2.17.0 but it doesn't work, it always gives the error of missing manifest file

**Comment by david24995** [comment]
> I also had the same issue, and found a solution.
> you could install Redux DevTools by following the steps below.
> 
> 1. Download extension.zip from the link below and unzip it.
>    https://github.com/zalmoxisus/redux-devtools-extension/releases/download/2.17.0/extension.zip
> 2. go to chrome extension url
>    chrome://extensions/
> 3. turn on developer mode from top right.
> 4. Click **_Load Unpacked_** and select the extracted folder(extensions) for use

Worked for me, Thanks

**Comment by zalmoxisus** [comment]
I'm sorry for not helping here. As per Chrome store issue, I tried now, and it seems that after installing, you have to go to `chrome://extensions/` and enable it.

As per the repo, I'm not actively maintaining it. There's work in progress by contributors in https://github.com/reduxjs/redux-devtools.

**Comment by Methuselah96** [comment]
Resolved in https://github.com/reduxjs/redux-devtools/issues/713.
