### ISSUE TITLE
DevTools' persist state

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#8]
Implemented DevTools' persistState in https://github.com/zalmoxisus/redux-devtools-extension/commit/f99e2035250354b23895f9f62751f14c16fa728e. 

Not in WebStore so far. To test it, clone the repository, run `npm i & npm run build:extension` and [load the extension's folder](https://developer.chrome.com/extensions/getstarted#unpacked) `./build/extension`.

As usually, add `?debug_session=<session_name>` to the url.

It would be better to create sessions directly from the dev panel, and also to select from the existent sessions.

**Comment by ohana54** [comment]
What about custom serialize/deserialize functions?
Do you have any creative idea how to supply the custom functions as "configuration"?
I would be happy to help with development but I don't know where to start.

BTW, this chrome extension is the best thing ever!! Really awesome!

**Comment by zalmoxisus** [comment]
Thanks, @ohana54, for your kind words.

Could you please provide more information about your user case, where you need custom serialize/deserialize functions? 

I guess your custom function should be added as a middleware or as a store enhancement.  You may add more store enhancements as usually in your `configureStore` before `window.devToolsExtension`:
```javascript
const finalCreateStore = compose(
  applyMiddleware(thunk),
  ...
  window.devToolsExtension || (f => f)
)(createStore);
```

If you want to add some store enhancements directly to the extension (for example not to repeat for every application), you may add them in `./src/app/store/configStore`.

I made it really easy to customize, everything is in `.src/app` and `src/browser/extension`. 

Build it with `npm i & npm run build:extension` and [load the extension's folder](https://developer.chrome.com/extensions/getstarted#unpacked) `./build/extension`; or run it in dev mode with `npm i & npm start` and [load the extension's folder](https://developer.chrome.com/extensions/getstarted#unpacked) `./dev`.

PRs are welcome.
