### ISSUE TITLE
Timeline jumping around

### ISSUE THREAD

**Issue by tareqdayya** [zalmoxisus/redux-devtools-extension#811]
Hi there,

I've been experiencing this bug lately where jumping to an action in the timeline works fine, but using the arrows afterwards doesn't. Here's a demo:

https://user-images.githubusercontent.com/41693150/131555681-c44d0b47-dc6e-412d-9375-112f2980f165.mov

What happens is that, after clicking the arrows, there's some sort of a timeout, and then the timeline just springs back to the last point where I used the "jump" function.

I'm on:
Version 2.17.2 of the extension.
Version 92.0.4515.159 (Official Build) (x86_64) of chrome.
MacOS Big Sur 11.5.2.

**Comment by Methuselah96** [comment]
I think this was fixed in [v3](https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.0). Can you try it out?

**Comment by tareqdayya** [comment]
seems to be gone. Closing
