### ISSUE TITLE
Persist Toggle UI does not change / work

### ISSUE THREAD

**Issue by chrisj-skinner** [zalmoxisus/redux-devtools-extension#814]
Hi,

The UI of persist button does not show up / work. The functionality works but it would be great it there was a fix for the UI side of things so it's easier to keep track of on / off states
 
![Screenshot 2021-09-09 at 13 08 47](https://user-images.githubusercontent.com/5794048/132683082-481cbed8-8504-45b6-a334-980ddbb746bc.png)

**Comment by msabramo** [comment]
I saw in #364 that this depends on https://github.com/zalmoxisus/remotedev-app/pull/30 but I don't know what the status of that is. I'm just a user who was also very confused by the persist button not showing that it's active.

**Comment by msabramo** [comment]
Is there any way that I or other folks in the community can help with this?

**Comment by Methuselah96** [comment]
This should be fixed in [v3](https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.0).
