### ISSUE TITLE
Should Issues Be Raised Here?

### ISSUE THREAD

**Issue by AlanCarlyle** [zalmoxisus/redux-devtools-extension#816]
I notice that this repository is has not been updated for some time and am wondering if issues with Redux DevTools should be raised here or at https://github.com/reduxjs/redux-devtools

I raised an issue earlier that is somewhat specific to Redux DecTools embedded in Chrome Dec Tools view. I notice that similar issues raised by other get tested and closed and am wondering those checking them are using the Chrome extension installation or newer yet unmerged code from reduxjs/redux-devtools

Another quite minor issues I just noticed was that the replay sliders speed rate modify list is showing the unselected speeds in the background font colour so they are not visible. Is this an issue for this repo or is it one for reduxjs/redux-devtools ? Could it have been fixed with the other non-extension instance of Redux DevTools?

**Comment by Methuselah96** [comment]
All issues should be raised on https://github.com/reduxjs/redux-devtools. Thanks!
