### ISSUE TITLE
unsafe-eval question

### ISSUE THREAD

**Issue by davidsmith2** [zalmoxisus/redux-devtools-extension#822]
I work for a US government contractor. Our client's IT department is disallowing the use of this extension for the following reason:

> The presence of “unsafe-eval” on the extension’s source code indicates that the extension can be used to execute source code.

This appears to be defined in the extension's manifest.json CSP definition:

https://github.com/zalmoxisus/redux-devtools-extension/blob/c220fd18d6fb4b0790a501ec4df0de52b5bee460/src/browser/extension/manifest.json#L64

Curious if any other potential users of the extension had run into this obstacle?

**Comment by Methuselah96** [comment]
Closing since this repo is no longer maintained and the question was also asked [here](https://github.com/reduxjs/redux-devtools/issues/971).
