### ISSUE TITLE
TypeError: window.devToolsExtension is not a function

### ISSUE THREAD

**Issue by HadarHarush** [zalmoxisus/redux-devtools-extension#827]
Bug in version 3.0.0.

**Comment by Methuselah96** [comment]
`window.devToolsExtension` [was renamed](https://github.com/reduxjs/redux-devtools/tree/main/extension#usage) to `window.__REDUX_DEVTOOLS_EXTENSION__` / `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` in 2.7 and was deprecated. It was then [removed](https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.0) in 3.0.

**Comment by Methuselah96** [comment]
Closing since this is resolved.
