### ISSUE TITLE
Redux DevTools triggering a false positive 'This page is using the production build of React. ✅'

### ISSUE THREAD

**Issue by Fernando-Espinosa** [zalmoxisus/redux-devtools-extension#829]
This issue was reviewed at: [Issue Link](https://github.com/facebook/react/issues/23107 )

And the conclusion was that Redux DevTools was triggering a false positive in certain pages not built with react.

**Repro steps**

1. Open any web app not made with React (e.g.: youtube.com, amazon.com, github.com, gmail.com, lucidchart.app)
2. The react icon is ON and the popover message says:

'This page is using the production build of React. ✅'

**Comment by Methuselah96** [comment]
Do you mind moving this issue over to https://github.com/reduxjs/redux-devtools? It is the new home for the extension and this repo is no longer updated.

**Comment by bvaughn** [comment]
Already filed:https://github.com/reduxjs/redux-devtools/issues/1030

**Comment by Methuselah96** [comment]
12 seconds. ;)

**Comment by Methuselah96** [comment]
Will take a look soon.

**Comment by gaearon** [comment]
Should this repo be archived? I thought Redux DevTools is unmaintained by looking at the commit log. Didn't realize there's another repo.

**Comment by Methuselah96** [comment]
It should be, unfortunately I only have write access and not admin access. I'll add a note to the README.

**Comment by Methuselah96** [comment]
I submitted a fixed extension to the Chrome Web Store a few hours ago that should fix this issue. Still waiting for it to be approved.

**Comment by bvaughn** [comment]
@Methuselah96 Would love to see the fix! I don't see any commits pushed to https://github.com/reduxjs/redux-devtools

**Comment by Methuselah96** [comment]
I've added a note to the README and a pinned issue about the new repo. Still waiting on the extension to be approved in the Chrome Web Store.
