### ISSUE TITLE
Security risk when enabled in production

### ISSUE THREAD

**Issue by msafi** [zalmoxisus/redux-devtools-extension#83]
Thanks for creating this extension. It's really cool!

We were discussing whether we should enable this extension in production and some team members raised the concern that calling `window.devToolsExtension()` would allow even a malicious Chrome extension to spoof this function and add itself to store configuration.

What do you think?

**Comment by zalmoxisus** [comment]
Yes, that's a good idea to use the extension in production as it will not affect the performance for regular users (who don't have the extension installed). And, yes, you are right, it would be easy for a malicious extension to get access to you store, but on the other hand it's even easier for it to execute some bad scripts directly and to steal passwords / tokens by watching forms or network requests.

A good practice would be to add a condition for including the extension - a variable in localStorage or a url query, which will use only the developers.

**Comment by a5l3** [comment]
WTF?
