### ISSUE TITLE
Add an option to copy states to clipboard

### ISSUE THREAD

**Issue by shubhamsizzles** [zalmoxisus/redux-devtools-extension#85]
Would be nice if the UI allowed one to easily copy data from a single/multiple reducers.

**Comment by zalmoxisus** [comment]
Thanks for the suggestion. It is certainly something great to have, but it should be implemented in one of the monitors. I'd suggest to implement this on [`redux-devtools-inspector`](https://github.com/alexkuz/redux-devtools-inspector) as it has a nice way of actions/states traversing. Something similar for the [`log-monitor`](https://github.com/gaearon/redux-devtools-log-monitor) was suggested [here](https://github.com/gaearon/redux-devtools-log-monitor/issues/18).

Closing for now as I don't see something we can do from the extension.

**Comment by ajacobs-isp** [comment]
@pastelsky and anyone who came to the ticket looking for a way to copy the state's JSON into the clipboard simply go to the part of the tree you want, click `(pin)` and then select the "Raw" tab where you'll be able to copy that part of the store for analysis in other tools.
