### ISSUE TITLE
TypeError: this.props.stateTreeSettings is undefined

### ISSUE THREAD

**Issue by lepirlouit** [zalmoxisus/redux-devtools-extension#858]
On firefox/ubuntu 22.04

I got a blank page in the redux developer tools, but works fine when I right click and display "To Left"

these are the two errors in the DevConsole of the extention

TypeError: this.props.stateTreeSettings is undefined devpanel.bundle.js:2:787387
Uncaught TypeError: this.props.stateTreeSettings is undefined devpanel.bundle.js:1527:40006

This also happen when I switch from "chart" to "tree" view

**Comment by Methuselah96** [comment]
Thanks for the issue! Looks like you're running into the same issue as https://github.com/reduxjs/redux-devtools/issues/1480 and https://github.com/reduxjs/redux-devtools/issues/1481. I've made a fix in https://github.com/reduxjs/redux-devtools/pull/1486 and am working on getting it released.

**Comment by lepirlouit** [comment]
sorry for the duplicate, thanks for the fix !
