### ISSUE TITLE
What about side effects?

### ISSUE THREAD

**Issue by max-mykhailenko** [zalmoxisus/redux-devtools-extension#86]
Maybe it's question not about extensions only. I can remove action in devtools, but I have side effect to browser hash and I can't imagine how I can revert url to the previous state. Maybe you have thoughts about it.
Thanks!

**Comment by zalmoxisus** [comment]
Thanks for opening this issue. It something that concerns me as well, but it is not something that could be solved on the extension or monitor side (as described in https://github.com/zalmoxisus/redux-devtools-filter-actions/issues/3). A possible solution was suggested in https://github.com/gaearon/redux-devtools/pull/263.

**Comment by max-mykhailenko** [comment]
@gaearon maybe we can log all side effects in redux and then downgrade them like database migrations?

**Comment by zalmoxisus** [comment]
Unfortunately, I don't see how we can handle it completely here. Side effects should be reverted by the middleware / function caused that. We'll not be able to downgrade them from the extension (as in your example to change the location hash back).

Not sure how universal the solution is, but in `v2.7` we can lock the changes and dispatch the actions explicitely without having any side effects. More details in [the blog post](Redux DevTools Extension v2.7).

Feel free to reopen the issue if you have any ideas how to implement it better.
