### ISSUE TITLE
Support monitors reducers

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#87]
Due to Chrome restrictions, an extension cannot communicate directly with the page script, so the only thing the injecting script does is adding instrument enhancer and relaying all the changes to the extension's background script, where we have all the orchestration.

Before we open a monitor window, no data are relayed to the extension and no monitors are rendered. In this way the extension wouldn't have signifiant impact on the app while not using it.

We need somehow to consume monitors' reducers on the app side without rendering the monitors. Also we should keep the ability to add / remove monitors on the fly.

**Comment by khankuan** [comment]
Hmm, do you mean that because the monitor may not be launched at the start of the app, the monitor reducer might not work as expected?

**Comment by zalmoxisus** [comment]
@khankuan, we don't render monitors inside the user's app, so they are not present there at all. Applying all available monitors and hiding them just to access their reducers wouldn't be a reasonable solution I think.

**Comment by khankuan** [comment]
Hmm not sure if I got the flow correct. Could we use monitor reducers the same way as the current reducer?

**Comment by zalmoxisus** [comment]
Actually, I looked into shift toggle implementation, and you don't need any reducers applied on the user's app side, everything should be done on the remote side monitor. We should just allow sending the changes from there to the app, which should be an easy fix in [`remotedev-app`](https://github.com/zalmoxisus/remotedev-app). I'll look into it.

The current issue is related only to [`filterable-log-monitor`](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/), which is for now the only monitor that we cannot support here.

To understand the flow, take a look at [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools). It's [the same principle](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/devTools.js) and it's agnostic to any monitors, because [they are applied outside](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/containers/DevTools.js) (it can be even on other device).

**Comment by khankuan** [comment]
Hmm, i checked out [filterable-log-monitor](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/). Which part of it required code on user's app side?

Cheers

**Comment by zalmoxisus** [comment]
@khankuan, sorry for the late response.

[`actionIdToDatumMap`](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/blob/master/source/reducers.js#L56) should be generated on the user's app side and sent with the liftedState. We could include its monitor as well to get it work, the issue is only to do it only when needed, which can be addressed later if we decide to support this monitor.

Regarding the shift toggle implementation, I tried your fork and it works great now (except [the issue I commented](https://github.com/gaearon/redux-devtools-log-monitor/pull/47/commits/552b04ae5d13167f19f9e7e6cb59bb806f8832e7#diff-64b38bb681a18e1ecd4f8f8279ff3684R164)).

Give it a try and feel free to reopen the issue if you have any troubles.

**Comment by khankuan** [comment]
@zalmoxisus hmm, I updated to the latest version but it seems like `this.props.dispatch` does not dispatch actions with type `@...`

**Comment by zalmoxisus** [comment]
@khankuan make sure to update `remotedev-app` as well, it should be at least `0.3.1` ([as specified on `package.json`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/package.json#L70)) to support [this change](https://github.com/zalmoxisus/remotedev-app/commit/e9f14eda10a80bb0a64965c4511a857c5529f9f6).

**Comment by khankuan** [comment]
I'm running on master and also tried updating to 0.3.2 but seems the same :/

**Comment by zalmoxisus** [comment]
@khankuan, strange. Just checked, replaced `redux-devtools-log-montor` lib with that generated from your fork, and it works well except for [the error I described above](https://github.com/gaearon/redux-devtools-log-monitor/pull/47/commits/552b04ae5d13167f19f9e7e6cb59bb806f8832e7#diff-64b38bb681a18e1ecd4f8f8279ff3684R164) that makes it to work only first time.

**Comment by khankuan** [comment]
I've fix the issue you've described here :)
https://github.com/gaearon/redux-devtools-log-monitor/pull/47/commits/5b0c7bbedd87a1ddf1ba3e087dfcddcd2e859256

**Comment by zalmoxisus** [comment]
:+1: Tested and it works now without any issues.

Check inside `node_modules/remotedev-app` whether [this change is present](https://github.com/zalmoxisus/remotedev-app/commit/e9f14eda10a80bb0a64965c4511a857c5529f9f6) and to log what is being dispatched. Also check if [the extension receives this and dispatch inside the app](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L81).
