### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#9]
We're supporting firefox with all the features except running from Firefox DevTools panel (which will come as soon as it [will be implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1211859)). Minimal required version is Firefox 48, which should be released soon. For now use Firefox Nightly or Developer Edition. 

To build the extension run `npm i && npm run build:firefox` and [load the extension's folder](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) `./build/firefox`. It is also available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/remotedev/).

**Comment by rbvea** [comment]
+1

**Comment by veggiemonk** [comment]
@zalmoxisus @rbvea 
It just becomes easier to write cross browser extension: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by zalmoxisus** [comment]
@veggiemonk, yes we rely on WebExtensions (as well as in [crossbruilder boilerplate](https://github.com/zalmoxisus/crossbuilder), but as you see [the issues above](https://github.com/zalmoxisus/redux-devtools-extension/issues/9#issue-114236914) aren't fixed yet.

**Comment by afc163** [comment]
Need it too

**Comment by jnmandal** [comment]
Sorry if this is obvious but I just wanted to ask explicitly if there is anything we can do in this project or are we just waiting on mozilla?

**Comment by zalmoxisus** [comment]
@jnmandal, the situation is a bit complicated there. Mozilla added WebExtensions API in Firefox 46, but it's still in alpha stage and a lot is missing there yet. At the same time the old addons API will be removed in the future releases, so it makes not sense to use that, just to wait when WebExtensions API is finished.

[Quoting Mozilla](https://developer.mozilla.org/en-US/Add-ons/WebExtensions):
> We're aiming for a first stable release in Firefox 48.

Anyway, we have already a crossbrowser (and even not only browser) solution with all the features of this extension - [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools).

**Comment by zalmoxisus** [comment]
We're supporting firefox with all the features except running from Firefox DevTools panel (which will come as soon as it [will be implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1211859)). Minimal required version is Firefox 48, which should be released soon. For now use Firefox Nightly or Developer Edition. 

To build the extension run `npm i && npm run build:firefox` and [load the extension's folder](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) `./build/firefox`. It will also should be available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/remotedev/) soon.

**Comment by Fahrradflucht** [comment]
Hm,  is there a reason why the extension on AMO is not signed? Aurora won't let me install it.

**Comment by zalmoxisus** [comment]
@Fahrradflucht, it has not been reviewed yet.

As it's not vanila js, but a babel/webpack bundle with a lot of dependencies as well minified, the extension needs full review, which takes a while as reviewers are just volunteers. It's not that fast to review the full functionality we have here. More details: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews

You can just build the extension by yourself [as indicated in README](https://github.com/zalmoxisus/redux-devtools-extension#12-for-firefox).

**Comment by zalmoxisus** [comment]
The extension was fully reviewed and approved. The reviewer is also redux-react guy 😱

**Comment by siemiatj** [comment]
Hmm for some reason addon doesn't work for me. Using Fx 48.0.1, installed from AMO. Everything is configured properly as redux devtools show up properly on Chrome. Is adding `devToolsExtension` to the store enough ? That's my configureStore file : 

```javascript
export default function configureStore(initialState, history) {
  // Installs hooks that always keep react-router and redux
  const middleware = [thunk, promiseMiddleware, routerMiddleware(history)];
  let store;

  if (__DEVCLIENT__) {
    middleware.push(createLogger());
    store = createStore(rootReducer, initialState, compose(
      applyMiddleware(...middleware),
      typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ?
      window.devToolsExtension() : f => f
    ));
  } else {
    store = createStore(rootReducer, initialState, compose(applyMiddleware(...middleware), f => f));
  }

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('common/reducers', () => {
      const nextReducer = require('../common/reducers');
      store.replaceReducer(nextReducer);
    });
  }

  return store;
}
```

**Comment by zalmoxisus** [comment]
@siemiatj, yes it works exactly the same as for Chrome, except the fact that it's not available for DevTools panel (since [it is not supported yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1211859)). So, you have to open it from the popup, context menu, or using shortcuts. Or alternatively, you can open it programatically with `window.devToolsExtension.open()`.

Do you see the extension's icon on the location bar? Does `window.devToolsExtension` object exists?

**Comment by siemiatj** [comment]
So I don't have the icon on the location bar, but I can open it programmatically. And suddenly it started working properly.

That's my store definition if anyone finds it useful : 

```javascript
export default function configureStore(initialState, history) {
  const middleware = [thunk, promiseMiddleware];
  const reactRouterReduxMiddleware = routerMiddleware(history);
  if (__DEVCLIENT__) {
    middleware.push(reactRouterReduxMiddleware, createLogger());
  } else {
    middleware.push(reactRouterReduxMiddleware);
  }

  const finalCreateStore = applyMiddleware(...middleware)(createStore);

  const store = finalCreateStore(rootReducer, initialState, typeof window === 'object' &&
    typeof window.devToolsExtension !== 'undefined' ? window.devToolsExtension() : f => f);

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('reducers', () => {
      const nextReducer = require('reducers');
      store.replaceReducer(nextReducer);
    });
  }

  return store;
}
```

**Comment by zalmoxisus** [comment]
@siemiatj, you're mixing the old Redux API with the new one, which is not supported. In the new API you pass enhancers (and middlewares) via the third createStore argument. It should be:
```js
const store = finalCreateStore(rootReducer, initialState, 
compose(
  applyMiddleware(...middleware),
  typeof window === 'object' &&
    typeof window.devToolsExtension !== 'undefined' ? window.devToolsExtension() : f => f
));
```

**Comment by clarkbw** [comment]
FYI DevTools panel support has landed and is supported in Firefox 54 (DevEdition). Let me know if there's anything I can do to help.  Thanks.

**Comment by clarkbw** [comment]
I just did a quick test and the panel is working as expected in Fx 54.  

I did find that the `devtools.inspectedWindow.getResources` API is not supported in Firefox (I filed [bug 1361121](https://bugzilla.mozilla.org/show_bug.cgi?id=1361121) for this), however there is no need to detect `file://` URLs in Firefox so I was able to guard against the API anyway.  Things seem to work just great.

See changes here: https://github.com/zalmoxisus/redux-devtools-extension/compare/master...clarkbw:firefox-webextension

**Comment by zalmoxisus** [comment]
@clarkbw thanks a lot for investigating it!

I like the implementation, just not sure how safe it will be to relay on `typeof browser === undefined` instead of `navigator.userAgent.indexOf('Firefox') === -1`.

**Comment by clarkbw** [comment]
> I like the implementation, just not sure how safe it will be to relay on typeof browser === undefined instead of navigator.userAgent.indexOf('Firefox') === -1.

Thanks! I'm not sure how future proof that test will be either.

I'll fix it up and open a PR

**Comment by clarkbw** [comment]
I'm not sure there's anything specific left to do here anymore.

**Comment by zalmoxisus** [comment]
Yes, we have now all the features for Chrome and Firefox extension. @clarkbw thanks a lot for your contribution! Just a reminder to myself that we need to add tests for firefox as described in https://github.com/SeleniumHQ/selenium/issues/1181.
