### ISSUE TITLE
Why does it need hard-coded extension ID and key?

### ISSUE THREAD

**Issue by mondaychen** [zalmoxisus/redux-devtools-extension#90]
I'm new to chrome extension development. While reading the source code, I noticed that in [`src/browser/extension/inject/index.js#L4`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/index.js#L4) there's a hard-coded `window.devToolsExtensionID`, and in [`src/browser/extension/manifest.json`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/manifest.json#L71) there's a hard-coded key.

I tried to change `devToolsExtensionID` to `window.devToolsExtensionID = chrome.runtime.id;`, and remove `key` in manifest.json, the extension still works in my local environment.

**Comment by zalmoxisus** [comment]
It's necessary to inspect not only web pages, but also [Chrome apps and extensions](https://github.com/zalmoxisus/redux-devtools-extension#how-to-include-it-in-chrome-apps-and-extensions).  So, an inspected app or extension can [connect to our extension to send and receive data](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/contentScript.js#L10).

You can see an working example of this scenario on [the crossbuilder boilerplate](https://github.com/zalmoxisus/crossbuilder).

**Comment by mondaychen** [comment]
Thanks for the answer!
