### ISSUE TITLE
Remove Diff monitor

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#97]
Are there any advantages of using Diff Monitor since we now have Diff functionality in the Inspector Monitor?

There are some issues there [solved](https://github.com/whetstone/redux-devtools-diff-monitor/pulls) by @jhen0409, but not sure how maintained the project is. To support it in future we'll also need to support theming there as suggested in #96.

**Comment by Koleok** [comment]
I don't think the diff monitor has enough to offer to really justify itself in light of the inspector

**Comment by jhen0409** [comment]
The Inspector has not yet implement some features, like https://github.com/alexkuz/redux-devtools-inspector/issues/19 https://github.com/alexkuz/redux-devtools-inspector/issues/20.

But I agree removing Diff monitor, I don't know they whether or not to continue to maintain project, if they don't fix these problems, it's not conducive to self-build for extension.

**Comment by zalmoxisus** [comment]
@jhen0409, while these features are present in the Log Monitor, that's not a problem. We want to have multiple monitors, each of them should be focused on solving specific problems and do it well.

**Comment by alexkuz** [comment]
`Inspector` now supports skipping and committing actions.

**Comment by zalmoxisus** [comment]
Removed in `v1.3.0`.
